### ISSUE TITLE
State field not displaying on checkout unless you refresh page.

### ISSUE THREAD

**Issue by vaporsyndicate** [woocommerce/storefront#1000]
Using: WP v4.9.8, WooCommerce v3.51, StoreFront v2.3.5, WooCommerce ShipStation Integration v4.1.25 - all WooCommerce Products - all updated to the most current version. 

State field is hidden upon initial visit to checkout page. After refreshing the page, it appears. 

![screenshot1](https://user-images.githubusercontent.com/38982424/48650306-986d6200-e9c3-11e8-8a57-133462ec9419.png)
![screenshot2](https://user-images.githubusercontent.com/38982424/48650307-986d6200-e9c3-11e8-9ecd-1b9ca1c8e74b.png)

What needs to be fixed to make it so that it appears on the first visit to the page?

**Comment by tiagonoronha** [comment]
@vaporsyndicate tested this with the latest version of Storefront + WooCommerce + WooCommerce ShipStation and I couldn't replicate this issue.

The 'State' fields shows up correctly without the need to refresh the page.

If you're still experiencing this issue, please contact us through our support channels: https://woocommerce.com/contact-us/
