### ISSUE TITLE
Gutenberg gallery block: leaking margin

### ISSUE THREAD

**Issue by simison** [woocommerce/storefront#1005]
When adding a Gutenberg gallery block, it seems to get extra marging when looked at frontend. Note spacing compared to edge of text content:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/87168/49222167-d1ee9600-f3e3-11e8-9aab-1f7ef2d3ff2c.png">

Seems to be caused by generic `ul` `margin` rule:

<img width="212" alt="screenshot 2018-11-29 at 14 31 41" src="https://user-images.githubusercontent.com/87168/49222145-c26f4d00-f3e3-11e8-976f-dfb50fe34525.png">

While this should be fixed at Gutenberg core, it might be a bit late at this point.

**Comment by tiagonoronha** [comment]
@simison Storefront 2.4.0, currently in beta, addresses this and other Gutenberg related issues: https://github.com/woocommerce/storefront/releases/tag/version%2F2.4.0-beta1

Thanks! :)

**Comment by simison** [comment]
Fantastic! 🚢  👍
