### ISSUE TITLE
Gravity Forms compatibility

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#1010]
We load jquery in `wp_footer` which causes an incompatibility with Gravity Forms. More details here; https://wordpress.org/support/topic/storefront-conflicts-with-gravity-forms/

Looks like there's an easy compatibility fix;

`add_filter( 'gform_init_scripts_footer', '__return_true' );`

**Comment by tiagonoronha** [comment]
We don't use jQuery in the frontend so this needs to be debugged further before we decide to add this compatibility filter.

**Comment by tiagonoronha** [comment]
I tested this as per the instructions on the forum thread and I wasn't able to replicate the issue.

I created a form with conditional fields and the form loaded as expected. Disabling JavaScript confirmed that the the form doesn't load, also as expected.

I can only conclude that there is some other plugin creating a conflict.
