### ISSUE TITLE
[2.4] Backend does not load - WSOD

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#1011]
I'm running:
- WordPress 4.9.8
- Gutenberg 4.6.1
- Storefront 2.4

No plugins (except Gutenberg). I cannot enter the editor (gives the WSOD).

If I disable Gutenberg, the old editor loads fine. Other themes work fine. 

Also, if using WP 5 (and no Gutenberg plugin), the editor screen returns a 500 error, instead of the WSOD.

Known issues?

**Comment by GlennMartin1** [comment]
I'm running PHP 7.2.

Checking errors now....

**Comment by GlennMartin1** [comment]
Ok, I just made a brand new install - same thing.

Here's the PHP error log:

`[Thu Dec 06 15:04:04.498084 2018] [php7:error] [pid 27970] [client 73.238.155.60:41874] PHP Fatal error: Uncaught Error: Using $this when not in object context in /nas/content/live/testwp123/wp-content/themes/storefront/inc/customizer/class-storefront-customizer.php:906\nStack trace:\n#0 [internal function]: Storefront_Customizer::block_editor_customizer_css('')\n#1 /nas/content/live/testwp123/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)\n#2 /nas/content/live/testwp123/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)\n#3 /nas/content/live/testwp123/wp-includes/plugin.php(453): WP_Hook->do_action(Array)\n#4 /nas/content/live/testwp123/wp-content/plugins/gutenberg/lib/client-assets.php(1388): do_action('enqueue_block_e...')\n#5 [internal function]: gutenberg_editor_scripts_and_styles('post.php')\n#6 /nas/content/live/testwp123/wp-includes/class-wp-hook.php(286): call_user_func_array('gutenberg_edito...', Array)\n#7 /nas/content/live/testwp123/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)\n#8 /nas/content/live/testwp123/wp-includes/plugin.php(453): WP in /nas/content/live/testwp123/wp-content/themes/storefront/inc/customizer/class-storefront-customizer.php on line 906, referer: https://testwp123.wpengine.com/wp-admin/edit.php`

**Comment by GlennMartin1** [comment]
(my host is WP-Engine).

**Comment by tiagonoronha** [comment]
@GlennMartin1 there's a method wrongly declared a being a static method: https://github.com/woocommerce/storefront/blob/master/inc/customizer/class-storefront-customizer.php#L903

Removing `static` from that line resolves the issue and will make the error go away. We'll be releasing a fix ASAP.

Thanks for reporting!

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1012
