### ISSUE TITLE
Latest Storefront release 2.4 breaks function of Storefront Blog Customiser

### ISSUE THREAD

**Issue by robokow** [woocommerce/storefront#1014]
Storefront Release 2.4 deals differently with the meta-data of a blogpost. This breaks the function of another official woocommerce plugin Storefront Blog Customiser. It is not possible to move the meta-data around via the customizer anymore. Reverting back to Storefront version  2.3.5 solved my issue.

**Comment by tiagonoronha** [comment]
@robokow for issues related to our extensions please contact us via our support channels:

https://woocommerce.com/contact-us/

Thank you!

**Comment by robokow** [comment]
You just did a release that brakes your own officially supported plugins. That does not come across as very professional...
