### ISSUE TITLE
Infinite scroll on the site using StoreFront

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/storefront#1016]
Infinite scroll on the site bollypiano.com/product-category/midi/ is not working.

Error in console:

> POST>https://bollypiano.com/?infinity=scrolling 500
> send    @    jquery.js:4
> ajax    @    jquery.js:4
> n.(anonymous function)    @    jquery.js:4
> Scroller.refresh    @    infinity.min.js:4
> (anonymous)    @    infinity.min.js:4
> setInterval (async)        
> Scroller    @    infinity.min.js:4
> (anonymous)    @    infinity.min.js:4
> i    @    jquery.js:2
> fireWith    @    jquery.js:2
> ready    @    jquery.js:2
> K    @    jquery.js:2

On Kibana, I can see some errors related to the infinite scroll of Storefront.

> PHP Fatal error:  Uncaught Error: Call to undefined function storefront_is_product_archive() in /wordpress/themes/storefront/2.4.1/inc/jetpack/class-storefront-jetpack.php:64
> Stack trace:
> #0 /wordpress/core/5.0.0/wp-includes/class-wp-hook.php(286): Storefront_Jetpack->jetpack_infinite_scroll_loop('')

zd-1629767 hc-8663574

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1018
