### ISSUE TITLE
Update demo to latest version of Storefront

### ISSUE THREAD

**Issue by fhaps** [woocommerce/storefront#1017]
User in 1626879-zen reported that post meta is no longer showing the way that it currently looks like in the [demo store](https://themes.woocommerce.com/storefront/blog/). This is what it looks like in the demo:

![](http://cld.wthms.co/XZ2tkd+)
Image Link: http://cld.wthms.co/XZ2tkd

I believe that the way the post meta is displayed in Storefront 2.4+ has changed, and that section is no longer available.

This is how it displays in the latest version of Storefront:

![](http://cld.wthms.co/v8lFF2+)
Image Link: http://cld.wthms.co/v8lFF2

Could the [demo store](https://themes.woocommerce.com/storefront/blog/) be updated to reflect these changes? To avoid confusion among users.

Not sure if this is the right place to report this, but let me know if it should be moved elsewhere.

**Comment by tiagonoronha** [comment]
This has been discussed internally. Closing the issue.
