### ISSUE TITLE
Author information has disappeared since 2.4

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/storefront#1021]
Since SF2.4, the author information on blog posts has disappeared. I've looked through the changelog file, but I can't seem to find an indication of why this is happening.

Before:

![http://cld.wthms.co/LpyAEo](http://cld.wthms.co/LpyAEo+)
Link to image here: http://cld.wthms.co/LpyAEo.

After:

![http://cld.wthms.co/dgI6LU](http://cld.wthms.co/dgI6LU+)
Link to image here: http://cld.wthms.co/dgI6LU.

**Comment by GlennMartin1** [comment]
Not a bug. That was done due to Gutenberg. See the official blog post: https://woocommerce.wordpress.com/2018/11/23/storefront-2-4-beta-1/

**Comment by jobthomas** [comment]
Ignore me then. Thanks for the update. :D @tiagonoronha I'll add a PR into the changelog (this is probably big enough to mention there.

**Comment by tiagonoronha** [comment]
@jobthomas author information and comments was moved to above the title as you can see in your second screenshot.

Category and tags will be at the end of the post.

We did indeed forget to include that change in the changelog, I will update it in the next release.
