### ISSUE TITLE
Gravatar missing from Blog page posts.

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/storefront#1024]
The Gravatar that once showed ( [#](http://cld.wthms.co/bJtcWV) ) shows no more ( [#](http://cld.wthms.co/8fPIZg) ).

**Comment by tiagonoronha** [comment]
@johndcoy we changed the layout in 2.4: https://woocommerce.wordpress.com/2018/11/23/storefront-2-4-beta-1/
