### ISSUE TITLE
Change in filter name for inline woocommerce css from version 2.4.0

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/storefront#1030]
Not a bug but an issue for sites with child themes that rely on removing inline CSS.

Old File:  /storefront/inc/customizer/class-storefront-customizer.php 
line 914 
`return apply_filters( 'storefront_customizer_woocommerce_css', $woocommerce_styles );`

New File: /storefront/inc/woocommerce/class-storefront-woocommerce-customizer.php 
line 307
`return apply_filters( 'storefront_woocommerce_customizer_css', $styles );`

The filter name for inline CSS has changed in Storefront 2.4.0 from 
storefront_customizer_woocommerce_css
to
storefront_woocommerce_customizer_css

This causes design changes for child themes removing inline CSS, in my case quite severe (checkout buttons becomes illegible). Can this be highlighted better for users upgrading to the new Storefront version? The moving of files was mentioned in blog, but not the renaming of the filter. 

Appreciate it will become obvious during testing, but would be good to flag this up as it will break child theme designs that rely on removing inline CSS. 

If anyone uses a child theme & needs to remove inline CSS then the code used to be
`add_filter('storefront_customizer_woocommerce_css', '__return_false');`
For version 2.4.0 or higher has now to be 
`add_filter('storefront_woocommerce_customizer_css', '__return_false');`

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1038
