### ISSUE TITLE
WC "Related products" does not respect Customizer setting...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#1032]
The WooCommerce **Related products** (on single product page) does not respect the **Products per row** setting in the Customizer.

## To Reproduce:
- Go to **Customizer** > **WooCommerce** > **Product Catalog** > **Products per row**
- Regardless of setting, the front-end will always display three **Related products** in the row.

Like the rest of the shop, **Related products** should respect the **Products per row** setting.

## Solution:
As you will see here: https://github.com/woocommerce/storefront/blob/master/inc/woocommerce/class-storefront-woocommerce.php#L187 Storefront sets the **Related products** to 3. This should instead defer to the Customizer setting.

**Comment by tiagonoronha** [comment]
@GlennMartin1 I initially labelled this issue as an enhancement but I spent some time thinking about it and I don't think that Related Products necessarily have to mirror the number of columns/products.

The settings in that Customizer section are for the Shop page/Archives and it's easy to make the case that you will not want this setting to be the same.

But feel free to convince me otherwise :)

In the meantime, please use the available filter - `storefront_related_products_args`.

Thank you!

**Comment by GlennMartin1** [comment]
@tiagonoronha  Related Products is not the "Focus" product - _just suggestions_ - so it's reasonable that **more products, but smaller ones** would be shown.

Go to any Amazon product page; they have similar sections, but with **6 - 8** small products in a row. Or compare eBay which has **6**. Walmart has **6**. No doubt that design is intentional.

> I don't think that Related Products necessarily have to mirror the number of columns/products.

I agree not "necessarily." But in my case:
- my full-width (no side widgets) shop page has 4 images.
- but the "Related Products" setting (out-of-the-box hard-coded setting of 3) results in LARGER images than the shop. That makes no sense.

Possible solutions:
- WORST: Keep it at three, which results in huge pictures for _suggestions_.
- GOOD: Make it hard-coded to **4**, **5**, or **6**, instead of only 3.
- BETTER: Make it match the Customizer setting (as this issue initially proposed).
- BEST: Make it a Customizer setting to choose.

Your call - you're the boss 👍

**Comment by GlennMartin1** [comment]
Could this be reconsidered?

If not, I won't ask again, but I think it's most reasonable.

Consider that large stores have far more related products - no doubt that's strategic on their part. 

I've offered a few possibe solutions and would be thrilled with any of them. 

Thanks for your consideration.
