### ISSUE TITLE
Shortcodes included in the short description of products do not expand in the shop page

### ISSUE THREAD

**Issue by fhaps** [woocommerce/storefront#1042]
With the help of Storefront Powerpack, I configured the shop page to display the short description of products on the shop page. 

I expected the short descriptions to be displayed in the same format, however I discovered that shortcodes that were included in the short description do not expand on the shop page – the shortcode itself is shown in plain text.

I tested this with both shortcodes that are part of WooCommerce core, and shortcodes added by other extensions like [Product Documents](https://www.woocommerce.com/products/product-documents/?aff=10486&cid=1131038). The result was the same one.

![](http://cld.wthms.co/qARCQd+)
Image Link: http://cld.wthms.co/qARCQd

**Comment by tiagonoronha** [comment]
Issue moved to [woocommerce/storefront-powerpack #174](https://github.com/woocommerce/storefront-powerpack/issues/174) via [**ZenHub**](https://www.zenhub.com/)
