### ISSUE TITLE
Mobile menu shows unwanted pages

### ISSUE THREAD

**Issue by Tigzy** [woocommerce/storefront#1044]
Hello, 
On mobile the menu automatically adds pages even if the checkbox to do so is unchecked in settings.
The desktop menu looks fine.

Step to repro: 
Create a random page, don't add it to the menu.
Display home page on mobile, the page is in the menu

**Comment by tiagonoronha** [comment]
Hi @Tigzy.

I just tried to replicate this issue without success.

It seems to be that you do not have a menu assigned to the "Handheld" location.

Go to Appearance > Menus, create a new menu and assign it to the "Handheld Menu" location. This way you can control exactly what goes into that menu.

Thanks!

**Comment by Tigzy** [comment]
You are right, I just need to assign my header menu to Handheld menu as well, thanks !
