### ISSUE TITLE
Re-run the guided tour with sample data

### ISSUE THREAD

**Issue by fi0** [woocommerce/storefront#1048]
how do I run it again?

**Comment by tiagonoronha** [comment]
The guided tour is meant to be used when installing Storefront for the first time. You can force it to run by going to <your-site>/wp-admin/options.php and manually changing the value of `storefront_nux_dismissed` and `storefront_nux_guided_tour` from `1` to `0`.

For support, please use the WordPress forums: https://wordpress.org/support/theme/storefront/

Thank you!
