### ISSUE TITLE
Empty sidebar

### ISSUE THREAD

**Issue by fi0** [woocommerce/storefront#1049]
The sidebar column should be removed when the sidebar is empty.

**Comment by tiagonoronha** [comment]
Hi @fi0! That's how Storefront works by default. 

If there's no widgets in the sidebar, the layout becomes full width.

Keep in mind that if you have widgets that only show on specific pages, such as filters for the Shop page, WordPress still considers that sidebar has having widgets.

**Comment by jobthomas** [comment]
I'm reopening this @tiagonoronha - I've tested this with the individual blog template. There are no widgets added to the sidebar, but the posts still do not display as full-width:

![http://cld.wthms.co/Mrbtkz](http://cld.wthms.co/Mrbtkz+)
Link to image here: http://cld.wthms.co/Mrbtkz.

I am able to change this if I use Powerpack, but that's not available for blog posts. 

![http://cld.wthms.co/y1hV1X](http://cld.wthms.co/y1hV1X+)
Link to image here: http://cld.wthms.co/y1hV1X.

I also tested the same without Powerpack active and the same happened: empty sidebar as far as widgets are concerned but not a full-width rendering.

**Comment by jobthomas** [comment]
So, I've tested the following: adding a widget and then deleting it again and that prompted the sidebar to disappear. I haven't been able to find where the problem was in the first place, but as a temporary workaround; just adding a widget and deleting it again seems to work.
