### ISSUE TITLE
Hidden Post Title in Continue Reading Link Leads to Incorrect Translation

### ISSUE THREAD

**Issue by corsonr** [woocommerce/storefront#1050]
Here: https://github.com/woocommerce/storefront/blob/45b3d1ebd1a13aff1fe4fd8143a932c224f86656/inc/storefront-template-functions.php#L397

The post title is embed within the `screen-reader-text` class which means it doesn't show to visitors.  

Since it's also embed in a `sprintf()` function it leads to weird translation.

In English it's not a big deal:

![](http://cld.wthms.co/ZWGiRx+)

But in French, or any another language having attributes:

![](http://cld.wthms.co/YiCb1w+)

which means "continue reading of ". And because latin languages do need to add an extra word (corresponding to `of`) the syntax needs to be modified.

**Comment by tiagonoronha** [comment]
I can't think of a way of implementing this without complicating it too much. Any ideas? :)

While not perfect, I'd recommend adding an additional `screen-reader-text` within the translation itself.

`Continuer la lecture<span class="screen-reader-text"> de</span> %s`

Closing for now.
