### ISSUE TITLE
[2.4.3] Customizer's alternate button color not working...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#1052]
WordPress 5.0.3
Storefront 2.4.3
Homestore 2.0.28

Go to **Customizer** > **Buttons** > **Alternate Button Background Color**; this setting does not make any difference.

2.4.3 was just released, in which https://github.com/woocommerce/storefront/pull/1028 fixed the **Button Color**, but it did not fix the **Alternate Button Background Color** (which is supposed to include post nav, etc...). That setting currently makes no difference.

**Comment by tiagonoronha** [comment]
@GlennMartin1 the alternate button color is applied to buttons with the `.alt` class. I looked through a few examples of things and color are definitively being applied correctly.

Here's an example: 

<img width="1622" alt="screenshot 2019-02-22 at 18 28 31" src="https://user-images.githubusercontent.com/1177726/53262882-b8ea3e00-36cf-11e9-84be-5900f22319f6.png">

Please provide a specific example and I'll look into it. Thank you!

**Comment by GlennMartin1** [comment]
My understanding was that post navigation buttons were a part of Alternate Button Background Color.

If that's incorrect, then it's all set. Thanks for your time.

**Comment by tiagonoronha** [comment]
I checked Homestore and I couldn't find any references to that ever being an option. I'll this issue to Homestore's repo and I'll see if we can get that in.
