### ISSUE TITLE
[2.4] Bundle/Composite child items not hidden between handheld/desktop sizes

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/storefront#1053]
### Description

For simplicity/readability Bundle/Composite child cart items are hidden and displayed as parent item meta at lower-then-desktop sizes.

Due to a styling error, meta + child items are simultaneously displayed between handheld + desktop sizes.

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1055
