### ISSUE TITLE
img border-radius: 3px in style.css

### ISSUE THREAD

**Issue by seoidau** [woocommerce/storefront#1056]
Hello

I have always wondered why the Storefront theme's style.css has

```
img {
    border-radius: 3px;
}
```

Why? Every child theme I have made I have had to undo this. Removing it would help make Storefront just that little more "clean and simple", would it not?

**Comment by tiagonoronha** [comment]
Hi!

Storefront has many small design details like this. Besides being a super extensible theme, it is also used by many as is. 

Small details like these add a bit more character and make the theme visually pleasant.

Thank you!
