### ISSUE TITLE
Columns with WC product shortcode get messed up

### ISSUE THREAD

**Issue by ajgw** [woocommerce/storefront#1058]
I had a page with few Gutenberg two column layout blocks created. In one two column block I had put in shortcodes for displaying products including a columns parameter: show products in two columns.

After I called that page with Storefront 2.4.3 the whole page layout was messed and all columns were displayed in one row beside each other. I tried disabling plugin WooCommerce Blocks but with not effect.

I had to remove shortcode with product columns setting from page to get it work as expected.

Create a columns block and write any content into each column. Create another column block below and put a shortcode block into both columns.

I used this simple shortcode for my products [products categories="foto" columns="2"]

Now all column blocks display beside each other in one row.

**Comment by tiagonoronha** [comment]
Hi @ajgw! I'm not sure if I understand your issue.

I added a Columns block with two columns. On each column I added the `[products categories="foto" columns="2"]` shortcode. Columns display as expected.

What am I missing? Thank you!

**Comment by ajgw** [comment]
Hi Tiago, I have setup a page like this:

Title > 2-column-block with headline and paragraph in each column > 2-column-block with product shortcode … in each column.

Below are two screenshots: first pagelayout in backend, second result in frontend. Frontend shows all columns in one row and not separated by block.





Mit Gruss aus Bremerhaven an der Nordsee,
Adrian Wackernah

Adrian Wackernah
Lüneburger Str. 32
27572 Bremerhaven

Atelier An der Mühle
An der Mühle 45
27570 Bremerhaven

Tel. 0471-4836 5189
Tel. 0151-2404 3961

https://atelier-an-der-muehle.de <https://atelier-an-der-muehle.de/>

**Comment by tiagonoronha** [comment]
@ajgw images are not showing up. You'll need to reply via Github to add the screenshots. E-mail attachments do not show up here.

**Comment by ajgw** [comment]
![layout](https://user-images.githubusercontent.com/3390880/53272687-3e7ee580-36f2-11e9-9aaf-5b7c2b8f19a7.jpg)
![frontend](https://user-images.githubusercontent.com/3390880/53272694-43dc3000-36f2-11e9-860e-293a4d3d89c6.png)

**Comment by tiagonoronha** [comment]
Thank you for the screenshots! I'm afraid I cannot reproduce this issue:

<img width="814" alt="screenshot 2019-02-22 at 22 02 37" src="https://user-images.githubusercontent.com/1177726/53273994-96671d80-36ed-11e9-8b20-05207e510481.png">

<img width="1159" alt="screenshot 2019-02-22 at 22 00 54" src="https://user-images.githubusercontent.com/1177726/53273942-6c156000-36ed-11e9-8cb4-9b20ad0af7ed.png">

If possible, please post the URL to this page on your site and I'll have a look at the issue.

**Comment by ajgw** [comment]
Sure: https://stage.atelier-an-der-muehle.de/two-columns-with-products/

I see that div has class of two columns and there is a flexwrap is set to nowrap, so it shouldn't wrap. But why?

**Comment by ajgw** [comment]
Upps and sorry. I found the reason in Meow Gallery Plugin which made the bug. After deactivating plugin all went fine. Thanks for your patience.

**Comment by tiagonoronha** [comment]
Thanks for letting me know!
