### ISSUE TITLE
HomePage Featured image

### ISSUE THREAD

**Issue by broros** [woocommerce/storefront#1059]
The theme storefront is poorly designed, the homepage featured image has some inline styling ( width: 1342px; margin-left: -130.516px; ) that is causing the image to flicker when reloading the page.

the feature image image div should be above the main content div.

![featured_image](https://user-images.githubusercontent.com/598228/52631095-1df59680-2e7b-11e9-8557-c301c53275d1.png)

**Comment by tiagonoronha** [comment]
Hi!

The featured image size is calculated dynamically. If you don't like this functionality, you can remove it with the following snippet:

```
function gh1059_dequeue_script() {
   wp_dequeue_script( 'storefront-homepage' );
}

add_action( 'wp_print_scripts', 'gh1059_dequeue_script', 100 );
```

It's also possible to move the hero section:

```
remove_action( 'homepage', 'storefront_homepage_content', 10 );
add_action( 'storefront_content_top', 'storefront_homepage_content', 10 );
```

You can add the snippets above to a custom child theme: https://docs.woocommerce.com/document/set-up-and-use-a-child-theme/

Thank you!
