### ISSUE TITLE
Updates page / td.plugin-title - include link to release notes.

### ISSUE THREAD

**Issue by WM4362** [woocommerce/storefront#1061]
A small enhancement for your consideration...

I've noticed that on the Dashboard > Wordpress Updates page, the update entries for Storefront don't include a link to the related release notes (like most all other Plugins do).

This adds another step to the update process as I now have to open another tab and go find them.

So (like other Plugin's), if this link could be included with future updates, I suspect that would be useful to many users. E.g. the recent 2.4.3 update would have looked something like this (with the hyperlink opening in a modal (_class="thickbox open-plugin-details-modal"_)).

**Storefront**
You have version 2.4.2 installed. Update to 2.4.3. [View version 2.4.3 details](https://woocommerce.wordpress.com/2019/02/05/storefront-2-4-3-release-notes/).

**Comment by tiagonoronha** [comment]
Hi @WM4362. That is a WordPress feature and has only been implemented for plugins, not themes.

There's nothing we can do from our side. I'm afraid.

Thank you for the suggestion though!
