### ISSUE TITLE
Columns not displaying nicely in header widget

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/storefront#1062]
I would expect that adding the `[products]` or any other shortcode would default columns for that widget, but this is not the case in the header widget (I understand it is not for the other widget areas as this would make it look very cramped).

If I'm not mistaken it should be easy to fix, but adding `.header-widget-region` here: https://github.com/woocommerce/storefront/blob/71dfd55372642d06555665e41839a769ce3a3449/assets/css/woocommerce/woocommerce.scss#L2033-L2036

So add a new line below `.site-main` to result in:

```
.site-main,
.header-widget-region
```

I've tested with this code and it works while using it in the editor. 

![https://cld.wthms.co/OjDHgZ](https://cld.wthms.co/OjDHgZ+)
Link to image here: https://cld.wthms.co/OjDHgZ.

While this is the before:

![https://cld.wthms.co/3IEvMR](https://cld.wthms.co/3IEvMR+)
Link to image here: https://cld.wthms.co/3IEvMR.

cc @eduardozulian

**Comment by jobthomas** [comment]
@tiagonoronha I was too lazy to compile but I think this fix would work - happy to also submit a PR once I have more time

**Comment by eduardozulian** [comment]
Thanks, Job.

cc @WillBrubaker since we already talked about this.

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1065
