### ISSUE TITLE
Google search

### ISSUE THREAD

**Issue by broros** [woocommerce/storefront#1064]
missing important google search attributes
https://developers.google.com/search/docs/data-types/product

![google-search](https://user-images.githubusercontent.com/598228/53304008-04b2f980-382e-11e9-94ef-603354794cf9.png)

**Comment by ben72** [comment]
I've got those fields. I think I have them from the Yoast WooCommerce SEO plugin. There are other plugins for adding schema attributes as well.

**Comment by tiagonoronha** [comment]
Hi @broros!

SEO best practices are always changing and are hard to keep up with.

There are many plugins you can use for that like the Yoast WooCommerce SEO plugin mentioned above.

Thank you.

**Comment by broros** [comment]
This should be part of the theme and it was part of the theme until the last maintainer decided to do away with schema attributes
