### ISSUE TITLE
JetPack Infinite Scroll product categories: clicking BACK button doesn't return you as expected

### ISSUE THREAD

**Issue by seanconklin** [woocommerce/storefront#1071]
Moving over from #1063 as a separate issue

I have reproduced this issue with the latest Storefront theme, WooCommerce, and JetPack.

Instead of reloading the full product category page scrolled to the last position, the user clicks into a product then clicks the BACK button on their browser to see the lower results from the last page they were infinitely scrolled to.

Example URL: https://jinnybeyer.com/product-category/fabric/

Steps to reproduce:

- Scroll down past Palette number 12 so it loads more results.
- Click Palette number 14.
- Click BACK button on browser.
- Notice if you scroll up the top product is Palette number 13, not all of the subcategories you see when you had first landed on the URL.

Note: Reproduced using Safari and FireFox browsers.

Note: This seems to be caused by the return URL containing `page/2/`

My client regards this as a user experience problem in that their users click the browser BACK button they don't go back on the original category page scrolled to their last position as usual with the BACK button behavior. We all know AJAX and BACK buttons can be tricky!

I understand the URL is changing with scroll for some reason, perhaps accessibility or SEO related. I would open that up with JetPack since this appears to be their default behavior, though I suspect they would then toss this back over to Woo since it's not in reference to a core WP example and the product categories and theme play a role in the output, as well as user context while shopping.

There may be an acceptable workaround. Examples ( button on top to return to full view, eliminating the URL change with some code, using code to auto force reload and scroll ). Would anybody have any suggestions on code snippets or references to further research this?

**Comment by tiagonoronha** [comment]
@seanconklin this is a combination of things, none actually related to Storefront.

* WooCommerce only outputs the categories in the first page: https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L2246-L2248
* Jetpack only paginates the current page via JavaScript/AJAX, but when you use the back button, the page is reloaded and you get the page as if you were browsing without that option.

You can open issues on both WooCommerce and Jetpack, but in your specific case, it seems that what you need is actually a custom implementation that suits your customers' needs.

Thank you!

**Comment by seanconklin** [comment]
Thanks for the research @tiagonoronha . I agree it's a JetPack issue so I've moved it into this 2014 ticket still open https://github.com/Automattic/jetpack/issues/222
