### ISSUE TITLE
TypeError: e[0] is undefined -- began in version 2.4.4

### ISSUE THREAD

**Issue by seanconklin** [woocommerce/storefront#1079]
Getting this browser console error - just started today with the v2.4.4 update:

Error: `TypeError: e[0] is undefined`
Location: `navigation.min.js:1:217`
Detail: `<anonymous> /wp-content/themes/storefront/assets/js/navigation.min.js?ver=2.4.4:1`

Above is from latest FireFox. Safari console says `TypeError: undefined is not an object (evaluating 'e[0].querySelectorAll')`

**Comment by tiagonoronha** [comment]
I've tested and confirmed that this is an issue where there's no menu assigned to the "Handheld" location. Working on a patch.

**Comment by seanconklin** [comment]
Please note that I do have a menu assigned to `Handheld Menu` and `Primary Menu`, but this is an empty menu with no links.

**Comment by tiagonoronha** [comment]
@seanconklin thanks, I also covered that edge case in the PR referenced above!

**Comment by tiagonoronha** [comment]
The code was reverted and a hotfix released in 2.4.5.
