### ISSUE TITLE
Product post or page: add edit link for site owner to easily enter editor

### ISSUE THREAD

**Issue by lancewillett** [woocommerce/storefront#1083]
> Wish I had edit links on product pages and posts in Storefront.

Via an internal feedback post by Ryan Boren (see kibbling P2) a suggestion to make editing flow easier.

In this specific case, Ryan uses an iPad to edit his site and often has trouble getting quickly to the admin screens.

> Trying to get to the Products screen of my site on iOS Safari. I cannot figure out how to get to my Stores admin beyond the setup page. Cyclical nav that punts me back to the front page of my site.

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1105
