### ISSUE TITLE
Additional scrollbar when cart contents passes the end of the page

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/storefront#1088]
Storefront has some JavaScript code which reduces the length of the mini shopping cart and adds a scrollbar. However if the original length of the mini shopping cart surpasses the end of the page, we get an additional scrollbar showing up.

![image](https://user-images.githubusercontent.com/11388669/54827797-b832d080-4caa-11e9-83a6-814653aeb2e1.png)

This only happens when the cart contents is really long and the page contents is relatively short. So it's best to reproduce with a short page, or lots of variable products in the cart which take up more horizontal space.

On initial page load the double scrollbar is shown, but as soon as we hover over the mini cart it disappears. This is because the JavaScript code is triggered which reduces the height of the cart and adds the scrollbar, see: https://github.com/woocommerce/storefront/blob/version/2.4.5/assets/js/woocommerce/header-cart.js#L13-L22

To fix this upon initial page load I'd suggest to add the following CSS:

```
.site {
    overflow-y: hidden;
}
```

This is already set for the x overflow so the two could probably be combined, see: https://github.com/woocommerce/storefront/blob/version/2.4.5/assets/css/base/_base.scss#L278-L280

Affected ticket: 1897234-zen

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1118
