### ISSUE TITLE
Cart Page Design Improvements

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/storefront#1090]
Storefont is a great woo commerce theme but it's default cart page design lacks professionalism. Kindly improve the default cart page design of storefront theme to make it appealing to customers.

### Storefront Theme Default Cart Page on Mobile
![screenshot-www kalashcards com-2019 03 24-20-24-36](https://user-images.githubusercontent.com/11793930/54881409-b6693880-4e75-11e9-95e3-87ae9956ab92.png)

### Flatsome Theme Default Cart Page on Mobile
![screenshot-flatsome3 uxthemes com-2019 03 24-20-26-23](https://user-images.githubusercontent.com/11793930/54881412-bd904680-4e75-11e9-8bba-3b4ec92d3a0c.png)

### Storefront Theme Default Cart Page on Desktop 
![screenshot-www kalashcards com-2019 03 24-20-41-39](https://user-images.githubusercontent.com/11793930/54881414-c5e88180-4e75-11e9-8274-6d2271cb6731.png)

### Flatsome Theme Default Cart Page on Desktop 
![screenshot-github com-2019 03 24-20-42-02](https://user-images.githubusercontent.com/11793930/54881421-cb45cc00-4e75-11e9-8295-bad937fad2e0.png)

**Comment by mikejolley** [comment]
I agree this is important :)

This is something that's being worked on in WooCommerce core, specifically the Gutenberg Blocks (https://github.com/woocommerce/woocommerce-gutenberg-products-block). Storefront supports the cart and checkout blocks which have improved designs. I don't think we need to track this specifically in Storefront so I will close this issue.
