### ISSUE TITLE
inconsistent styling on product tabs...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#1092]
WordPress 5.1.1
WooCommerce 3.5.7
Storefront 2.4.5
Homestore 2.0.29

The styling on the product tabs is inconsistent.

### For the ADDITIONAL INFORMATION tab, there's a nice dark horizontal line:
![additional](https://user-images.githubusercontent.com/30901407/55278986-9a3c2000-52e9-11e9-8cfa-b0e83631467c.jpg)

### But the DESCRIPTION tab does not have that:
![desc](https://user-images.githubusercontent.com/30901407/55278981-901a2180-52e9-11e9-8952-5d3f680a6d5d.jpg)

### And the REVIEWS tab does not have that, either:
![reviews](https://user-images.githubusercontent.com/30901407/55278999-b770ee80-52e9-11e9-8463-f8d7f6526cf9.jpg)

**Comment by tiagonoronha** [comment]
Issue moved to [woocommerce/homestore #68](https://github.com/woocommerce/homestore/issues/68) via [**ZenHub**](https://www.zenhub.com/)
