### ISSUE TITLE
Image gallery block breaks with no sidebar in Edge

### ISSUE THREAD

**Issue by jessestu** [woocommerce/storefront#1095]
STEPS TO RECREATE

1. Activate Storefront
2. Remove sidebar widgets.
3. Create a new page with a Gallery block. Set the columns to 4 (not the default 3).

EXPECTED RESULT

To show like it does in Chrome:

![Working](https://user-images.githubusercontent.com/32908730/55812175-18e64980-5ab0-11e9-938d-aeaa26b69b74.png)

Or, to show as it does in Edge with 3 columns:

![Working-3-column](https://user-images.githubusercontent.com/32908730/55812181-1daafd80-5ab0-11e9-979e-3b2dd454a96d.png)

EXPERIENCED RESULT

Edge breaks the fourth column and it wraps to the next line, but in an ugly way:

![Broken](https://user-images.githubusercontent.com/32908730/55812189-23084800-5ab0-11e9-97b9-31eec3fb7fed.png)

_Note: I don't have edge so couldn't look at the Inspector, was only able to check results in Browserstack._

**Comment by jessestu** [comment]
This is a user-reported issue. Here are the results from their site:

Chrome:

![Chrome](https://user-images.githubusercontent.com/32908730/55812453-a4f87100-5ab0-11e9-806a-17038982b05d.png)

Edge:

![Screen Shot 2019-04-07 at 15 27 48](https://user-images.githubusercontent.com/32908730/55812468-a9bd2500-5ab0-11e9-8099-977cbd0c4fa1.png)

**Comment by arunsathiya** [comment]
I stumbled upon this issue and was curious to test. I am not able to reproduce this on Storefront though, with a page having `Full width` page template and core gallery block. It's important to note that I am not using Jetpack's gallery block or any other plugin's gallery block features.

![Screenshot 2019-04-16 at 21 34 56](https://user-images.githubusercontent.com/18581859/56225811-ae28a580-608f-11e9-8035-ab1ef33aea8f.png)
![Screenshot 2019-04-16 at 21 34 14](https://user-images.githubusercontent.com/18581859/56225816-aff26900-608f-11e9-8539-2d7bd73fe5cb.png)
![Uploading Screenshot 2019-04-16 at 21.34.18.png…]()

Wonder if I should be doing something specific to reproduce this. 🤔

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1104

**Comment by tiagonoronha** [comment]
@jessestu @arunsathiya I was able to replicate it. Turns out that for some reason Edge was not correctly calculating the width of the columns. 🤷🏻‍♂️

**Comment by jessestu** [comment]
Thank you for the fix!
