### ISSUE TITLE
Image block full width stop being full-width

### ISSUE THREAD

**Issue by AlchemyUnited** [woocommerce/storefront#1110]
The WP core Gutenberg image block has a setting for full width (.alignfull) but in Storefront this is only true for @media (min-width: 66.4989378333em). Below that min-width margins / padding gets added and the image stops being full width. 

I can understand this for the image toolbar width setting "wide width" but it would make sense if full width was always full width, wouldn't it?

**Comment by nielslange** [comment]
Closing in benefit of https://github.com/woocommerce/storefront/issues/1270
