### ISSUE TITLE
Category order not respected on Homepage

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/storefront#1111]
Storefront and WooCommerce 3.6.2 do not respect the category order when displayed on the homepage.

Tested with WooCommerce 3.6.1 (and 3.6.2), Homepage Control and Storefront 2.4.5

Category list:
![](https://cld.wthms.co/38kL1n+)Image Link: https://cld.wthms.co/38kL1n

WooCommerce 3.6.1:
![](https://cld.wthms.co/KLsm4a+)Image Link: https://cld.wthms.co/KLsm4a

WooCommerce 3.6.2:
![](https://cld.wthms.co/m4JD6f+)Image Link: https://cld.wthms.co/m4JD6f

**Comment by hannahswain** [comment]
hc-12264505 - sorting is not working for this customer with WooCommerce 3.6.2.  Rolled back to WooCommerce `3.6.1` > customer will report back on status.

It's working correctly for me on WC `3.6.1` and `3.6.2`. Tested the following:

* Update from WC 3.6.1 > 3.6.2 and see if custom sort order is still respected > it is
* Modify sort order > new sort order is showing up correctly

**Comment by tiagonoronha** [comment]
PR here: https://github.com/woocommerce/storefront/pull/1112

**Comment by tiagonoronha** [comment]
@melindahelt @hannahswain 2.4.6 released with a fix for this issue - https://woocommerce.wordpress.com/2019/04/26/storefront-2-4-6-release-notes/

**Comment by melindahelt** [comment]
Thanks for the quick turn around @tiagonoronha

**Comment by hannahswain** [comment]
Thanks @tiagonoronha !
