### ISSUE TITLE
Store Left / Right Pagination Icon Appear Over Gallery Pagination

### ISSUE THREAD

**Issue by DustinHartzler** [woocommerce/storefront#1113]
When a viewing a product's additional images in full-screen mode, the left / right store pagination covers up the image pagination as seen here:
![2019-04-26 at 08 53](https://user-images.githubusercontent.com/2293077/56809040-e99a4100-6800-11e9-90f9-5ac964ff5d1d.png)

This happens with WooCommerce 3.6 and Storefront 2.4.5.

**To reproduce**
- Enable Storefront Pagination
- Navigate to a product page that has multiple images
- Click on the magnifying glass to see the gallery bigger
- Notice the Storefront Pagination overlaps the gallery navigation.

**Comment by dexterski** [comment]
Temporary solution – just add in CSS:
`.pswp {
	z-index: 9999999;
}`

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1117
