### ISSUE TITLE
Brands integration too small images

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/storefront#1116]
Tested with this image: 
![Slide8-300x300](https://user-images.githubusercontent.com/8783673/56901099-a1e11700-6a97-11e9-9ffb-ec6ca4e6dcea.png)

Both the brand page and the product page show as tiny:

Brand: 

![https://cld.wthms.co/BLu7rm](https://cld.wthms.co/BLu7rm+)
Link to image here: https://cld.wthms.co/BLu7rm.

https://github.com/woocommerce/storefront/blob/9b06cbbc9dfa757567e63c62cf8879e91f5cfb2b/assets/css/woocommerce/extensions/brands.scss#L65

Single product:

![https://cld.wthms.co/v2kGmM](https://cld.wthms.co/v2kGmM+)
Link to image here: https://cld.wthms.co/v2kGmM.

https://github.com/woocommerce/storefront/blob/9b06cbbc9dfa757567e63c62cf8879e91f5cfb2b/assets/css/woocommerce/extensions/brands.scss#L141

I presume just making the modularscale for the thumbnails would fix this.

Quick fix in the mean time:

```
.storefront-wc-brands-single-product img {
  max-height: 100px;
}

.tax-product_brand .woocommerce-products-header .brand-thumbnail {
  max-height: 200px;
}
```

**Comment by jobthomas** [comment]
@tiagonoronha I'd probably also suggest to make the max-height on the archive bigger than that on the single product

**Comment by tiagonoronha** [comment]
@jobthomas that image has a huge amount of white space around the logo, that's why you are getting that result.

**Comment by jobthomas** [comment]
I've also left that as a comment for the customer, but currently, the result is less than 36px, which is still very small (fwiw, for the default of the shortcodes, 64px is used), that seems to be a better target, not?

**Comment by jobthomas** [comment]
When cropping to this:

![omega2](https://user-images.githubusercontent.com/8783673/56901894-70694b00-6a99-11e9-8bf1-065db33bc167.png)

![https://cld.wthms.co/90k0bh](https://cld.wthms.co/90k0bh+)
Link to image here: https://cld.wthms.co/90k0bh.

**Comment by tiagonoronha** [comment]
@jobthomas if you completely remove the white space, it looks ok. I think that's an acceptable size, that is not too big or too small.

Image used: 

![omega-gh](https://user-images.githubusercontent.com/1177726/56981406-be07b580-6b76-11e9-81fd-41b11c6b13d1.png)


Here's what it looks like:

<img width="779" alt="Screenshot 2019-04-30 at 18 33 28" src="https://user-images.githubusercontent.com/1177726/56981305-7aad4700-6b76-11e9-852e-05c62e3245df.png">

<img width="735" alt="Screenshot 2019-04-30 at 18 33 17" src="https://user-images.githubusercontent.com/1177726/56981311-7e40ce00-6b76-11e9-8a3a-115de76798b6.png">

**Comment by tiagonoronha** [comment]
@jobthomas ping :)

**Comment by jobthomas** [comment]
Totally missed that. Yeah, I can see that this is big enough. Just offering some custom CSS will be the solution then.
