### ISSUE TITLE
Broken Links in Image Captions

### ISSUE THREAD

**Issue by bradleysa** [woocommerce/storefront#1119]
After updating to Storefront 2.4.6, hyperlinks in the image captions for Jetpack photo galleries are displaying as broken.

**Comment by tiagonoronha** [comment]
Hi @bradleysa, I tested this locally and I couldn't replicate the issue.

I added a "Slideshow" block, added links to the captions of the images, and everything appears to be working correctly.

Storefront doesn't do any modifications to galleries in Jetpack. 

If you're still experiencing this issue, I suggest opening an issue on Jetpack's repo: https://github.com/Automattic/jetpack/issues
