### ISSUE TITLE
Product pagination displaying on top of image gallery navigation

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/storefront#1120]
If I got to a product single page and open the image gallery, the Storefront product pagination buttons are displayed on top of the WooCommerce image gallery navigation buttons, making it harder to go to the previous and next images. Maybe the product pagination buttons shouldn't appear when viewing the image gallery? See screenshot below:

![Screenshot from 2019-05-01 14-50-27](https://user-images.githubusercontent.com/77215/57033538-886cd600-6c23-11e9-8eb1-f89edb58e157.png)

**Comment by tiagonoronha** [comment]
@rodrigoprimo fixed already and pending release :)

https://github.com/woocommerce/storefront/pull/1117
