### ISSUE TITLE
Billing email address not pre-populating on checkout when registered from the My Account page

### ISSUE THREAD

**Issue by admrbsn** [woocommerce/storefront#1123]
When a user registers via the My Account page, the user is successfully registered into WordPress as a customer. When they, however, add a product and go to the checkout page, the billing email address isn't pre-populated into the input field. This seems to be something that was introduced by WooCommerce 6.0 (it works in 5.8).

**Comment by tiagonoronha** [comment]
@admrbsn I just tested with the latest version of WooCommerce and Storefront and the fields are being pre populated, as expected.

If you still think need help with this, please open an issue in the WooCommerce repo: https://github.com/woocommerce/woocommerce

This repository is for the Storefront theme.
