### ISSUE TITLE
Missing Dependencies: the-neverending-homepage (storefront-jetpack-infinite-scroll)

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/storefront#1126]
I installed Debug Bar and it always shows:

Missing Dependencies:
storefront-jetpack-infinite-scroll
wp-content/themes/storefront/assets/css/jetpack/infinite-scroll.css
the-neverending-homepage (missing)

Note:
Fresh install woocommerce and jetpack (default settings)

**Comment by tiagonoronha** [comment]
@erikdemarco I tried to replicate this issue without much luck.

Here's what I did:

* Installed latest Storefront, WooCommerce, Jetpack
* Installed Debug Bar

I checked the homepage, archives, pages, posts, products, and I cannot get Debug Bar to output this error.

Is there anything that I might be missing?

Thank you

**Comment by erikdemarco** [comment]
@tiagonoronha sorry my bad, its  not debug bar, its query monitor:
=> https://wordpress.org/plugins/query-monitor/

See 'Styles' debug information

**Comment by tiagonoronha** [comment]
@erikdemarco thank you, I was able to replicate the issue. You can safely ignore it.

This PR fixes the warning: https://github.com/woocommerce/storefront/issues/1126
