### ISSUE TITLE
[2.5] console errors...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#1128]
Wordpress 5.2.0
Storefront 2.5
Homestore 2.0.31

On all my installation with this environment, I get this console error:

![console errors](https://user-images.githubusercontent.com/30901407/57469163-fdf42a00-7253-11e9-9532-500bd1c8d182.jpg)

**Comment by tiagonoronha** [comment]
Appears to be a WordPress issue: https://core.trac.wordpress.org/ticket/47183
