### ISSUE TITLE
Editor styles do not reflect Customizer changes

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#1130]
Wordpress 5.2.0
Storefront 2.5
Homestore 2.0.31
Powerpack 1.4.15

In the Customizer, go to the Powerpack Designer, select the body, and change to a non-default font.

Save and close, and edit a post/page. Note that the font is not changed in the (Gutenberg) editor. 

(the theme is supposed to specify editor styles)

**Comment by tiagonoronha** [comment]
This is a Powerpack issue, not Storefront.

Closing.
