### ISSUE TITLE
"My Account" page layout changes in Full-Width

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/storefront#1136]
## Issue

When setting the "My Account" page to use the `Fullwidth` page template, the navigation tab switches to the right-hand side with no option to change the default layout.

## Screenshots

With `Fullwidth` page template:

![https://cld.wthms.co/ZChIWh](https://cld.wthms.co/ZChIWh+)
Full Image: https://cld.wthms.co/ZChIWh+

With `Default` page template:

![https://cld.wthms.co/iyEeWR](https://cld.wthms.co/iyEeWR+)
Full Image: https://cld.wthms.co/iyEeWR+

I expected the layout of the tab to stay the same regardless of the page template being used. In my mind, the only thing that should change the layout is when RTL languages are in effect.

I tested with:

* Storefront 2.5.0
* WooCommerce 3.6.2

**Comment by tiagonoronha** [comment]
This is done on purpose. See: https://github.com/woocommerce/storefront/issues/712

The reason why it the navigation doesn't align to right on default is so that it doesn't "clash" with the sidebar, which would make it hard to read.

**Comment by RiaanKnoetze** [comment]
@tiagonoronha - How would one flip it back? I see the decision in #712 but there's no option in either core or Powerpack to change that.

**Comment by tiagonoronha** [comment]
@RiaanKnoetze This change was introduced more than a year ago. You can revert it with CSS:

```
@media (min-width:768px) {
    .page-template-template-fullwidth-php .woocommerce-MyAccount-navigation {
        float: left;
        margin-right: 4.347826087%;
    }

    .page-template-template-fullwidth-php .woocommerce-MyAccount-content {
        float: right;
        margin-right: 0;
    }
}
```

**Comment by uok** [comment]
Thanks for posting the solution, works great in Woo 3.6.5 with Storefront 2.5.1
(although I don't understand why this change was made as full-width does not have a sidebar)
