### ISSUE TITLE
Front Page / Full Width Page Title: storefront_page_header()

### ISSUE THREAD

**Issue by BusinessBloomer** [woocommerce/storefront#1137]
I noticed you updated storefront_page_header() to (maybe) make it Gutenberg-friendly:

```
function storefront_page_header() {
		**if ( is_front_page() && is_page_template( 'template-fullwidth.php' ) ) {
			return;
		}**
		// etc.
```

I believe this new conditional makes no sense. On my full-width static page I want the title to show.

I suggest to change that to:

```
function storefront_page_header() {
		**if ( apply_filters( 'storefront_disable_title_home_fullwidth', is_front_page() && is_page_template( 'template-fullwidth.php' ) ) ) {
			return;
		}**
		// etc.
```

Please let me know

**Comment by ben72** [comment]
@BusinessBloomer see more info on the title here #1127
