### ISSUE TITLE
Address 2 field requests apartment number on en-gb localisation

### ISSUE THREAD

**Issue by Wegerich** [woocommerce/storefront#1139]
In the UK the correct address format runs from smallest "thing" to largest, with the postal code at the end. https://www.postoffice.co.uk/mail/how-to-address-mail

So

> Name
> Company
> Room/Department, Floor, House Name (Address 1)
> Building Number, Street (Address 2)
> City
> County 
> Postal Code

Currently when checking out the placeholder text for Address 1 is "Street number and name" and then Address 2 is "Flat or apartment number (optional)". 

I would like to propose that this is reversed in the en-gb localisation. Alternatively, the placeholder text could be changed to simply "Address Line 1" and "Address Line 2".

**Comment by GlennMartin1** [comment]
This issue should instead be posted in the WooCommerce repo https://github.com/woocommerce/woocommerce/issues/new/choose

**Comment by Wegerich** [comment]
OK, thanks, I have done here 

https://github.com/woocommerce/woocommerce/issues/23755
