### ISSUE TITLE
When we add image overlay with more content at that time overlay should not be a swipe from the image. also Cursor should be in center align.

### ISSUE THREAD

**Issue by nayana96249** [woocommerce/storefront#1146]
Step to follow:

-> Add Cover Block.
-> Add overlay.
-> Add more content.
-> Overlay should not swipe from the image.

Please find the below-attached video :

https://www.screencast.com/t/IKEWfUabh

**Comment by tiagonoronha** [comment]
@nayana96249 please update to the latest version of the theme, this issue has been fixed.

Thank you

**Comment by nayana96249** [comment]
@tiagonoronha Thank you for the update. I have updated the theme and it's working fine now.
