### ISSUE TITLE
"Table" Block: Background color is not getting changed from the "Color Settings"

### ISSUE THREAD

**Issue by rohanraha156** [woocommerce/storefront#1147]
**Steps to recreate:**
1) Create a new page and add the "Table" block.
2) Create a table having two columns and two rows.
3) Try to change the background color of the table from the Color Setting option.
4) The color of the table is not getting changed

Videoclip: https://www.screencast.com/t/5YU0z6xrTtM

Already posted this issue in the below Trac URL:
https://core.trac.wordpress.org/ticket/47400#comment:2

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1167
