### ISSUE TITLE
Cover image block design issue - Storefront theme

### ISSUE THREAD

**Issue by BagthariyaSumit** [woocommerce/storefront#1155]
Theme issue: Storefront 

Version: 2.5.0

Steps to Follow :

1) Active Storefront theme.

2) Open Editor.

3) Add cover image Block.

4) Check the issue design and content text wrapping
Please find the below-attached issue video :
https://www.screencast.com/t/KADVoFuf

**Expected result**
1) Active Twenty Nineteen theme. (Latest version) 

2) Open Editor.

3) Add cover image Block.

4) Check the design of cover image block
Expected Result image
https://www.screencast.com/t/xSTWWbZj

Thank you

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1168
