### ISSUE TITLE
Separator block style preview should be center aligned.

### ISSUE THREAD

**Issue by nayana96249** [woocommerce/storefront#1156]
***Describe the bug***
Separator block style preview should be center aligned.

**/*To reproduce*/**

**/*Steps to reproduce the behavior:*/**

1. Open Editor'.
2. Click on 'Add block option'.
3. Add Separator block.
4. See the style Preview of Separator Block.

**Expected behavior**

Separator style should be in center align.
 
**Please find below Video:**

https://www.screencast.com/t/vpZA2rcQK

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1169
