### ISSUE TITLE
A Guide to managing hooks in Storefront 2.5.0

### ISSUE THREAD

**Issue by blachawk** [woocommerce/storefront#1157]
I have spent days trying to figure out how to apply remove_action effectively for storefront 2.5.0.  Nothing is working for me. 

Why do some people post this as an answer....
`remove_action( 'storefront_homepage', 'storefront_page_content', 20 );`

while other sources post this an answer....
`remove_action( 'homepage', 'storefront_homepage_content', 10 );`

In either case, none of them remove my storefront home page content.

I’m running…
* WordPress 5.2.1
* WooCommerce 3.6.4
* StoreFront 2.5.0

I have a child theme set in place for storefront. The child folder is labeled as storefront-child, and its activated.

I see that the storefront hooks are all located on inc/storefront-template-hooks.php

But copying them over to my functions.php within my child theme and setting them to remove_action, instead of add_action, does absolutely nothing.

Is this a major bug, or am I missing something?

I just want to remove a hook.  Is there an official guide on how to do this with Storefront 2.5.0?

**Comment by tiagonoronha** [comment]
Hi @blachawk!

If you just installed Storefront using the latest version (2.5.0), you most likely got the new homepage: https://docs.woocommerce.com/document/installation-configuration/#section-12

This means that you can now simply edit the "Homepage" page and add or remove blocks in the new editor without the need for custom code.

I hope this helps! :)
