### ISSUE TITLE
Remove comments that aren't required from important comments in style.css

### ISSUE THREAD

**Issue by taishoDev** [woocommerce/storefront#1160]
In style.css that is located in:

/wp-content/themes/storefront/style.css

there is a huge block of comments, all of them marked as important. 

Decent minifiers that respect important comments won’t remove it. Is it really important how sizing is inspired or that I should look no further? Apart from very disputable marketing value (attract developers viewing CSS file, who can see that theme generates hardly removable bloat in CSS), I can’t see any reason to put most of this stuff as important.

I suggest putting all copyright and license info together as important because this is legally required and the rest as a standard comment. Sooner or later developers or clients look at page load metrics and what they see is that there is a major minification problem with Storefront theme.

```
/*!
Theme Name:   Storefront
Theme URI:    https://woocommerce.com/storefront/
Author:       Automattic
Author URI:   https://woocommerce.com/
Description:  Storefront is the perfect theme for your next WooCommerce project. Designed and developed by WooCommerce Core developers, it features a bespoke integration with WooCommerce itself plus many of the most popular customer facing WooCommerce extensions. There are several layout & color options to personalise your shop, multiple widget regions, a responsive design and much more. Developers will love its lean and extensible codebase making it a joy to customize and extend. Looking for a WooCommerce theme? Look no further!
Version:      2.5.0
License:      GNU General Public License v2 or later
License URI:  https://www.gnu.org/licenses/gpl-2.0.html
Text Domain:  storefront
Tags:         e-commerce, two-columns, left-sidebar, right-sidebar, custom-background, custom-colors, custom-header, custom-menu, featured-images, full-width-template, threaded-comments, accessibility-ready, rtl-language-support, footer-widgets, sticky-post, theme-options, editor-style

This theme, like WordPress, is licensed under the GPL.
Use it to make something cool, have fun, and share what you've learned with others.

Storefront is based on Underscores https://underscores.me/, (C) 2012-2017 Automattic, Inc.

Resetting and rebuilding styles have been helped along thanks to the fine work of
Eric Meyer https://meyerweb.com/eric/tools/css/reset/index.html
along with Nicolas Gallagher and Jonathan Neal http://necolas.github.com/normalize.css/

All sizing (typography, layout, padding/margins, etc) are inspired by a modular scale that uses 1em as a base size with a 1.618 ratio.
You can read more about the calculator we use in our Sass here: https://github.com/modularscale/modularscale-sass

FontAwesome License: SIL Open Font License - http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL
Images License: GNU General Public License v2 or later

======
Note: Do not edit this file. If you wish to add your own CSS, go to Customizer > Additional CSS.
======
*//*!
 * normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css
 */
```

**Comment by tiagonoronha** [comment]
@taishoDev thank you for your suggestions. I looked into it and from everything that's currently in the commented section, the "Do not edit" note is the only bit that can be moved to a non-important comment.

We'd like to keep all copyright & credit comments as they are.

I implemented this change in https://github.com/woocommerce/storefront/issues/1160.

**Comment by GlennMartin1** [comment]
@tiagonoronha  implemented in https://github.com/woocommerce/storefront/pull/1171

**Comment by taishoDev** [comment]
Comments like "Use it to make something cool, have fun, and share what you've learned with others." are still considered important. Very disappointing.

**Comment by tiagonoronha** [comment]
Let's agree to disagree.

You're free to create a child theme, dequeue the main Storefront stylesheet and compile your own.
