### ISSUE TITLE
Shipping choices table crammed

### ISSUE THREAD

**Issue by sandrodz** [woocommerce/storefront#1164]
While working on the shipping plugin, I've noticed that storefront shipping table looks weird. Left side is empty and right side is crammed.

<img width="1248" alt="Screen Shot 2019-06-17 at 1 47 54 PM" src="https://user-images.githubusercontent.com/8479569/59595307-965cb480-9106-11e9-9995-9835f9740ecb.png">

`th` at 50% looks way better:

<img width="1159" alt="Screen Shot 2019-06-17 at 1 49 59 PM" src="https://user-images.githubusercontent.com/8479569/59595433-d6239c00-9106-11e9-917b-0c0f7a8382da.png">

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1172
