### ISSUE TITLE
Featured image size

### ISSUE THREAD

**Issue by ElPablo010** [woocommerce/storefront#1174]
I have set up a new website based on the Storefront theme. When I hover over the featured image on my single product page, the image becomes larger in size. Is this normal behaviour, or is this a bug? 
<img width="1281" alt="Schermafbeelding 2019-06-26 om 06 11 51" src="https://user-images.githubusercontent.com/47521855/60150595-9c732500-97d9-11e9-8b39-08cf9239cb1c.png">
<img width="1390" alt="Schermafbeelding 2019-06-26 om 06 11 59" src="https://user-images.githubusercontent.com/47521855/60150596-9ed57f00-97d9-11e9-8b03-8fa654f6137f.png">

**Comment by BusinessBloomer** [comment]
+1

Note: this behavior happens when the single product page template is made into full-width i.e. the sidebar is removed via remove_action() and CSS is used to make the #primary element 100% width

**Comment by ElPablo010** [comment]
And what do you suggest to fix this?

Mvg,
Bien à vous,
Kind regards,

**Comment by tiagonoronha** [comment]
@ElPablo010 you appear to be using a customized version of Storefront.

By default, the width of the single product images is 416px. However, when making changes to the theme this number might not be correct anymore.

If you're using a child theme, you can define the new size in your functions.php file:

```
add_filter( 'storefront_woocommerce_args', 'gh_1174_woocommerce_support' );

function gh_1174_woocommerce_support( $args ) {
    $args['single_image_width']    = 416;
    $args['thumbnail_image_width'] = 324;
    return $args;
}
```

Thanks!
