### ISSUE TITLE
store_credit_link conditional incorrectly wraps the privacy link as well as the credit link. (version 2.5.0)

### ISSUE THREAD

**Issue by johngarnett** [woocommerce/storefront#1175]
In version 2.5.0 of the storefront theme, storefront/inc/storefront-template-functions.php

function storefront_credit()

This conditional:   <?php if ( apply_filters( 'storefront_credit_link', true ) ) { ?>

is incorrectly wrapping the_privacy_policy_link as well as the storefront_credit_link.

It should be possible to disable the credit link without also disabling the privacy link, but as the code is written, it isn't possible without adding a replacement storefront_credit() function in the child theme's functions.php.

Thanks,
John Garnett

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1178
