### ISSUE TITLE
Wide and full alignment controls do not respect selected page template

### ISSUE THREAD

**Issue by mahdiyazdani** [woocommerce/storefront#1179]
It seems both wide and full alignment controls are still visible and functional in both default and full-width page templates.

![](https://i.imgsafe.org/49/4934c54c52.gif)

**Comment by juliaamosova** [comment]
Thank you for raising this issue @mahdiyazdani. I can reproduce the same.

**Comment by nielslange** [comment]
Closing in benefit of https://github.com/woocommerce/storefront/issues/1270
