### ISSUE TITLE
WC Products by Category block does not respect columns

### ISSUE THREAD

**Issue by ajgw** [woocommerce/storefront#1197]
If I create a products by category block into post/page, last product in first row breaks into next row. Following products are as expected. This is related to Storefront 2.5.3.

![Bildschirmfoto 2019-08-20 um 13 23 29](https://user-images.githubusercontent.com/3390880/63343212-b77f9280-c34d-11e9-87d0-c3463f02f928.png)

**Comment by vedanshujain** [comment]
I am not able to reproduce on a fresh StoreFront + WooCommerce install. Can you please provide a System report from Dashboard -> WooCommerce -> Status. 
Can you also specify what is your screen resolution, this can help us in reproducing the issue.

**Comment by ajgw** [comment]
Well, I gave it another test on a sting site. I deactivated all plugins except Woocommerce. I have setup only one block Products by Category with setting 3 columns, 2 rows. I had Woocommerce 3.6.5 and Storefront 2.5.1 on site and did a screenshot at start of test, after update Woocommerce to 3.7.0 and last after update of Storefront to 2.5.3:

![Woocommerce 3-6-5 and Storefront 2-5-1](https://user-images.githubusercontent.com/3390880/63538730-c5cdda00-c518-11e9-8bc7-216c742db322.png)

![Woocommerce 3-7-0 and Storefront 2-5-1](https://user-images.githubusercontent.com/3390880/63538750-d5e5b980-c518-11e9-9994-25f3aa568151.png)

![Woocommerce 3-7-0 and Storefront 2-5-3](https://user-images.githubusercontent.com/3390880/63538769-dd0cc780-c518-11e9-8a06-a18170348cc3.png)

**Comment by ajgw** [comment]
You can see in first row that last product is not in row, it is broken into next row.

**Comment by ajgw** [comment]
Screenresolution is Macbook Pro 15 inch Retina = 2880 by 1800 px. Systemreport:

`
### WordPress Environment ###

WordPress address (URL): https://stage.dekuenst.de
Site address (URL): https://stage.dekuenst.de
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.6-nmm1
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.44-nmm1-log
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: x5y1j_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 1.58MB
Datenbank-Datengröße: 1.18MB
Datenbank-Indexgröße: 0.40MB
x5y1j_woocommerce_sessions: Daten: 0.04MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_order_itemmeta: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_woocommerce_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_commentmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_comments: Daten: 0.07MB + Index: 0.06MB + Engine MyISAM
x5y1j_frm_fields: Daten: 0.03MB + Index: 0.01MB + Engine MyISAM
x5y1j_frm_forms: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
x5y1j_frm_items: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_frm_item_metas: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_links: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_ms_snippets: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_options: Daten: 0.80MB + Index: 0.07MB + Engine MyISAM
x5y1j_postmeta: Daten: 0.10MB + Index: 0.05MB + Engine MyISAM
x5y1j_posts: Daten: 0.11MB + Index: 0.07MB + Engine MyISAM
x5y1j_snippets: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_termmeta: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_terms: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_term_relationships: Daten: 0.01MB + Index: 0.02MB + Engine MyISAM
x5y1j_term_taxonomy: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_ukuu_favorites: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_usermeta: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
x5y1j_users: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_wcpv_commissions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_wcpv_per_product_shipping_rules: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_wc_admin_notes: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_wc_admin_note_actions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_wc_customer_lookup: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_wc_download_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_wc_order_coupon_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_wc_order_product_lookup: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_wc_order_stats: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_wc_order_tax_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_wc_product_meta_lookup: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_wc_tax_rate_classes: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
x5y1j_wc_webhooks: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
x5y1j_wpmelon_advbedit_temp: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: von Automattic – 3.7.0

### Inactive Plugins (21) ###

BackWPup: von Inpsyde GmbH – 3.6.10
Code Snippets: von Shea Bunge – 2.13.3
Formidable Forms: von Strategy11 – 4.01.02
Formidable Forms Pro: von Strategy11 – 4.01.02
Germanized for WooCommerce: von Vendidero – 2.3.2 – Nicht getestest mit der aktiven WooCommerce-Version
Germanized for WooCommerce Pro: von Vendidero – 1.10.0 – Nicht getestest mit der aktiven WooCommerce-Version
Opening Hours: von Jannik Portz – 2.1.4
Storefront Footer Bar: von WooThemes – 1.0.4
Storefront Parallax Hero: von WooCommerce – 1.5.7
Storefront Powerpack: von WooCommerce – 1.5.0
Storefront Visual Hook Guide: von Antonio Sanchez (ARCHTKT) – 2.0.1 – Nicht getestest mit der aktiven WooCommerce-Version
Vendidero Helper: von Vendidero – 1.2.1
WooCommerce Admin: von WooCommerce – 0.15.0 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Advanced Bulk Edit: von George Iron – 4.4.3-beta4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Cash On Pickup: von Marian Kadanka – 1.5 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Name Your Price: von Kathy Darling – 2.9.5 – 2.10.0 ist verfügbar – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Product Add-ons: von WooCommerce – 3.0.13 – 3.0.14 ist verfügbar – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Product Vendors: von WooCommerce – 2.1.18 – 2.1.19 ist verfügbar – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Subscriptions: von Automattic – 2.5.7 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Subscriptions - Preserve Billing Schedule: von Prospress Inc. – 1.0.0 – Nicht getestest mit der aktiven WooCommerce-Version
wpSEO: von Team wpSEO – 4.5.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop-Basis: #9 - /shop/
Warenkorb: #10 - /warenkorb/
Kasse: #11 - /kasse/
Mein Konto: #12 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 226
Oldest: 2019-07-22 21:53:33 +0200
Newest: 2019-08-22 20:02:36 +0200

Pending: 3
Oldest: 2019-08-28 15:01:37 +0200
Newest: 2020-01-15 02:00:00 +0100

Canceled: 1
Oldest: 2019-08-22 20:55:35 +0200
Newest: 2019-08-22 20:55:35 +0200

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by ajgw** [comment]
Beside I saw that this block isn't any longer responsive on mobile. I saw a similar post at github Woocommerce latest release about.

**Comment by ajgw** [comment]
If I deselect in style.css wc-block-grid-products the value display: flex;, then last image moves back to first line – it does not break anymore into next line.

Is it a Safari desktop version 12 issues? But on Mobile iPhone it is same and block isn't responsive!

**Comment by vedanshujain** [comment]
I can reproduce on Safari desktop but not on Chrome or Firefox. Blocks not being responsive is a different issue though and is being tracked at https://github.com/woocommerce/woocommerce/issues/24444 as you mentioned. These two seem unrelated.
