### ISSUE TITLE
CSS .product-name column 45% width incorrect for smaller screens

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/storefront#1202]
file: /storefront/assets/css/woocommerce/woocommerce.css?ver=2.5.3

line 986

```
table.woocommerce-checkout-review-order-table .product-name {
  width: 45%;
  word-wrap: break-word; }
```
The width needs to be confined to screens 768 px upwards, otherwise on handheld view the title gets squashed to the left. 

Screenshot: 
<img width="575" alt="Bildschirmfoto 2019-09-04 um 14 44 22" src="https://user-images.githubusercontent.com/19706428/64256296-78436b00-cf23-11e9-9b25-60b3c480ef09.png">

**Comment by juliaamosova** [comment]
@EdithAllison can you please provide steps to reproduce the issue? 

So far the checkout page looks good on my end in handheld view:

![Screenshot_20191115-154918](https://user-images.githubusercontent.com/19143190/68952173-b54b9980-07bf-11ea-9ed9-2ba864a95b63.png)

**Comment by EdithAllison** [comment]
Hi juliaamosova, apologies, I've tested and it's an issue with the theme we are using which shows the price below the product title instead of next to it. Apologies for the incorrect bug report. I can confirm that everything works correctly on handheld with the default Storefront theme. Thank you for checking! Edith

**Comment by juliaamosova** [comment]
Thanks for your follow-up @EdithAllison!
