### ISSUE TITLE
Impossible to enter an apostrophe in Site Title in Customizer

### ISSUE THREAD

**Issue by jfarsen** [woocommerce/storefront#1203]
I'm using the Canada Multilingual (French) keyboard on Mac OS, and the combination key to write an apostophe is SHIFT-comma.

For an unknown reason, using this in any software works, but in the WP Customizer, it doesn't. I doesn't work in the Site Title field, or any other WP Customizer field for that matter.

**Comment by keusta** [comment]
hello @jfarsen  you try ' (shift + 4)  but maybe you should try ’ (alt + 4) on mac keyboard.
The reason is that prog language is using simple quote 'to embed variable' so when you put one in your title it must be escaped /' to work..

**Comment by juliaamosova** [comment]
@jfarsen I can't reproduce this. I am using the `Canadian French - CSA` Keyboard on my Mac:

<img width="237" alt="Screen Shot 2019-11-15 at 3 40 07 PM" src="https://user-images.githubusercontent.com/19143190/68951465-69e4bb80-07be-11ea-8193-33434bfd35e0.png">

`Shift + comma` works well for me in the Customizer and apostrophe (`'`) can be added without any issues:

![ap](https://user-images.githubusercontent.com/19143190/68951812-1626a200-07bf-11ea-9451-cf3c024de540.jpg)

I am using MacOS Catalina version 10.15.1. What OS are you using?

**Comment by nerrad** [comment]
Hi there, this issue has been open for a while with no response, and we were unable to reproduce. 

I'm going to close this, but if there's anything to add please do leave a comment and we can consider re-opening.
