### ISSUE TITLE
Use Bootstrap with storefront

### ISSUE THREAD

**Issue by tranminhdz** [woocommerce/storefront#1210]
Hi,

I use bootstrap 4 with storefront and the style is broken. How can I use Bootstrap with storefront?

Thanks

**Comment by juliaamosova** [comment]
@tranminhdz it would be good to know what kind of issues you are having exactly. Please provide us with a bit more details so we could take a look further.

**Comment by haszari** [comment]
Closing this issue. Please reopen or add a more specific issue with more details of the problem.
