### ISSUE TITLE
Ensure compatibility with WP 5.3

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/storefront#1213]
WordPress 5.3 brings some changes to templates, as described in the [release post](https://wordpress.org/news/2019/09/wordpress-5-3-beta-1/) and also on [WP Tavern](https://wptavern.com/preparing-themes-for-wordpress-5-3). We need to ensure Storefront is compatible.

**Comment by vedanshujain** [comment]
Looks we are compatible with 5.3, I tested following things:

1.  Group Block nested with Products block with multiple columns, Columns block and Gallery block on multiple screen sizes. We are rendering expected number of columns even with multiple columns so looks like everything is fine there (except for unresponsiveness on small screen size which will be resolved by #1200 ). 

2. `alignwide` and `alignfull` CSS classes for blocks when side bar was not present. They were also working as expected. 

3. `has-x-columns` class present in multiple product blocks was also working as expected when nested inside Group or Column block.

4. Checked that we don't have any custom CSS for table and group block.

5. Gallery block output is changed, but looks like our render is visually similar to pre 5.3 and multiple columns are working here as well. 

It does not look like any of the other dev notes are relevant to us, but I will update if they are. I am closing this issue but will re-open if a dev note is published which might be relevant. Feel free to comment in case I have missed something.

**Comment by vedanshujain** [comment]
Took a look at the [5.3 field guide again](https://make.wordpress.org/core/2019/10/17/wordpress-5-3-field-guide/) now that RC4 has been released, I don't see anything that will cause conflict with StoreFront theme.
An important area where conflicts might be is with grids, but in my last round of testing, they were working as expected and there aren't any changes since then.
