### ISSUE TITLE
Typography text color affects site pages and gutenburg editor

### ISSUE THREAD

**Issue by dpet** [woocommerce/storefront#1214]
My site has a dark background and white text. I have to set the text to white in the typography section in the customizer. When I edit in Gutenburg I can't see the text because it has turned white.

**Comment by juliaamosova** [comment]
Thanks for raising this issue @dpet. I can reproduce it. 

Here is how the post looks at the front end:

![dark](https://user-images.githubusercontent.com/19143190/68949176-c09bc680-07b9-11ea-825e-a45ee66530cb.jpg)

And here is how it looks at the back end of you try to edit it using Gutenberg editor:

![light](https://user-images.githubusercontent.com/19143190/68949183-c42f4d80-07b9-11ea-817c-71464864b34b.jpg)

We should likely keep the text of the page / post black in the editor despite of the color it has at the front end.

**Comment by juliaamosova** [comment]
There is a previously reported issue exist which is related to the same issue: https://github.com/woocommerce/storefront/issues/1181. 

Closing this one as a duplicate. Please continue to discuss in https://github.com/woocommerce/storefront/issues/1181.
