### ISSUE TITLE
Possible to de-queue or optimize Fontawesome loading?

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/storefront#1218]
2433256-zd

A customer reached out today saying the following:

> Is there any chance to dequeue fontawesome? Or to optimize the loading? Because google insights is complaining about it.

Is this something that we've heard from customers before with Font Awesome cdn loading slowly? And is there anything on our side (Storefront) that would be slowing down that load at all?

**Comment by ben72** [comment]
#1089 #524

**Comment by FreshPhil** [comment]
Ahh thanks @ben72 !
I'll close this.

**Comment by ben72** [comment]
@FreshPhil np! you can add any comments to #1089
