### ISSUE TITLE
Move 'Product Page' customizer menu under 'WooCommerce'

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/storefront#1224]
### Description

Storefront adds a 'Product Page' in the customizer where the "Sticky Add to Cart" and "Product Pagination" options are located.

Since these are WooCommerce-related, it might make sense to move them under the 'WooCommerce' section, which is added by WooCommerce.

Not really an issue, but quite straightforward and yields a more consistent, no-surprises UX = low-hanging fruit here.

**Comment by GlennMartin1** [comment]
I like that idea.

Be aware that some folks use Storefront without using WooCommerce.

**Comment by franticpsyx** [comment]
@GlennMartin1 the 'Product Page' menu item is only added when WooCommerce is active, as far as I can tell. So the proposed change only affects users who have installed WC.

**Comment by juliaamosova** [comment]
Thank you for bringing this up @franticpsyx. I agree that moving the `Product page` section to `WooCommerce` makes sense and will add to the consistent UI experience.

**Comment by nielslange** [comment]
@franticpsyx, @GlennMartin1 & @juliaamosova I've addressed this enhancement in https://github.com/woocommerce/storefront/pull/1244. Feel free to test the PR and let me know if something needs to be adjusted.
