### ISSUE TITLE
Add `rel="noopener"` or `rel="noreferrer"` for Built with Storefront & WooCommerce in footer

### ISSUE THREAD

**Issue by shirokoweb** [woocommerce/storefront#1229]
Since `<a href="https://woocommerce.com" target="_blank" title="WooCommerce - The Best eCommerce Platform for WordPress" rel="author">Built with Storefront &amp; WooCommerce</a>`  footer link has a "_blank" attribute, it **MUST** include `rel="noopener"` or `rel="noreferrer"` attributes for obvious security reasons.
Oh and by the way, [authorship markup is no longer supported in web search](https://support.google.com/webmasters/answer/6083347?hl=en).

**Comment by juliaamosova** [comment]
Thanks for reporting the issue @shirokoweb.

**Comment by nielslange** [comment]
@shirokoweb & @juliaamosova I fixed this issue in https://github.com/woocommerce/storefront/pull/1243. Feel free to test the fix and let me know if the PR needs to be adjusted.

**Comment by GlennMartin1** [comment]
This is a good improvement.

However, I think that line should be changed a bit further, because Storefront is used on themes **without** using WooCommerce at all.

Because of that:
- the text should not include reference to WooCommerce, perhaps simply `Built with Storefront.`
- the hover text should be reworded, too; not sure exactly what.

Thanks!

**Comment by nielslange** [comment]
> This is a good improvement.
> 
> However, I think that line should be changed a bit further, because Storefront is used on themes **without** using WooCommerce at all.
> 
> Because of that:
> 
> * the text should not include reference to WooCommerce, perhaps simply `Built with Storefront.`
> * the hover text should be reworded, too; not sure exactly what.
> 
> Thanks!

@GlennMartin1: I've adjusted the logic as follows.

**If WooCommerce is active:**

- Link: https://woocommerce.com
- Hover: WooCommerce - The Best eCommerce Platform for WordPress
- Label: Built with Storefront &amp; WooCommerce

**If WooCommerce is not active:**

- Link: https://woocommerce.com/storefront/
- Hover: Storefront -  The perfect platform for your next WooCommerce project.
- Label: Built with Storefront

**Comment by GlennMartin1** [comment]
LGTM!
