### ISSUE TITLE
Navigation Block not working with bold style

### ISSUE THREAD

**Issue by AtrumGeost** [woocommerce/storefront#1237]
## Describe the bug
When you add the Navigation Block and set the Bold style it won't be rendered in the front end.

## To Reproduce
1. Go to a page or post
2. Add the Navigation block
3. Add a menu item
4. Set the bold style for the menu item
5. Publish/Update

## Screenshots

![Screen Shot 2019-12-17 at 16 14 29](https://user-images.githubusercontent.com/3696121/71034916-69ef1880-20e8-11ea-994a-83c50fbf03fb.png)

![Screen Shot 2019-12-17 at 16 27 41](https://user-images.githubusercontent.com/3696121/71035767-2f867b00-20ea-11ea-8558-6907322f3f1b.png)

## Expected behavior

For the menu item to be displayed in bold style

### Browser Environment

Google Chrome Version 79.0.3945.79 (Official Build) (64-bit)

- Platform: macOS Catalina 10.15.1 (19B88)

**Comment by nielslange** [comment]
@AtrumGeost This issue is caused by Gutenberg and had been reported on https://github.com/WordPress/gutenberg/issues/18844 already.

**Comment by AtrumGeost** [comment]
Oh, ok. Thank you, @nielslange! I'm closing this issue :)
