### ISSUE TITLE
SEARCH FORM ELEMENT HAS A 1.618 EM MARGIN-BOTTOM

### ISSUE THREAD

**Issue by Javier-vega** [woocommerce/storefront#1240]
## Describe the bug

Using Storefront theme it seems that the element Search Form (a part of Elementor) has a 1.618 em margin-bottom, so I can not get it centered vertically as the rest of elements. There is no problem with Twenty Sixteen theme, or Twenty Twenty, only with Storefront.

Guys from Elementor told me that:

_This property is not related to Elementor, but to all of the form tags in Storefront theme._

_You can override it by using:_

form.elementor-search-form {
    margin-bottom: 0;
}

Isolating the problem (mark completed items with an [x]):
- [   **Using Elementor** ]   I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [X] I can reproduce this bug consistently using the steps below.

## To Reproduce

1. Create a page.
2. Edit with Elementor
3. Add a Search from element
4. The search box will appear with a 1.618 margin bottom

## Screenshots
![margin-bottom](https://user-images.githubusercontent.com/59137766/71325371-13207f00-24ec-11ea-8317-1670042dacd2.png)

## Expected behavior
No margin bottom by default.

### Browser Environment

- Platform: Windows 10.
- Browser(s): Chrome.
- Plugins: Elementor Pro

### WordPress Environment

<details>
`
### WordPress Environment ###

WordPress address (URL): https://casita2.lacasitademimbre.com
Site address (URL): https://casita2.lacasitademimbre.com
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.12
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.30-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: cs_
MaxMind GeoIP Database: ✔
Tamaño total de la base de datos: 24.46MB
Tamaño de los datos de la base de datos: 18.67MB
Tamaño del índice de la base de datos: 5.79MB
cs_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cs_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
cs_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cs_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
cs_woocommerce_order_items: Datos: 0.16MB + Índice: 0.06MB + Motor InnoDB
cs_woocommerce_order_itemmeta: Datos: 1.52MB + Índice: 0.66MB + Motor InnoDB
cs_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
cs_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
cs_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
cs_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cs_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
cs_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cs_aelia_dismissed_messages: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_aelia_exchange_rates_history: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_commentmeta: Datos: 0.08MB + Índice: 0.07MB + Motor MyISAM
cs_comments: Datos: 0.31MB + Índice: 0.20MB + Motor MyISAM
cs_links: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
cs_litespeed_img_optm: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
cs_litespeed_optimizer: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
cs_mailchimp_carts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_mailchimp_jobs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_options: Datos: 2.63MB + Índice: 0.18MB + Motor MyISAM
cs_postmeta: Datos: 9.55MB + Índice: 1.99MB + Motor MyISAM
cs_posts: Datos: 2.15MB + Índice: 0.48MB + Motor MyISAM
cs_termmeta: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
cs_terms: Datos: 0.02MB + Índice: 0.06MB + Motor MyISAM
cs_term_relationships: Datos: 0.26MB + Índice: 0.47MB + Motor MyISAM
cs_term_taxonomy: Datos: 0.03MB + Índice: 0.03MB + Motor MyISAM
cs_tinvwl_analytics: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cs_tinvwl_items: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_tinvwl_lists: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_usermeta: Datos: 0.92MB + Índice: 0.55MB + Motor MyISAM
cs_users: Datos: 0.07MB + Índice: 0.05MB + Motor MyISAM
cs_wcpdf_invoice_number: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cs_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
cs_wc_customer_lookup: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
cs_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
cs_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
cs_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
cs_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
cs_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
cs_wc_product_meta_lookup: Datos: 0.08MB + Índice: 0.16MB + Motor InnoDB
cs_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cs_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
cs_yoast_seo_links: Datos: 0.09MB + Índice: 0.05MB + Motor InnoDB
cs_yoast_seo_meta: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

CMP - Coming Soon & Maintenance Plugin: por NiteoThemes – 3.6.8
Elementor Pro: por Elementor.com – 2.8.1
Elementor: por Elementor.com – 2.8.2
Facebook for WooCommerce: por Facebook – 1.9.15 – No probado con la versión activa de WooCommerce
LitExtension Customer Password Plugin: por LitExtension – 1.0.0
Limit Login Attempts Reloaded: por WPChef – 2.10.0
Loco Translate: por Tim Whitlock – 2.3.1
Mailchimp for WooCommerce: por Mailchimp – 2.3 – No probado con la versión activa de WooCommerce
Perfect WooCommerce Brands: por Alberto de Vera Sevilla – 1.7.7
Product Variation Swatches for Woocommerce: por ThemeHigh – 1.0.4
TI WooCommerce Wishlist Plugin: por TemplateInvaders – 1.15.4
WC - APG Campo NIF/CIF/NIE: por Art Project Group – 1.4.0.1 – No probado con la versión activa de WooCommerce
Additional Variation Images Gallery for WooCommerce: por Emran Ahmed – 1.1.34
WooCommerce Admin: por WooCommerce – 0.23.2
WooCommerce PayPal Checkout Gateway: por WooCommerce – 1.6.18
WooCommerce Stripe Gateway: por WooCommerce – 4.3.1
Booster for WooCommerce: por Algoritmika Ltd – 4.6.1
WooCommerce Multiple Customer Addresses: por Lagudi Domenico – 16.3 – No probado con la versión activa de WooCommerce
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 2.4.2
WooCommerce Services: por Automattic – 1.22.2
WooCommerce: por Automattic – 3.8.1
Yoast SEO: por Equipo Yoast – 12.7.1

### Inactive Plugins (8) ###

Akismet Anti-Spam: por Automattic – 4.1.3
Checkout Field Editor for WooCommerce: por ThemeHigh – 1.4.0
EU VAT for WooCommerce: por Algoritmika Ltd – 1.7.2
Jetpack by WordPress.com: por Automattic – 8.0
La Casita de Mimbre: por Oscar Zamora – 1.0.0
LiteSpeed Cache: por LiteSpeed Technologies – 2.9.9.2
WooCommerce Checkout & Account Field Editor: por ThemeLocation – 1.2.3 – No probado con la versión activa de WooCommerce
WooCommerce EU VAT Assistant: por Aelia – 1.12.1.191217

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

installatron_hide_status_test.php: por  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #2919 - /tienda/
Carrito: #2920 - /carrito/
Finalizar compra: #2921 - /finalizar-compra/
Mi cuenta: #2922 - /mi-cuenta/
Términos y condiciones: #2850 - /condiciones-de-contratacion/

### Theme ###

Name: Storefront Child
Version: 1.0.0
Author URL: https://www.drimway.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: /home/drimway/casita2.lacasitademimbre.com/wp-content/plugins/woo-variation-gallery/templates/product-images.php
/home/drimway/casita2.lacasitademimbre.com/wp-content/plugins/woo-variation-gallery/templates/product-thumbnails.php

### Plantillas de TI WooCommerce Wishlist ###

Anulaciones: –

### Action Scheduler ###

Complete: 365
Oldest: 2019-12-02 21:00:16 +0100
Newest: 2019-12-22 18:51:09 +0100

Pending: 2
Oldest: 2019-12-22 19:51:09 +0100
Newest: 2019-12-22 19:51:09 +0100

Canceled: 2
Oldest: 2019-12-06 20:17:35 +0100
Newest: 2019-12-07 13:45:30 +0100

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by haszari** [comment]
Thanks for reaching out @Javier-vega ! It looks to me like the suggested css override would work well. Is that solution workable for you? You could add this to Customizer or to a child theme.

```
form.elementor-search-form {
margin-bottom: 0;
}
```

**Comment by Javier-vega** [comment]
Hi @haszari , yes, that solution is the one I am using, but maybe the correct solution would be to fix it in Storefront (I am not a developer, I don't know the difficulty of fixing that in Storefront).
Thanks for your answer!

**Comment by haszari** [comment]
Closing this – the impact is low and there is an easy & safe workaround.
