### ISSUE TITLE
Create a social icon menu

### ISSUE THREAD

**Issue by nunomarques2** [woocommerce/storefront#1245]
Hi,

I have tested this https://docs.woocommerce.com/document/create-a-social-icon-menu/
and woocommerce test it and cant put social icons in the secondary menu.

WP.comSat, Dec 28, 5:44 PM
I tested the code myself and wasn't able to get it to work either. It looks like the code is from 2 years ago. Sometimes, Storefront makes updates that could affect this, so per the doc, it looks like you'll need to create an issue on our public repo here: https://github.com/woocommerce/storefront/issues/new

**Comment by nunomarques2** [comment]
Need Help here

**Comment by cliffathouriste** [comment]
No one on here describes the problem in details or reenacts the problem so others can help them I am sitting up here tearing a whole inside of the storefront theme using it in a framework capacity and have a great understanding of it but these but these issues but these issues aren't detailed enough to give you help

**Comment by nunomarques2** [comment]
It works! sorry for the mistake
