### ISSUE TITLE
Is Storefront abandoned?

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#1248]
From August 2019 to the present (about 5 months), there were 0 releases.

In the 12 months prior to August 2019, there were 12 releases, average 1 per month.

Is Storefront abandoned?

**Comment by pmcpinto** [comment]
Hi @GlennMartin1,

Apologies for the late reply on this issue. Storefront is not abandoned, we’re going to address some of the high-priority issues that we have right now in the repo and we plan to have a release coming soon.

During the past few months, we were more focused on creating WooCommerce blocks that bring more functionality and flexibility for building sites using Storefront. You can have access to our latest blocks by downloading our [feature plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/). As an example, we’re currently working in the cart and checkout blocks and we’re confident that they’ll represent a great alternative to the current checkout experience.

Stay tuned for more updates!
