### ISSUE TITLE
Product grid blocks: image is aligned to the left when there are few columns

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/storefront#1250]
**To Reproduce**
1. Add a _Top Rated Products_ block.
2. Set the number of columns to 1 or 2.
3. In the editor, notice the image is aligned to the left instead of being centered.

**Screenshots**
![imatge](https://user-images.githubusercontent.com/3616980/73081577-29917000-3ec8-11ea-90af-d4cefa3a74a9.png)

**Comment by Aljullu** [comment]
I moved this issue to Storefront since it looks to only affect that theme. In the frontend, there is specific CSS to fix this:

https://github.com/woocommerce/storefront/blob/master/assets/css/woocommerce/woocommerce.scss#L350-L353

However, that file is not loaded in the editor. I think all code comprised between [line 303 and line 371](https://github.com/woocommerce/storefront/blob/master/assets/css/woocommerce/woocommerce.scss#L303-L371) should be moved to another file that is loaded both in the frontend and in the editor.

**Comment by haszari** [comment]
Thanks for reporting this @Aljullu. Added to 2.5.5 as it would be good to tidy this up.

**Comment by haszari** [comment]
We've tagged 2.5.5 RC 1 including this fix - @Aljullu feel free to grab the zip file and test it out :)

https://github.com/woocommerce/storefront/releases/tag/version%2F2.5.5-rc.1

**Comment by Aljullu** [comment]
@haszari I did some smoke testing with 2.5.5 RC1 and everything looked good to me. :+1:
