### ISSUE TITLE
Empty Cart image is not centered

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/storefront#1255]
According to the designs, it should be centered:
![imatge](https://user-images.githubusercontent.com/3616980/72904649-86a5ee00-3d2f-11ea-9a12-9d5ed3bb801c.png)

**Comment by Aljullu** [comment]
It looks like this issue is only reproducible on Storefront and with the last version of Gutenberg installed.

**Comment by haszari** [comment]
@Aljullu this issue affects the cart block in WooCommerce Blocks (which are still in development). With that in mind, let's hold off on fixing this for now.

**Comment by Aljullu** [comment]
Actually I noticed this issue is affecting all image blocks:
1. Add an image block.
2. Set its size to 25%, for example.
3. Notice the toolbar marks it as `centered`, but in fact, it's left aligned.
4. Switch to another theme (2020, for example) and notice the image is centered.

![Peek 2020-02-20 13-43](https://user-images.githubusercontent.com/3616980/74934673-07b3dc00-53e7-11ea-84dd-3cf39c8efbfa.gif)

Back in Storefront, pressing _Align center_ correctly centers it, but default styles differ from the rest of themes.

**Comment by haszari** [comment]
> Notice the toolbar marks it as centered, but in fact, it's left aligned.

Good find! I'm thinking we should report that as a separate issue. I also noticed that there are some quirks with full/wide alignment in Storefront.

**Comment by Aljullu** [comment]
> I'm thinking we should report that as a separate issue. 

I think they are the same bug, fixing one will fix the other and the other way around. The _Cart_ block is using an inner image block.

**Comment by haszari** [comment]
Does this bug still occur with #1296 fix?

**Comment by Aljullu** [comment]
@haszari I answered there. :slightly_smiling_face:

**Comment by haszari** [comment]
Round 2 .. is this still an issue @Aljullu ? :)

**Comment by Aljullu** [comment]
Yeah, I can still reproduce this. I think our latest patches didn't change this at all.

**Comment by Aljullu** [comment]
Closing this since it was fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2366.
