### ISSUE TITLE
Linked product info (in Grouped products) are cut off on product page for some viewport widths

### ISSUE THREAD

**Issue by KevWal** [woocommerce/storefront#1259]
Some grouped products do not show the prices for the individual products - they are 'cut off' on the screen.
![86694777_10157058991763660_3221387572655685632_n](https://user-images.githubusercontent.com/2286500/74523550-2ad91a00-4f15-11ea-8ced-a548f1aee727.jpg)
I can kind of fix it for affected products with:

.postid-2192 td, table th {
padding: 1em 0em !important;
text-align: left;
vertical-align: top;
}

but not ideal.

**Comment by haszari** [comment]
Thanks for the bug report @KevWal - can you provide some more details so we can easily reproduce the issue?

- How are your products set up?
- Where are the prices not displayed correctly - product page, cart? 
- Details of the environment where the bug occurs, e.g. desktop or mobile, what browser, window/screen size.

Thank you :)

**Comment by KevWal** [comment]
Thanks for looking at this.  To answer your questions:

Products are setup as Grouped products:

![image](https://user-images.githubusercontent.com/2286500/75089114-6c894680-554d-11ea-896a-6bd3a3fb60b3.png)

Prices are not displayed on the Product page:

![image](https://user-images.githubusercontent.com/2286500/75089129-a35f5c80-554d-11ea-8202-f6ade5189b8e.png)

Issue happens on the desktop, at any browser width above 766 pixels. 

If 766 to  1200 - it cuts off lots of the grouped products table, and you don't get a horizontal scroll bar to find the rest of the table:

![image](https://user-images.githubusercontent.com/2286500/75089208-6c3d7b00-554e-11ea-93e9-ace52b9c4905.png)

Above 1200 you can see that it is just cut off:

![image](https://user-images.githubusercontent.com/2286500/75089254-e110b500-554e-11ea-8af9-0506a5a06245.png)

Below 766 the 'mobile view' works fine:

![image](https://user-images.githubusercontent.com/2286500/75089197-5334ca00-554e-11ea-8059-990d8b19b803.png)

Screenshots all taken in Chrome.  Issue is identical in Chrome.

Sorry I can't show the issue on a live website as I have added the following CSS to solve the issue:

.single-product div.product.product-type-grouped .summary {
    float: none!important;
    width: 100%;
}

Thanks
Kevin

**Comment by haszari** [comment]
Thanks for the detailed info @KevWal - I can reproduce this, definitely a bug.

To reproduce: 

- Add/edit a product so it has a long name, e.g. `X87364589FTUYGJN4355-3845 000 long with pivot`.
- Add long-name product to a grouped product, publish.
- View the product page for the grouped product at a range of screen sizes.
- Between 768px and 1200px wide, linked product pricing may be obscured by the sidebar.

<img width="1004" alt="Screen Shot 2020-02-24 at 12 50 11 PM" src="https://user-images.githubusercontent.com/4167300/75122600-4a85f480-5704-11ea-8451-9ef6066f194e.png">

**Comment by KevWal** [comment]
Thanks.  Could I add a couple of points to your bullets above please:

Issue occurs both if a right hand side bar exists, or doesn't exist.

Issue also occurs with a window size above 1200 pixels.

**Comment by haszari** [comment]
Also found that there's a similar problem for cart and checkout.

<img width="983" alt="Screen Shot 2020-04-22 at 4 13 38 PM" src="https://user-images.githubusercontent.com/4167300/79940507-15a0de80-84b6-11ea-9e51-b989c4faf8d2.png">

<img width="948" alt="Screen Shot 2020-04-22 at 4 26 16 PM" src="https://user-images.githubusercontent.com/4167300/79940512-189bcf00-84b6-11ea-8386-ccec3d135a1d.png">

**Comment by Aljullu** [comment]
The fix for this issue will be included in Storefront 2.5.6, which is planned to be released in a couple of weeks. If you want, you can already try the Release Candidate:
https://github.com/woocommerce/storefront/releases/tag/version%2F2.5.6-rc.1
We did a lot of internal testing, but if you find an issue, we would appreciate if you could report it.
