### ISSUE TITLE
Customizer Footer Heading & Link colors not applying

### ISSUE THREAD

**Issue by eduilson** [woocommerce/storefront#1260]
When inserting a widget in a footer column, the title of that widget does not change when you customize the footer header color

## To Reproduce
1. Go to Widgets
2. Add a widget in the footer area

![image](https://user-images.githubusercontent.com/23145787/74587736-1b210a80-4fd5-11ea-9105-547ac48ab5c0.png)

3. Go to the customization page and try to change the title color

![image](https://user-images.githubusercontent.com/23145787/74587772-7f43ce80-4fd5-11ea-9ac5-a3b797edffe8.png)

In `storefront/inc/customizer/class-storefront-customizer.php:793` we have the following:

```
.site-footer h1, .site-footer h2, .site-footer h3, .site-footer h4, .site-footer h5, .site-footer h6 {
    color: ' . $storefront_theme_mods['footer_heading_color'] . ';
}
```

And in `storefront/inc/class-storefront.php:280`:

```
$widget_tags = array(
    'before_widget' => '<div id="%1$s" class="widget %2$s">',
    'after_widget'  => '</div>',
    'before_title'  => '<span class="gamma widget-title">',
    'after_title'   => '</span>',
);
```

Solution: add `.site-footer .widget-title` in `storefront/inc/customizer/class-storefront-customizer.php:793`

I consider it a theme bug, because to fix this, it would be necessary to change the tag via filter

**Comment by jessepearson** [comment]
This is actually more than just the headings, it's also the links. I had two reports today about the issue:
18800697-hc
18802594-hc
18800057-hc

Looks like there are a couple reports in the forums, as well. 

I tested the PR, and it works to fix the issue.

**Comment by haszari** [comment]
Thanks for the reports @eduilson & @jessepearson. From my testing it looks like there are two related issues:

- Customizer `Footer > Heading color` doesn't apply correctly (I also reproduced this in 2.5.3)
- Customizer `Footer > Link color` doesn't apply correctly (bug introduced in 2.5.4)

I agree this is an important issue to fix, so I've added this issue to the next release (2.5.5).

Thanks to @nielslange we have a PR in the pipeline addressing this.

**Comment by ryanr14** [comment]
2729107-zen from chat today. :)

**Comment by nielslange** [comment]
@jessepearson & @ryanr14 I created https://github.com/woocommerce/storefront/pull/1261 to fix both the heading and link colours in the footer. Let's hope that the PR is in such a shape that @haszari can merge it soon. 🤞😀🤞

**Comment by bondimedical3** [comment]
I just updated to 2.5.4 and cannot apply Link colours to my footer widget text. Is there a temporary fix?

**Comment by ryanr14** [comment]
Howdy @bondimedical3, I believe the following CSS will change that link color. Replace with your preferred color hex code of course. :)

`.site-footer a:not(.button):not(.components-button) {
color: #fff;
}`

**Comment by haszari** [comment]
We've tagged 2.5.5 RC 1 including this fix - @eduilson @jessepearson @ryanr14 @bondimedical3 please feel free to grab the zip file and test it out :)

https://github.com/woocommerce/storefront/releases/tag/version%2F2.5.5-rc.1

**Comment by ryanr14** [comment]
> Customizer Footer > Heading color doesn't apply correctly (I also reproduced this in 2.5.3)
Customizer Footer > Link color doesn't apply correctly (bug introduced in 2.5.4)

I tested based on these two items and things appear to be working for me.

![https://d.pr/i/y1dLg1](https://d.pr/i/y1dLg1+)
Image link: https://d.pr/i/y1dLg1

**Comment by bondimedical3** [comment]
@ryanr14 Hi Ryan. I have noticed another bug with the latest update, Link colour in the Footer Customizer is also affecting the colour of the buttons of the mobile footer widget. I have white text links in the footer of my website however this makes the Account, Search and cart buttons disappear as they are on a white background. Do you have a temporary fix for this?
