### ISSUE TITLE
No padding between YouTube video and List block...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#1271]
## Describe the bug
There is no padding between a YouTube video block and a List block.

Isolating the problem (mark completed items with an [x]):
- [X] I have deactivated other plugins and themes and confirmed this bug occurs when only Storefront theme is active.
- [X] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Insert a List block.
2. Insert a YouTube video.
3. Left-justify (wrap) the YouTube video.
4. Note there is no padding between the List numbers/bullets.

## Screenshots
![no padding](https://user-images.githubusercontent.com/30901407/75084379-b6dadb00-54ed-11ea-9bb4-65799d1c051e.jpg)

## Expected behavior
There should be padding around the YouTube video.

FYI: This same result is seen with or without Gutenberg activated. **OR** perhaps this is this a Gutenberg issue?

**Comment by nielslange** [comment]
I might be a bit too fast with the PR as I just see that other themes show the same issue. It seems that this is rather a Gutenberg issue.

cc: @GlennMartin1, @senadir & @haszari

**Comment by haszari** [comment]
@nielslange @GlennMartin1 Do you know if this issue is tracked in Gutenberg/WordPress core?

**Comment by haszari** [comment]
I compared Storefront with Twenty Twenty & Twenty Nineteen .. possibly we could improve this. 

<img width="856" alt="Screen Shot 2020-02-24 at 12 41 59 PM" src="https://user-images.githubusercontent.com/4167300/75122526-21189900-5703-11ea-94a0-c998e954e1b7.png">

<img width="1375" alt="Screen Shot 2020-02-24 at 12 43 04 PM" src="https://user-images.githubusercontent.com/4167300/75122532-368dc300-5703-11ea-9e7e-065adca59082.png">

<img width="970" alt="Screen Shot 2020-02-24 at 12 43 32 PM" src="https://user-images.githubusercontent.com/4167300/75122538-473e3900-5703-11ea-85c0-3ea3ab9ddf9b.png">

**Comment by GlennMartin1** [comment]
After posting this here, I checked the Gutenberg repo but couldn't locate it.

**Comment by senadir** [comment]
Better upstream it to GB so we can get more opinions

**Comment by nielslange** [comment]
@haszari As @GlennMartin1 mentioned, this issue isn't tracked in the Gutenberg repo yet.

@senadir Sounds good. I'll close my PR for now.

**Comment by GlennMartin1** [comment]
Closing this issue; I reported this at https://github.com/WordPress/gutenberg/issues/20414.

**Comment by GlennMartin1** [comment]
As you will note here: https://github.com/WordPress/gutenberg/issues/20414#issuecomment-590923713, Gutenberg doesn't want to address this, stating that themes should address it instead.

Can this PR https://github.com/woocommerce/storefront/pull/1272 be reopened and merged?

**Comment by haszari** [comment]
> Can this PR #1272 be reopened and merged?

Works for me :)

I'll give @nielslange PR a test today or tomorrow and see if we can get this in 2.5.5.

**Comment by nielslange** [comment]
@haszari If you check out the PR, please also keep an eye on the alignment of list items next to a floating image. The default margin is rather small and I planned to create a second PR to increase the margin in this case as well. Thus, instead of using the same margin for this PR, I already used a bigger margin due to the [Laws of Proximity](https://www.verywellmind.com/gestalt-laws-of-perceptual-organization-2795835).

**Comment by haszari** [comment]
This fix is included in the latest 2.5.5 RC: https://github.com/woocommerce/storefront/releases/tag/version%2F2.5.5-rc.2

Aiming to release 2.5.5 to WordPress.org tomorrow.
