### ISSUE TITLE
Non-aligned image blocks lost margins with release 2.5.5

### ISSUE THREAD

**Issue by nielslange** [woocommerce/storefront#1276]
## Describe the bug

This issue was reported in https://github.com/woocommerce/storefront/pull/1265#commitcomment-37538847 and caused by https://github.com/woocommerce/storefront/pull/1265 which got shipped with [Storefront 2.5.5](https://github.com/woocommerce/storefront/releases/tag/version%2F2.5.5) got released.

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to `/wp-admin/post-new.php?post_type=page`
2. Add an image
3. Add a separator below the image
4. Save and look up the page to see the error

## Current behaviour
The separator is not visible.

![current-behaviour](https://user-images.githubusercontent.com/3323310/75601511-6ca9b900-5aee-11ea-9d41-6aefd97870b4.png)

## Expected behaviour
The separator is visible.

![expected-behaviour](https://user-images.githubusercontent.com/3323310/75601514-6f0c1300-5aee-11ea-9d31-5f71304a9589.png)

### Browser Environment

- Platform: macOS 10.15.3
- Browser(s): Chrome 80.0.3987.122

### WordPress Environment

- Local by Flywheel
- PHP version: 7.3.5
- WP version: 5.3.2

**Comment by haszari** [comment]
Marking this PR as blocked for now - may not be needed. See https://github.com/woocommerce/storefront/issues/1280#issuecomment-614956252
