### ISSUE TITLE
Image block captions wrap error not using full image width (introduced in 2.5.5)

### ISSUE THREAD

**Issue by nielslange** [woocommerce/storefront#1280]
## Describe the bug
Clearly describe the issue. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to /wp-admin/post-new.php?post_type=page
2. Add an image with a caption and resize the image
3. Save and look up the page to see the error

## Current behaviour

![current-behaviour](https://user-images.githubusercontent.com/3323310/75625909-196e5e00-5bf5-11ea-8552-43e716b81efa.png)

## Expected behaviour

![expected-behaviour](https://user-images.githubusercontent.com/3323310/75625910-1c694e80-5bf5-11ea-9187-48ec9ea5a932.png)

### Browser Environment

- Platform: macOS 10.15.3
- Browser(s): Chrome 80.0.3987.122

### WordPress Environment

- Local by Flywheel
- PHP version: 7.3.5
- WP version: 5.3.2

**Comment by Aljullu** [comment]
@nielslange to me it looks like #1277 fixes this issue as well. Can you confirm? I might be missing some specific case where it's reproducible, thought.

**Comment by haszari** [comment]
> to me it looks like #1277 fixes this issue as well. Can you confirm? I might be missing some specific case where it's reproducible, thought.

I agree, I don't think this PR is needed (assuming we end up merging #1277). Marking this PR as blocked for now.
