### ISSUE TITLE
Category Page Images Aren't Centering When Browser Is Resized

### ISSUE THREAD

**Issue by synora** [woocommerce/storefront#1283]
## Describe the bug
User has noticed their product category images are not centering when the browser is resized. 
A product category page of theirs: https://theweddingveilshop.co.uk/bridal-accessories/headpieces/ 

This issue has just recently begun for them. They noticed this occurring specifically after the latest Storefront update. The images would previously align center. I'm able to replicate this on my test site with Chrome as my browser. 

Isolating the problem (mark completed items with an [x]):
- [X ] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [X ] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Visit a product category page
2. Resize browser to the thinnest horizontal width possible: https://d.pr/i/b20WSF
3. You'll find the text and product buttons are correctly aligned, but the image is not. 

Note: I thought the issue might have to do with Powerpack, but the problem persists even with Powerpack deactivated. 

2758194-zen
18126391-hc

**Comment by enoch85** [comment]
This happens since the last update. All my pictures are left centred: https://shop.hanssonit.se/ It doesn't matter if I resize or not.

They were all centred before  Storefront 2.5.5.

**Comment by bondimedical3** [comment]
I am experiencing the same issue, square product images are not centered on category pages and the name of the product is very close to the image!

**Comment by nielslange** [comment]
Thanks for reporting this issue, @synora, @enoch85 & @bondimedical3.

**Comment by haszari** [comment]
Possibly related: #1296 #1298

**Comment by haszari** [comment]
Fixed by #1313

**Comment by Aljullu** [comment]
The fix for this issue will be included in Storefront 2.5.6, which is planned to be released in a couple of weeks. If you want, you can already try the Release Candidate:
https://github.com/woocommerce/storefront/releases/tag/version%2F2.5.6-rc.1
We did a lot of internal testing, but if you find an issue, we would appreciate if you could report it.
