### ISSUE TITLE
product images -> user defined: don't work as expected

### ISSUE THREAD

**Issue by MelzerM** [woocommerce/storefront#1291]
I'd like to switch to the storefront theme, but i have problems with the image dimensions.

Due to the fact that i have a lot of image dimensions, i used the Customiser -> WooCommerce -> Product images -> user defined, where i choose a ratio of 5:7 in all other tested themes the images in the product catalog got cropped to those dimensions unless they where way to small, but with storefront there seem to be other limitations.

For example now every image in the shop catalog is displayed with Dimensions of

158,75 x 222,25

with storefront enabled i get three diffrent dimensions:

173,4 x 245,367
173,4 x 242,967
173,4 x 200,7  (in this case the image would be the desired ratio but rotated by 90 degree, but the resolution is high enough cut off the sides to get 5:7

In addittion it would be great if there would be a solution that on every row of products, the price and add to cart button would be on the same level, so it wouldn't look to messed up. If this could be easily done with css, i would be happy if some one could point me to a solution.

**Comment by haszari** [comment]
Hi @MelzerM - there's a lot to unpack in your bug report!

> Due to the fact that i have a lot of image dimensions, i used the Customiser -> WooCommerce -> Product images -> user defined, where i choose a ratio of 5:7 in all other tested themes the images in the product catalog got cropped to those dimensions unless they where way to small, but with storefront there seem to be other limitations.

Could you please update this issue with detailed steps for reproducing the issue in Storefront and WooCommerce – attach specific example image files that cause the problem. The more detail you include, the better – use the [issue template as a guide](https://github.com/woocommerce/storefront/blob/master/.github/ISSUE_TEMPLATE/1-Bug-report.md), and feel free to include as much info as is relevant. 

Please include all steps needed to reproduce the bug on a blank WooCommerce + Storefront install.

> In addittion it would be great if there would be a solution that on every row of products, the price and add to cart button would be on the same level, so it wouldn't look to messed up. If this could be easily done with css, i would be happy if some one could point me to a solution.

This sounds like a different issue – please log this one separately, with as much detail as possible. 

There's a related feature in [WooCommerce Blocks](https://docs.woocommerce.com/document/woocommerce-blocks/#section-5) which might be useful to you – the `Align last block` setting in the `All Products` block. The default setup for this block has `Add to cart` as the last block, so this will align them all nicely. 

<img width="1270" alt="Screen Shot 2020-03-24 at 3 29 38 PM" src="https://user-images.githubusercontent.com/4167300/77382249-c5fec280-6de4-11ea-9fa6-11c7748d278c.png">

**Comment by nerrad** [comment]
There hasn't been a reply for nearly 4 months. I'm going to close this issue. However if there's any additional information that can be added in response to the request please do add as comments to the issue and we can consider reopening.
