### ISSUE TITLE
Default install not rendering, 404

### ISSUE THREAD

**Issue by xhostcom** [woocommerce/storefront#1292]
## Describe the bug
Clearly describe the issue. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

Default install is not rendering, shows 404?

Isolating the problem (mark completed items with an [x]):
- [ ] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [ ] I can reproduce this bug consistently using the steps below.

### Browser Environment
Please provide as much detail as possible about your testing environment.

- Platform: e.g. macOS, Windows, iOS
- Browser(s):

Linux, Node latest, Vue CLI 3.

### WordPress Environment
Please provide relevant details of your WordPress setup and server environment.

<details>
```
Copy and paste the system status report from WooCommerce > System Status in WordPress admin.
```
</details>

**Comment by nielslange** [comment]
Hello @xhostcom, Would you mind providing the necessary information such as `Describe the bug`, `To Reproduce`, as mentioned in the bug report ticket? Based on the current information, it's not possible to reproduce this issue.

**Comment by haszari** [comment]
Closing this issue – please reopen if you have more details about the issue.
