### ISSUE TITLE
Site Title: H1 class?

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/storefront#1294]
This is hopefully a quick question.

In Storefront theme, the site title does not have the H1 class applied. Is this because there's already an H1 class applied elsewhere on each page, and only 1 should be applied per page? Can someone explain this further to me?

If someone were wanting to apply an H1 tag to the site title, how would they go about doing this?

**Comment by nielslange** [comment]
@ldr2273 In https://yoast.com/academy/seo-copywriting-training/single-h1/, the folks from Yoast suggest to only use one `h1` per page. As the page title, e.g. `My fancy product`, is more important than the site title, e.g. `My fancy shop`, formatting the site title as `h1` does not sound right to me. The only exception I can imagine would be the site title on the homepage itself. 

Do you have an example of this issue? 

> If someone were wanting to apply an H1 tag to the site title, how would they go about doing this?

The best way to accomplish this would be to create a child-theme. Please keep in mind that this might have a negative impact on the SEO of the site as mentioned in Yoast's post.

**Comment by ldr2273** [comment]
Thanks for the insight @nielslange. I've reached out to grab a use-case/example of why or when it might be necessary to apply an H1 tag to the site title and will update you as soon as I hear back.

**Comment by haszari** [comment]
Closing this issue for now - @ldr2273 please open a more specific issue if needed.
