### ISSUE TITLE
fontawesome

### ISSUE THREAD

**Issue by Shoco-1218** [woocommerce/storefront#1300]

**Comment by haszari** [comment]
Hi @Shoco-1218 – can you fill out some more details of the issue please? Please use one of the [issue templates](https://github.com/woocommerce/storefront/tree/master/.github/ISSUE_TEMPLATE) so we can understand and reproduce the issue.

In particular –

- Clearly describe the issue, including any setup steps.
- Explain what you expected to happen, with screenshots if applicable.

In the meantime I'm going to close this issue – go ahead and reopen when you have more info to add :)

**Comment by haszari** [comment]
Possibly related issue: #1278
