### ISSUE TITLE
2.5.5 is inconsistency using "header" colours for the footer, instead of "footer" colours (at the smallest responsive size.)

### ISSUE THREAD

**Issue by jaydisc** [woocommerce/storefront#1302]
This changed between 2.5.3 and 2.5.5.

In 2.5.5:

The colour of links (the font awesome icons) in the footer at the smallest responsive size is set by the user in Appearance → Customise → Footer → Link Colour:

    .site-footer a:not(.button):not(.components-button) {
        color: #990000;
     }

But, the footer background-colour at the same responsive size is set by the user in Appearance → Customise → HEADER → Background Colour, and NOT Appearance → Customise → FOOTER → Background Colour.

This is inconsistent and causes unexpected styling - in one case, red links on a red background. This is because the user has set the link colour there with the expectation that it sits on top of the background-colour defined in the same area.

In 2.5.3:

The colour of links (the font awesome icons) in the footer at the smallest responsive size is set by the user in Appearance → Customise → HEADER → Link Colour:

Now, while that is arguably wrong (why are the footer colours being pulled from the user's _header_ colour settings), at least it was CONSISTENT, as the footer background-colour at the smallest responsive size is set by the user in Appearance → Customise → HEADER → Background Colour.

**Comment by Aljullu** [comment]
The fix for this issue will be included in Storefront 2.5.6, which is planned to be released in a couple of weeks. If you want, you can already try the Release Candidate:
https://github.com/woocommerce/storefront/releases/tag/version%2F2.5.6-rc.1
We did a lot of internal testing, but if you find an issue, we would appreciate if you could report it.
