### ISSUE TITLE
fix broken icons in comment list/form (or remove broken css if problematic)

### ISSUE THREAD

**Issue by haszari** [woocommerce/storefront#1319]
## Describe the bug
There's some [css in `icons.css` which adds icons for comment author, "edit comment" pencil etc](https://github.com/woocommerce/storefront/blob/master/assets/css/base/icons.scss#L34-L63).

This is no longer working - it looks like the parent selectors (e.g `#comments commentlist`) have changed at some point.

Perhaps we can remove this css. Or if these icons are important (or this is a recent regression) we can fix them up.

## Screenshots
This is current behaviour, no icons:

<img width="832" alt="Screen Shot 2020-04-20 at 3 57 52 PM" src="https://user-images.githubusercontent.com/4167300/79712723-c4f77d00-831f-11ea-96bc-83544c25f473.png">

If I hack `commentlist` back in we get some nice icons:

<img width="875" alt="Screen Shot 2020-04-20 at 3 59 25 PM" src="https://user-images.githubusercontent.com/4167300/79712779-ec4e4a00-831f-11ea-9617-2a807598cabe.png">

(Discovered when reviewing #1279.)

**Comment by nielslange** [comment]
Due to aesthetic and usability reasons, I'd rather keep the icons and correct the CSS code, so that the icons become visible again.

**Comment by haszari** [comment]
> keep the icons and correct the CSS code, so that the icons become visible again

@nielslange I'm happy with that as long as it's safe/low risk and we have time to test it :)

I'm a little curious how long this has been broken. If it's multiple releases then perhaps it's more risky to bring it back, as it might feel like an unexpected visual change to some stores. The risk is probably pretty low though (at a guess).

**Comment by haszari** [comment]
Adding to 2.5.7, hopefully we can tidy this up safely.

**Comment by gglobalstep** [comment]
This issue is observed to be **Open** on WooCommerce 4.2 RC 1
**Environment:**
Windows
OS: 10
Browser: Chrome(Version 81.0.4044.138 (64-bit))

MAC 
OS: Mojave v10.14.6
Browser: Safari(v13.0.5)

**Comment by haszari** [comment]
Thanks for testing this @gglobalstep :)

Can you confirm the Storefront version where you saw the issue? This issue is fixed in Storefront 2.5.7 RC 1.

Please ensure you are testing with Storefront 2.5.7 RC 1 by following the steps here - https://github.com/woocommerce/storefront/wiki/Release-testing-instructions:-Storefront-2.5.7

**Comment by gglobalstep** [comment]
This issue is observed to be "Fixed" on WooCommerce 4.2 RC 2
**Environment:**
Windows
OS: 10
Browser: Chrome(Version 81.0.4044.138 (64-bit))

MAC
OS: Mojave v10.14.6
Browser: Safari(v13.0.5)
