### ISSUE TITLE
Gutenberg trunk: several blocks are left aligned on wide screens

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/storefront#1320]
## To Reproduce
1. Get Gutenberg master.
2. Add a paragraph or a list block + some other blocks.
3. In a wide viewport, notice paraghraph and list are left-aligned but the other blocks are centered.

This happens because `<p>` and `<ul>` have left and right margins set to 0. We would want to set the left and right margins to `auto` to fix this. For the list, this is a bit more tricky because it needs a left margin of `3em`, we could try to make it a padding instead.

However, I think it makes sense to wait before fixing this until an official version of Gutenberg is released. Twenty Twenty seems to be affected as well.

## Screenshots
![imatge](https://user-images.githubusercontent.com/3616980/79757346-451be380-831c-11ea-9ea4-fff51183e89f.png)

**Comment by haszari** [comment]
> However, I think it makes sense to wait before fixing this until an official version of Gutenberg is released. Twenty Twenty seems to be affected as well.

Agreed - it feels like this regression should be reported to Gutenberg directly.

**Comment by wpniall** [comment]
Another 3 reports in [Storefront Theme & Gutenberg Heading Blocks Alignment In Editor](https://wordpress.org/support/topic/storefront-theme-gutenberg-heading-blocks-alignment-in-editor/) on the WordPress.org forums. One user (@globalmatt) said they renamed the `storefront/assets/css/base/gutenberg-editor.css` file, which I can confirm fixes the alignment issues:

**gutenberg-editor.css loaded**

![https://d.pr/i/EsSzEV](https://d.pr/i/EsSzEV+) 
Full Size: https://d.pr/i/EsSzEV

**gutenberg-editor.css disabled**

![https://d.pr/i/o8KeY4](https://d.pr/i/o8KeY4+) 
Full Size: https://d.pr/i/o8KeY4

Another user (@lflizmark), reported that the H2 and H3 tags align incorrectly to the left, while the H1, H4, H5 and H6 align correctly.

**Comment by ylving** [comment]
The issue seems to stem from the use of **em** instead of **rem**:
`.wp-block{max-width:calc(66.4989378333em * 0.7391304348)}.wp-block[data-align=wide]{max-width:75.9987860952em}`

So a slightly less "destructive" option than renaming/disabling the stylesheet altogether would be to edit the stylesheet, changing **em** to **rem**:
`.wp-block{max-width:calc(66.4989378333rem * 0.7391304348)}.wp-block[data-align=wide]{max-width:75.9987860952rem}`

If you are already loading your own editor-styles in a child-theme, you can simply override those two rules. No need to disable or edit anything in the parent theme.
```
.wp-block {
  max-width: calc(66.4989378333rem * 0.7391304348) !important;
}

.wp-block[data-align=wide] {
  max-width: 75.9987860952rem !important;
}
```

**Comment by globalmatt** [comment]
@ylving Awesome, thanks! I added your 2 rulesets to an "editor" stylesheet in my child theme, and then enqueued the stylesheet using the `enqueue_block_editor_assets` hook, and it works perfectly. Great job!

(BTW I renamed the Storefront stylesheet purely for diagnosis - it wasn't intended as a fix of course. 😊)

I guess your fix above should be included in the Storefront theme.

**Comment by DearTanker** [comment]
Still not fix?

**Comment by seebz** [comment]
> The issue seems to stem from the use of **em** instead of **rem**:

Two easy ways to solve this old issue, both in the file `_variables.scss` :

1. Setting `$ms-base` in `rem`   
    ```
    $ms-base:           1rem, 0.875rem;
    ```
2. Setting `$container-width` in `px`  
   ```
   $container-width:   1215.98px;
   ```

Please fix :)

**Comment by DearTanker** [comment]
> @ylving Awesome, thanks! I added your 2 rulesets to an "editor" stylesheet in my child theme, and then enqueued the stylesheet using the `enqueue_block_editor_assets` hook, and it works perfectly. Great job!
> 
> (BTW I renamed the Storefront stylesheet purely for diagnosis - it wasn't intended as a fix of course. 😊)
> 
> I guess your fix above should be included in the Storefront theme.

can u share the full functions.php file to help me study the work.
