### ISSUE TITLE
Storefront icons.css typo line 4439

### ISSUE THREAD

**Issue by Marmio** [woocommerce/storefront#1333]
Maybe old news, but.... for those who come across a conflict with fontawesome text-file icon on header menu. Woocommerce/Storefront comes with a typo.  Check this:

file: [icons.scss](https://github.com/woocommerce/storefront/blob/master/assets/css/base/icons.scss#L114)

```
.main-navgation ul li a::before {
  display: inline-block;
  font-style: normal;
  font-variant: normal;
  font-weight: normal;
  line-height: 1;
  font-family: 'Font Awesome 5 Free';
  font-weight: 900;
  line-height: inherit;
  vertical-align: baseline;
  content: "\f15c";
  margin-right: 0.5407911001em; }
```

should be (my guess): 
.main-navigation (i/o  'navgation')

**Comment by haszari** [comment]
Thanks for reporting this @Marmio - good spotting. I've edited the description for clarity.

**Comment by haszari** [comment]
Closing this in favour of #1347.

Usually I'd close the newer issue but in this case #1347 has a recommended plan of action. Thanks for reporting @Marmio  :)
