### ISSUE TITLE
disparity between Button block in editor vs. frontend

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#1335]
## Describe the bug
The Button block incorrectly displays the button full-width in the frontend. It displays correctly in the editor.

Isolating the problem (mark completed items with an [x]):
- [X] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [X] I can reproduce this bug consistently using the steps below.

## To Reproduce
- intall Storefront theme Storefront 2.5.6-rc.1
- install Homestore childtheme 2.0.32  (current version)
- install Gutenberg plugin 7.9.1 (current version)
- create a single button in the **Buttons** block
- save and view in front end.

## Screenshots
**EDITOR:**
![backend](https://user-images.githubusercontent.com/30901407/80215653-d637d680-860a-11ea-82eb-2bd92cf998b4.jpg)

**FRONT-END:**
![frontend](https://user-images.githubusercontent.com/30901407/80215686-e2239880-860a-11ea-8318-1e7ec83e257f.jpg)

## Expected behavior
The front-end should display the button as it's shown in the editor.

**Comment by Aljullu** [comment]
I wasn't able to replicate this issue. @GlennMartin1 could you help me answering some questions?
* Was this happening with Storefront 2.5.5?
* Does it happen if you deactivate Homestore and use Storefront?
* Something that might help us is to get the same page contents as you.
  * Create a new page with the _Buttons_ block, so you can replicate the issue.
  * In the editor, press <kbd>Ctrl</kbd>+<kbd>A</kbd> (select all blocks) and then <kbd>Ctrl</kbd>+<kbd>C</kbd> (copy).
  * Now, paste the page code here.

Thank you in advance!

**Comment by GlennMartin1** [comment]
Ok - I've got the solution - or at least a workaround - keep reading.

Yes, this happens with Storefront 2.5.5.
It began after Gutenberg 7.9.0 was installed.

Yes, it happens even with Storefront (without Homestore).

The is only an issue for buttons that were created prior to Gutenberg 7.9.0.
If I create a new button, the issue no longer appears.

The OLD code (before Gutenberg 7.9.0) is this:
`<a class="wp-block-button aligncenter wp-block-button__link no-border-radius" href="https://www.hometowntrailers.com/dump-trailers/">Check out our inventory</a>`

The NEW code (after Gutenber 7.9.0) is this:
`<a class="wp-block-button wp-block-button__link no-border-radius" href="https://www.hometowntrailers.com/dump-trailers/">Check out our inventory</a>`

You will note that the OLD code had `aligncenter`. If it's left-aligned, it had `alignleft`. The new code doesnt' use that. 

My workaround is that I'm just creating new blocks.

**Comment by GlennMartin1** [comment]
Related: https://github.com/WordPress/gutenberg/issues/21685

Appears to be a Gutenberg bug.

**Comment by GlennMartin1** [comment]
To be resolved with https://github.com/WordPress/gutenberg/pull/21822

**Comment by Aljullu** [comment]
Awesome, thanks for investigating this @GlennMartin1. :+1:
