### ISSUE TITLE
Instagram embed not working

### ISSUE THREAD

**Issue by BusinessBloomer** [woocommerce/storefront#1341]
## Describe the bug

Instagram embeds e.g. https://www.instagram.com/p/B4NjwJ7oMB6 on its own line does not get translated into an embedded post. Instead, you see "https://www.instagram.com/p/B4NjwJ7oMB6" on frontend.

Tried with 2020 theme, works perfectly

## To Reproduce

Open new Gutenberg page, embed an instagram post (e.g. https://www.instagram.com/p/B4NjwJ7oMB6). On the backend you see the embedded content, on the frontend you don't

## Screenshots

https://www.screencast.com/t/yBEC4W5j

### Browser Environment

Google Chrome, desktop

### WordPress Environment

WP 5.4.1
Woo 4.0.1
Storefront 2.5.5

**Comment by haszari** [comment]
Thanks for reporting this @BusinessBloomer . I'm having trouble reproducing the issue. 

Here's what I tried:

- New post (using Block Editor/Gutenberg)
- Paste a url to an instagram post on its own line
- Url automatically converts into an embed in the editor, using `Instagram` block
- Publish post, embed shows in archive / blog page and post 

Can you report back with more details of how to reproduce the bug? 

Here's a gif:

![embed-insta](https://user-images.githubusercontent.com/4167300/81024281-16c70800-8ec7-11ea-9f3a-6383954f34f6.gif)

**Comment by BusinessBloomer** [comment]
If I create a new page/post, it works fine. But if I try to fix an existing post/page, even after making it a draft and then republishing, the embeds don't appear :|

**Comment by haszari** [comment]
Thanks for the new info @BusinessBloomer. I've managed to reproduce it, with a blog post, in the blog archive view.

<img width="947" alt="Screen Shot 2020-05-06 at 9 51 59 AM" src="https://user-images.githubusercontent.com/4167300/81119642-4c2f2c80-8f7f-11ea-8c85-ff608bf0e26a.png">

I tried switching themes (to Twenty Twenty and Maywood) and the embed showed fine, so this seems to be a problem in Storefront.

**Comment by BusinessBloomer** [comment]
Great!

**Comment by haszari** [comment]
Adding to 2.5.7 - this is a core block that we should be compatible with.

**Comment by haszari** [comment]
I can't reproduce this anymore! I don't see how this could have been broken by Storefront - I'm thinking perhaps there was a glitch with the embed or the instagram API that was temporarily causing this.

@BusinessBloomer Can you still reproduce this with the latest versions of WordPress and Storefront?

**Comment by BusinessBloomer** [comment]
Yes, I can still reproduce it: [https://apieceofsicily.com/en/sicilian-celebrities/](https://apieceofsicily.com/en/sicilian-celebrities/)

**Comment by haszari** [comment]
I found an issue in Gutenberg which might be relevant. https://github.com/WordPress/gutenberg/issues/14351

I think the embed functionality is powered by a script on the front end, and there's something stopping that from working correctly.

**Comment by mikejolley** [comment]
Embeds from Instagram and Facebook are no longer supported in WordPress due to changes in the Instagram API.

Refs:

https://yoast.com/facebook-instagram-embeds-broken/
https://wordpress.org/support/article/embeds/
