### ISSUE TITLE
Outdated Font Awesome Library

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/storefront#1345]
## Describe the bug
The Font Awesome library in SF only includes the "free" library and excludes "brands" - this means that social media icons (e.g. Facebook) won't render - regardless of whether they're added through custom HTML or 3rd party plugins.

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
To simulate a typical customer website - Steps to reproduce the behavior:
1. Install, activate https://wordpress.org/plugins/social-profiles-widget/
2. Add widget Social Profile widget to footer and add "Facebook" as a profile(Screenshot at: https://d.pr/i/zUxaI6)
3. View widget on front-end (Screenshot at: https://d.pr/i/Zx68pg)
4. Using browser tools - Notice the library being loaded is from SF - `Font Awesome 5 Free`; Changing that to `Font Awesome 5 Brands' or even `fontawesome` fixes the issue.

When looking at the Font Awesome library used on Storefront, I can see that it's incomplete and doesn't contain all the dependencies.

Essentially, SF will override all other instances of fontawesome by other plugins with outdated (or incomplete) versions of the FA library.

## Screenshots

![https://d.pr/i/nPDbIW](https://d.pr/i/nPDbIW+)
Full Image: https://d.pr/i/nPDbIW

![https://d.pr/i/iZhHe0](https://d.pr/i/iZhHe0+)
Full Image: https://d.pr/i/iZhHe0

## Expected behavior
I expected Storefront to show _all_ Font Awesome icons regardless of how they're added to a site.

**Comment by RiaanKnoetze** [comment]
For internal reference, please have a look at: https://a8c.slack.com/archives/C3NCP7ZJ6/p1588935685351700

**Comment by haszari** [comment]
Adding to 2.5.7 - looks like we should provide the full icon set for compatibility reasons.

**Comment by nielslange** [comment]
I've assigned this issue to me and will work on it later today!

**Comment by gglobalstep** [comment]
Could you please provide more information about how to test this issue on WooCommerce 4.2 RC1?

**Comment by haszari** [comment]
> Could you please provide more information about how to test this issue on WooCommerce 4.2 RC1?

Thanks for testing @gglobalstep !

You can test to confirm the brands icons are working correctly using the steps in the original issue above:

- Install, activate https://wordpress.org/plugins/social-profiles-widget/
- Add widget Social Profile widget to footer and add "Facebook" as a profile(Screenshot at: https://d.pr/i/zUxaI6)
- View widget on front-end (Screenshot at: https://d.pr/i/Zx68pg)

**Comment by gglobalstep** [comment]
Keeping this ticket "Open" as we are not able to see "font family: font-awesome".
Refer below artifacts:
![MAC](https://user-images.githubusercontent.com/41110392/83170880-dc056800-a132-11ea-8721-43e2fc69cc4a.jpg)
![Windows10](https://user-images.githubusercontent.com/41110392/83170886-ddcf2b80-a132-11ea-8daa-fc3eb6327756.png)

**Comment by nielslange** [comment]
> Keeping this ticket "Open" as we are not able to see "font family: font-awesome".
> Refer below artifacts:
> ![MAC](https://user-images.githubusercontent.com/41110392/83170880-dc056800-a132-11ea-8721-43e2fc69cc4a.jpg)
> ![Windows10](https://user-images.githubusercontent.com/41110392/83170886-ddcf2b80-a132-11ea-8daa-fc3eb6327756.png)

@gglobalstep Your screenshot shows the fonts for body. They will remain as they are and cannot be font-awesome as the regular text would not be readable any longer. In addition, your screenshot shows an entire different Facebook icon. This icon is not related to Font Awesome. 

- What is the URL of your test site?
- What plugin are you using to add the Facebook icon on the site?
