### ISSUE TITLE
Sticky Add to Cart does not take Woocommerce Min/Max Quantity in consideration

### ISSUE THREAD

**Issue by opicron** [woocommerce/storefront#1346]
## Is your feature request related to a problem? 
When using the Woocommerce Min/Max Quantity plugin the Stick Add to Cart adds 1pc to the cart instead of the minimum set quantity. Resulting in an notice at the Cart page.

## Describe the solution you'd like
Would it be possible to add compatibility with Woocommerce Min/Max Quantity plugin?

## Describe alternatives you've considered
I have considered removing the functionality of Sticky Add to Cart. But it is just to nice not to enable.

## Additional context
Example here: [removed]

**Comment by opicron** [comment]
fixed by hooking "woocommerce_product_add_to_cart_url" checking if is_single and adding quantity manually.

**Comment by haszari** [comment]
> fixed by hooking "woocommerce_product_add_to_cart_url" checking if is_single and adding quantity manually.

Hi @opicron  - looks like you've got a workable solution - nice work! Closing this issue since this can be solved using the hook.
