### ISSUE TITLE
Document Storefront's support policy WordPress and WooCommerce versions

### ISSUE THREAD

**Issue by haszari** [woocommerce/storefront#1350]
## Is your feature request related to a problem? Please describe.
It's not clear what versions of WordPress and WooCommerce are suitable for use with Storefront.

Having a clear support policy allows us to move fast and focus our testing and backward compatibility where it can have the most impact. 
## Describe the solution you'd like
[WooCommerce has recently shipped an "**L-2**" based policy](https://woocommerce.wordpress.com/2020/05/08/wordpress-core-support-policy/) - let's look at adapting a similar plan for Storefront.

**Comment by nielslange** [comment]
I'd follow an L-2 approach as well for now, which can always be adjusted to an L-1 approach later on if needed.

**Comment by haszari** [comment]
When we have a clear WordPress version support policy, we can be more proactive in tidying up use of old/deprecated apis, for example: https://github.com/woocommerce/storefront/pull/1143

**Comment by haszari** [comment]
This is now documented here: https://docs.woocommerce.com/document/storefront-requirements-version-support/

And that page is linked from the main install/setup doc: https://docs.woocommerce.com/document/installation-configuration/

So we're good - closing 🎉

**Comment by haszari** [comment]
Note - this is not currently enforced in code, and we don't have any explicit process to manage this. For example, we could:

- When planning a new release, look for opportunities for features/code to remove/tweak because it's targeting older versions of WooCommerce or WordPress.
- Explicitly test against older supported versions of WooCommerce or WordPress when testing/releasing.
- Add metadata to declare supported versions, e.g. in `style.css` header.
- Add code to check and warn if site is running an unsupported version of WooCommerce or WordPress.

I don't think there's any particular urgency to implement any of the above, unless something prompts us to.
