### ISSUE TITLE
Update dependencies! Or set up a bot to help us manage dependencies

### ISSUE THREAD

**Issue by haszari** [woocommerce/storefront#1363]
## Is your feature request related to a problem? Please describe.
Our npm dependencies are not fully up to date. We should be keeping libs updated unless we have a good reason not to.

```
Package                          Current  Wanted  Latest  Location
@babel/core                        7.8.4  7.10.0  7.10.0  storefront
@wordpress/babel-preset-default    3.0.2   3.0.2  4.13.0  storefront
autoprefixer                       9.7.4   9.8.0   9.8.0  storefront
bourbon                            5.1.0   5.1.0   7.0.0  storefront
grunt                              1.0.4   1.1.0   1.1.0  storefront
grunt-contrib-jshint               2.0.0   2.0.0   2.1.0  storefront
grunt-sass                         3.0.2   3.0.2   3.1.0  storefront
grunt-stylelint                   0.10.1  0.10.1  0.15.0  storefront
node-sass                         4.13.1  4.14.1  4.14.1  storefront
stylelint                         9.10.1  9.10.1  13.5.0  storefront
susy                              2.2.14  2.2.14   3.0.5  storefront
```

## Describe the solution you'd like
Set up RenovateBot or similar to auto-update so we don't have to manually do this. We'll need to test to ensure nothing's broken - our monthly release schedule & testing process should catch any regressions (we may need to adapt the process a little).

## Describe alternatives you've considered
- Stick with current versions … dangerous, and updating gets harder over time.
- Manually update individual dependencies ad hoc … takes more time, and may get ignored over time :)

## Additional context
I've called out on npm dependencies in particular but this bug covers all types of dependency - in particular composer. 

We have some manual dependencies (i.e. update source code with PRs containing library code), e.g. FontAwesome. Might want follow up tasks to address those - e.g. add steps to release / post release process, or migrate to managed dependencies (npm or similar).

A related area is build/bundle size - if we start automatically updating dependencies we may need tooling/process to keep an eye on asset sizes.

**Comment by haszari** [comment]
FYI @jconroy we'll probably want something similar across Storefront family (child themes and extensions). I'm assuming none of the other repos have a specific solution in place?

**Comment by jconroy** [comment]
Correct I have not seen any with a solution for managing dependencies - they are currently quite behind to say the least.

**Comment by slavicd** [comment]
> We should be keeping libs updated unless we have a good reason not to.
Why not the other way around?

**Comment by haszari** [comment]
> Why not the other way around?

There are lots of reasons to keep dependencies updated. For me, the main rationale is to keep up with any security fixes. 

Here are some articles on the topic:

https://github.blog/2019-01-31-keep-your-dependencies-secure-and-up-to-date-with-github-and-dependabot/

https://depfu.com/blog/2016/12/01/why-you-should-keep-your-dependencies-up-to-date

**Comment by slavicd** [comment]
You have given me the how, but not the why.

A security fix is just about the only good reason to update a library in a stable package. Other updates should be there only to be used by a further iteration of client code (minor or major). 

I am a strong believer of don't fix what is not broken.

**Comment by nielslange** [comment]
> You have given me the how, but not the why.

**... to keep up with any security fixes.**

**Comment by haszari** [comment]
This is underway now - we'll see how it goes with 2.5.8 release. See the PR for more details, rationale, and how this affects release testing.

https://github.com/woocommerce/storefront/pull/1376
