### ISSUE TITLE
Focus outline broken for My Account address buttons in Firefox

### ISSUE THREAD

**Issue by slavicd** [woocommerce/storefront#1364]
## Describe the bug

It looks like Storefront's implementation of icons is broken in Firefox when  outlines are present (they are by default in Storefront).

Apparently the `text-indent` property sends text way past the left border, but because it's technically still "visible" the outline goes around the negatively-indented text.

Here's a related S.O. [question](https://stackoverflow.com/questions/1432889/negative-text-indent-causes-large-link-selection-on-click).

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Go to Wocommerce's "My Account" page
2. Click on "Addresses"
3. Click on "Billing Address" or "Shipping Address" (alternatively in web inspector add the "focus" pseudoclass
4. See the outline that appears

## Screenshots
![image](https://user-images.githubusercontent.com/1071705/83062763-d1ca6780-a067-11ea-91d9-6cbae4a15729.png)

## Expected behavior
outline should be smaller and only circumvent the icon.

### Browser Environment
Firefox on Linux

**Comment by haszari** [comment]
Thanks for reporting this @slavicd !

I can reproduce the issue:

<img width="1263" alt="Screen Shot 2020-05-28 at 8 30 58 AM" src="https://user-images.githubusercontent.com/4167300/83069223-a70afe00-a0bd-11ea-913f-df7e6dadf563.png">

This looks similar to a previous issue, hopefully an easy fix. https://github.com/woocommerce/storefront/issues/1221
