### ISSUE TITLE
Replace jQuery with Vanilla JS

### ISSUE THREAD

**Issue by nielslange** [woocommerce/storefront#1365]
## Is your feature request related to a problem? Please describe.

WordPress moves away from jQuery towards Vanilla JS. The Storefront child themes and extensions should follow the same path.

## Describe the solution you'd like

The title says it all: _Replace jQuery with Vanilla JS_

## Describe alternatives you've considered

n/a

## Affected files

- [ ] https://github.com/woocommerce/storefront/blob/master/assets/js/admin/admin.js
- [ ] https://github.com/woocommerce/storefront/blob/master/assets/js/admin/customizer.js
- [ ] https://github.com/woocommerce/storefront/blob/master/assets/js/admin/plugin-install.js

**Comment by haszari** [comment]
At a minimum, I think we should not use jQuery in any new work (though - there is not likely to be major new features in Storefront).

When fixing issues or maintaining existing scripts, I think it's a great idea to consider removing the dependency on jQuery, if it's safe and convenient to do so.

**Comment by senadir** [comment]
Removing jQuery could cause some issues with other plugins or customizations that use jQuery but never managed to define it as a dependency, I share Rua that we should move away from writing new code in jQuery.

**Comment by nielslange** [comment]
Closed due to https://github.com/woocommerce/storefront/issues/1365#issuecomment-635623684 and https://github.com/woocommerce/storefront/issues/1365#issuecomment-636519919
