### ISSUE TITLE
Button size: cart vs. checkout

### ISSUE THREAD

**Issue by uok** [woocommerce/storefront#1420]
Hello,

Why does the button "proceed to checkout" on cart page have bigger padding/font-size/width compared to the "place order" button on the checkout page?

**Comment by nerrad** [comment]
Hi there, 

Would you be able to share some screenshots illustrating what you are seeing?

**Comment by uok** [comment]
Sorry, I found another plugin places the button at the end of the checkout form, which is outside the last div and therefore the default woo css is not applied.

**Comment by uok** [comment]
Sorry, I found another plugin places the button at the end of the checkout form, which is outside the last div and therefore the default woo css is not applied.

**Comment by nerrad** [comment]
I’m interpreting your reply meaning you found a solution, so I’ll close this issue. If I’ve interpreted incorrectly you can still leave a comment with more details about what the problem is and we can consider reopening.
