### ISSUE TITLE
Remove sample products from Storefront onboarding

### ISSUE THREAD

**Issue by haszari** [woocommerce/storefront#1432]
## Is your feature request related to a problem? Please describe.
Storefront has a rich onboarding flow, which imports products and generates store pages (and more).

As WooCommerce core has an [improved onboarding wizard](https://docs.woocommerce.com/document/woocommerce-setup-wizard/), there's less need for Storefront to assist here. And ideally any theme-specific onboarding would integrate with the new flow, rather than be driven from additional onboarding notices.

In particular, Storefront includes [sample product data](https://github.com/woocommerce/storefront/blob/69adc083fa1073284c18a89a429db4476f49f729/inc/nux/class-storefront-nux-starter-content.php#L66)
 and [images](https://github.com/woocommerce/storefront/tree/master/assets/images/customizer/starter-content). This is really convenient for development and demo purposes, but it's unlikely that it's used for real stores.

These sample products are added automatically after clicking through `Let's go` notice to customizer, and saving changes, if the store has no products. This could be confusing, as the merchant has not taken an explicit action to generate sample products. See docs: https://docs.woocommerce.com/document/installation-configuration/#section-10

## Describe the solution you'd like
Remove the sample products from onboarding/nux (new user experience). Optionally guide user to setting up products via WooCommerce core.

## Describe alternatives you've considered
- Definitely a possibility to keep this code in place, as it is useful for testing and demonstrating woo+storefront.
- Remove the product data from Storefront, and add a new prompt to download or generate sample products from an online service - this is probably overkill, and the problem is not unique to Storefront.

**Comment by haszari** [comment]
This is still quite a useful feature, and it's not currently available in Woo core. Marking this issue as blocked until an equivalent feature is implemented in core or wc-admin. Related issue: https://github.com/woocommerce/woocommerce-admin/issues/5022

**Comment by haszari** [comment]
🎉Update: Recent versions of WooCommerce core do include a [sample products task in the onboarding/task list](https://github.com/woocommerce/woocommerce-admin/issues/5022#issuecomment-681033921): 💜

<img width="1169" alt="Screen Shot 2020-08-27 at 10 04 07 AM" src="https://user-images.githubusercontent.com/4167300/91361948-803f9d80-e84d-11ea-8a92-bf7945404591.png">

Thanks @pmcpinto for pointing this out.

I've just tested this and it's the same sample products we know and love:

<img width="1471" alt="Screen Shot 2020-08-27 at 10 12 01 AM" src="https://user-images.githubusercontent.com/4167300/91362080-c1d04880-e84d-11ea-9ec5-b9bd1ce63c94.png">

With that in mind I think we can consider removing the sample products from Storefront.

**Comment by haszari** [comment]
Removing blocked status from this. Because equivalent functionality is available in core, to all themes, with a more explicit UI, we can remove the sample products from Storefront. 

We should take care when removing the feature to ensure there's no downside or impact on Storefront users. Documentation may also need updating.

**Comment by nielslange** [comment]
@haszari Even though recent WooCommerce versions have sample products in their onboarding list, the Storefront starter content is doing much more than simply adding test products to the site. I just created the following two test cases:

1. Storefront with starter content
1. Storefront without starter content

### Steps to reproduce both cases

1. Create a fresh WordPress installation
2. Install and activate the Storefront theme from the WordPress.org theme repo
3. Install and activate the WooCmmerce installation via Storefront onboarding prompt

<table>
<tr>
<td valign="top"><strong>Storefront with starter content:</strong>
<br><br>

![#1432-with-starter-content](https://user-images.githubusercontent.com/3323310/93663515-ce357300-fa92-11ea-8f87-4409a763cf1e.png)
</td>
<td valign="top"><strong>Storefront without starter content:</strong>
<br><br>

![#1432-without-starter-content](https://user-images.githubusercontent.com/3323310/93663513-cbd31900-fa92-11ea-919b-f1320d0a8e24.png)
</td>
</tr>
</table>

In my opinion, having the started content is still useful even though WooCommerce comes with the same sample products. What are your thoughts on this? Do you still think it's worth to remove the started content or shall we rather keep it? From a support perspective, I'd definitely keep it. 

cc: @jconroy & @nerrad

**Comment by haszari** [comment]
> In my opinion, having the started content is still useful even though WooCommerce comes with the same sample products. What are your thoughts on this? Do you still think it's worth to remove the started content or shall we rather keep it? From a support perspective, I'd definitely keep it.

I agree @nielslange  - the focus of this issue is the sample products only. Reading the description I see that's not very clear, so I've updated it!

**Comment by haszari** [comment]
I've started [prototyping this on a branch](https://github.com/woocommerce/storefront/pull/1484). As I explore the code more, I see that this could be a pretty risky change:

- There's a [filter hook `storefront_starter_content`](https://github.com/woocommerce/storefront/blob/trunk/inc/nux/class-storefront-nux-starter-content.php#L260), so some child themes or customizations might be building on this starter content in some way. E.g. a woo+storefront bootstrap/scaffold plugin/theme.
- The rest of the starter content may depend on / require the sample products. 

I'll keep experimenting, will back out if this is too risky.

**Comment by haszari** [comment]
Things seem to work but it's definitely a less friendly experience.

The Storefront onboarding works fine, but the end result is a sad home page with no products.

<img width="1164" alt="Screen Shot 2020-09-29 at 3 26 08 PM" src="https://user-images.githubusercontent.com/4167300/94505680-1c532f00-0268-11eb-94e8-cbbfe2e34cd4.png">

After that I ran the `Import products` step from WooCommerce onboarding `Personalization` task. This added in the products, and the home page looked good – with the exception of the category images:

<img width="1273" alt="Screen Shot 2020-09-29 at 3 24 46 PM" src="https://user-images.githubusercontent.com/4167300/94505593-ea41cd00-0267-11eb-91fe-45af6abbacb8.png">

With that in mind, I'm removing this from 2.8.0. Ideally we find a way to lean into the new woo core onboarding more, and use this as an opportunity to make Storefront more lean and simple – but this is not a priority.
