### ISSUE TITLE
Remove Grunt in favor of using npm scripts

### ISSUE THREAD

**Issue by Ismail-elkorchi** [woocommerce/storefront#1433]
## Is your feature request related to a problem? Please describe.
The Grunt task runner is built on top of Node.js, and frequently, the Grunt packages are actually just wrappers for the Node.js packages. As an example, the logic of [grunt-rtlcss](https://github.com/MohammadYounes/grunt-rtlcss) is built into [rtlcss](https://github.com/MohammadYounes/rtlcss). That extra tool and layer of abstraction is an obstacle for contributors that are only familiar with pure JavaScript and might not know how to use Grunt or others task runners.

## Describe the solution you'd like
Instead of having a Gruntfile.js, we could use npm scripts, and rely on the node package directly to run tasks. This will actually make it easier to contribute to StoreFront. 

References:

- https://medium.com/@maxsilvauk/npm-scripts-who-needs-grunt-or-gulp-77572da16022
- https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/
- https://css-tricks.com/why-npm-scripts/

**Comment by nerrad** [comment]
I agree with this. Grunt is a legacy build process from when Storefront was first created. Our team eventually will be reviewing all the repos we manage and attempt to get as much of them on common build processes/configuration but it's currently low on our priority list given the tasks we currently have.

Thanks for making sure this is on our radar though!
