### ISSUE TITLE
Add icons to store notices

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/storefront#1444]
## Is your feature request related to a problem? Please describe.
Default WooCommerce adds icons to the notices added via `wc_add_notice()`. It's my understanding the icons are helpful to folks who are color-blind since they may not be able to distinguish between the different color codes for notice|error|success notices. These are added in WooCommerce's woocommerce.css stylesheet, but not present in the storefront version of woocommerce.css.

## Describe the solution you'd like
Maintain default Woo's notice icons.

## Additional context
![image](https://user-images.githubusercontent.com/507025/90430147-29cfa380-e084-11ea-80d7-2fb3dcea8c36.png)
versus
![image](https://user-images.githubusercontent.com/507025/90430757-3d2f3e80-e085-11ea-94bf-b7f12df46567.png)

**Comment by haszari** [comment]
Thanks for the report @helgatheviking  - that's a great idea.

**Comment by helgatheviking** [comment]
I've got an issue up for the Twenty Twenty/default themes too: https://github.com/woocommerce/woocommerce/issues/27102
