### ISSUE TITLE
Development Environment failed

### ISSUE THREAD

**Issue by jessemarco** [woocommerce/storefront#1466]
I cloned repository, checkout branch for release/2.7.0 then install dependencies with npm install and I can not use "npm run build"

jesse@jesse:/var/www/html/storefront$ npm run build

    storefront@2.7.0 build /var/www/html/storefront
    grunt

Running "stylelint:all" (stylelint) task
Warning: Unexpected reserved word Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! storefront@2.7.0 build: grunt
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the storefront@2.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by haszari** [comment]
Hi @jessemarco  – thanks for participating!

Note that if you want to use 2.7.0 we recommend installing the [production build from WordPress.org](https://wordpress.org/themes/storefront/). Can you give a bit more info about why you want to build the `release/2.7.0` branch?

Here's the the full set of steps for setting up a local build of storefront:

1. Clone this repository, e.g. `git clone git@github.com:woocommerce/storefront.git` or use whatever git client you prefer.
2. Change directory to the new storefront repo, e.g. `cd storefront`.
3. `npm install` to install nodejs dependencies.
4. `composer install` to install PHP dependencies.
5. `npm run build` to build Storefront.

Storefront requires the following development tools. Please ensure these are installed and up to date.

- [Node.js and NPM](https://nodejs.org) (LTS version recommended).
- [Composer](https://getcomposer.org)

I took a look at the repo `CONTRIBUTING.md` doc, perhaps we can make this info clearer there – do you think that would be helpful?

I'm going to close this issue – I've just rebuilt Storefront locally and confirmed that there's no build problem on the main branch. Please feel free to open an issue with suggestions for how to improve the documentation.

**Comment by jessemarco** [comment]
I believe there is somewhere error here is my steps:

git clone https://github.com/woocommerce/storefront.git

cd storefront/

npm install

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '795f976fe0ebd8b75f26a6dd68f78fd3453ce79f32ecb33e7fd087d39bfeb978342fb73ac986cd4f54edd0dc902601dc') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

php composer.phar install
npm run build

Same error as above.

I want to read source code, have development ver. installed and look through git client what is new feature implemented, read non-minified scripts etc. It is not just about 2.7.0 release.

Thank you for replying me so quickly.

**Comment by jessemarco** [comment]
I had to remove stylelint task in grunt file, that fixed my problem.

**Comment by haszari** [comment]
Possibly you're running an older version of nodejs?
