### ISSUE TITLE
WordPress 5.6 compatibility – test, log any issues

### ISSUE THREAD

**Issue by haszari** [woocommerce/storefront#1485]
[WordPress 5.6](https://make.wordpress.org/core/2020/08/13/wordpress-5-6-release-planning/) is coming! The goal of this issue is to review WP 5.6 for any relevant changes and test Storefront to confirm everything's working correctly; and log any follow up issues if needed. Probably best to start this testing close to WP 5.6 RC – 17 Nov.

Widgets areas are changing – [now edited with block editor](https://github.com/WordPress/gutenberg/issues/13204)! So we may see some wrinkles with widget styling (etc).

**Comment by Aljullu** [comment]
I tested Storefront with WordPress 5.6 and I could only find one issue (#1512).

> Widgets areas are changing – [now edited with block editor](https://github.com/WordPress/gutenberg/issues/13204)! So we may see some wrinkles with widget styling (etc). 

Notice this feature has been punted to WordPress 5.7: https://core.trac.wordpress.org/ticket/51506.

**Comment by Aljullu** [comment]
I will proceed closing this issue for now. We did some testing + we have one more of RC testing to catch new issues. In case some arise, we can open individual issues for them.
