### ISSUE TITLE
PHP8 compatibility - investigation

### ISSUE THREAD

**Issue by haszari** [woocommerce/storefront#1486]
PHP v8 is coming - scheduled for release Nov 26 2020! 

- https://wiki.php.net/todo/php80
- https://www.php.net/archive/2020.php#2020-10-01-4
- https://stitcher.io/blog/new-in-php-8
- https://kinsta.com/blog/php-8/
- https://www.ionos.com/digitalguide/websites/web-development/php-8/

The goal of this issue is to investigate what's changed, how Storefront might be impacted, and log specific follow up issues as needed.

**Comment by Aljullu** [comment]
I tested Storefront with PHP 8 and I wasn't able to find any issue neither any PHP warning related to it.

**Comment by Aljullu** [comment]
I will proceed closing this issue for now. We did some testing + we have one more of RC testing to catch new issues. In case some arise, we can open individual issues for them.

**Comment by haszari** [comment]
I ran exakat and there's one issue to follow up (maybe a false alarm?)

<img width="1224" alt="Screen Shot 2020-11-06 at 4 01 06 PM" src="https://user-images.githubusercontent.com/4167300/98321230-68547900-2049-11eb-85fd-0955ece2f9ea.png">

**Comment by haszari** [comment]
Closing - @Aljullu already investigated the `array_key_exists` warnings and confirmed none of these are causing any bugs.

**Comment by haszari** [comment]
We missed one: https://github.com/woocommerce/storefront/issues/1551
