### ISSUE TITLE
Storefront: Heading Block color settings not working within Cover Block

### ISSUE THREAD

**Issue by philnick206** [woocommerce/storefront#1487]
When adding a Heading block within a Cover block, the color settings for the heading are shown in the editor but ignored when the page is viewed.

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce

1. Create a page with a Cover Block and a Heading Block on top
2. Change the color settings of the Heading Block
3. View the page

(Also, try adding a Group block with a background and then a Heading block)

## Expected behavior

1. The color settings of the Heading Block would show on the page
2. The color settings would adjust automatically based on the background color of the Cover block so that the text is readable  

## Actual result

1. The color settings are not changed on the page/remain black no matter what

## Screenshots

![cover_block_heading](https://user-images.githubusercontent.com/51966986/95011693-6eaa9c00-062a-11eb-8b96-cf3054e17e0d.gif)

### Browser Environment
Firefox 81 on macOS (Catalina)

### WordPress Environment
WP 5.5.1
WooCommerce 4.5.2
Storefront 2.7.0

**Comment by haszari** [comment]
Yep, I can totally reproduce this. Black background white text is particularly unreadable:

<img width="1431" alt="Screen Shot 2020-10-05 at 8 38 27 AM" src="https://user-images.githubusercontent.com/4167300/95025430-35cffd00-06e6-11eb-94b7-2aabec7958fc.png">

<img width="1146" alt="Screen Shot 2020-10-05 at 8 38 15 AM" src="https://user-images.githubusercontent.com/4167300/95025433-3799c080-06e6-11eb-95bd-49cb107f0f20.png">

Thanks for reporting this issue @philnick206 !
