### ISSUE TITLE
Rename @wordpress/env commands

### ISSUE THREAD

**Issue by nielslange** [woocommerce/storefront#1488]
## Is your feature request related to a problem? Please describe.

This is an improvement to the existing @wordpress/env commands.

## Describe the solution you'd like

We're currently using the following @wordpress/env commands:

```
"e2e:start": "wp-env start",
"e2e:stop": "wp-env stop",
"e2e:destroy": "wp-env destroy",
```

This is rather confusing as the command name implies that the e2e tests will be started. However, not the e2e test, but the environment will be started. Therefore, I suggest following the [WordPress convention](https://developer.wordpress.org/block-editor/packages/packages-env/#installation-as-a-local-package) and renaming these commands to:

```
"wp-env": "wp-env"
```

As @nerrad mentioned in p1601659985008100-slack-CD5QY4V6H, this also exposes the usage of the other `wp-env`  sub-commands such as:

```
npm run wp-env start
npm run wp-env stop
npm run wp-env logs
npm run wp-env clean all
npm run wp-env destroy
```

**Comment by nerrad** [comment]
Thanks for creating this issue @nielslange. I'd like to see this happen. Another benefit of this change is any `wp-env` available commands that come in future versions will be exposed automatically. As noted, this also creates some consistency with the implementation of this package in other WordPress and A8C projects.

**Comment by haszari** [comment]
Thanks @nielslange  - adding the generic `npm run wp-env` alias sounds like a good idea to me. 

The e2e tests depend on the wp-env environment being up, so I'd suggest leaving the other commands in place and/or adding docs for e2e.

**Comment by nerrad** [comment]
> The e2e tests depend on the wp-env environment being up, so I'd suggest leaving the other commands in place and/or adding docs for e2e.

The pattern in Gutenberg and elsewhere is to [include docs about environment for the e2e tests](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/testing-overview.md#end-to-end-testing). It's worth noting that e2e tests are NOT necessarily coupled to using `wp-env` for executing the tests. It's technically feasible for _any_ environment to be configured to be the url:port configured for the e2e tests. So I would suggest not keeping `e2e:start` etc for that reason alone.

**Comment by nielslange** [comment]
> Thanks @nielslange - adding the generic `npm run wp-env` alias sounds like a good idea to me.
> 
> The e2e tests depend on the wp-env environment being up, so I'd suggest leaving the other commands in place and/or adding docs for e2e.

I didn't plan to touch any other commands, @haszari.
