### ISSUE TITLE
Inconsistent sale badge background

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/storefront#1509]
## Describe the bug
The sale badge has a white background in the blocks but looks transparent everywhere else.

## To Reproduce
1. Make sure you have at least one product on sale.
2. Create a page with the _Handpicked products_ block and select a product on sale.
3. View it in the frontend and notice the sale badge has a white background.
4. Go to the single product page and inspect the _related products_. Notice the sale badge has a transparent background.

## Expected behavior
The sale badge styles should be consistent independently of which page they are displayed on.

## Screenshots
_Homepage:_
![imatge](https://user-images.githubusercontent.com/3616980/96705452-9f623380-1395-11eb-88e4-ab069dcad7a7.png)

_Single product page:_
![imatge](https://user-images.githubusercontent.com/3616980/96705482-abe68c00-1395-11eb-8ea7-a809e4f345f8.png)

**Comment by s3rrot** [comment]
Hi @Aljullu 

Yesterday I saw this and tried to solve in an easy way. Hope it helps. ;)

**Comment by ralucaStan** [comment]
Closing this is issue as it does not fall into any of our [issue criteria “buckets”](https://github.com/woocommerce/storefront/blob/trunk/STOREFRONT_STATUS.md).
