### ISSUE TITLE
Top menu navigation : Dark background with dark font - barely visible

### ISSUE THREAD

**Issue by lordspace** [woocommerce/storefront#1511]
Just installed WooCommerce and storefront and the top menu is barely visible ?!?.
https://www.loom.com/share/a2fdb482ed274f97860d74f8b595e206?from_recorder=1
Note: I've edited the site address a little bit.

![image](https://user-images.githubusercontent.com/137558/96721402-c11ee300-13b4-11eb-94a9-495d807b27c9.png)

> ### WordPress Environment ###
> 
> WordPress address (URL): https://wpdemo.net
> Site address (URL): https://wpdemo.net
> WC Version: 4.6.0
> REST API Version: ✔ 4.6.0
> WC Blocks Version: ✔ 3.4.0
> Action Scheduler Version: ✔ 3.1.6
> WC Admin Version: ✔ 1.6.1
> Log Directory Writable: ✔
> WP Version: 5.5.1
> WP Multisite: –
> WP Memory Limit: 256 MB
> WP Debug Mode: –
> WP Cron: ✔
> Language: en_US
> External object cache: –
> 
> ### Server Environment ###
> 
> Server Info: Apache
> PHP Version: 7.4.3
> PHP Post Max Size: 58 MB
> PHP Time Limit: 120
> PHP Max Input Vars: 1000
> cURL Version: 7.68.0
> OpenSSL/1.1.1f
> 
> SUHOSIN Installed: –
> MySQL Version: 5.5.5-10.3.22-MariaDB-1ubuntu1
> Max Upload Size: 50 MB
> Default Timezone is UTC: ✔
> fsockopen/cURL: ✔
> SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
> DOMDocument: ✔
> GZip: ✔
> Multibyte String: ✔
> Remote Post: ✔
> Remote Get: ✔
> 
> ### Database ###
> 
> WC Database Version: 4.6.0
> WC Database Prefix: x_58c90ee3_
> Total Database Size: 3.75MB
> Database Data Size: 2.34MB
> Database Index Size: 1.41MB
> x_58c90ee3_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
> x_58c90ee3_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
> x_58c90ee3_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
> x_58c90ee3_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
> x_58c90ee3_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
> x_58c90ee3_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
> x_58c90ee3_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_options: Data: 1.50MB + Index: 0.06MB + Engine InnoDB
> x_58c90ee3_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
> x_58c90ee3_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
> x_58c90ee3_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
> x_58c90ee3_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
> x_58c90ee3_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
> x_58c90ee3_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
> x_58c90ee3_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
> x_58c90ee3_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
> x_58c90ee3_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
> x_58c90ee3_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> x_58c90ee3_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
> 
> ### Post Type Counts ###
> 
> attachment: 2
> custom_css: 1
> customize_changeset: 3
> nav_menu_item: 3
> page: 6
> post: 2
> product: 2
> revision: 4
> 
> ### Security ###
> 
> Secure connection (HTTPS): ✔
> Hide errors from visitors: ✔
> 
> ### Active Plugins (1) ###
> 
> WooCommerce: by Automattic – 4.6.0
> 
> ### Inactive Plugins (0) ###
> 
> 
> ### Must Use Plugins (1) ###
> 
> sandbox.php: by  –
> 
> ### Settings ###
> 
> API Enabled: –
> Force SSL: –
> Currency: USD ($)
> Currency Position: left
> Thousand Separator: ,
> Decimal Separator: .
> Number of Decimals: 2
> Taxonomies: Product Types: external (external)
> grouped (grouped)
> simple (simple)
> variable (variable)
> 
> Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
> exclude-from-search (exclude-from-search)
> featured (featured)
> outofstock (outofstock)
> rated-1 (rated-1)
> rated-2 (rated-2)
> rated-3 (rated-3)
> rated-4 (rated-4)
> rated-5 (rated-5)
> 
> Connected to WooCommerce.com: –
> 
> ### WC Pages ###
> 
> Shop base: #8 - /shop/
> Cart: #9 - /cart/
> Checkout: #10 - /checkout/
> My account: #11 - /my-account/
> Terms and conditions: ❌ Page not set
> 
> ### Theme ###
> 
> Name: Storefront
> Version: 2.8.0
> Author URL: https://woocommerce.com/
> Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
> WooCommerce Support: ✔
> 
> ### Templates ###
> 
> Overrides: –
> 
> ### Action Scheduler ###
> 
> Complete: 2
> Oldest: 2020-10-21 10:23:29 +0000
> Newest: 2020-10-21 10:25:33 +0000

**Comment by Aljullu** [comment]
Hi there @lordspace, did you use the customizer in order to achieve those colors? In the customizer, when you change the header background, you should be able to change the header text color as well:

![imatge](https://user-images.githubusercontent.com/3616980/96737858-6be7cf00-13be-11eb-92cb-640aeaec4d72.png)

**Comment by lordspace** [comment]
@Aljullu thank you for the suggestions. The defaults should set in a such a ways so it runs without having to do that step.

**Comment by Aljullu** [comment]
The default background color is `#ffffff` and the text color `#404040`, ensuring there is enough contrast. If the store owner changes the background color, I think it's fair to expect they will check if the text color needs to be changed as well.

I will proceed closing this issue, but feel free to ping me if you think I missed something. :slightly_smiling_face:

**Comment by lordspace** [comment]
If those are the defaults why the text is not visible?

**Comment by Aljullu** [comment]
Unfortunately, I'm unable to explain what happened in your specific store, but my guess is that at some point you or somebody else modified the header background? If you do a clean install of WP+WC+Storefront the default header background should be `#ffffff`.
