### ISSUE TITLE
Update node/npm versions in package.json.engines

### ISSUE THREAD

**Issue by haszari** [woocommerce/storefront#1521]
https://github.com/woocommerce/storefront/blob/f6db3d25597e246ae52e375e2fa362da634efa00/package.json#L62-L65

Very very old min versions. Should probably update to LTS.

I wonder if there's a bot that can help maintain these, I think I was assuming RenovateBot would notice this!

**Comment by Aljullu** [comment]
@haszari is it ok if I move this issue to milestone 3.0.0? I missed this issue last week and I'm wary about rushing a fix for it into 2.9.0 whose RC is planned for tomorrow.

**Comment by haszari** [comment]
> move this issue to milestone 3.0.0? I missed this issue last week and I'm wary about rushing a fix for it into 2.9.0 whose RC is planned for tomorrow.

@Aljullu I agree, best not to rush it - we can catch this early in 3.0.0 👍
