### ISSUE TITLE
jQuery 3+ fixes, or migrate away from jQuery where practical

### ISSUE THREAD

**Issue by haszari** [woocommerce/storefront#1535]
## Is your feature request related to a problem? Please describe.
WordPress core v5.6 is [updating the bundled version of jQuery to v3](https://make.wordpress.org/core/2020/11/05/updating-core-jquery-to-version-3-part-2/).

Storefront uses the bundled jQuery in a few places. So we'll need to review & test and potentially make some fixes in time for WordPress 5.6.

While we're looking at this, if it's safe & practical to move away from depending on jQuery, then let's do that.

More info:

- https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/ 
- https://make.wordpress.org/core/2020/11/05/updating-core-jquery-to-version-3-part-2/
- https://jquery.com/upgrade-guide/

**Comment by nerrad** [comment]
This will need addressed for WordPress 5.7.

**Comment by mikejolley** [comment]
I've been through the JS files and looked for console warnings and nothing is being flagged. 5.7 has been out a while now :)
