### ISSUE TITLE
Move Storefront setup notice to an inbox message

### ISSUE THREAD

**Issue by senadir** [woocommerce/storefront#1539]
Storefront registers a big notice when installed.
![image](https://user-images.githubusercontent.com/6165348/99840027-0c6f1180-2b6c-11eb-969a-d399151433cd.png)

We need to move that notice an inbox message.
We also need to omit the 'add example product' because that step should be covered by the task list.

**Comment by haszari** [comment]
Thanks for logging this @senadir . The notice covers a few set-up / onboarding tasks, so may be better implemented as a task list item. 

Whoever picks this up – please investigate and propose how to reimplement the notices using the improved inbox/task list features in WooCommerce Admin.

**Comment by budzanowski** [comment]
It looks like there is only one admin notice inside the whole storefront repository ^.
