### ISSUE TITLE
CSS: Please include page ID class in the classlist that appears within the body tag. 

### ISSUE THREAD

**Issue by nagpai** [woocommerce/storefront#1540]
## Is your feature request related to a problem? Please describe.
The page id that appears in the classlist of the body tag in any page or post html code, helps support team a long way in targetting CSS only to that specific page or post. 

The Shop page in Storefront, due to some reason has page ID missing in the list of class. It does not even have a specific class like maybe `woocommerce-shop-page`.

## Describe the solution you'd like

Have the page ID and a special class for the Shop page which will help us add CSS rules specific to that page. 

## Describe alternatives you've considered
Used a not rule which turned out  convoluted, and I am not sure if it works correctly

> body:not(.post-type-archive-product) #woocommerce_product_categories-7 {
    display: none;
}

**Comment by nagpai** [comment]
The body tag of the Shop page currently looks like this 


> <body class="archive post-type-archive post-type-archive-product logged-in admin-bar wp-embed-responsive theme-storefront woocommerce woocommerce-page woocommerce-js group-blog storefront-align-wide right-sidebar woocommerce-active debug-bar-maximized customize-support infinite-scroll neverending">

**Comment by haszari** [comment]
Thanks for the suggestion @nagpai – this sounds like a useful improvement.

> The Shop page in Storefront, due to some reason has page ID missing in the list of class. It does not even have a specific class like maybe `woocommerce-shop-page`.

Do you know if this affects other themes as well - would it be better to fix in Storefront?

Can you clarify your needs/issue – do you specifically want to target the `Shop` page, or do you need more specific classes added to (all) other pages too?

**Comment by nagpai** [comment]
@haszari  - Thanks for the reply, 

It looks like the issue is related to WooCommerce Core. @nielslange  tested this and was able to replicate this with other themes. (TwentyTwenty notably). He suggested moving this to core as well. 

>Can you clarify your needs/issue – do you specifically want to target the Shop page, or do you need more specific classes added to (all) other pages too?

It would be good to have this across other pages too, since users would have a requirement to target CSS to specific pages. 

Either Niels or I will tag the issue in WooCommerce Core repo.

**Comment by haszari** [comment]
> It looks like the issue is related to WooCommerce Core. @nielslange tested this and was able to replicate this with other themes. (TwentyTwenty notably). He suggested moving this to core as well.

cc @juliaamosova for awareness - not sure if there is an existing issue in core repo, feel free to move this one or link 👍

**Comment by nielslange** [comment]
> Either Niels or I will tag the issue in WooCommerce Core repo.

@nagpai & @haszari: I already pinged @juliaamosova on this and believe that this should be addressed in the Woo core rather than within Storefront.
