### ISSUE TITLE
php8 compatibility - implode parameter ordering

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/storefront#1551]
implode() for historical reasons could accept its parameters in either order (For consistency with explode()) however, it is deprecated not to use the documented order of arguments. 

I was running [PHP8 compatibility sniff](https://github.com/PHPCompatibility/PHPCompatibility) over the child themes and noticed the following in storefront core

> Passing the $glue and $pieces parameters in reverse order to implode has been deprecated since PHP 7.4 and is removed since PHP 8.0; $glue should be the first parameter and $pieces the second

Affecting the following line https://github.com/woocommerce/storefront/blob/trunk/inc/nux/class-storefront-nux-starter-content.php#L659

**Comment by haszari** [comment]
Thanks for catching this @jconroy ! Interesting that we missed this (though we were using Exakat, maybe PHPCompatibility has improved recently). 

Let's get this fix in the next release. cc @budzanowski  - can you get a fix for this into 3.0.0 final? If so - great, if not (or if for some reason there's a problem) we can defer this in 3.1.0.

**Comment by budzanowski** [comment]
@haszari PR is ready. I will try to target 3.0.0.
https://github.com/woocommerce/storefront/pull/1553
