### ISSUE TITLE
PHP8 compatibility. Fatal error receives while selecting storefront theme.

### ISSUE THREAD

**Issue by apeksha10** [woocommerce/storefront#1554]
## Describe the bug
PHP-8 compatibility. Fatal error receives while selecting storefront theme.

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. I have PHP 8 on my local, WP 5.5.3
2. Install and activated WooCommerce
3. selecting Storefront theme
4. site loading continuously and below fatal error received.

Fatal error : Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in C:\xampp\htdocs\wordpress\wp-includes\widgets.php:1265 Stack trace: #0 C:\xampp\htdocs\wordpress\wp-includes\widgets.php(1265): array_merge(wp_inactive_widgets: Array, sidebar-1: Array, header-1: Array, footer-1: Array, footer-2: Array, footer-3: Array, footer-4: Array) #1 C:\xampp\htdocs\wordpress\wp-includes\widgets.php(1220): retrieve_widgets(true) #2 C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(289): _wp_sidebars_changed('Twenty Twenty') #3 C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #4 C:\xampp\htdocs\wordpress\wp-includes\plugin.php(478): WP_Hook->do_action(Array) #5 C:\xampp\htdocs\wordpress\wp-includes\theme.php(3267): do_action('after_switch_th...', 'Twenty Twenty', Object(WP_Theme)) #6 C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(287): check_theme_switched('') #7 C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #8 C:\xampp\htdocs\wordpress\wp-includes\plugin.php(478): WP_Hook->do_action(Array) #9 C:\xampp\htdocs\wordpress\wp-settings.php(546): do_action('init') #10 C:\xampp\htdocs\wordpress\wp-config.php(94): require_once('C:\\xampp\\htdocs...') #11 C:\xampp\htdocs\wordpress\wp-load.php(37): require_once('C:\\xampp\\htdocs...') #12 C:\xampp\htdocs\wordpress\wp-admin\admin.php(34): require_once('C:\\xampp\\htdocs...') #13 {main} thrown in C:\xampp\htdocs\wordpress\wp-includes\widgets.php on line 1265

## Screenshots
https://www.screencast.com/t/iPG4gdDSc

**Comment by haszari** [comment]
Hi there @apeksha10 - thanks for testing with PHP8!

WordPress and the community of themes and plugins are currently working towards PHP8 support. Regarding WP core **WordPress 5.6** is the release that is targeted for PHP8 support. 

If you're testing Storefront or other themes/plugins with PHP8, I recommend using [WordPress 5.6 (currently at beta/RC)](https://wordpress.org/download/releases/#betas). 

You can find out more about WordPress PHP8 compatibility testing here:

- https://make.wordpress.org/core/2020/10/06/call-for-testing-php-8-0/
- https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/
- https://wordpress.org/download/releases/#betas

When you've upgraded to WordPress 5.6, please comment to let us know of you are still seeing this issue. Thanks 😄

**Comment by apeksha10** [comment]
Yes.. after uploading WordPress 5.6 copy, No fatal error received while selecting the storefront theme.

**Comment by haszari** [comment]
> Yes.. after uploading WordPress 5.6 copy, No fatal error received while selecting the storefront theme.

Great - thanks for confirming. I'll close this issue.
