### ISSUE TITLE
[BUG] Fatal error when WooCommerce Admin is disabled

### ISSUE THREAD

**Issue by ospiotr** [woocommerce/storefront#1563]
####Hey there!

**Describe the bug**

I am using an [official WooCommerce filter](https://woocommerce.wp-a2z.org/oik_hook/woocommerce_admin_disabled/) to disable WooCommerce Admin in my site:
`add_filter( 'woocommerce_admin_disabled', '__return_true' );`

When Storefront is trying to display a notice (when Storefront is installed but not yet configured), fatal error happens:

```
Fatal error:  Uncaught Exception: Invalid data store. in /wp-content/plugins/woocommerce/includes/class-wc-data-store.php:107
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct()
#1 /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/Note.php(85): WC_Data_Store::load()
#2 /wp-content/themes/storefront/inc/nux/class-storefront-nux-admin-inbox-messages-customize.php(32): Automattic\WooCommerce\Admin\Notes\Note->__construct()
#3 /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/NoteTraits.php(74): Storefront_NUX_Admin_Inbox_Messages_Customize::get_note()
#4 /wp-content/themes/storefront/inc/nux/class-storefront-nux-admin.php(193): Storefront_NUX_Admin_Inbox_Messages_Customize::possibly_add_note()
#5 /wp-includes/class-wp-hook.php(287): Storefront_NUX_Admin->admin_inbox_messages()
#6  in /wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 107
```
**Solution**

It seems that Storefront since version 3.0.0 is not checking if WooCommerce Admin is activated. It is trying to display the WooCommerce Admin notice without checking if it is possible.

There is a WooCommerce function for this: **[is_wc_admin_active](https://woocommerce.wp-a2z.org/oik_api/woocommerceis_wc_admin_active/)**

**To Reproduce**
1. Use fresh WooCommerce installation
2. Apply the filter `add_filter( 'woocommerce_admin_disabled', '__return_true' );`
3. Make sure that WooCommerce Status shows WooCommerce Admin as Inactive: https://i.imgur.com/hgP2Zyg.png
4. Activate Storefront
5. Fatal error on the frontend of the admin panel.

**Operating environment:**
- Storefront  version: 3.0.0
- WooCommerce version: 4.8.0
- WordPress version: 5.6
- PHP version: 7.4.13

**Comment by haszari** [comment]
Thanks for reporting this @ospiotr ! Looks like we missed that filter. 

@senadir Can you take a look at this as part of porter rotation? Thank you 🙇
