### ISSUE TITLE
Missing method causing 500 error

### ISSUE THREAD

**Issue by mfilip** [woocommerce/storefront#1580]
## Describe the bug
Missing method or bad method name `Storefront_NUX_Admin_Inbox_Messages_Customize::possibly_add_note();` trigger 500 error when trying to enter Woocommerce `/wp-admin/admin.php?page=wc-admin`. After checking error log I have found that  `possibly_add_note'  method is not exist in class definition Storefront_NUX_Admin_Inbox_Messages_Customize. Class do not inherit so called method is missing or have bad name

## To Reproduce
1. Install version 3.1.0 
2. Try to enter  `/wp-admin/admin.php?page=wc-admin`
3. Check file `storefront/inc/nux/class-storefront-nux-admin.php:193`
4. Check file `storefront/inc/nux/class-storefront-nux-admin-inbox-messages-customize.php` where class is defined

**Comment by nerrad** [comment]
Confirmed.

**Comment by nerrad** [comment]
Actually, it was pointed out to me by @Aljullu  (and I missed) that `possibly_add_note` comes from [`NoteTraits`](https://github.com/woocommerce/woocommerce-admin/blob/7fbed9e56ed3715625343b336439858d1ee79c89/src/Notes/NoteTraits.php#L73-L81). It's likely this would be related to an older version of WooCommerce active that doesn't have `NoteTraits` available (or the method referenced available).

**Comment by Aljullu** [comment]
Correct. @mfilip do you have some more details that could help us reproduce the issue? It would be interesting to know the WordPress and WooCommerce versions you are using. A screenshot of the error would also be helpful.

In the meanwhile, you can try if installing [WooCommerce Admin](https://wordpress.org/plugins/woocommerce-admin/) fixes the issue?

Thanks in advance!

**Comment by mfilip** [comment]
I'm using wordpress:5.6-php7.3 and woocommerce 4.2 for bug check but from our testing error occuring till most recent wocommerce version with above wordpress. About screens there is not much I can make because on frontend you got blank screen.  

Logs with error:
```web_1  | 172.20.0.1 - - [11/Jan/2021:12:17:25 +0000] "POST /wp-login.php HTTP/1.1" 302 1172 "http://localhost:8000/wp-login.php?redirect_to=http%3A%2F%2Flocalhost%3A8000%2Fwp-admin%2Fadmin.php%3Fpage%3Dwc-admin&reauth=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
web_1  | [Mon Jan 11 12:17:25.908190 2021] [php7:error] [pid 211] [client 172.20.0.1:37636] PHP Fatal error:  Uncaught Error: Call to undefined method Storefront_NUX_Admin_Inbox_Messages_Customize::possibly_add_note() in /var/www/html/wp-content/themes/storefront/inc/nux/class-storefront-nux-admin.php:193\nStack trace:\n#0 /var/www/html/wp-includes/class-wp-hook.php(287): Storefront_NUX_Admin->admin_inbox_messages('')\n#1 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)\n#2 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)\n#3 /var/www/html/wp-admin/admin-header.php(292): do_action('admin_notices')\n#4 /var/www/html/wp-admin/admin.php(239): require_once('/var/www/html/w...')\n#5 {main}\n  thrown in /var/www/html/wp-content/themes/storefront/inc/nux/class-storefront-nux-admin.php on line 193, referer: http://localhost:8000/wp-login.php?redirect_to=http%3A%2F%2Flocalhost%3A8000%2Fwp-admin%2Fadmin.php%3Fpage%3Dwc-admin&reauth=1
web_1  | 172.20.0.1 - - [11/Jan/2021:12:17:25 +0000] "GET /wp-admin/admin.php?page=wc-admin HTTP/1.1" 500 25772 "http://localhost:8000/wp-login.php?redirect_to=http%3A%2F%2Flocalhost%3A8000%2Fwp-admin%2Fadmin.php%3Fpage%3Dwc-admin&reauth=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
web_1  | 172.20.0.1 - - [11/Jan/2021:12:17:25 +0000] "GET /wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/app/style.css?ver=1.2.3 HTTP/1.1" 200 11751 "http://localhost:8000/wp-admin/admin.php?page=wc-admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"```

**Comment by mfilip** [comment]
In my humble opinion is simple even if somthing should come from `NoteTraits` is not implemented inside class `Storefront_NUX_Admin_Inbox_Messages_Customize` as static method of this class. If there is not class extension to inherit this method calling missing one will cause 500 error. 
```
public function admin_inbox_messages() {
			// The setup already has happened. No inbox message needed.
			if ( true === (bool) get_option( 'storefront_nux_dismissed' ) ) {
				return;
			}
			// Storefront settings page link and welcome message.
			require 'class-storefront-nux-admin-inbox-messages-customize.php';
			Storefront_NUX_Admin_Inbox_Messages_Customize::possibly_add_note();
		}

```
I do not think this is related to woocommerce version but rather bug in coding

**Comment by Aljullu** [comment]
Thanks for the details @mfilip! I was able to reproduce the issue in WooCommerce 4.2. I will try to open a PR with a fix today. In the meanwhile, updating WooCommerce to the latest version should fix the issue.
