### ISSUE TITLE
Checkout block: error notice icon is missing

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/storefront#1582]
## To Reproduce
1. Remove all available shipping methods from WooCommerce > Settings > Shipping.
2. Go to the Checkout block and scroll to the Shipping step.
3. Notice the notice icon is missing:
![imatge](https://user-images.githubusercontent.com/3616980/104434296-5f24e280-558b-11eb-8251-bc2a349e2c8f.png)

Maybe a regression from #1574?

**Comment by nerrad** [comment]
I'm giving this a higher priority only because it's a poor first experience for users of storefront and the checkout blocks. So I want to make sure it is prioritized before other bugs.
