### ISSUE TITLE
Conflict with WooCommerce Blocks, Star Rating Icons Missing

### ISSUE THREAD

**Issue by JoshuaGoode** [woocommerce/storefront#1586]
## Describe the bug
WooCommerce blocks fail to load star rating icons when Storefront is active.

The blocks attempt to load `font-family: star;` which appears to be available as a .woff, .eot, and .ttf under`wp-content/plugins/woocommerce/assets/fonts/`

Other themes do not appear to be having issues.

Possible regression related to https://github.com/woocommerce/storefront/pull/1574
cc: @mikejolley @opr @Aljullu 

Discussed internally with @GeoJunkie and @fevered.

Isolating the problem:
- [X] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [X] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Create a page using WooCommerce's product blocks.
2. Ensure at least one product that appears in the block has a rating.
3. View the front-end of the page.

## Screenshots
![image](https://user-images.githubusercontent.com/4887830/104657629-4998e100-568f-11eb-9375-e12edcbd96ba.png)

### WordPress Environment
Tested across WordPress.com, Pressable, Jurassic Ninja, and SiteGround.

Various infrastructures but all running WooCommerce 4.9 and Storefront 3.3.0

**Comment by JoshuaGoode** [comment]
I seem to be missing privileges to add labels within this repo, adding some pings to the original report.

**Comment by Aljullu** [comment]
Thanks for opening this issue @JoshuaGoode!

 I can confirm the issue, it seems to affect several blocks:

* PHP-based product grid blocks:
![imatge](https://user-images.githubusercontent.com/3616980/104707222-6a5b4800-571c-11eb-816f-9cd7eccad0f9.png)
* All Products block:
![imatge](https://user-images.githubusercontent.com/3616980/104707126-4ac41f80-571c-11eb-984d-079343fa4d9d.png)
* Reviews blocks:
![imatge](https://user-images.githubusercontent.com/3616980/104707178-5e6f8600-571c-11eb-9fd9-e6e87bded661.png)

Shop page is not affected:
![imatge](https://user-images.githubusercontent.com/3616980/104707301-8363f900-571c-11eb-959d-1cb2ab210639.png)
