### ISSUE TITLE
Remove maximum-scale from viewport meta tag

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/storefront#1599]
Storefront defines `maximum-scale=2.0` in its viewport meta tag, but this is bad for accessibility. It limits how much users can zoom in the page.

Some browsers have an option to ignore it, but it would be better to completely remove it from the theme.

The relevant code line:

https://github.com/woocommerce/storefront/blob/2618a3119d93e7624bc3ebafcbb88be7a8e695c2/header.php#L14

**Comment by Siddharth1010** [comment]
Hi @Aljullu , I'll remove it from `header.php`
