### ISSUE TITLE
Editor Placeholder Text Disappears With Dark Background

### ISSUE THREAD

**Issue by joweber123** [woocommerce/storefront#1618]
## Describe the bug
If you choose a dark background in the Customizer and then go to create a new page, it appears to be completely blank.  The placeholder text 'Add Title' is there but it is the same color as the background. 
![Markup on 2021-03-02 at 15:43:23](https://user-images.githubusercontent.com/24914028/109609006-1393bb80-7b6e-11eb-8bb5-a9d16cec490c.png)

## To Reproduce
1. Go to Customize > Background and choose `#020202` or any other very dark color.
2. Then create a new page. 
3. The default placeholder text is now not visible. 

## Screenshots
This can be solved by activating the newest Gutenberg plugin.  When active this will add a new class `.is-dark-theme` which makes this text visible.  At the time of this writing, the Gutenberg plugin is running *Version 10.0.2* 

![Markup on 2021-03-02 at 15:49:16](https://user-images.githubusercontent.com/24914028/109609574-dc71da00-7b6e-11eb-89e7-1cc74575d825.png)

## Expected behavior
Default text should be visible on the Editor screen.

### WordPress Environment
I am able to replicate this on a local install as well as on WordPress.com.

**Comment by nerrad** [comment]
Thanks for leaving this report @joweber123!

**Comment by nielslange** [comment]
@joweber123 Can you still reproduce this problem locally and on WordPress.com? You mentioned that with the Gutenberg plugin version 10.0.2, the problem did not appear. Based on https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/, the recent WordPress version 5.8 contains the functionality of Gutenberg version 10.0-10.7.

That said, I was also not able to reproduce this problem when using WordPress 5.7.2 locally, so I assume that this particular problem had been addressed in an earlier version of WordPress already. Long story short, can you still reproduce this problem on your end, or can this issue be closed?

**Comment by joweber123** [comment]
We can close this issue.  Looks like it has already been solved by some update. Thanks for taking a look @nielslange!
