### ISSUE TITLE
Product Navigation repeating

### ISSUE THREAD

**Issue by notrealdev** [woocommerce/storefront#1631]
Hi, i have product category with 4 products.
When go to product page and click next product.
It keeps on repeating 1 and 2 instead of going to sequential to the next products in the category.

My images:
https://i.imgur.com/Xct1l6Z.jpg
https://i.imgur.com/33hRsqV.jpg

My video:
https://youtu.be/bor4Lkbfi3c

Can you check it?
Thanks.

**Comment by GlennMartin1** [comment]
This is likely the cause and resolution, here: https://github.com/woocommerce/storefront/issues/848#issuecomment-386105350

**Comment by notrealdev** [comment]
Thank @GlennMartin1 I will try it 👍

**Comment by notrealdev** [comment]
Yes, as @GlennMartin1 said
`The date and time for each product is basically the same`
Thank you.
