### ISSUE TITLE
TTFB is too slow due to Storefront theme

### ISSUE THREAD

**Issue by WhatEverBusiness** [woocommerce/storefront#1638]

**Comment by GlennMartin1** [comment]
I regularly get approx 1-second fully-loaded time with Storefront.

**Comment by WhatEverBusiness** [comment]
Sometimes it loads at 3+ seconds TTFB too.

**Comment by nerrad** [comment]
> The hosting provider and WooCommerce both confirmed that the issue is coming from the theme itself, and not any plugin.

Can you please provide additional information on how this conclusion was arrived at? Unfortunately at the moment there is not enough information provided that allows us to take any action here.
