### ISSUE TITLE
Featured Category or Featured Product WooCommerce blocks button do not centre align

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/storefront#1651]
## Describe the bug
When using the Featured Category or Featured Product WooCommerce blocks on a page within Storefront the buttons do not centre align when specified to do so. They seem to always align to the left.

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
Steps to reproduce the behaviour:
1. Create a page and add the Featured Category or Featured Product WooCommerce blocks.
2. Leave the settings as the default on the blocks and then view the page.
4. See error displaying.

## Expected behaviour

Within the page when the blocks are added they are centre aligned within the editor.

![buttons-editor](https://user-images.githubusercontent.com/1190565/115412725-80314b00-a1ec-11eb-98c0-f28dd9e15b46.png)

When viewing on the customer-facing site using Storefront the buttons are aligned to the left.

![buttons-frontend](https://user-images.githubusercontent.com/1190565/115412868-a656eb00-a1ec-11eb-8120-fbf8d1024143.png)

Testing with the Twenty Twenty-One theme enabled the buttons respect the editor settings and display centered.

![twenty-buttons](https://user-images.githubusercontent.com/1190565/115413177-e0c08800-a1ec-11eb-850e-0e9e7a4368c3.png)

### Browser Environment
Please provide as much detail as possible about your testing environment.

- Platform: All
- Browser(s): All

### WordPress Environment
Please provide relevant details of your WordPress setup and server environment.

The latest version of WordPress, WooCommerce and the Storefront theme.

**Comment by ralucaStan** [comment]
Hello @stuartduff,
thank you for taking the time to report this bug. 

This was fixed as part of the [v4.9.0 release](https://github.com/woocommerce/woocommerce-gutenberg-products-block/releases/tag/v4.9.0) nine days ago. Let us know if you can still reproduce it after updating WooCommerce Blocks to the latest version.

**Comment by nerrad** [comment]
@stuartduff feel free to update this issue if you find it still isn't fixed.
