### ISSUE TITLE
Some font face & family rules are partially slashed

### ISSUE THREAD

**Issue by JJJ** [woocommerce/storefront#1662]
## Describe the bug

See: https://themes.trac.wordpress.org/browser/storefront/3.5.1/assets/css/base/icons.css
Specifically: `font-family:Font Awesome\ 5`

In (what becomes) icons.css, the `font-face` definitions and `font-family` rules end up having a single slash in them.

Because everything in this file is mysteriously slashed identically, this doesn't cause bugs with Storefront itself, but attempting to extend it requires CSS to use `Font Awesome\ 5 Brands` instead of `Font Awesome 5 Brands`.

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Install Storefront
2. Edit: `assets/css/base/icons.css`
3. See definitions for: `Font Awesome\ 5`

## Expected behavior
I expect to use `Font Awesome 5 Brands` for the font-family, and not `Font Awesome\ 5 Brands`.

### Browser Environment
Please provide as much detail as possible about your testing environment.

- Platform: Any
- Browser(s): Any

### WordPress Environment
Any

### Research
1. Font Awesome's vendor SCSS appears OK
2. Storefront's core SCSS appears OK

**Comment by nerrad** [comment]
This is an odd one, the css is a compiled file and it's not clear what is causing the backslash here. I did a brief google search to see if I could find anything on this type of behaviour and couldn't.

Whoever picks this up, we could try switching to a different sass engine maybe and see if that fixes?
