### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by colemickens** [woocommerce/storefront#1669]
## Describe the bug

Hi, I hope this isn't too odd. I'm a bit nervous that there's only one reference that I can find to this project's license, and it's one of those little project pill-badge things that says GPL-3-or-later and links to: https://packagist.org/packages/woocommerce/woocommerce (which doesn't seem to authoritative indicate anything about `storefront`'s license...).

Is this accurate - is Storefront GPL3-or-later? Would it make sense to have a copy of GPL3 in the repo, maybe named LICENSE or COPYING?

**Comment by mikejolley** [comment]
Hi,

It's GPL like WooCommerce itself.

I don't think we need a dedicated licence file since it's stated in the readme(s) and main style file. However, I did notice some places said GPL 2 and some GPL 3, so I've made it consistent in https://github.com/woocommerce/storefront/pull/1674

Thanks
