### ISSUE TITLE
Storefront hides disclosure arrow on <summary> tags. 

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/storefront#1720]
## Describe the bug
Storefront styles hide disclosure arrow on `<summary>` tags. 

- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
Create a page with a custom HTML block containing the following markup:

```html
<details>
  <summary>Summary</summary>
  <ul>
    <li>Details</li>
    <li>Details</li>
    <li>Details</li>
</ul>
</details>
```

## Expected behaviour
The summary should show, complete with a disclosure arrow to indicate that it is expandable:
![Screenshot 2021-06-30 at 09 43 56](https://user-images.githubusercontent.com/1097338/123930611-d3abdc00-d987-11eb-9246-42a2aff8557e.png)

## Actual behaviour
The summary title displays, but without a disclosure arrow to indicate that it can be expanded:
![Screenshot 2021-06-30 at 09 44 37](https://user-images.githubusercontent.com/1097338/123930658-dd354400-d987-11eb-9682-dac290909edc.png)

## Cause
The cause of this behaviour is the `<summary>` tag being set to `display: block` overriding the browser's default `list item` behaviour. The CSS involved comes from an (out-of-date) copy of normalize.css and is:
```css
article, aside, details, figcaption, figure, footer, header, hgroup, main, menu, nav, section, summary {
    display: block;
}
```

**Comment by 9ete** [comment]
Here's a fix (removed the summary selector from the CSS rule in _normalize.css).

https://github.com/woocommerce/storefront/pull/1723
