### ISSUE TITLE
Fonts url path contains duplicate slash

### ISSUE THREAD

**Issue by vanderwijk** [woocommerce/storefront#1742]
When checking the source code of my store I found that the inline styles for the star and WooCommerce fonts contain a duplicate slash. See this example from the source page of my store:

`@font-face {
				font-family: star;
				src: url(https://bestelgrindenzand.nl/wp-content/plugins/woocommerce/assets/fonts//star.eot);
				src:
					url(https://bestelgrindenzand.nl/wp-content/plugins/woocommerce/assets/fonts//star.eot?#iefix) format("embedded-opentype"),
					url(https://bestelgrindenzand.nl/wp-content/plugins/woocommerce/assets/fonts//star.woff) format("woff"),
					url(https://bestelgrindenzand.nl/wp-content/plugins/woocommerce/assets/fonts//star.ttf) format("truetype"),
					url(https://bestelgrindenzand.nl/wp-content/plugins/woocommerce/assets/fonts//star.svg#star) format("svg");
				font-weight: 400;
				font-style: normal;
			}
			@font-face {
				font-family: WooCommerce;
				src: url(https://bestelgrindenzand.nl/wp-content/plugins/woocommerce/assets/fonts//WooCommerce.eot);
				src:
					url(https://bestelgrindenzand.nl/wp-content/plugins/woocommerce/assets/fonts//WooCommerce.eot?#iefix) format("embedded-opentype"),
					url(https://bestelgrindenzand.nl/wp-content/plugins/woocommerce/assets/fonts//WooCommerce.woff) format("woff"),
					url(https://bestelgrindenzand.nl/wp-content/plugins/woocommerce/assets/fonts//WooCommerce.ttf) format("truetype"),
					url(https://bestelgrindenzand.nl/wp-content/plugins/woocommerce/assets/fonts//WooCommerce.svg#WooCommerce) format("svg");
				font-weight: 400;
				font-style: normal;
			}`

In the the file inc/woocommerce/class-storefront-woocommerce.php on line 101 there is a superflous slash in this line of code:

`$fonts_url = plugins_url( '/woocommerce/assets/fonts/' );`

Removing the trailing slash from this line should fix the issue (alternatively, the slash can be removed from the lines 109 - 112 and 118 - 123.

Also, adding `font-display: swap;` should give a nice improvement to the Google Pagespeed Insights score so maybe this can be done too.

**Comment by vanderwijk** [comment]
Reopening this issue as I accidentally closed it when merging the fix to my fork.

**Comment by mikejolley** [comment]
Hi @vanderwijk 

Did you want to open a pull request for this since you have the fix in your branch?

Thanks

**Comment by vanderwijk** [comment]
Yes, I tried to open a pull request but it somehow ended up in my fork instead of in this repo. I have never opened a pull request before so this is a bit of a learning curve. Do you have any tips for me?

**Comment by mikejolley** [comment]
Only https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork - the GitHub UI allows this.

**Comment by vanderwijk** [comment]
> Only https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork - the GitHub UI allows this.

Thanks! I installed Github Desktop and that made creating the pull request super easy.
