### ISSUE TITLE
Since 3.6.0 - Release Source code archives missing build/compilation files

### ISSUE THREAD

**Issue by user-1138** [woocommerce/storefront#1760]
## Describe the bug
Since Release 3.6.0, the .zip/.tar.gz Source code assets, are missing all of the build/compilation related files (i.e. Grunt, Composer, Sass, etc...).

For example, download the 3.6.0 [Source Code (zip)](https://github.com/woocommerce/storefront/archive/refs/tags/3.6.0.zip), and it only contains the .php, .txt, and image (.jpg, .png., .svg, etc) files.

Download the 3.5.1 [Source Code (zip)](https://github.com/woocommerce/storefront/archive/refs/tags/3.5.1.zip) and it contains the hidden .github directory, plus all of the other grunt, composer, sass, etc. files.

Isolating the problem (mark completed items with an [x]):
- [X] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [X] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Go to [https://github.com/woocommerce/storefront/releases/tag/3.6.0](https://github.com/woocommerce/storefront/releases/tag/3.6.0)
2. Download and extract [https://github.com/woocommerce/storefront/archive/refs/tags/3.6.0.zip](https://github.com/woocommerce/storefront/archive/refs/tags/3.6.0.zip) or [https://github.com/woocommerce/storefront/archive/refs/tags/3.6.0.tar.gz](https://github.com/woocommerce/storefront/archive/refs/tags/3.6.0.tar.gz)
3. Open the extracted directory.
4. Voilà!

## Screenshots
NA

## Expected behavior
I expect all the build/compilation stuff to be in the Source Code archives.

FYI - Specifically, I use Grunt to build all the sass stuff for each release, so that I can merge the latest css changes with my custom child theme's css code and I then minify and serve only my own .css assets on my prod websites (to reduce HTTP requests) I'm a stickler for performance :-D, and this also helps to keep my custom/child theme css structurally/syntactically inline with Storefront css targeting the correct elements/tags, etc...

This was easier before Storefront switched to minified/Sass style sheets somewhere around Storefront 2.x.x ( I can't remember ), but it's easy enough to build the sass stuff with Grunt since then to get the desired beautified css files with comments.

If you could put all this back into the archives (particularly the latest 3.8.0 one) that'd be much appreciated, I'm about 3 months behind on my theme updates... 8-P

Thanks!

### Browser Environment
NA

- Platform: NA
- Browser(s): NA

### WordPress Environment
NA

**Comment by opr** [comment]
Thanks for reporting this @user-1138, definitely a strange one!

We added a `.gitattributes` file in https://github.com/woocommerce/storefront/pull/1674 with the goal to exclude `.scss` files from the _built_ archives. Looks like excluding them from the _source_ archives is an unintended side effect.

I'll add this job to our backlog to investigate, ~~but in the meantime you can get the source archives for each tag by going to this URL:~~

~~https://github.com/woocommerce/storefront/tree/3.8.1 (change the version number on the end)~~

~~then download the archive using this button on the GitHub website:~~

Edit: looks like the files are also missing from these archives too.

<img src="https://user-images.githubusercontent.com/5656702/129925565-91a64385-639e-44c2-a48b-d08f2157f9ed.png" width=380 />~~

**Comment by user-1138** [comment]
No probs @opr! And yeah, it had me scratchin' my head at first... 8-P

**Comment by opr** [comment]
Hi @user-1138 - After discussing internally, we're going to move forward with fixing this for future releases and tags, but we won't be backporting the fix to earlier releases.

If you need files from those earlier versions, I'd recommend [cloning this repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository) and then [checking out the tags](https://www.git-tower.com/learn/git/faq/git-checkout-tag/) you need. 

Thanks again for reporting this issue!

**Comment by user-1138** [comment]
No probs - on all counts!
