### ISSUE TITLE
Full width block broken in 3.8.0

### ISSUE THREAD

**Issue by vanderwijk** [woocommerce/storefront#1761]
When using a full width cover block, this is no longer spanning the full width of the browser.

I have been able to reproduce this on two different sites. See screenshots below.

This issue is caused by a missing 'width: auto' from PR #1713 

<img width="1552" alt="V3 7 0" src="https://user-images.githubusercontent.com/1212909/129880629-8b3126f6-cd82-44d5-8050-f056d3b564bd.png">
<img width="1551" alt="V3 8 0" src="https://user-images.githubusercontent.com/1212909/129880650-395ec263-c4ea-4edd-80b5-62b9dc30f60a.png">

See also this support topic by a different user https://wordpress.org/support/topic/white-space-on-right-side-blocks-are-not-full-width/

**Comment by opr** [comment]
Thanks for filing this issue! I've created a PR (#1762) that will address this.

**Comment by opr** [comment]
Hello @vanderwijk - [Storefront 3.8.1](https://github.com/woocommerce/storefront/releases/tag/3.8.1) has been released which fixes this regression. Many thanks again for reporting this quickly, and for also sharing your fix.
