### ISSUE TITLE
Menus NOT working on Storefront theme from Woocommerce

### ISSUE THREAD

**Issue by annabellegauberti** [woocommerce/storefront#1777]
Further to my ticket opened on 3 August 2021, I have not received any appropriate answers from you, since you bloody tested my websites crefovi.com and crefovi.fr from your desktop.

I told you, in my original email dated 2 August 2021, that the issue with the menu was on the devices which are IPHONES, AND PROBABLY ALL MOBILE PHONES.

So I need you to go back to the drawing board, constructively review my ticket below, and constructively, professionally and with intelligence provide added value answers and solutions to my outstanding points below.

----

 Further to my support ticket dated 1 August 2021, I have not heard back from you in any productive way with respect to the following outstanding technical issues relating to your premium theme storefront.

 
Would you please revert back to me in a meaningful and efficient manner, to resolve this ongoing issue?
 
 
 
The menu bar is not opening on the mobile versions of both my websites www.crefovi.com  and www.crefovi.fr , on both my iphones 8.
 
Would you please correct this fault and then let me know that it has now been repaired, and that my "menu bars" on the mobile versions of my websites https://crefovi.com  and https://crefovi.fr  are now properly working?

**Comment by nielslange** [comment]
> Further to my ticket opened on 3 August 2021, I have not received any appropriate answers from you, since you bloody tested my websites crefovi.com and crefovi.fr from your desktop.

We are happy to help you, but we will not tolerate abusive language. If you want our continued help, I’m going to ask you to be respectful.

Kindly note that this repository is for development purposes only. Support requests for the Storefront theme need to be addressed to https://wordpress.org/support/theme/storefront/. Please also keep the [Storefront support guidelines](https://wordpress.org/support/topic/guide-for-using-the-storefront-forum-2/) in mind.
