### ISSUE TITLE
[GlobalStep] "Add to cart" button text appears misaligned  if products per row is set to "6" for Storefront theme.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/storefront#1787]
## Bug Description:
When products per row is set to "6" for storefront theme, the "Add to Cart" button text appears misaligned.

## Environment:
Woocommerce Version : WooCommerce 5.5 RC 1 and 5.4.1
WordPress version: (v5.8 Beta 3)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the onboarding setup wizard.
1. Choose the Storefront theme.
1. Add Some Products.
1. Go to Appearance->Customize.
1. Select WooCommerce->Product catalog option.
1. Set product per rows value to 6.
1. Observe that "Add to Cart" button text appears misaligned.

## Actual Result:
"Add to cart" button text appears misaligned  if products per row is set to "6" for Storefront theme.

## Expected Result:
"Add to cart" button text should be properly aligned if products per row is set to "6".

## Screenshot:

![#30200_2](https://user-images.githubusercontent.com/41110392/124145442-6c3a7d00-daaa-11eb-9155-d24cc436f9c4.png)
![#30200](https://user-images.githubusercontent.com/41110392/124145459-70ff3100-daaa-11eb-92a4-bed71244fd3c.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
@Aljullu - makes sense.

**Comment by 9ete** [comment]
Fixed via reverting https://github.com/woocommerce/storefront/pull/1624 which applies a `word-break: break-all` style to all elements with the class `.button` and then to add the break-all style specifically to the download buttons as specified in the reverted issue.

**Test Steps:**
Install and activate all the required plugins.
Complete the onboarding setup wizard.
Choose the Storefront theme.
Add Some Products.
Go to Appearance->Customize.
Select WooCommerce->Product catalog option.
Set product per rows value to 6.
Observe that "Add to Cart" button text _now does not_ appear misaligned.

Before:

![Screen Shot 2021-09-25 at 2 39 43 PM](https://user-images.githubusercontent.com/1033613/134786635-223ec86e-a74b-4a24-98ca-98c6b1dd12b1.png)


After:

![Screen Shot 2021-09-25 at 2 39 58 PM](https://user-images.githubusercontent.com/1033613/134786639-7386c118-0d23-4773-8bef-a002dc60995b.png)

**Comment by 9ete** [comment]
@Aljullu ready for review.

https://github.com/woocommerce/storefront/pull/1797
