### ISSUE TITLE
Multiple 404 console errors since update to v3.9.0

### ISSUE THREAD

**Issue by doffine** [woocommerce/storefront#1799]
Hello Storefront team,

## Describe the bug
We just updated our three Storefront installations to v.3.9.0. After this we checked the shops as usual and found multiple 404 console errors:

Shop Frontend:
1) GET https://[URL]/wp-content/themes/storefront/assets/js/navigation.min.js?ver=3.9.0 [HTTP/2 404 Not Found 1150ms]
2) GET https://[URL]/wp-content/themes/storefront/assets/js/woocommerce/header-cart.min.js?ver=3.9.0 [HTTP/2 404 Not Found 1350ms]
3) GET https://[URL]/wp-content/themes/storefront/assets/js/footer.min.js?ver=3.9.0 [HTTP/2 404 Not Found 1281ms]
4) The 404 from footer.min.js comes a second time

WordPress Dashboard:
1) GET https://[URL]/wp-content/themes/storefront/assets/js/admin/plugin-install.min.js?ver=3.9.0 [HTTP/2 404 Not Found 1332ms]

Isolating the problem (mark completed items with an [x]):
- [ ] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
We didn't do this since the shops are in live mode. But since all of the errors are 404s we guess that this is not necessary anyway.
Instead we took a look into your current Storefront ZIP downloadable at https://downloads.wordpress.org/theme/storefront.3.9.0.zip
There we saw, that all the minified versions of these files that get 404s are missing in the ZIP.

- [X] I can reproduce this bug consistently using the steps below.
Just reload the shop's frontend or WordPress admin dashboard and watch the console.

### Browser Environment
- Platform: current Windows 10
- Browser(s): current Firefox and current Chrome

### WordPress Environment
WordPress 5.8.1
PHP 7.4

Beside this we don't use any WordPress caching plugin or server side caching, and of course, we did reset browser cache, too.

Greetings,
-doffine

**Comment by dathwa** [comment]
Yep. This is happening on all sites where we have storefront parent theme. We tested in staging on pure storefront theme and same issues.
WordPress 5.8.1
PHP 7.4
storefront 3.9.0

JQMIGRATE: Migrate is installed, version 3.3.2
www.example.com/:1304 GET https://www.example.com/wp-content/themes/storefront/assets/js/navigation.min.js?ver=3.9.0 net::ERR_ABORTED 404
www.example.com/:1309 GET https://www.example.com/wp-content/themes/storefront/assets/js/woocommerce/header-cart.min.js?ver=3.9.0 net::ERR_ABORTED 404
www.example.com/:1310 GET https://www.example.com/wp-content/themes/storefront/assets/js/footer.min.js?ver=3.9.0 net::ERR_ABORTED 404
www.example.com/:1311 GET https://www.example.com/wp-content/themes/storefront/assets/js/woocommerce/extensions/brands.min.js?ver=3.9.0 net::ERR_ABORTED 404

**Comment by willfaulds** [comment]
Yes I have traced the issue #1800

**Comment by willfaulds** [comment]
A temporary fix for those affected would be to download the minified js files from the Storefront 3.8.1 link given in #1800 and add them manually via FTP to the corresponding folder(s).

**Comment by tjcafferkey** [comment]
@doffine this was a known issue and has been resolved. Please update to Storefront 3.9.1 to fix this.

More information found here https://github.com/woocommerce/storefront/issues/1800#issuecomment-928196332
