### ISSUE TITLE
Storefront

### ISSUE THREAD

**Issue by MIRCEANETOIU** [woocommerce/storefront#1819]
## Describe the bug
Clearly describe the issue. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

Isolating the problem (mark completed items with an [x]):
- [ ] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront theme are active.
- [ ] I can reproduce this bug consistently using the steps below.

### Browser Environment
Please provide as much detail as possible about your testing environment.

- Platform: e.g. macOS, Windows, iOS
- Browser(s):

### WordPress Environment
Please provide relevant details of your WordPress setup and server environment.

<details>
```
Copy and paste the system status report from WooCommerce > System Status in WordPress admin.
```
</details>

**Comment by opr** [comment]
Hi there @MIRCEANETOIU it looks like you submitted only the template used for creating the issue without providing any more information for us to help you.

I'll close this issue for now, but if there's something specific you would like to report please feel free to leave a reply and reopen the issue.
