### ISSUE TITLE
Making storefont a "block theme" (so category pages can be edited with guttenberg)

### ISSUE THREAD

**Issue by gingerling** [woocommerce/storefront#1821]
## Is your feature request related to a problem? Please describe.

I have been looking at solutions for really great category pages, as these are how most customers arrive on my store, but I'm not happy with any of the methods right now. It looks like from wordpress 5.9 there will be lots of freedom to edit these pages if you have a block theme https://github.com/WordPress/gutenberg/issues/33094#issuecomment-939357267

## Describe the solution you'd like
I would like to be able to edit category pages with a full guttenberg experience, and I'd like to keep storefront theme. I'm hoping storefront will eventually become a full block theme https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/

## Describe alternatives you've considered

Redirects: Using something like storefront blocks by pootlepress but it just redirects the category url to a normal wordpress page which disrupts the structure of the site affecting nav and seo (actually you don't need the plugin to do this, just do it with a redirect plugin)

Custom: Building some kind of custom template for categories, but it's overkill for my situation

Canonical url: Having landing pages sepeartre to some key categories and using a canonical url on the real category, so google sends people to the landing page. I might do this as as a temporary measure.

## Additional context
My store is in prestashop but i'm rebuilding in wordpress now, while I rebuild I may as well get it how I like it! I could do with an understanding of if this work is planned, when it's due for release etc. I would hope to help a lot with testing process if I'm building my new store while the beta is being tested!

**Comment by Aljullu** [comment]
Thanks for opening this issue @gingerling, it's really nice to see how much interest block themes are gathering in the Woo community, we are excited too!

We are currently working on improving how WooCommerce behaves with block themes, and we have many more improvements planned for the near future, you can read more about this in this article: "[Peek into the WooCommerce Blocks Roadmap](https://developer.woocommerce.com/2021/08/31/peek-into-the-woocommerce-blocks-roadmap/)". We would like WooCommerce to work well in all block themes and this is where we are currently focusing all our current efforts. That means users will be able to use WooCommerce with any block theme.

At the same time, Storefront is a classic theme and there are no plans to convert it into a block theme. Take into account that WordPress will keep supporting classic themes for a long time, as will WooCommerce. So we don't have any immediate plans to retire Storefront. However, we expect in the years to come new themes will appear that will improve the shopper and store owner experience so much that many stores will embrace them.

I'm going to close this issue, given that currently it's not on our roadmap to convert Storefront into a block theme. You can follow all news related to WooCommerce and block themes/FSE from our development block in [developer.woocommerce.com](https://developer.woocommerce.com/blog/).

**Comment by gingerling** [comment]
yes, the reason I like storefront is this long term support - actually, I only ever use this kind of community developed theme, like the 2021 type themes for websites and storefront for stores.

I'm not clear from your answer if there will be a "new" classic theme for WooCommerce at some point, that is a block theme? Presumably there will be? I don't really want to use "a block theme", I'd like to use "THE block theme" for woocommerce :)

thanks for all the awesome work, loving woo so far!

**Comment by Aljullu** [comment]
Thanks for your kind words @gingerling!

> I'm not clear from your answer if there will be a "new" classic theme for WooCommerce at some point, that is a block theme? Presumably there will be? I don't really want to use "a block theme", I'd like to use "THE block theme" for woocommerce :)

Unfortunately we don't have an answer for that yet. It's not something we have in our short-term plans, but we are still evaluating if it would be valuable to create a WC-focused block theme. Our current focus is to make WooCommerce work great with all block themes out there, that includes the community theme for the next WP version ([Twenty Twenty Two](https://github.com/wordpress/twentytwentytwo)) and any other block theme available (ie: [Quadrat](https://wordpress.org/themes/quadrat/), [Blockbase](https://wordpress.org/themes/blockbase/) and [Seedlet](https://wordpress.org/themes/seedlet-blocks/)).
