### ISSUE TITLE
Editing a section template in an elementer does not work correctly with the StoreFront theme

### ISSUE THREAD

**Issue by DanielCyran** [woocommerce/storefront#1938]
Storefront has a problem with the templates in the elementer
when I enter:
Dashboard / Templates / Saved Templates
Then it adds a new one, I choose "section" adds a name
I'm going to edit in elementor and the problem is that this section cannot be edited ... you can only switch to footer or header editing
; /
surely adding a template as a "page" works correctly but it overloads the page ...

I tested on several other themes, e.g. hello elementor, astra and everything works fine, the problem only occurs with the StoreFront theme

**Comment by tomasztunik** [comment]
Hi Daniel. We do not provide here direct support for 3rd party plugins compatibility. 

Can you please go to https://wordpress.org/support/plugin/elementor/ and report your issue there? The plugin authors, community and/or support team will try to help. In the meantime quick search gave me [this result](https://wordpress.org/support/topic/elementor-doesnt-work-on-my-shop-page/ ) maybe it will help.
