### ISSUE TITLE
Prevent infinite loop on prev/next product navigation

### ISSUE THREAD

**Issue by chrono-meter** [woocommerce/storefront#2053]
## Is your feature request related to a problem? Please describe.
`Storefront_WooCommerce_Adjacent_Products::get_product()` has no execution time limit. So it may take huge execution time or enter infinite loop.
In my environment, it causes by [Simple Custom Post Order](https://wordpress.org/plugins/simple-custom-post-order/).

## Describe the solution you'd like
Memo a previous adjacent ID for prevent infinite loop.

**Comment by albarin** [comment]
Hi @chrono-meter!
Thanks for reporting this. Unfortunately, we haven't been able to reproduce the issue ourselves, could you provide more detailed steps to reproduce it so we can try to help?
Thanks a lot!

**Comment by danieldudzic** [comment]
Hi @chrono-meter!

I have responded in: https://github.com/woocommerce/storefront/pull/2054#issuecomment-1290327110
