### ISSUE TITLE
Changed files missing from last two commits.

### ISSUE THREAD

**Issue by user-1138** [woocommerce/storefront#2152]
## Describe the bug
Hi there, just a quick FYI - I noticed the last two commits (4.5.6 & 4.6.0) are missing changed files I would normally expect to see with version bumps (i.e. README.txt, package.json & style.scss). These files have indeed been version bumped, but they don't show up as changed files in the commit for some reason (you can see they are shown in the 4.5.5 commit).

4.5.5 - [https://github.com/woocommerce/storefront/commit/8eb94e9aa8e4bd1f1102c4072c081b62406ee247](https://github.com/woocommerce/storefront/commit/8eb94e9aa8e4bd1f1102c4072c081b62406ee247)
4.5.6 - [https://github.com/woocommerce/storefront/commit/f6cb90b262607c3937702d0e5b9e71b256c58dff](https://github.com/woocommerce/storefront/commit/f6cb90b262607c3937702d0e5b9e71b256c58dff)
4.6.0 - [https://github.com/woocommerce/storefront/commit/f13b5c2f138466420c62d34d7b0e8210c3aaa789](https://github.com/woocommerce/storefront/commit/f13b5c2f138466420c62d34d7b0e8210c3aaa789)

## Expected behavior
All changed files should be shown under each commit.

**Comment by Aljullu** [comment]
Hi there, @user-1138! Thanks for taking the time to open this issue. I'm not sure to understand what's wrong. There are these two commits (https://github.com/woocommerce/storefront/commit/753d09b3478447507227bbd621ba06ffcc98c45f and https://github.com/woocommerce/storefront/commit/8eb94e9aa8e4bd1f1102c4072c081b62406ee247) which bumped the version to 4.5.6 and 4.6.0 respectively. Is there something else that you think needs to be done?

**Comment by thealexandrelara** [comment]
Hey @user-1138! Thank you for opening this issue. I believe you’re referring to the changed files displayed on the left side, which shows all changed files, right? For example, it shows for the 4.5.5 commit:

![Image](https://github.com/woocommerce/storefront/assets/20469356/6938e524-d660-4fbc-bcb7-881e2b2c614c)

However, it does not show for the 4.5.6 (https://github.com/woocommerce/storefront/commit/f6cb90b262607c3937702d0e5b9e71b256c58dff) and 4.6.0 (https://github.com/woocommerce/storefront/commit/f13b5c2f138466420c62d34d7b0e8210c3aaa789) commits. If you look at the top of the commit, you’ll see that only one file was changed in both of these commits: 

![Image](https://github.com/woocommerce/storefront/assets/20469356/cb88b731-cf85-4ae4-acb9-8ee026a39a5e)

When that happens, GitHub will not display the left-side navigation menu, so unfortunately, we cannot do anything on our side.

I suggest you open a discussion on [GitHub Community Discussions](https://github.com/orgs/community/discussions) and post a suggestion there so they can consider implementing this feature for single-file commits.

I'm closing this issue, but feel free to reopen it if you want to add more information or if I misunderstood your expectations.
