### ISSUE TITLE
Prevent coupons from woocommerce subscriptions

### ISSUE THREAD

**Issue by mrsimhadrinag** [woocommerce/storefront#2155]
I have used Woocommerce Coupons(Advanced Coupons for WooCommerce Free) and WooCommerce Subscriptions (https://woocommerce.com/products/woocommerce-subscriptions/) plugins. I have successfully implemented subscriptions with products and each product has two types of options are available one is one time purchase and another one is subscription type purchase with discount. But coupons are applied on both options. I don't want to apply on subscriptions. Can any one help with this?

**Comment by roykho** [comment]
Hi @mrsimhadrinag - Thanks for reaching out however the best place to get product support is by going to [WooCommerce Support](https://woocommerce.com/my-account/contact-support/) - There will be folks that are equipped to handle product support questions.

With that, I will be closing this issue.
