### ISSUE TITLE
Measurement price calculator duplicate fields....

### ISSUE THREAD

**Issue by manojsiddoji** [woocommerce/storefront#2174]
#2128 
### Is your feature request related to a problem? Please describe.
Can we override the theme template to modify things with the help of child theme !!

### Describe the solution you'd like
Can we override the theme template to modify things with the help of child theme !!

**Comment by dinhtungdu** [comment]
Hi @manojsiddoji,

Can you please clarify your issue? From the description, it's not clear to me what is the issue you're experiencing. If you're reporting an issue, please also include reproducible testing instructions.

About the linked issue, I can see it's an issue related to the `Measurement Price Calculator for WooCommerce` plugin, a paid extension. So you should contact the extension developer for support.

About templates, you can override the WooCommerce PHP templates from the theme as detailed here: https://woocommerce.com/document/template-structure/.

**Comment by manojsiddoji** [comment]
Hi @dinhtungdu ,

Thanks for your response! I appreciate your guidance,
Regarding the Measurement Price Calculator issue, I understand it's a paid extension, and I will reach out to the developer for support.

Thanks for the link about overriding WooCommerce templates! I’ll check it out.

**Comment by dinhtungdu** [comment]
I'm closing this issue but feel free to continue the conversation, I'm happy to reopen it if necessary.
