### ISSUE TITLE
Header text colours automatically adjust when background image is selected

### ISSUE THREAD

**Issue by seb86** [woocommerce/storefront#366]
![storefront header image text colour issue](https://cloud.githubusercontent.com/assets/497406/14300613/d0a5f3da-fb91-11e5-9a2e-e8c82eb134c8.png)

Also, the menu navigation text colour needs adjusting.

**Comment by jameskoster** [comment]
Hm, I think this would need to be optional. IE after you've uploaded the image a prompt appears asking if you'd like to dynamically generate the colors based on it. Sounds like a fun feature that we can consider for 2.1.

**Comment by BurlesonBrad** [comment]
plugin territory?

**Comment by jameskoster** [comment]
@BurlesonBrad a feature plugin would be a good starting point, sure.

**Comment by tiagonoronha** [comment]
The controls to change the text color are under the control where you add the image, and colors are easily adjustable.

I don't see this as being necessary.
