### ISSUE TITLE
Add Style Linting

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#449]
See https://github.com/woothemes/woocommerce/pull/11648

**Comment by BurlesonBrad** [comment]
**I got this one**  _(........I think)_ :stuck_out_tongue_winking_eye:

**Comment by jameskoster** [comment]
@BurlesonBrad go for it xD

**Comment by BurlesonBrad** [comment]
after reading over it line by line, learning a bit **(A TON!)** , and understanding what each line does, 

.......basically each line is ~indeed~ good to go _**as-is,**_ right?

**Comment by jameskoster** [comment]
@BurlesonBrad yep we should definitely use the same rules as WooCommerce.
