### ISSUE TITLE
Look in to whether we should make use of the Customizer notifications API for our settings

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#454]
https://make.wordpress.org/core/2016/07/05/customizer-apis-in-4-6-for-setting-validation-and-notifications/

**Comment by opportus** [comment]
If it's aiming user experience optimization, then why not?
If you plan to implement it, I think I'd have time to work slowly on it. It's interesting for me :)

**Comment by jameskoster** [comment]
> If it's aiming user experience optimization, then why not?

@opportus Simply because off the top of my head I'm not sure any of our options would need to provide feedback. They're mostly just color pickers. I haven't played with 4.6 properly yet but I assume the core color picker control will already have feedback on invalid entries.

**Comment by jameskoster** [comment]
Closing this one, nothing in core requires validation.
