### ISSUE TITLE
Support for Jetpack Infinite scroll on shop page

### ISSUE THREAD

**Issue by boboz** [woocommerce/storefront#465]
Standard support for Infinite scroll is built in, but since this is a WooCommerce theme support for the shop page should be added.

By default the shop page loads products in a 3-column design. While reaching the bottom of the page, infinite scroll loads more products but does it in a single-column design with large images and product description texts. Also the products loaded by infinite scroll repeats products already displayed

**Comment by jameskoster** [comment]
Worked on this in https://github.com/woocommerce/storefront/commit/87d4d3a9c388032993be0aeea1401c169b00f254
