### ISSUE TITLE
Add hook for featured image display on single posts

### ISSUE THREAD

**Issue by gurdeepsembi** [woocommerce/storefront#482]
For standard blog posts, would it be possible to add a hook/action so that we can use a child theme to stop the output the featured image above the post content?

This could be done by adding an action in the **storefront_post_content** function in **wp-content/themes/storefront/inc/storefront-template-functions.php** on line 323.

This would help with reducing the load time on the posts for those who do not want to load the featured image.

**Comment by opportus** [comment]
Hi @gurdeepsembi 

Meanwhile you can overwrite `storefront_post_content()` in your child theme.

**Comment by gurdeepsembi** [comment]
Hi @opportus,

Thanks for the quick reply, I have actually used that exact same method . 👍 

The reason why I think a hook is better is because most of the time we don't want to touch anything else in that function as this causes headaches on upgrades if the core storefront theme changes that function. Hehe, hope our 2p's don't cancel each other out!

**Comment by jameskoster** [comment]
I've thought about this in the past but couldn't really think of a good reason for someone to remove the function. 

If you don't want to display featured images then just don't add them to your posts? Thinking about it from the users perspective; I think it would be poor UX for them to be able to add featured images to posts but not have them display.

**Comment by gurdeepsembi** [comment]
Take this example: For blog posts, the featured image is used to display the posts on the archive page in a masonry format. On the single post page, we want to display the featured image, just not at the top of the  post before the content. 

I agree it would be poor UX to not show the featured image in the single-post, but there should be flexibility for where it appears and we can do this using the hooks.

**Comment by jameskoster** [comment]
OK, that is a good point :)

I'm not opposed to adding actions before/after `the_content()`. Did you wanna send a PR? :)

Any specific reason you're against adding more actions @opportus ?

**Comment by opportus** [comment]
> Any specific reason you're against adding more actions @opportus ?

Nop, @gurdeepsembi point is definitely more important than mine. 👍

**Comment by opportus** [comment]
Hi @gurdeepsembi 

> On the single post page, we want to display the featured image, just not at the top of the post before the content.

Excuse me, but it's not very clear to me... Where do you display the featured image then? After the content? I'm not really a frontend developer, but I think I wouldn't take a risk by saying that this doesn't have sense?

**Comment by opportus** [comment]
Hi @gurdeepsembi 

> On the single post page, we want to display the featured image, just not at the top of the post before the content.

Excuse me, but it's not very clear to me... Where do you display the featured image then?

I believe what you wanted to point with your example is the need to add a featured image to display it into archives, which would require then an option for simply **disabling** it on single post, right?

Here's a solution you might be interested in...

```php
function storefront_post_thumbnail( $size ) {
    if ( has_post_thumbnail() ) {
      the_post_thumbnail( $size );
    }
}
```

As you can see, its role is extremely basic and simple, that's just a wrapper, which lead to assume easily that it'll never get updated, so you can directly override it in your child theme by making something like this:

```php
function storefront_post_thumbnail( $size ) {
    if ( has_post_thumbnail() && is_archive() ) {
      the_post_thumbnail( $size );
    }
}
```

@jameskoster 

> Any specific reason you're against adding more actions @opportus ?

Apart that I'm just a "Keep It Simple Stupid" fervent follower, nop.

**Comment by opportus** [comment]
Hi @gurdeepsembi 

> On the single post page, we want to display the featured image, just not at the top of the post before the content.

Excuse me, but it's not very clear to me... Where do you display the featured image then?

I assume what you wanted to point with your example is the need to add a featured image to display it into archives, which would require then an option for simply **disabling** it on single post, right?

Looks like there is an existing WP native filter hook that you could use to achieve what you need:
https://developer.wordpress.org/reference/hooks/post_thumbnail_html/

Though it's not an optimal solution for your own code since it will still fire `get_the_post_thumbnail()`, we at least don't bloat the original code with accessory stuff.

@jameskoster 

> Any specific reason you're against adding more actions @opportus ?

Apart that I'm just a "Keep It Simple Stupid" fervent follower, nop.

**Comment by gurdeepsembi** [comment]
Hi @opportus,

Thanks for those pointers, I will check that out.

> Excuse me, but it's not very clear to me... Where do you display the featured image then?

It would be good to have the option to display it before/after the content using the hooks. A lot of the time, our clients want to insert the featured image somewhere in the post content, and they do this using the native WP image embed. In this case, we would use the hook to not add the featured image automatically at all.

Sometimes we are working on an existing site that we are moving to the storefront theme and there are a lot of existing posts in the database already and it is not feasible to go through hundreds of posts to remove the featured image from within the post content.

If it is not possible to add the hooks then we can use the workarounds, but I think it would be really useful for developers using storefront as their base theme for all projects. We also use the Genesis framework and we used the ability to remove the hooks for the featured image. We want to use Storefront as our base theme as it gives us a solid foundation for when clients want to start selling online with the native WC integration, but we also need it to be able to easily customisable for non-ecommerce sites.

Hope that explains where I am coming from with this?

**Comment by opportus** [comment]
@gurdeepsembi, thank you for your beneficial experience feedback !

To @jameskoster to deal with that now :P

Just one thing... I can't wrap my head around the point of putting a **featured** image after the content :D Could you enlight me please?

**Comment by jameskoster** [comment]
I have no objection to adding this :)
