### ISSUE TITLE
Update Font Awesome v4.6.3

### ISSUE THREAD

**Issue by poyu1221** [woocommerce/storefront#483]
Due to Updated Instagram logo on Font Awesome v4.6.3.
Would you Update  Font Awesome to v4.6.3?
Thank you!

**Comment by jameskoster** [comment]
Done!

**Comment by RicardoRDS** [comment]
@jameskoster my first post here. I would like to add Font Awesome v4.7.0 due to "fa-user-o" icon as it makes website look cleaner. Could you add it please?
Thanks!

**Comment by jameskoster** [comment]
FontAwesome is updated to 4.7 in Storefront 2.2 (coming soon).
