### ISSUE TITLE
Widgets defaulting to "below header" sidebar on new installs

### ISSUE THREAD

**Issue by pmgarman** [woocommerce/storefront#484]
Nothing is "broken" but this is a poor experience for new users.

Steps to reproduce: Setup clean install of WordPress, install and activate Storefront. View the site and all the default widgets are in the below header sidebar giving the impression to a new user that the sidebar is broken. Below the widgets content does show up with a blank sidebar as if the sidebar should have been there and not above the content.

**Comment by jameskoster** [comment]
It's rudimentary but the only 'fix' I can find for this is to change the order the widget regions are registered in. Currently the 'below header' region is registered first so that's the one wp sticks the default widgets in o_O

**Comment by pmgarman** [comment]
@jameskoster I look forward to this epic fix!
