### ISSUE TITLE
Stars missing in product review form if prettyphoto disabled

### ISSUE THREAD

**Issue by FrancescoCarlucci** [woocommerce/storefront#496]
Hi,

just noticed that Storefront does not add WooCommerce font itself. So if pretty photo is not enabled in WooCommerce settings, "stars" are missing in product review form.

Steps to reproduce:

- disable pretty photo in WC > settings > product > display
- visit a single product page

Possible solution:

- add WooCommerce font-face in /storefront/assets/sass/woocommerce/woocommerce.css

![schermata 2016-10-08 alle 12 08 06](https://cloud.githubusercontent.com/assets/6959990/19212382/34301a52-8d50-11e6-8356-ee7270fd3614.png)

![schermata 2016-10-08 alle 12 09 11](https://cloud.githubusercontent.com/assets/6959990/19212384/3c472906-8d50-11e6-9ad6-5bce5b9dd1a4.png)

**Comment by jameskoster** [comment]
Fixed for 2.1.4 already :) 

https://github.com/woocommerce/storefront/commit/885e13a2a5c8f345f1fbfffe585d9675c8f27328

**Comment by FrancescoCarlucci** [comment]
Very cool :)
