### ISSUE TITLE
Gateway Timeout 504 error on /wp-admin/edit.php?post_type=page

### ISSUE THREAD

**Issue by BusinessBloomer** [woocommerce/storefront#503]
I'm getting a weird error which Siteground thinks is because of Storefront. I can access all admin pages in WordPress but the "Pages" section (/wp-admin/edit.php?post_type=page), which gives me a 504 error.

Here's what SG said:

> After my investigation I have found that the problem is related to your current Wordpress theme as if I disable it the page /wp-admin/edit.php?post_type=page loads fine. 
> 
> I have made a strace of all signals that system does when that URL is accessed with theme enabled, it can be viewed here : 
> 
> https://businessbloomer.com/strace.txt
> 
> You can give this information to your theme developers in order to investigate why that happens. 
> 
> As a temporary fix I have created .htaccess file within public_html/wp-admin/ folder in your account and put the following code there : 
> 
> Code:
> <IfModule mod_dtimeout.c>
> <Files ~ ".php">
> SetEnvIf Request_URI "edit.php" DynamicTimeout=300
> </Files>
> </IfModule>
> 
> This will increase timeout limit for edit.php script to 300 seconds when default limit is 120 seconds. 504 error comes after 120 seconds passed and script did not give any results.

Any ideas?

**Comment by jameskoster** [comment]
Hey,

I've not seen this issue before. I have access to a site hosted on SiteGround which runs Storefront and can access the pages menu just fine there.

In the strace I saw; `/wp-content/themes/storefront-bbloomer`

Looks like you're running a Storefront child theme. I'd recommend speaking to the author of that child theme about this.

But first, try activating the Storefront parent theme (not the child theme) and see if you can access the pages management screen.

Cheers

**Comment by jameskoster** [comment]
Closing this, please re-open if you're able to share any additional information.
