### ISSUE TITLE
Child theming

### ISSUE THREAD

**Issue by Ne-Ne** [woocommerce/storefront#507]
Hi All,

I have successfully created a child theme, using Storefront.

However I have noticed that there are default styles applied to `<img>` which is interfering with my current css code. I decided I use a child theme so I will not loose my code during Storefront version updates, however I now I am required to create overrides. Which seems like unneeded overhead.

Below is the css example of the default styles for an img:

<img width="539" alt="screenshot 2016-11-14 22 49 40" src="https://cloud.githubusercontent.com/assets/2177851/20286081/f9a88eca-aabc-11e6-902c-ad0c2d6e78ac.png">

I understand if this image sat behind a specific class, however it does add extra time for child theme developers. At the moment I have similar issues with font weights / sizes / line-height etc.. In an ideal world I would like like separation between my .css file and Storefront's.

Do you have any advice getting around this?

Many thanks

**Comment by jameskoster** [comment]
Hey, github isn't really the place for a question like this, you'd be better off posting on the [support forums](https://wordpress.org/support/theme/storefront). Please keep github issues to bug reports.

> However I have noticed that there are default styles applied to <img> which is interfering with my current css code.

Interfering how?

> I decided I use a child theme so I will not loose my code during Storefront version updates, however I now I am required to create overrides.

That's exactly the purpose of a child theme. They allow you to override the parent themes styling / templates and customise it further using hooks / actions / filters etc.

It sounds to me as though you want to start with an entirely blank canvas. If that's the case then Storefront (and indeed a child theme) probably isn't for you. Better to create your own parent theme :)
