### ISSUE TITLE
Add support for AMP

### ISSUE THREAD

**Issue by mattyza** [woocommerce/storefront#513]
https://ampproject.org/
https://ampbyexample.com/#samples_templates

It'd be great to have support for AMP in Storefront, to help stores serve mobile-friendly screens even quicker. Services such as Facebook also offer support for rendering AMP screens, resulting in faster load of the relevant screen, from within Google, Facebook, etc.

It feels like this would belong in Storefront, rather than in WooCommerce, as it is primarily visual in nature.

Thoughts?

@jameskoster @kellychoffman @mjepson

**Comment by tiagonoronha** [comment]
> It feels like this would belong in Storefront, rather than in WooCommerce, as it is primarily visual in nature.

Shouldn't we rather put in core and then let theme developers style the AMP layout to match the overall look and feel of their themes?

Otherwise, if all WooCommerce themes start adding AMP support, we will end up with thousands of different implementations of the same technology.

**Comment by mattyza** [comment]
Great idea, @tiagonoronha!

**Comment by jameskoster** [comment]
Agreed, core feels more appropriate overall.

**Comment by panthar1** [comment]
Any update on this? How can I get AMP working with storefront/child theme?
