### ISSUE TITLE
Notice generated about missing variable when Quick View is active. 

### ISSUE THREAD

**Issue by lucasstark** [woocommerce/storefront#514]
When the WooCommerce Quick View extension is active a waring is generated about a missing variable, darken_factor. 

Notice:  Undefined variable darken_factor in /wp-content/themes/storefront/inc/woocommerce/class-storefront-woocommerce.php on line 340

**Comment by jameskoster** [comment]
thanks for the report!

**Comment by luminuu** [comment]
I have a question regarding this issue: I noticed this warning appearing on a local installation of mine. Here in Github, the changes are done, but on the latest version 2.1.8 you can download via wordpress.org or woocommerce.com, the lines causing the warning are still in the _class-storefront-woocommerce.php_ file. Can you have a look on this?

**Comment by jameskoster** [comment]
Looks like we didn't merge the fix in to the 2.1 dev branch. The fix will be included in 2.2 which will be going to beta soon.
