### ISSUE TITLE
CSS Grid does not work with changing the the number of products on the shop page.

### ISSUE THREAD

**Issue by Goosse** [woocommerce/storefront#515]
_I'm not sure if this should be filed under the plugin or the theme_

I changed the number of columns in the grid by adding the following to my child theme:
```
function loop_columns() {
return 4; // 4 products per row
}
add_filter('loop_shop_columns', 'loop_columns', 999);
```

This updates the first and last classes correctly, but does not include a `columns-4` class as `storefront/assets/sass/woocommerce.scss` @ lines 2234-2299 suggests should be happening

**Comment by Goosse** [comment]
I just figured out a solution:

```
add_action('woocommerce_before_main_content', function(){ if (is_shop())echo '<div class="columns-4">';}, 20);
add_action('woocommerce_after_main_content', function(){ if (is_shop())echo '</div>';}, 20);
```

This seems like something that should be included in the storefront theme, since it is already handling the grid css.

**Comment by jameskoster** [comment]
Yeah I think we should add this. Then we can take the CSS out of Powerpack (cc @tiagonoronha)

You'll want to tweak your snippet though. Use the product loop actions and lose the `is_shop()` query. With your snippet the column setting will be ignored in related product / upsell /shortcode loops.

Might also consider using the `storefront_loop_columns` filter.

**Comment by michakrapp** [comment]
Just a note, escpacially for @jameskoster 
This interferes with the Plugin [WooCommerce Product Archive Customiser](https://github.com/jameskoster/woocommerce-product-archive-customiser)

**Comment by jameskoster** [comment]
@michakrapp would you mind opening a separate issue?
