### ISSUE TITLE
YouTube embed is sized incorrectly when sidebar is active

### ISSUE THREAD

**Issue by joelwills** [woocommerce/storefront#522]
A YouTube embed on a page without a sidebar looks great, like this:

![Screenshot](http://joelwills.com/wnjr+)

Link to image: http://joelwills.com/wnjr

However, with a sidebar, on a page, looks like this:

![Screenshot](http://joelwills.com/V7Gu+)

Link to image: http://joelwills.com/V7Gu

Slightly cropped left and right and height is not adjusted to correct aspect.

On a post it's even worse due to the author meta data on the other side:

![Screenshot](http://joelwills.com/lAYy+)

Link to image: http://joelwills.com/lAYy

On mobile it's not pretty:

![Screenshot](http://joelwills.com/1dTsw+)

Link to image: http://joelwills.com/1dTsw

- This affects child themes too, to varying degrees.
- The video plays the correct width but with header and footer borders. 
- Left or right sidebar doesn't matter

**To replicate**

In Storefront, or child theme, make sure there is a sidebar widget, then add

`https://youtu.be/FJe5MkoUVIA`

To a post or page and preview. Thumbnail of the video is cropped.

**To fix**

I'm honestly not sure how to fix it as the settings seem to be coming from YouTube, but I'm not sure why it is embedding incorrectly.

Please let me know if I can help further in any way, thanks!

Related: 504267-zd-woothemes

**Comment by jameskoster** [comment]
Yeah this seems to be a YouTube 'thing'. There's nothing in the theme causing the iframe to display at that size and I notice the same thing happens with a variety of themes.

If it's upsetting a user I'd recommend giving [this plugin](https://wordpress.org/plugins/fitvids-for-wordpress/) a try.

**Comment by joelwills** [comment]
Thanks very much @jameskoster !
