### ISSUE TITLE
Allow Dequeuing of Font-awesome

### ISSUE THREAD

**Issue by woodenfox** [woocommerce/storefront#524]
Currently there is no way for font-awesome to be dequeued. It's currently handled via "@import 'assets/sass/vendors/font-awesome/font-awesome';" in the style.scss

For those who want to disable font-awesome or enqueue their own CDN, it would be greatly appreciated if this were handled via the wp_enqueue.

https://github.com/woocommerce/storefront/commit/408a70dfd5ea204aac82a27756d2045d0cf98052#diff-f75cdbcea8034badbb1b7f8097fcb138

**Comment by jameskoster** [comment]
Do you think the performance enhancements are worth it?

The issue that we'd also have to include the .css file (we only include .scss currently).

**Comment by woodenfox** [comment]
In this case, I do believe it's worth it. I can also think of a handful of
reasons people would want to disable, self-manage, or CDN the latest
version of font-awesome.

**Comment by jameskoster** [comment]
OK we'll look at this in 2.2.

The only drawback is that you'll be able to dequeue FontAwesome, but there will still be CSS in core referencing the glyphs which could look funky on the frontend.

So let's move all FontAwesome related CSS to a separate stylesheet and enqueue that with the core FontAwesome stylesheet as a dependency.
