### ISSUE TITLE
Wizard: Starter Content

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#525]
Add starter content with logic to include content specified by the user;

* Widgets
* Menus
* Products
* Homepage

**Comment by gorgoglionemeister** [comment]
Hi! What about implementing the new starter content WordPress 4.7 theme feature?

[Starter content for themes in 4.7](https://make.wordpress.org/core/2016/11/30/starter-content-for-themes-in-4-7/)

**Comment by jameskoster** [comment]
@gorgoglionemeister that's the plan! Should have made that clear in the issue description xD

That is just a part of our plans for the overall setup experience in Storefront however. We're likely going to add a guided tour to the Customizer as well.
