### ISSUE TITLE
Bookings default Styles are confusing

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/storefront#527]
A user pointed out that in Storefront, available dates in Bookings are shown "Black":
![screen shot 2016-12-21 at 8 13 08 am](https://cloud.githubusercontent.com/assets/3220162/21396498/5e605e1a-c755-11e6-8124-664dce831605.png)

I had never thought of that before, but it makes sense that the colour black doesn't really look bookable, but instead unavailable.  

I think we should do a more obvious approach to bookable slots:
![screen shot 2016-12-21 at 8 14 58 am](https://cloud.githubusercontent.com/assets/3220162/21396607/a36c92d0-c755-11e6-9703-f93273c87794.png)

@jameskoster if this makes sense to you I'd be happy to do up a PR with the changes.

**Comment by tiagonoronha** [comment]
Thanks for reporting this @mikeyarce :) 

Good catch, PR?

**Comment by bfintal** [comment]
I just built the master and I'm still seeing this:
<img width="423" alt="screen shot 2017-02-24 at 2 42 56 am" src="https://cloud.githubusercontent.com/assets/1033611/23273727/1af32d7e-fa3b-11e6-806d-657677dbbf64.png">
