### ISSUE TITLE
type:enhancement Should Featured Images in Archive be Clickable by Default?

### ISSUE THREAD

**Issue by BurlesonBrad** [woocommerce/storefront#528]
Someone popped me a friggin' ~stupid~ fb chat message & asked me why the featured images on their category pages weren't clickable.  I told 'em, "Well, by default, that's exactly what they are supposed to do."

I'm all for leaving Storefront alone for the most part, but this one got me thinking a bit.  Under the umbrella of UX, heatmaps, psychology, and _"$what-should-be-default"_ **vs.** _"$what-should-be-edited-by-users"_ this one's got me leaning more towards the _should-be-default_ side.

But, before I get yelled at _(even more)_ for:

1. being on "vacation" 
2. having the laptop open too long 
3. opening SF up
4. editing it 
5. and even submitting a patch

Does anyone else see this as a 'commit to core' type of enhancement?

_oh, I see how it is: Facebook opened is 👍, but the second I open atom, she gives me **"the look"**_ 👀

**Comment by jameskoster** [comment]
I'm not a fan of this personally. Purely because if I see a pointer when hovering an image in a blog post, I expect clicking it will open a larger version of the image. So to have some images behave that way, and other act as permalinks is an awkward inconsistency for me.

Fortunately this is an easy customisation if you want to add this behaviour to a site. Just plug `storefront_post_thumbnail()`.

**Comment by BurlesonBrad** [comment]
I'm not usually considered _vague_, but I'm always open to the reality that this might have the potential to be clarified a bit more: https://youtu.be/qtPIIOAF1_Y

**Comment by jameskoster** [comment]
I hear you @BurlesonBrad, but there's a difference that's important to highlight here; each of the sites you used as examples (and the vast majority that do this) use a different design treatment or placement of the featured image. This distinguishes it from regular images in the post and hints at the behaviour you expect.

I'm not opposed to changing this, but we should do something with the image as well, even if it's just moving it out of the main content section.

If you wanna open a new issue for that we'll review it :)
