### ISSUE TITLE
WC2.7: Terms and conditions checkbox not changing visually

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/storefront#531]
I updated to WooCommerce 2.7 (master) with no other plugins enabled. I created a Terms and conditions page which enables the Terms and conditions checkbox in the checkout.

However the checkbox status does not visually change when clicked on. If I click it once (check it) I can still proceed with checkout but the checkbox still looks unchecked.

![Checkbox](https://cloudup.com/cAp5XRO9sfp+)
Image link: https://cloudup.com/cAp5XRO9sfp

I also noticed the checkbox on the section "Ship to a different address?" moves to the left side of the text when updating. The checkbox here does work correctly.

**Comment by BurlesonBrad** [comment]
![toc](https://cloud.githubusercontent.com/assets/6208757/21934445/0a97a1f4-d96f-11e6-896a-d49e149bc26f.gif)
_(perhaps I'm not seeing them....)_ but I don't see any console errors either 😕

**Comment by jameskoster** [comment]
Good catch, this is due to the markup changes we made to all checkboxes in 2.7. We'll release a patch for this soon.

**Comment by BurlesonBrad** [comment]
https://github.com/woocommerce/woocommerce/commit/5b01bb693e6328dce2eafc9ac6e81172c98b29cc 👀 @mikkamp 


Thanks @jameskoster 👍

**Comment by jameskoster** [comment]
This will be fixed in 2.1.7.

**Comment by ben72** [comment]
This removes the fontawesome style. I thought that was pretty neat..
