### ISSUE TITLE
Auto-fill glitches on checkout

### ISSUE THREAD

**Issue by axcho** [woocommerce/storefront#543]
I have [an online store](http://superbodyfuel.com/) with the Storefront theme, and customers often experience glitches with auto-filled addresses and other info during the checkout process.

Here's a recent report from a customer on mobile, on an LG G4 with Chrome browser:

> As far as the auto fill, I have my address and card saved through chrome, so when I started to type and it gave me the pre filled option, I selected it. But, several times when I went to tap it, the screen would suddenly go down to the bottom of the page for some reason, and not fill.
> 
> With the card portion, it was slightly worse: having failed at prefilling the card number, I typed it manually. Then, when I went to the date and tried to prefill that portion, it did the same bottom of the page thing, but also deleted the card number above as well.

It does not seem to happen on other WooCommerce stores without the Storefront theme, so I thought I'd report it here. My apologies if this is not a Storefront issue.

Thanks.

**Comment by jameskoster** [comment]
That's strange, it's working just fine for me on your site and my development install. 

The only thing I can think that might cause this is the sticky order review feature. There is a fix for an edge case (small browser windows) that is yet to be deployed in Storefront core.

You might try dequeuing `storefront-sticky-payment` to check.

**Comment by axcho** [comment]
> You might try dequeuing storefront-sticky-payment to check.

Thanks! Just tried that, and it seems to fix the issue (according to the customer who last reported it).

**Comment by jameskoster** [comment]
Thanks for letting me know. That issue should be fixed when 2.2 drops so I'll close this out for now.
