### ISSUE TITLE
Reviews Date displaying as a block lvl element

### ISSUE THREAD

**Issue by Droidism** [woocommerce/storefront#545]
With the WooCommerce sample text imported, navigate to Ninja Silhouette (T-shirt) and view Cobus his review. Here the date and the colon ( : ) are displayed as block lvl elements and dropped below the the name. 

![screen shot 2017-02-15 at 17 25 13](https://cloud.githubusercontent.com/assets/10343479/22983917/fc0534a4-f3a3-11e6-99f3-245a9977a3c7.png)

Changing the value on line 663 in `woocommerce.sccs` to `display: inline;` fixes this issue.

**Comment by jameskoster** [comment]
This is based on the review template changes coming in WC 2.7. Storefront 2.2 won't be released until then so this will be a non-issue.
