### ISSUE TITLE
Bug in add-widgets.js of Mega Menus extension

### ISSUE THREAD

**Issue by bitadvisor** [woocommerce/storefront#558]
Hi there,

There's a bug on line 39 in add-widgets.js of Mega Menus extension - it assumes that wp.customize.Widgets is always set while it can be undefined.

Developers are allowed to filter out specific components via customize_loaded_components filter hook. If widgets component is removed, wp.customize.Widgets is not set in JS. Same is true for nav_menus.

Omitting customizer components is a documented functionality in WordPress core so everyone should play by these rules.

Thanks!

**Comment by tiagonoronha** [comment]
Thanks for reporting! I'll open an issue in the correct (private) repo. :)
