### ISSUE TITLE
Onboarding Guide + WooCommerce 3.0.0 = AUTO-DRAFT product names.

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/storefront#560]
As it says I had one issue using the new onboarding guide and WooCommerce 3.0.0, and I tried it twice.

After the first try I'd reset my test site and activated WooCommerce and Storefront again (in that order). Adding the sample products works fine only that the product names all say AUTO-DRAFT.

<img width="949" alt="screen shot on 2017-03-16 at 23_24_36" src="https://cloud.githubusercontent.com/assets/867748/24075279/8090d856-0bee-11e7-8964-1d5a06243106.png">

This problem is solved by using the current release of WooCommerce 2.6.14

**Comment by BurlesonBrad** [comment]
I've sold millions of dollars worth of auto-draft in my day.  I say leave it.

**Comment by claudiosanches** [comment]
@jameskoster @tiagonoronha before changing the status from `auto-draft` to `publish` or anything else, need to apply a new title.

**Comment by tiagonoronha** [comment]
@claudiosanches can you explain why this is happening with 3.0.0? We don't set the posts to `publish` manually, it's all done by WordPress core.

**Comment by claudiosanches** [comment]
@tiagonoronha we are using it now to ensure that all variations have the name properly changed after saved the product.

**Comment by tiagonoronha** [comment]
@claudiosanches it breaks this core functionality: https://make.wordpress.org/core/2016/11/30/starter-content-for-themes-in-4-7/

**Comment by claudiosanches** [comment]
So maybe we can fix on WooCommerce to be still able to change variations.
