### ISSUE TITLE
Duplicate products with Jetpack infinite scroll

### ISSUE THREAD

**Issue by boboz** [woocommerce/storefront#563]
Default WordPress (4.7.3) install with with Jetpack (4.7.1), WooCommerce (2.6.14), Storefront (2.1.8) and WooCommerce dummy data.

Clicking "Older Products" -button, loads the already displayed first 12 products again.

[Test site](http://tiny.cc/infinitescroll )

**Comment by JulianHi** [comment]
@jameskoster there seems to be some Problems with this bugfix.

1.: With this Bugfix Jetpack Infinity Scroll miscalculates the total amount of entries (is_last_batch) this causes JP to not set the body class .infinity-end.neverending which can be used to reenable the footer. It might be possible to override this by adding a custom filter for infinite_scroll_is_last_batch.

2: During the infinity scroll JP modifies the URL. The current Page is added (eg.: /page/4/ for page 4).

When someone now Bookmarks this page or reloads the page the problem occurs again in a strange way.

Do you have any idea how to fix?

**Comment by jameskoster** [comment]
Might be worth bringing this up in https://github.com/woocommerce/storefront/pull/702 where @tiagonoronha is working on the infinite scroll integration.
