### ISSUE TITLE
Sticky 'place order' button on checkout needs updating

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#570]
The calculation we make before making the order review sticky needs updating to account for https://github.com/woocommerce/woocommerce/pull/12861

At this point it might be worth considering whether we make the entire order review sticky or _just_ the place order button.

cc @tiagonoronha

**Comment by RiaanKnoetze** [comment]
Looks like the recent changes in WooCommerce (specifically the markup around terms & conditions) is affecting the sticky order overview behaviour on Storefront's checkout page.

See the following screenshots for context:

![http://cld.wthms.co/pKqMEH+](http://cld.wthms.co/pKqMEH++)
Full Image: http://cld.wthms.co/pKqMEH++

and 

![http://cld.wthms.co/jPhm8H](http://cld.wthms.co/jPhm8H+)
Full Image: http://cld.wthms.co/jPhm8H+

Notice how the "Payment Button" is hidden.

On the last screenshot, my browser size was set to 1500 x 890

**Comment by jameskoster** [comment]
I think we agreed to remove this feature @tiagonoronha ?

**Comment by tiagonoronha** [comment]
It's been removed in master, but it's still pending a new release.

**Comment by jameskoster** [comment]
That explains why I couldn't find it. Derp.
