### ISSUE TITLE
Gallery thumbnail alignment issues

### ISSUE THREAD

**Issue by philbearman** [woocommerce/storefront#571]
In Woocommerce version 3.0.5, the gallery thumbnails aren't aligning properly in some circumstances. I believe this may be because one of my images is taller than the others, and therefore occupies two rows.

I notice in the CSS that every 4th child of the list (li:nth-child(4n)) overrides margin-right, setting it to zero, but the tall image means that every fourth image isn't necessarily positioned at the end of a row.

See a screenshot here - I've labelled the 4th, 8th and 12th items - these are the ones receiving the zero margin-right which is causing the layout to look wrong: http://imgur.com/a/bMhV8

I managed to fix it by adding the following CSS override as suggested by Mike at Woocommerce:

`.single-product div.product .woocommerce-product-gallery.woocommerce-product-gallery--columns-4 .flex-control-thumbs li:nth-child(4n+1)
{
	clear: left;
}`

@jameskoster - as the site isn't live yet I can't provide a link to it on here, but if there's a way I can send a link to you privately so you can take a look, I'm happy to do that?

**Comment by jameskoster** [comment]
Ah, the gallery thumbnails, that makes sense. I was thinking this was the catalog thumbnails. No worries, I should be able to replicate / fix now.

**Comment by philbearman** [comment]
Great!
