### ISSUE TITLE
Small gallery itens

### ISSUE THREAD

**Issue by Alexandre-Mainardi** [woocommerce/storefront#572]
Hi everyone, 

I've been using the StoreFront with Galeria Child for a while. Since last update, my photos at product page are displayed with 180px. Anyone has facing this problem? 

Here is te link with reported error -> http://bagtton.com/produto/saquinho-calcinha/

Any help is welcome
![screen shot 2017-05-09 at 11 51 43 pm](https://cloud.githubusercontent.com/assets/14119130/25881315/8e32ccf6-3512-11e7-8b10-840f8ad9ee1e.png)

**Comment by jameskoster** [comment]
Looks like a thumbnail size issue to me. Double check your settings and regenerate thumbnails if necessary :)
