### ISSUE TITLE
where to edit for changing homepage popular products section style

### ISSUE THREAD

**Issue by Yeadh** [woocommerce/storefront#577]
I want to add carousel for the storefront homepage popular products section.
where to edit ?

**Comment by ben72** [comment]
You should ask for support on https://wordpress.org/support/theme/storefront

But something like this should work:
    add_action( 'popular_products', 'storefront_popular_products', 50);
    function popular_products() {
        // carousel code here
    }

**Comment by Yeadh** [comment]
Yes,
I have used this function and it's work but I wanted to know where they(storefront) have created the function

**Comment by ben72** [comment]
Not sure what you mean. Search the code or ask for support on https://wordpress.org/support/theme/storefront

**Comment by Yeadh** [comment]
Thanks

**Comment by jameskoster** [comment]
Cheers @ben72 

Closing this out as it's support.
