### ISSUE TITLE
Category pages - header and text is centered

### ISSUE THREAD

**Issue by el-presidente** [woocommerce/storefront#578]
The new 2.2.0 centers header and body text - is that a feature or a bug?

On one of the pages there's also a lot of white space between the header

https://www.landgarden.se/produkt-kategori/odlingslada/

![screen shot 2017-05-22 at 12 30 07](https://cloud.githubusercontent.com/assets/937382/26304120/78b6d002-3eea-11e7-8947-01538a5acc3c.png)

I dig the new design tweaks - heads up!

**Comment by jameskoster** [comment]
When using a full width template (IE no sidebar) we decided that centrally aligned headings / descriptions were more engaging. So, not a bug :)

> I dig the new design tweaks - heads up!

Glad to hear it!

**Comment by el-presidente** [comment]
OK thanks - any CSS-snippet to left align those two?

**Comment by tiagonoronha** [comment]
This should do the trick :)

```
@media (min-width:768px) {
	.storefront-full-width-content .woocommerce-products-header {
		text-align: left;
	}
}
```

**Comment by el-presidente** [comment]
Thanks - what should I add to include the Cart and Checkout page?

**Comment by tiagonoronha** [comment]
```
@media (min-width:768px) {
	.storefront-full-width-content .woocommerce-products-header, .storefront-full-width-content.woocommerce-account .entry-header, .storefront-full-width-content.woocommerce-cart .entry-header, .storefront-full-width-content.woocommerce-checkout .entry-header {
		text-align: left;
	}
}
```

For further questions, please post on the WordPress.org forums. :)

https://wordpress.org/support/theme/storefront/
