### ISSUE TITLE
Extra "Calculate shipping" in checkout page.

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/storefront#580]
Just updated and now there is a "Calculate shipping" icon in checkout page, when you click in it nothing happens.

![screenshot from 2017-05-22 14-29-08](https://cloud.githubusercontent.com/assets/1264099/26320917/1526c766-3efb-11e7-90f1-b9cb2032f008.png)

**Comment by BurlesonBrad** [comment]
Você quebrou a internet
![claudios-broke-the-innerwebs](https://cloud.githubusercontent.com/assets/6208757/26324027/b86aab68-3ef6-11e7-953e-210fd84c2cf3.png)

**Comment by claudiosanches** [comment]
Only happens with 3.1.0-dev.
