### ISSUE TITLE
Existing footers empty after upgrading to 2.2.0

### ISSUE THREAD

**Issue by pdwetz** [woocommerce/storefront#581]
I updated my test site and my four column footer was reset. After digging through the code a bit it looks like the logic was updated, but was it meant to impact existing sites? Are we meant to re-add them manually?

**Comment by tiagonoronha** [comment]
It's a bug, already reported in #579.

Sorry for the trouble.

**Comment by pdwetz** [comment]
Thanks. Maybe rename 579? I saw it, but the title gives no hint so I didn't even bother looking at it.
