### ISSUE TITLE
Problems after Update 2.2.x

### ISSUE THREAD

**Issue by KLucky13** [woocommerce/storefront#582]
Hello,

Today I updated the storefront theme and all off a sudden my website looks different.. All the fonts have changed and also on the top of the site, the buttons and background no longer have a contrast. Before if the background would have been black, the zone around the buttons would have been a darker grey to have contrast between them. 

I cannot seem to find to put it back like it was before the update?

Kind regards,

Kenny

**Comment by KLucky13** [comment]
You can compare what I mean.

This site did not get the update yet = www.heart4music.com
This one was updated = www.magneetroerder.com

Also the text is pushed in a smaller zone instead over the complete length of the page... I don't like it at all..

Kind regards,

Kenny

**Comment by jameskoster** [comment]
These are a part of the design tweaks we made in 2.2.0. You can read more about those changes in the [development blog](https://storefront.wordpress.com/2017/05/22/storefront-2-2-0-is-now-available-to-download/).

I'm sorry you're not keen on some of the changes but fortunately things like the header background color are easily changed in the Customizer.

Changing font-weights etc is also very simple. I recommend posting in the WordPress.org support forums for help with that. You'll need to add a little custom css to the CSS module in the Customizer.

I'm going to close this issue out as it's not technically a bug. If you do spot anything else you think might be a bug don't hesitate to open another issue.
