### ISSUE TITLE
Compiled style.css

### ISSUE THREAD

**Issue by pdewouters** [woocommerce/storefront#583]
Why not include the built stylesheet in the main repo so that it can be used as a submodule?

**Comment by jameskoster** [comment]
> Why not include the built stylesheet in the main repo

Simply because it's not a development file.

> it can be used as a submodule

I'm interested to hear the scenario in which you'd like to include Storefront as a submodule.

**Comment by pdewouters** [comment]
we include all third party code as submodules as a general rule if we can

**Comment by jameskoster** [comment]
I suppose it doesn't cause any harm to include the compiled .css files. If this would help folks out then I've no objections.

@tiagonoronha any thoughts?

**Comment by tiagonoronha** [comment]
One of the reasons why we removed compiled CSS in the first place, is that people would often submit pull requests to the compiled CSS and completely ignore the Sass files.

There was also the issue of people using different compilers which would often result in merge conflicts.

So yeah, not really a fan of the idea. :)

**Comment by pdewouters** [comment]
fair enough
