### ISSUE TITLE
Add to cart notice appears behind Product Hero on homepage

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/storefront#584]
As tested on https://giveherhope.co.za

* If you add a product to the cart on that page
* It will display the add-to-cart notice semi behind the header

![http://cld.wthms.co/lJyrJ](http://cld.wthms.co/lJyrJ+)
Link to image here: http://cld.wthms.co/lJyrJ.

cc @jameskoster

**Comment by jameskoster** [comment]
This is an issue in Product Hero. I'll close this issue out for now.

**Comment by jobthomas** [comment]
Moved
