### ISSUE TITLE
2.2.2 still removes all widgets

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/storefront#586]
Installing 2.2.2 over 2.1.8 removed all widgets in sidebar and footer. The layout created with the WooCommerce Product Archive Customiser is not applied anymore. 4x16 is now ugly layed out. With  2.1.8 the images were scaled down to fit. this seems not to be done anymore. I also use the WooCommerce Customizer and  the Theme Customisations plugins. It seems to me that 2.2.x is not tested enough against the Woo plugins mentioned. Looking forward to test a new version. TNX Egbert Jan, NL

**Comment by jobthomas** [comment]
Same happened to me. The widgets are still saved under **Appearance > Widgets > Inactive Widgets**.

![http://cld.wthms.co/ScbR4](http://cld.wthms.co/ScbR4+)
Link to image here: http://cld.wthms.co/ScbR4.

cc @tiagonoronha

**Comment by tiagonoronha** [comment]
I'm looking into it at the moment.

@EgbertJan @jobthomas what options did you select in the welcome pop-up screen?

**Comment by jameskoster** [comment]
> The layout created with the WooCommerce Product Archive Customiser is not applied anymore. 4x16 is now ugly layed out. With 2.1.8 the images were scaled down to fit. this seems not to be done anymore

This sounds like a separate issue btw, I suggest posting that on the wordpress.org support forums.

**Comment by EgbertJan** [comment]
I did post is there too. This might well  be an issue with something else (I have several Woo plugins in use) but layout was fine while I was at Storefront 2.1.8. All missery started with the 2.2.2 update (I missed 2.2.0 and 2.2.1).

**Comment by tiagonoronha** [comment]
Widgets issue has been fixed here: c543795c836ef206157403f0c7157b4444854488

For the issue you're having with the extension, post in the WordPress.org forums and/or the plugin repository: https://github.com/jameskoster/woocommerce-product-archive-customiser

Thanks
