### ISSUE TITLE
Left align versus centered part two

### ISSUE THREAD

**Issue by el-presidente** [woocommerce/storefront#587]
#578 was closed so I have to reopen this to vent some frustration in the left align vs centered discussion.

First of all I don't think it makes sense to center all of WooCommerce pages but not Wordpress'. Now I have WooCommerce pages centered and Wordpress pages left aligned, there's no coherence between them. Maybe I'm missing a new setting but that should be streamlined.

The other thing is on my iphone / or decrease my browser width then all of a sudden the headings are not centered but left aligned, which doesn't make sense for me.

Screenshots of my cart before and after decreasing the width:

![screen shot 2017-05-24 at 08 50 51](https://cloud.githubusercontent.com/assets/937382/26390278/353ce1ca-405e-11e7-8739-ac46f4c79f2a.png)
![screen shot 2017-05-24 at 08 51 10](https://cloud.githubusercontent.com/assets/937382/26390279/353d231a-405e-11e7-88fa-4c43a55bdd8c.png)

**Comment by jameskoster** [comment]
The coherence is that pages without a sidebar have centrally aligned titles/descriptions.

On mobile central alignment doesn't work so well due to the small screen.

These aren't bugs, which is why your last issue was closed / locked. These are personal preference items which you can get help with on the WordPress.org support forums :)

**Comment by el-presidente** [comment]
I know the support forum - I think this is a failure in the design therefore Github.

On my Wordpress page fx Contact page my header is left aligned - but when I go to my Cart on a WooCommerce it's centered - is that coherent? Both are without sidebars.

And sorry but when it doesn't work on mobile why do it desktop then.

**Comment by jameskoster** [comment]
> On my Wordpress page fx Contact page my header is left aligned - but when I go to my Cart on a WooCommerce it's centered - is that coherent? Both are without sidebars.

_That_ might be a bug. We'll investigate.
