### ISSUE TITLE
Homepage Cataegory Products

### ISSUE THREAD

**Issue by vishal7bohara** [woocommerce/storefront#589]
Unable to change products in the categories like New In, Best Sellers etc given at homepage

**Comment by ben72** [comment]
Those are AFAIK automatic collections based on new products added and sales history. So you should not be able to change those directly.

**Comment by ben72** [comment]
@vishal7bohara this is where you post bugs. Please use the support forum for support, https://wordpress.org/support/theme/storefront

**Comment by jameskoster** [comment]
@ben72 is correct :)
