### ISSUE TITLE
Storefront doesn't allow usage of JavaScript on an action

### ISSUE THREAD

**Issue by bor0** [woocommerce/storefront#590]
## Introduction
We investigated this with @rynaldos and concluded it's an issue on the Storefront side. When combined with [Google analytics integration](https://github.com/woocommerce/woocommerce-google-analytics-integration/), JavaScript code appears on the homepage product page.

<img width="989" alt="screen shot 2017-05-26 at 9 14 53 am" src="https://cloud.githubusercontent.com/assets/1620929/26485411/4a0aef08-41f7-11e7-91c0-ac489818a227.png">

## Steps to reproduce
1. Create a new page (Homepage) and set the template to Homepage.
2. Make this page the new static front page.
3. Create a file `test.php` within `mu-plugins/`:
```php
<?php
function test() {
    echo "<script>alert( 'Hello!' );</script>";
}

add_action( 'woocommerce_after_shop_loop_item', 'test' );
```
Expected: Hello alert appears
Actual:
![screen shot 2017-05-26 at 09 38 38 am](https://cloud.githubusercontent.com/assets/1620929/26485371/1daff822-41f7-11e7-852b-7dc72d528ca5.png)

Note that if you go to the product list page, this works correctly, thus WC core allows us to use script tags in the `woocommerce_after_shop_loop_item` action.

## Investigation
We've found [this](https://github.com/woocommerce/storefront/blob/ed4254db74c0a8c1ad4cd387655a4d507382c187/inc/storefront-template-functions.php#L582) to be the issue, introduced by b42e92a44b35e6f10050dad1521bb35c56e9d3c9 in 2.2.0.

**Comment by jameskoster** [comment]
This is cause by the shortcode output being run through `wp_kses_post()`. We probably don't need to do that as the shortcode attributes are already sanitized.

**Comment by MaletinatoR** [comment]
Wen the update will be availeble?

**Comment by jameskoster** [comment]
@MaletinatoR in the next release. No specific date set just yet.

If you need the fix sooner you can add it manually. Just replace your version of storefront/inc/storefront-template-functions.php with this one; https://github.com/woocommerce/storefront/blob/17e63487759cdfd201cbf4364ac6fbd5df28c0af/inc/storefront-template-functions.php
