### ISSUE TITLE
WooSlider Compatibility

### ISSUE THREAD

**Issue by joelwills** [woocommerce/storefront#592]
The latest Storefront is no longer compatible with WooSlider on the front page. 

1) Set the front page up as a page using the Homepage tempalte (the normal setup)

2) Activate WooSlider, create a slide or two, use Add Media to add a Slideshow to the page you set as home

3) Visit the homepage and make sure if you're using Homepage Control that the Storefront Homepage Content section is set to display.

Two issues occur:

a) Images don't appear, though the text (if any), frame and slider controls do

b) Slider is only half the width it should be (perhaps due to the images not showing?)

![Screenshot](http://joelwills.com/j9Z55+)

Link to image: http://joelwills.com/j9Z55

Replicated on my site and user site

580988-zd-woothemes

**Comment by tiagonoronha** [comment]
@joelwills I just tested and WooSlider seems to be working as expected.

Don't forget that you need to add the slide image directly to the slide post content. The thumbnail is only for the "thumbnail navigation" option: https://cloudup.com/cBlwm8-Ijm1

As for the width issue, you'll need to edit Storefront CSS to make the content of that area full width.

**Comment by joelwills** [comment]
@tiagonoronha Thanks, sorry I was confused as for themes with WooSlider built in it uses the  Featured Image for the slide. 

> As for the width issue, you'll need to edit Storefront CSS to make the content of that area full width.

Thanks, though I disagree, it should be full width like it is on any other page in Storefront. It's only the home page (or if you have a sidebar on another page) that it's not full width. There's no reason for it not to be the full width of the area just on the homepage.

I guess that's an issue with the `.entry-content` area though and not WooSlider.

**Comment by joelwills** [comment]
@tiagonoronha Should I open up another issue for the width of the content area? I notice many customer using WooSlider in the content area which is now no way near full width.

Thanks!

**Comment by joelwills** [comment]
@tiagonoronha Pinging about my question above? Thanks!

**Comment by tiagonoronha** [comment]
@joelwills sorry about the delay here, completely missed this.

We don't support WooSlider in Storefront, so I suggest you give the customer the CSS to make it full width.
