### ISSUE TITLE
Storefront and WooCommerce Advanced Product Labels problem

### ISSUE THREAD

**Issue by flabernardez** [woocommerce/storefront#594]
In the last Storefront update, products that have labels and click on add to cart on index product page and goes to product page, not cart page or same page. Meanwhile products who doesn't have labels, works correctly.

Thank you so much.

**Comment by jameskoster** [comment]
Hey,

Are you saying that when you click the add-to-cart button for a product that has a label, it isn't added to the cart? It just takes you to the product page?

I just tested this myself and didn't encounter any issues. I recommend posting this in support including a url to your site and we can investigate from there.

Cheers
