### ISSUE TITLE
Drop-down for mobile menu

### ISSUE THREAD

**Issue by boboz** [woocommerce/storefront#596]
Hi!

I think drop-down functionality (same as in standard menu behaviour) for the mobile menu would be a nice addition.

**Comment by ben72** [comment]
Hello,
This forum is for reporting bugs. Please post  ideas and feature requests on the [Storefront Ideasboard](http://ideas.woocommerce.com/forums/275029-storefront).
Thanks!

**Comment by tiagonoronha** [comment]
@ben72 thanks for the suggestion, this isn't something we are considering at the moment though. :)

You're more than welcomed to create an extension to replace the default mobile menu with a dropdown.

**Comment by blachawk** [comment]
It appears that the latest version of storefront as made this original request an official feature.  But is there a way to reverse the process.  I would prefer less clicks on a mobile menu and simply show my full menu without customers having to click to open a sub menu.  Is this possible?
