### ISSUE TITLE
New Version of Storefront Altered Width of Front Page

### ISSUE THREAD

**Issue by irreverance** [woocommerce/storefront#597]
Note: I am not overly technically inclined. I'm not sure if this is a bug, and if I need to do something else to get it fixed, please let me know.

A couple nights ago, I updated to the newest Storefront theme. A couple format issues have arisen.

The body of the homepage now has narrower margins. I had hoped to fix this by recreating the page. When I use PageBuilder to add a 3-column block, it appears that it will fill the page like it should, but when I drop it the margins shrink back to the more narrow look.
Near the bottom, it appears that new sections have appeared (which I like). The "Shop by Category" images, however, are blank. I don't seem to be able to change them in PageBuilder.

**Comment by jameskoster** [comment]
> The "Shop by Category" images, however, are blank.

You need to add category images in WooCommerce to fix this. Navigate to Products -> Categories, click one and upload an image :)

> The body of the homepage now has narrower margins

Could you please share a URL for us to investigate this?

**Comment by ben72** [comment]
This might be related? It would be nice if it worked out-of-the-box in Storefront.
The Storefront Pro plugin calls this "Page builder support", see https://vimeo.com/144468570#at=633

**Comment by irreverance** [comment]
Thanks. I'll look at the Vimeo vid. The webpage is www.puppytutor.me.

**Comment by jameskoster** [comment]
You can fix this with;

`.page-template-template-homepage .entry-content, .page-template-template-homepage .entry-header {
max-width: none;
}`

You've also added a `<div class="col-full">` to your post content, removing that will help as well.
