### ISSUE TITLE
Search label popup on IE10

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/storefront#598]
When hovering over the search input field in Windows 10 / IE11, the corresponding `.screen-reader-text` label _also_ shows up and is poorly formatted.

![http://cld.wthms.co/Dzy5a0](http://cld.wthms.co/Dzy5a0+)
Full Image: http://cld.wthms.co/Dzy5a0+

Using the following seems to solve the issue:

```
#masthead .woocommerce-product-search .screen-reader-text {
  display: none;
}
```

**Comment by jameskoster** [comment]
We should probably just remove the `:hover` styles for `.screen-reader-text` @tiagonoronha ?
