### ISSUE TITLE
Product Image Enlarge Bar Top of Images

### ISSUE THREAD

**Issue by mybizdw** [woocommerce/storefront#600]
Since the newest update with Storefront my child theme Deli, on product images a bar is showing above the images. When click on the bar opens up the image, this can be done by just clicking on the image. 
This was not there prior to the latest Storefront update. How do I get rid of it on my website?
My website is http://hometooutdoors.com. Click on any product and can see the bar at top of the images.

**Comment by ben72** [comment]
Not sure if there is an option in your theme to turn it off? If not you can just add this to your child theme or a plugin:
`.woocommerce-product-gallery__trigger { display: none !important; }`

**Comment by mybizdw** [comment]
Thank you. By adding the code - .woocommerce-product-gallery__trigger { display: none !important; } it turned it off. 
Debbie

**Comment by jameskoster** [comment]
FYI this is a WooCommerce feature, not a Storefront feature.

You can read more about adding/removing support [here](https://woocommerce.wordpress.com/2017/02/28/adding-support-for-woocommerce-2-7s-new-gallery-feature-to-your-theme/).
