### ISSUE TITLE
Storefront causes Structured Data Errors on Blog Posts

### ISSUE THREAD

**Issue by joelwills** [woocommerce/storefront#602]
If you use [Google's Structured Data Tool](https://search.google.com/structured-data/testing-tool/u/0/) on a Storefront blog post URL it causes errors.

For example:

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fdemo.woothemes.com%2Fstorefront%2F2014%2F09%2F01%2Fbirds-in-flight-and-the-power-of-a-remote-working-team%2F

Under `BlogPosting` there are two errors:

![Screenshot](http://joelwills.com/7pjVb+)

Link to image: http://joelwills.com/7pjVb

Switching to a default theme, like TwentySeventeen, resolves these issues. The first url error is set as the author archive URL and in my tests the second image error disappeared.

587682-zd-woothemes

**Comment by jameskoster** [comment]
Saw another issue like this recently but can't find it now :s 

Ultimately the missing image isn't an issue. See the response [here](https://webmasters.stackexchange.com/questions/83300/schema-org-blogposting-and-image-required).

Going to guess the same is true for the logo url.

**Comment by tiagonoronha** [comment]
It seems Google doesn't accept structured data without an image and will always throw an error.

@jameskoster should we hide the logo array if there's no logo? See [here](
 https://github.com/woocommerce/storefront/blob/master/inc/storefront-template-functions.php#L949-L951).

**Comment by jameskoster** [comment]
Sounds good.

**Comment by tiagonoronha** [comment]
Made the adjustment.. closing!
