### ISSUE TITLE
Installation Process: Links

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/storefront#604]
1) I feel like these three links should be opening in new tabs. Taking them away from their website could be quite confusing: http://cld.wthms.co/ZXTHHT

2) This support link doesn't exist: http://cld.wthms.co/qZDri6. https://support.woocommerce.com/. Also need to be careful, as you don't get premium support just for having used our free Storefront theme.

3) The Documentation link should be far more prevalent - perhaps centered above or below the extension suggestions. I linked to the documentation for users as least 3 times today in Live Chat Support and they were all very thankful for me pointing them there. People aren't finding it during the setup process. The Homepage setup process is probably the most valuable and under-referenced thing we have in Storefront. Guiding people there would be a ton of help and could prevent many support tickets.

**Comment by tiagonoronha** [comment]
1. Thanks for the suggestion, added [here](https://github.com/woocommerce/storefront/commit/a1db2897cabe19b0f48995ab873b807ca9fec95b)

2. We've already edited that link, it now links to the WordPress.org support forums.

3. When people get to that page, it's because they have been through the setup process that will ask them or setup the homepage for them. 

Perhaps we can move this into a separate issue and try to find out other ways we can guide the user. Maybe a "Next steps" section?

**Comment by jameskoster** [comment]
As a part of https://github.com/woocommerce/storefront/issues/644 we'll be presenting the Customizer Guided Tour to all users (not just fresh sites). So there won't be any users who won't be guided through setting up the homepage template.

Do you still think the documentation link should be more prevalent @WPprodigy ? Are they any other specific docs that folks find particularly useful?

**Comment by WPprodigy** [comment]
Hmm, I'll have to try out the tour process after installing on a non-fresh site. The docs link could probably still use some highlighting though.

**Comment by jameskoster** [comment]
Thought about this some more. For non-fresh sites we can't actually create the homepage for users in the Customizer (we can create the page, but not assign the template).

So on this screen we'll need to check if the homepage template is in use - if not, display a prominent link to the documentation. Design to come.
