### ISSUE TITLE
Image Lazy Load plugins not working on the Storefront homepage

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/storefront#605]
In relation to a topic the WP.org forums and after some testing, it seems that various Image Lazy Load plugins are not working on the homepage template of Storefront.

Topic: https://wordpress.org/support/topic/lazy-load-homepage-error/

Below are two of the popular plugins that I tested and they do seem to work on the blog and product archives sections etc but not on the homepage template of Storefront for some reason.

https://wordpress.org/plugins/lazy-load/#description
https://wordpress.org/plugins/a3-lazy-load/

**Comment by jameskoster** [comment]
The product images aren't loaded any differently on the homepage to the produce archives. Or any differently to regular post images.

I wonder if it's something to do with the fact that the products are pulled in via shortcode. Would you be able to test that in another page @stuartduff ?

If that's the case, we might consider creating a doc instructing folks on how to integrate with Lazy Load. I'm not sure we should build any such integration in to our products though, folks should be free to pick and choose which plugin to run.

**Comment by stuartduff** [comment]
@jameskoster I spent some time cross testing this again tonight using some shortcodes to gain a better comparison in addition to the initial info. I tested using both plugins again but grabbed some screenshots of **a3 lazy load** as it's easier to see what images are loading as it has a loader icon.

Firstly I added a `[product_category category="clothing" columns="3" per_page="12"]` shortcode to a page and the lazy load seems to function as expected with this.

![screen capture on 2017-06-19 at 22-49-41](https://user-images.githubusercontent.com/1190565/27307437-a45c0e9e-5541-11e7-8ea2-48f978c04141.gif)

I then added a recent products shortcode too `[recent_products per_page="12" columns="4"]` as that's one we use on the homepage template and that also seems to lazy load correctly too.

![screen capture on 2017-06-19 at 22-54-53](https://user-images.githubusercontent.com/1190565/27307599-584e511e-5542-11e7-9d2c-d8d7ef1d8bc8.gif)

I then set the test page as the homepage of the site to see what the results were and the lazy load functioned again.

With the SF Homepage template activated however the lazy load did not function again so it does seem isolated to only products which display via the homepage template which is rather weird.

**Comment by jameskoster** [comment]
That is very odd. How about if you add a shortcode to the homepage content whilst still using the homepage template?

**Comment by stuartduff** [comment]
Odd indeed :)

With the recent products shortcode added to the homepage content area the lazy load functions correctly. The other products on the homepage still no joy however.

![screen capture on 2017-06-20 at 12-05-25](https://user-images.githubusercontent.com/1190565/27330361-fa5b33aa-55b0-11e7-9a6a-fc076e31f380.gif)

**Comment by jameskoster** [comment]
Those spinners... do the images just never load? I wonder if it's anything to do with our `storefront_do_shortcode()` function.

**Comment by stuartduff** [comment]
Yeah the just spin and the image never appears when using a3 lazy load.

With the Lazy Load plugin which a8c have contributed too however it creates a gap above the product image which seems to be a 1x1 px transparent image like this.

**Comment by stuartduff** [comment]
After some further investigation this evening it seems to be related to running the `$shortcode_content` output through `wp_kses_post` like this example below.

https://github.com/woocommerce/storefront/blob/version/2.2.3/inc/storefront-template-functions.php#L630

When `wp_kses_post` is removed echoing out `$shortcode_content` directly lazy loading is then operating correctly and this resolves the incorrect behaviour for both lazy load plugins I tested.

![screen capture on 2017-06-20 at 20-37-00](https://user-images.githubusercontent.com/1190565/27352336-40537132-55f8-11e7-96f6-796f45f68f06.gif)

**Comment by tiagonoronha** [comment]
@stuartduff `wp_kses_post ` has already been removed [here](https://github.com/woocommerce/storefront/commit/17e63487759cdfd201cbf4364ac6fbd5df28c0af).

Wait for 2.2.4 :)

**Comment by jameskoster** [comment]
I thought that might be the issue but was sure we'd already deployed that change. Makes sense.

Thanks for your help investigating @stuartduff !

**Comment by stuartduff** [comment]
@jameskoster @tiagonoronha Awesome and lets close this out then :)
