### ISSUE TITLE
Advanced Product Labels CSS displayed on the Homepage template

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/storefront#607]
#### Affected tickets 

588557-zd-woothemes

#### What I expected

To use Advanced Product Labels on my homepage

#### What happened instead

Each label is displayed with CSS code under the product image / above the label:

![Screenshot](http://cld.wthms.co/kz4WQB+)
Screenshot: http://cld.wthms.co/kz4WQB
https://woostore.mystagingwebsite.com/homepage/

This problem doesn't happen on shop / category pages - the labels are displaying correctly there, with no extra CSS code:

![Screenshot](http://cld.wthms.co/vZVhbZ+)
Screenshot: http://cld.wthms.co/vZVhbZ
https://woostore.mystagingwebsite.com/

#### Steps to reproduce 

1. Install and activate WooCommerce Advanced Product Labels: https://woocommerce.com/products/woocommerce-advanced-product-labels/
2. In WooCommerce > Settings > Product Labels, add any label for the products
3. Set up a page with Homepage template and see how the labels are showing there.
4. Compare with a shop / category page and see it works correctly this time.

Reproduced on Pressable with WC 3.0.8, APL 1.1.1 & Storefront 2.2.3

**Comment by tiagonoronha** [comment]
@madeincosmos this has been fixed [here](https://github.com/woocommerce/storefront/commit/17e63487759cdfd201cbf4364ac6fbd5df28c0af).

2.2.4 will be available soon.
