### ISSUE TITLE
public function change_breadcrumb_delimiter overriding custom functions

### ISSUE THREAD

**Issue by WM4362** [woocommerce/storefront#609]
WordPress 4.8-en_AU | Storefront 2.2.3 | WooCommerce 3.0.8

I noticed after the Storefront 2.2 upgrade my custom breadcrumb delimiter was not styled correctly. My delimiter was now wrapped in and set `::after` a `<span class="breadcrumb-seperator">` which I traced back to the below filter/action in [class-storefront-woocommerce.php](https://github.com/woocommerce/storefront/blob/33cf0000b9d3cc9b0bbf5e165bf8a1a66c052f3b/inc/woocommerce/class-storefront-woocommerce.php). 

Line 33:
`			add_filter( 'woocommerce_breadcrumb_defaults',          array( $this,'change_breadcrumb_delimiter' ) );`

Line 181:
```		
/**
		 * Remove the breadcrumb delimiter
		 * @param  array $defaults thre breadcrumb defaults
		 * @return array           thre breadcrumb defaults
		 * @since 2.2.0
		 */
		public function change_breadcrumb_delimiter( $defaults ) {
			$defaults['delimiter'] = '<span class="breadcrumb-separator"> / </span>';
			return $defaults;
		}
```

This was simply remedied by setting a priority to the filter in my functions.php (per below), but I'm curious to understand why this 'change_breadcrumb_delimiter' public function was added to Storefront and why it is necessary as  seemingly another layer on top of the already adequate woocommerce_breadcrumb_defaults filter?

`add_filter( 'woocommerce_breadcrumb_defaults', 'woocommerce_breadcrumb_defaults_custom', 90 );`

Thanks!

**Comment by jameskoster** [comment]
We wanted to style the breadcrumb separator (and make it easy for Storefront users to do the same thing). The filter is just to wrap it in a unique class.

As you figured out you can override this behaviour by adding a priority to your own custom filter.

**Comment by WM4362** [comment]
Ok, thanks James, that explains it!
