### ISSUE TITLE
Idea: Import demo data whenever you'd like too

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/storefront#610]
I had two users in live chat last week who managed to install Storefront and WooCommerce, but missed the opportunity to use the wizard and/or install demo content. As a result, they were really struggling with how things work/how things looked. I offered to import the WC demo data and they agreed. After doing so, they were very happy with the new look and excited that they could see what they can do now.

Right now, we only install the SF demo content if it's a new site. I'd like to propose we also add a tool (perhaps to WC > SS > Tools) that allows you to install SF demo content as well. This would be a great help in support, and we can maybe work it into the setup-flow as an optional choice for those that aren't on a brand-new site as well.

**Comment by jameskoster** [comment]
I don't think this problem is specific to Storefront. Having an easy way to import demo content would be useful for all themes. So I'd suggest we add this feature to WooCommerce. We could then conditionally highlight that feature on the Storefront welcome screen as a 'last chance' before they exit the initial nux.

I think you'll still get folks submitting tickets though because WC tools are not exactly easy to find, especially for new users.

**Comment by WPprodigy** [comment]
Thought about that too. But SF has it's own demo content that appears when you first visit the customizer right? That content is more than just WooCommerce Products, and includes a homepage featured image and stuffs. That's why I was thinking this may be a good fit for SF.

Agree that tools aren't easy to find. It could be there as a secondary option, but hopefully those that need this done would be shown an notice at the right time during the setup process that they would take advantage of.

**Comment by jameskoster** [comment]
> But SF has it's own demo content that appears when you first visit the customizer right?

Yes but it's all built into cores Starter Content feature. This crux of this entire feature is that it only does it's thing on fresh sites. Having a way to add all of this content to non-fresh sites is going beyond the original scope and will introduce some technical fluff I think. @tiagonoronha can confirm.

> but hopefully those that need this done would be shown an notice at the right time during the setup process that they would take advantage of.

They are shown a big notice to visit the Customizer (at which point Starter Content is initiated).

I'm not saying it wouldn't be useful to have a tool to do this. I suppose we just need a clearer picture of the user story so we can work out the best course of action. Could you elaborate a little? What steps did they take before contacting support?

**Comment by tiagonoronha** [comment]
@WPprodigy I understand your request, but we are already bending the way Starter Content works more than I'd like.

If you need to install the SF dummy content in a site, you can manually change the `fresh_site` flag to `1` in the WordPress options table. Then go to the Customizer and you should see the starter content.

**Comment by jameskoster** [comment]
> you can manually change the fresh_site flag to 1 in the WordPress options table

Customers can do this at `/wp-admin/options.php`. Just in case you didn't know. I only learned (or perhaps remembered that I forgot) about this recently 😱
