### ISSUE TITLE
Strings Not translated

### ISSUE THREAD

**Issue by keusta** [woocommerce/storefront#611]
Hello and good job on this fresh update... I have a few problems withs strings not translated in my french version..
They are correclty listed in the file woocommerce-fr_FR.mo and the file is correctly hosted wp-content>languages>plugins> but when i browse my website, the cart page, the checkout page and the 'add to cart' widget seems to show strings in english. I v got woocommerce Version 3.0.8 and the last Storefront Version : 2.2.3... and last polylang version 2.1.5..

 What's really weird is that, all was working before the update my previous storefront version was under 2... 
You could see the problem here www.obvious-store.com/panier/

**Comment by jameskoster** [comment]
The translations are all handled on WordPress.org. It's possible that the latest versions haven't been translated into French enough just yet. You can translate Storefront [here](https://translate.wordpress.org/projects/wp-themes/storefront).

**Comment by keusta** [comment]
Thanks @jameskoster for the reply, i just checked the french version and the strings are missing in the file. Can you add theses strings in the file, so we can translate them ?. 

First, Here the list fort **the cart page** : 
"Update cart", "Cart totals", "Shipping", "Calculate shipping", " Proceed to checkout".
<img width="620" alt="capture d ecran 2017-06-26 a 16 24 53" src="https://user-images.githubusercontent.com/1273122/27544026-350dce38-5a8c-11e7-9717-bdceccdd4400.png">
Here the list fort **the checkout page** : 
"Billing details", "Company name", "Street Adress", "Apartement, suite, unit, etc. (optional)", "Order notes", "Notes about your order, e.g. special notes for delivery".
<img width="1123" alt="capture d ecran 2017-06-26 a 16 26 24" src="https://user-images.githubusercontent.com/1273122/27544202-b43605e0-5a8c-11e7-8c29-2cc6d27d35b3.png">
<img width="613" alt="capture d ecran 2017-06-26 a 16 33 19" src="https://user-images.githubusercontent.com/1273122/27544356-2b92191c-5a8d-11e7-9034-e5bd6d2c9990.png">

Here the list for the **account page** : 
"Hello $username (not $username? Sign out)", "From your account dashboard you can view your recent orders, manage your shipping and billing addresses and edit your password and account details.", "Account details".
<img width="816" alt="capture d ecran 2017-06-26 a 16 34 26" src="https://user-images.githubusercontent.com/1273122/27544509-a5431932-5a8d-11e7-9418-80e11aa18ade.png">

Here the list for **the account/orders/ page** : 
"Go shop".
<img width="821" alt="capture d ecran 2017-06-26 a 16 38 22" src="https://user-images.githubusercontent.com/1273122/27544593-e99d48a0-5a8d-11e7-955e-b69c77904ed9.png">

Here the list for **the account/edit-account/ page** : 
"Password change", "Current password (leave blank to leave unchanged)", "New password (leave blank to leave unchanged)", "Confirm new password".
<img width="596" alt="capture d ecran 2017-06-26 a 16 39 49" src="https://user-images.githubusercontent.com/1273122/27544673-26ef694a-5a8e-11e7-85c6-60b5bbf303bc.png">

Here the list for **the product page** : 
"Additional information", "Related products".
<img width="256" alt="capture d ecran 2017-06-26 a 16 41 08" src="https://user-images.githubusercontent.com/1273122/27544931-da19182c-5a8e-11e7-8d02-354d761e2ea3.png">

Here the list for the cart widget : 
"View cart".
<img width="1104" alt="capture d ecran 2017-06-26 a 16 47 35" src="https://user-images.githubusercontent.com/1273122/27545093-3b9c3520-5a8f-11e7-9f8a-9dda8b677f7e.png">
<img width="265" alt="capture d ecran 2017-06-26 a 16 46 41" src="https://user-images.githubusercontent.com/1273122/27545094-3ba0f95c-5a8f-11e7-9fa2-f5e6a01e6702.png">
 
Is it possible that when updating your code, you didnt take time to point the right path to the translated string that moved ? When i look in .mo file, there's lines going with the key/value pointing to exact line number in each related file... but sometimes it didnt point to the good number... 

Can you confirm this ?
Thank you for the good job !

**Comment by tiagonoronha** [comment]
@keusta all of the above are WooCommerce strings. 

https://translate.wordpress.org/projects/wp-plugins/woocommerce

**Comment by keusta** [comment]
@tiagonoronha ok lets check this out, sometimes im lost with all these tricky translations process :)

**Comment by tiagonoronha** [comment]
Closing this issue. Please post on the WordPress support forums if you need further support: https://wordpress.org/support/theme/storefront
