### ISSUE TITLE
Header Mini cart scroll effect requires refresh to incorporate new products

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/storefront#613]
After a report on the .org forums, it seems like the minicart could maybe be enhanced in a future version of Storefront with the way it updates and operates.

Currently, it requires a page refresh for the scroll to reveal itself after adding products to cart. If you then add any additional products the cart the mini cart becomes a long list without the scroll bars which do not display again until a page refresh. Tested on our demo and on my test installs.

http://imgur.com/T3ZZmBc

We could maybe investigate if it's possible to update the mini cart in real-time whilst retaining the scroll functionality in the future.

WP.org topic: https://wordpress.org/support/topic/mini-cart-and-scroll-bars/

**Comment by nishitlangaliya** [comment]
Hi

I have added some css to which worked for me to add auto scroll when product in cart increase more then 3 so please check pr https://github.com/woocommerce/storefront/pull/618 for the same and let me know if any changes required.

Thanks

**Comment by jameskoster** [comment]
It should check on mouseover. Sounds like a bug.

**Comment by nishitlangaliya** [comment]
@jameskoster ,

Thanks for your prompt reply.

Ok I will do some adjustment to add css on mouseover to add scroll is it fine ?

Thanks

**Comment by nishitlangaliya** [comment]
@jameskoster ,

As per suggestion mouseover css added and done pr https://github.com/woocommerce/storefront/pull/622 

Thanks

**Comment by jameskoster** [comment]
No it's a bug in the javascript. If you look [here](https://github.com/woocommerce/storefront/blob/master/assets/js/woocommerce/header-cart.js#L22) you'll see the script should check the cart height on mouse over and add the CSS accordingly.

**Comment by nishitlangaliya** [comment]
Yes understood your concern. Thanks for suggestions. I will look into this and will update you for the same ASAP.

Thanks

**Comment by nishitlangaliya** [comment]
fixes -613

When add_to_cart call it renders new html to mini cart so below variable becomes undefined or null so we have to redefine variable on mouseover as well.
```
var cart = document.querySelector( '.site-header-cart' );

            var windowHeight  = window.outerHeight,
                cartBottomPos = cart.querySelector( '.widget_shopping_cart_content' ).getBoundingClientRect().bottom + cart.offsetHeight,
                cartList      = cart.querySelector( '.cart_list' );
```
I have redefine it in js file and it worked for me . Hope this works :)

Thanks

**Comment by nishitlangaliya** [comment]
@tiagonoronha ,

Thanks for your reply.

I have closed my old pr and kept final PR which is https://github.com/woocommerce/storefront/pull/624. so can you please check for the same and let me know if any change required.

Thanks
