### ISSUE TITLE
storefront functions [json+ld]

### ISSUE THREAD

**Issue by inetbiz** [woocommerce/storefront#620]
Your image object needs to conform to http://schema.org/ImageObject and is missing some principle items. I would like to feature request the `caption`, `thumbnail` and `representativeOfPage` properties be inserted / amended.

**Comment by inetbiz** [comment]
I'm not sure what to change in https://github.com/woocommerce/storefront/blob/master/inc/storefront-template-functions.php#L934 in order to get the `$attr` for **image description**. I think that should be used for http://schema.org/caption

**Comment by tiagonoronha** [comment]
The structured date output is not present only in single pages/posts/products. It's also outputted to the homepage, archives, search results, etc.

For that reason, adding support for `representativeOfPage` is not that simple. Not all images are representative of the page.

I'll into this asap.

**Comment by inetbiz** [comment]
@tiagonoronha ah. This is true. So append to string after logic filter?

**Comment by inetbiz** [comment]
@tiagonoronha also review https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Foutput.jsbin.com%2Fpacodi for products and https://search.google.com/structured-data/testing-tool/u/0/?url=https://output.jsbin.com/vucuvex#url=https%3A%2F%2Foutput.jsbin.com%2Fvucuvex for category pages. courtesy of @jvandriel in our conversation at https://plus.google.com/+DenverProphitJr/posts/Mobiax1srhM for full context.

**Comment by inetbiz** [comment]
Also this is how a category page should be written up. https://json-ld.org/playground/#/gist/c735f8a1c4f14523227e4064bfb61acb

**Comment by inetbiz** [comment]
The main takeaway is there should never be more than one top level entity. A category page is a collection of like entities expressed in a nested entity of listitems that further have nested entities of product and offer.

A product page will be coming up this week. I added notes here since this function controls json+ld everywhere.

**Comment by inetbiz** [comment]
@tiagonoronha guideline for a product page. https://json-ld.org/playground/#/gist/0453ffd28f753ec202501283b496947c

**Comment by jvandriel** [comment]
> _"Also this is how a category page should be written up. https://json-ld.org/playground/#/gist/c735f8a1c4f14523227e4064bfb61acb"_

I'd not use the above mentioned template for category pages but https://output.jsbin.com/vucuvex instead.

**Comment by tiagonoronha** [comment]
After looking into this a bit more, I found out that what I said above is not 100% correct. Since WooCommerce 3.0, structured data is handled by the plugin, and not Storefront.

Currently, Storefront is only outputting the json-ld format for non-WooCommerce pages.

We've also started a discussion internally about the value our integration of json-ld is adding, and we came to the conclusion that there are many plugins out there that do this much better than us.

For that reason, we'll be removing this functionality from the theme soon.

Suggested plugins:

https://wordpress.org/plugins/wordpress-seo/
https://wordpress.org/support/plugin/wp-structuring-markup

**Comment by inetbiz** [comment]
@tiagonoronha then you should strongly consider microdata format in html5. Persons in East Europe rely on Yandex. Yandex does not accept json+ld. A plugin cannot handle microdata insertion. Only new forked copies.

**Comment by tiagonoronha** [comment]
> The following syntaxes are currently supported: JSON-LD, RDFa, microdata, and microformats.

https://tech.yandex.com/validator/

**Comment by JamesJosephFinn** [comment]
Just putting my chosen WP SEO tool here: [Squirrly SEO](https://www.squirrly.co/wordpress-seo-by-squirrly) is an excellent substitute/replacement for Yoast.
