### ISSUE TITLE
Type found in /inc/storefront-template-functions.php

### ISSUE THREAD

**Issue by inetbiz** [woocommerce/storefront#621]
https://github.com/woocommerce/storefront/blob/master/inc/storefront-template-functions.php#L40 had extra open bracket.

**Comment by tiagonoronha** [comment]
Hi there! 

There's nothing wrong with that line. The first open bracket iss the beginning of the list item tag.

Here's the output:

`<li class="comment even thread-even depth-1" id="comment-1">`
