### ISSUE TITLE
Footer bar on Android hinders user view when filling out fields

### ISSUE THREAD

**Issue by svenhutchinson** [woocommerce/storefront#625]
Not sure if anything can be done about this or not but when inputting checkout fields on Android the mobile footer bar goes above the keyboard input.   iOS it doesn't do this.   Having that there on mobile when inputting data almost completely takes up all the screen.

Can be seen on our demo at checkout.  (I don't have an Android to test sadly but I checked with the user that they can see it on our demo site)

Ticket https://woothemes.zendesk.com/agent/tickets/599084

**Comment by dsmithweb** [comment]
Feedback from user in 684873-zd-woothemes

> Honestly, I don't understand how this behavior could be tagged as a enhancement task.
>
> Have they really try to buy from an Android device?? It's not a[n a]esthetic matter, the experience is not good at all. Let's me explain you please point by point why I think this is so important in order to convince you to pass this info for the developers hoping they re-think the prio of this task...
> When you try to fill the checkout fields and you open the keyboard, the free space that you have to put your info and do scroll for next fields is super tiny. The navigation bottom menu is still active and is eating the 20% of the screen. Taking in account that the navigation bar, the top menu and the keyboard are open also, the webpage space to put your info is the 20% of the screen probably. And I'm taking in account that I have a medium - big screen, for users with small screens has to be impossible to buy.

Note from me: I use an LG Aristo, a relatively small (Android) phone, and while I agree that more space would be better, I don't find the Storefront footer's presence significantly impedes checkout-- not enough for me to recommend shifting the classification of this issue from "Enhancement."

**Comment by jameskoster** [comment]
We could hide the footer bar when checkout inputs are focussed. Could even do that only on certain (x small) screen sizes.

Needs testing though. I'm surprised this makes a significant difference to the checkout experience.
