### ISSUE TITLE
Homepage content width 

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/storefront#626]
I've lost count how many times I've seen this referenced in support. Users write something along the lines of:

> After a recent update, the content on my homepage is much narrower than it used to be. It used to be as wide as the menu above. How can I set the width back to the way it used to be?

This is because of the new styles introduced in Storefront:

```
.page-template-template-homepage .entry-content, .page-template-template-homepage .entry-header {
    max-width: 41.0994671405em;
    ...
}
```

Is there any reason why the homepage content area has such a large difference in width when compared to the rest of the sections? That's also having a large effect on child theme support.

Since Powerpack doesn't have a width property on a per-section basis, the _only_ way to support customers is by providing custom CSS.

**Comment by tiagonoronha** [comment]
The reason for the difference in width is mostly readability, to avoid very long lines to text.

But I can see why it is causing some confusion. 

@jameskoster what do you think? worth keeping or should we remove the width?

**Comment by jameskoster** [comment]
Isn't this only for the homepage hero component? Personally I think it would look weird with wide text. 

For every person that posts in support there are hundreds who don't mind.

It's a 1 line css change which can be done in the Customizer. Personally I don't think it's urgent to change this in Storefront itself. We might even see people posting in support about the change afterwards asking how to revert it :p

**Comment by BurlesonBrad** [comment]
**hashbrown=TechnicalDebt** _(pretty sure I just hashbrown-ed incorrectly)_ 🥇 
**#scopecreep** _(much better)_ 👍 

btw: same thing happening in woohelp group

### Shouldn't the answer be ➡️ "Universally Consistent" ⬅️  ?  
I mean, y'all are all mixing a few different & various things together:
1. Default 
2. PowerPack
3. Hero Component of... 
4. ....Homepage Template (sometimes used / sometimes toggled to `full-width` )
5. _(4 and a half)_  No one mentioned "what happens" when the Parallax Hero is added to the mix 

Look, within the realm of `Storefront & Extensions` there's really only two occasions where anything in a store's width can be modified or changed by the end-user:

- One of those instances is via PowerPack's | Page layout | Define the width of your site content.
- And the other is if they opt for a Parallax Hero to bust outta the `<div>` _(Hero Layout = Full Width)_
![hero-layout-full-width](https://user-images.githubusercontent.com/6208757/28043343-12b97a88-6597-11e7-9c06-a62f98c92387.png)


So, both of those plugins have the capacity to change the width accordingly within their own code, right? Sure! 👍

But, by **"default"** shouldn't the width be **"Universally Consistent"** ❓ 
From the menu all the way down to the footer, and everything & anything in between, nothing should deviate 👍 
Even (**and especially**) when using the new template of `homepage` _(which 🤔  had a toggle in the beta & probably should have stayed a toggle ✋)_ 
The store owner shouldn't have to modify it, nor should Ninja @RiaanKnoetze have to support it.
It should be 🌏 Universal 🌎 

If the store owner wants to modify it **from** `default`, then it's on them & not the Ninjas 👊

**Comment by RiaanKnoetze** [comment]
@jameskoster @tiagonoronha - I totally understand the design reasoning for "long lines of text" and "one line of css", although I think further consideration should be given to:

1. One line of CSS that's repeated over hundreds of tickets doesn't lessen the support burden;
2. It assumes that the user will be adding **text** - if they're using the Parallax Hero Shortcode, a page builder or a 3rd party slider shortcode then _all_ of those will show up inside a reduced width content area.

**Comment by jameskoster** [comment]
> hundreds of tickets

Is it hundreds of tickets?

> Parallax Hero Shortcode, a page builder or a 3rd party slider shortcode then all of those will show up inside a reduced width content area.

Is it common for folks to add a Parallax Hero shortcode when it is already added to the homepage automatically?

Is it safe to assume that text is the most common form of content to be displayed here?  If so then that's what we should optimise for. Once you add third party anything it starts to fall in to customisation territory imho.

**Comment by BurlesonBrad** [comment]
jeeze, this should probably be made into one of my whiteboard videos but, here goes.....

Folks, that's the problem when you rolled out Storefront 2.2.  The onboarding did a few good things.  The widget areas + adding additional pages + a few other issues weren't really considered & that was somewhat addressed in 2.3 & 2.4 ~ which is great.  But I really want to be fair and objective on all perspectives and viewpoints.

Initially, there was a checkbox (defaulted toggle to check) that was under the big blue button prompting the site owner / store owner for the `homepage` template.  

For whatever reason _(in the beta, but not in the release?)_ that toggle was removed in the release version of Storefront.

That one decisions folks is what's causing a **LOT** of issues.  Honestly speaking from a technical-debt, user experience, ear to the ground, on the front lines, point-of-view, that **choice-of-default-inclusion** of the `homepage` template needs to be either removed or made into an option **(not a self defeating / support ticket creating _DECISION_)!**  said with love 💟 but also in bold 😉 

Look, from _"both-sides-of-the-isle"_, I understand what the goal is.  I do.

But, you've got to understand that not only is the `homepage` template jacking with layouts, it's doing several other things, again that's **neither** in favor of the support ninjas **nor** the store owners as well. 

The onboarding prompting to install WooCommerce, prompting for customizations via the `wp-customizer`, prompting for upsells to Storefront Extensions, .....all those are great! They really are!!

But no one asked for their homepage content to change widths.  No one, either existing users or new users as well, has ever seen a theme where, when you simply add a featured image, it then takes whatever is in the content editor and does all sorts of wacky and weird things to it.  

These store owners build a homepage with all types of options including shortcodes from plugins, text content, content & images, video, MailChimp sign ups, other email sign up forms, default WooCommerce shortcodes, [specific high margin products](https://docs.woocommerce.com/document/woocommerce-shortcodes/#section-9),  [Elementor](https://github.com/pojome/elementor), Visual Composer, [Live Composer](https://github.com/live-composer/live-composer-page-builder), [WooRockets](https://github.com/WooRockets/WR-PageBuilder), [Pootle](https://github.com/pootlepress/pootle-page-builder), for the Cool Kids there's [HumanMade's builder](https://github.com/humanmade/modular-page-builder), [SiteOrigin](https://github.com/siteorigin),  **(ok, ok, Brad, that's overkill. we get the point)**

So, the second the `homepage` template is **default** installed, added, & applied to `is_front_page` then that's when 💩 starts happening

> hundreds of tickets

**BEFORE** _(too late for "after")_ it was assigned it to @tiagonoronha , perhaps the technical debt 💰 ⏳  for WC Support Ninjas and headaches for store owners should have been thought out and considered 🤔 before the  _**"decision not option"**_  for the `homepage` was added. 

It wasn't. It happened. And it's now there. Let's move forward.

@jameskoster I get that it might not be _"perceived"_ as an issue, but it is. Out of the **100,000+ installations and 1,475,388 downloads**, if @RiaanKnoetze is mentioning it, if I'm mentioning it _(and helping educate when I have time over in the fb group)_, the understanding of "sample representative data" is questioned, and you're still wondering _"is it hundreds of tickets?"_, ....well, that's perfectly fine.  

Again, I want to be very fair and objective & see things from a holistic 360 viewpoint here.  But, more importantly, I want to make sure you've got the opportunity to do the same.  

And, a _"completely objective viewpoint"_ can easily be done via a [Zendesk Search Query](https://support.zendesk.com/hc/en-us/articles/203663226-Zendesk-Support-search-reference#topic_ahr_wsc_3v) 👍 

## Storefront is making _(some)_ great strides forwards.

At the same time though, let's not forget that Storefront's intent is:
1. "rest assured the integration between WooCommerce, WooCommerce extensions and Storefront is water-tight"
2. "The Storefront philosophy is to do one thing well"
3. A "provide a rock solid foundation"

Is the `homepage` option great ❓ Yes. Yes! YES! **YES!! _(Lemme go ahead and add a for more emoji just so everyone is clear:)_
## **YES** ❗️ 🎉 👍 🥇 💯 ⬆️ 🔼 👋 🤜 ✊ 💥 🤛 

Can the `homepage` template be included? Sure.
Is the `homepage` featured image a confusing feature? Possibly.
Does the `homepage` template create layout confusion? Yes.
Can the `homepage` template be made even better with PowerPack? Absolutely.

But should it be applied _(without option)_ by default? No.

**Comment by RiaanKnoetze** [comment]
> Is it hundreds of tickets?

That's difficult to say as only users that bought premium Storefront extensions are able to open a support ticket. That said, I easily deal with 2-3 tickets daily about that. As for how many are dealt with by _other_ ninjas, I don't know :)

Also bear in mind that our [Support Policy](http://www.woothemes.com/support-policy/#customisation) doesn't officially provide support for CSS customisations, nor are all of our ninjas versed in CSS (even if it's a small change).

Perhaps an alternative workaround would be to create a free .org plugin to gauge whether it should be added (back) into the core Storefront theme - e.g. **Storefront Full-width Homepage Content**?

**Comment by tiagonoronha** [comment]
@RiaanKnoetze is there a support document on this issue? If you're getting 2-3 tickets daily, that would probably be the first step.

**Comment by RiaanKnoetze** [comment]
Support is heading in the other direction - instead of giving users custom code to add to their site (which adds more of an update headache down the line), we should perhaps focus on better backwards compatibility? We ran into the same issue with the H2/H3 markup issue with WC 3.0 :)

That said, the number of support tickets I've seen on this have dropped quite a bit in the past few weeks.

**Comment by rottervision** [comment]
hi git/woo peeps - please help if you can... I have Storefront + Storefront Extensions Bundle + Parallax Hero +  Homepage Template = a lot of  white-space (almost a full inch), below the header, and on both margins. I can not figure out how to get rid of it,... (latest versions of everything)  #content.site-content {margin-top: -50px;} pushes my content up, but also my breadcrumb trail (which I wouldn't mind either getting rid of, or live linking, or controlling) - furthermore , my footer with a  cloud tag is almost a full screen on a decent sized monitor as well as an iPhone 6s ... any advice at all on filling out the page more would be greatly appreciated. cheers!

**Comment by RiaanKnoetze** [comment]
Hey @rottervision - Please log a support request at https://woocommerce.com/my-account/ticket; This Github repo is only geared for coding purposes, specifically logging bugs and enhancement requests.

Thanks :)

**Comment by rottervision** [comment]
thanks - right after i posted at git , it dawned on me to do just what you recommended - so i did  - i even did the temp admin email thin as well - thanks for the reply

On Aug 22, 2017, at 11:22 AM, RiaanKnoetze <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @rottervision<https://github.com/rottervision> - Please log a support request at https://woocommerce.com/my-account/ticket; This Github repo is only geared for coding purposes, specifically logging bugs and enhancement requests.

Thanks :)

**Comment by jameskoster** [comment]
Going to close this out, assuming folks have adapted to the new width or used some css to update as required.

Feel free to re-open is this is still a major issue in support.
