### ISSUE TITLE
An issue with product gallery

### ISSUE THREAD

**Issue by wearehappybits** [woocommerce/storefront#628]
How to reproduce:
 - http://imgur.com/JZazYzU
 - Press a couple of times in this area as in the image right mouse button and it will open the second image in a new tab.

Concerns:
 - Did you try having a second image without white space around? It actually is visible behind the main one:
https://ibb.co/kVqZVF

**Comment by tiagonoronha** [comment]
@wearehappybits I spent a bit of time on this but I was unable to replicate any of the issues.

What version of Chrome are you using? 

Also, please send the link to the site in the second image.

Thanks!

**Comment by wearehappybits** [comment]
Page is https://demo.woothemes.com/storefront/product/build-your-dslr/#camera-body chrome version is Version 59.0.3071.115 (Official Build) (64-bit) 

What you need to do is go to my provided link (any product page fits) and in the area of summary entry-summary press quickly a few times right mouse button and browser should trigger opening a product image in a new tab.

Also, try adding a few images with no white space around them to the gallery. Part of the next image is visible behind the first image.

**Comment by jameskoster** [comment]
I'm also unable to replicate this issue.

**Comment by wearehappybits** [comment]
This was caused by a chrome addon.
