### ISSUE TITLE
max-width does not work correctly

### ISSUE THREAD

**Issue by pavelevap** [woocommerce/storefront#629]
`max-width` is used [here](https://github.com/woocommerce/storefront/blob/4ea0688cabba7e23b6faf3043ac51aec4a2278af/assets/sass/woocommerce/woocommerce.scss#L1267) (for table vertical heading), but it seems to me that it does not work correctly and it is never limited to 150px?

> In CSS 2.1, the effect of 'min-width' and 'max-width' on tables, inline tables, table cells, table columns, and column groups is undefined.

https://www.w3.org/TR/CSS21/visudet.html#propdef-max-width

**Comment by tiagonoronha** [comment]
Thanks for the report! :)
