### ISSUE TITLE
Checkout button in woocommerce

### ISSUE THREAD

**Issue by architgarg123** [woocommerce/storefront#630]
The proceed to button on cart page is misaligned. Screenshot http://prntscr.com/fxgl9o
How can I fix it? Thanks in advance.

**Comment by tiagonoronha** [comment]
@architgarg123 do you see the same issue in the demo? https://demo.woothemes.com/storefront/

For support, please open a topic in the WordPress support forums: https://wordpress.org/support/theme/storefront

This site is for bugs only.
