### ISSUE TITLE
jQuery-independent theme to increase performance

### ISSUE THREAD

**Issue by valdrinkoshi** [woocommerce/storefront#631]
Hello, thanks for the awesome theme, it's indeed a great starting point!

I've been testing the theme with [LightHouse](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en) and noticed that First Meaningful Paint can be improved of almost a whole second when jQuery is not loaded (I've modified `wp-content/script-loader.php` and removing jQuery and full jQuery UI scripts):

| with jQuery | without jQuery |
|----------|--------|
| <img width="837" alt="screen shot 2017-07-19 at 5 31 06 pm" src="https://user-images.githubusercontent.com/6173664/28395485-55ea7a50-6ca9-11e7-9435-11496f375efd.png"> | <img width="837" alt="screen shot 2017-07-19 at 5 31 19 pm" src="https://user-images.githubusercontent.com/6173664/28395489-5e02909c-6ca9-11e7-91fc-184affa35472.png"> |

It would be great to see this theme being jQuery-agnostic and use native Web Platform features. 

After skimming quickly through the code, this looks like very much possible, and would be a very much welcomed win for our end-users which would get see the page refreshing a whole second faster! 🤑

WDYT? I can contribute through a PR, but before doing that I'd like to hear your opinion.

**Comment by jameskoster** [comment]
Wow, that's a significant difference. I've thought about doing this in the past and never got around to it.

Although not a reason _not_ to do this, it's worth noting that the vast majority of Storefront users are running WooCommerce which is going to load jQuery regardless.

I think we'd definitely be interested in seeing a PR :)

**Comment by tiagonoronha** [comment]
Echoing at @jameskoster said! Majority are running WooCommerce, so you'll always end up with jQuery anyway.

You can also simply dequeue the jQuery related scripts in a child theme.

**Comment by jameskoster** [comment]
I think it still makes sense for Storefront to be 'jQuery-agnostic' though. There may be a day in the future where WC doesn't depend on jQuery.

**Comment by valdrinkoshi** [comment]
Yeah, the idea would be to delegate the choice of using or not jQuery to the users of this theme, e.g. using `wp_deregister_script('jquery')`. It looks like Wordpress [guards against jQuery being deregistered for critical **admin** scripts](https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.wp-scripts.php#L198-L199).

**Comment by jameskoster** [comment]
I don't think we need to `deregister` jQuery. We just need to remove it as a dependency in any instances of `wp_enqueue_script()`.
