### ISSUE TITLE
Woo.com purchase flow from SF screen & WP.com sign in

### ISSUE THREAD

**Issue by MarinaWoo** [woocommerce/storefront#633]
When on the [Storefront screen](https://syrianna.mystagingwebsite.com/wp-admin/themes.php?page=storefront-welcome) and I click to purchase the SF Exts bundle, I get bounced to sign in with WordPress.com on WooCommerce.com and after doing so it drops me into the [Reader](https://wordpress.com/) - not signed in and on the product page.

So this link:

https://woocommerce.com/products/storefront-extensions-bundle/?utm_source=product&utm_medium=upsell&utm_campaign=storefrontaddons

when it hits the WP.com sign in seems to turn into the Reader.

Hope that makes sense!

**Comment by jameskoster** [comment]
I'm confused xD

That link works fine for me? It takes me to the Storefront Bundle screen on woo.com. 

From there, any issues that arise will be woo.com specific. But it all seemed to work as expected for me?

**Comment by BurlesonBrad** [comment]
Scenario replicated: [WP.com](https://wordpress.com/)=logged out 🚫  ; [WC.com](https://woocommerce.com/)=logged out 🚫 ;  
[https://screencast-o-matic.com/watch/cbiZ27lvxY](https://screencast-o-matic.com/watch/cbiZ27lvxY)

**Comment by tiagonoronha** [comment]
@MarinaWoo ping 🔔
