### ISSUE TITLE
Duplicated product and missing products on Shop page 

### ISSUE THREAD

**Issue by carladoria** [woocommerce/storefront#634]
On shop page, clicking "Older Products" button, loads one duplicated product and does not load 3 products. 
Steps to reproduce:
- On page https://dcaseydesign.com/shop/ click "older products"
- Necklace "Funky Hand Crocheted Beaded Necklace" is repeated twice
- Several items are missing ("Swarovski Crystal Teardrop Hoop Earrings" for example)
Scrolling down takes you to this link: https://dcaseydesign.com/shop/page/2/
Weird enough, going to link https://dcaseydesign.com/shop/page/2/ allows you to view all products
Infinite Scroll behavior is set by default in "We’ve changed this option to a click-to-scroll version for you since you have footer widgets in Appearance → Widgets, or your theme uses click-to-scroll as the default behavior."
Could be related to [https://github.com/woocommerce/storefront/issues/563](url)

**Comment by tiagonoronha** [comment]
@carladoria I wasn't able to replicate the issue you're having locally.

However, I did end up finding a different bug. Feel free to give a try: https://github.com/woocommerce/storefront/commit/5c0ca27201854bd2a2364e199ac3c69a5c7fabea

**Comment by tiagonoronha** [comment]
@carladoria are you still having this issue?

**Comment by carladoria** [comment]
Yeah, I'm not able to reproduce it anymore. The user has also made some changes to their shop page.

**Comment by tiagonoronha** [comment]
Thanks, closing for now. :)
