### ISSUE TITLE
Mini Cart Markup changes

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/storefront#639]
617450-zd-woothemes

When comparing the markup for the mini-cart in the header between 2.6.9 and 3.1.1, one can see that 2.6.9 uses `ul > li` to wrap the message, adding some padding to show it nicely. 3.1.1 uses a `p` element instead.

Compare the following screenshots:

![http://cld.wthms.co/N1wpo](http://cld.wthms.co/N1wpo+)
Full Image: http://cld.wthms.co/N1wpo+

![http://cld.wthms.co/f6VjzA](http://cld.wthms.co/f6VjzA+)
Full Image: http://cld.wthms.co/f6VjzA+

I was able to replicate this on my local testing installation.

**Comment by mikeyarce** [comment]
This is fixed in https://github.com/woocommerce/storefront/pull/617
