### ISSUE TITLE
Getting error Uncaught TypeError: jQuery is not a function in woocommerce.min.js

### ISSUE THREAD

**Issue by emgk** [woocommerce/storefront#640]
In StoreFront + Woocommerce website, I am getting the below error.
```
Uncaught ReferenceError: Cookies is not defined
    at HTMLDocument.<anonymous> (woocommerce.min.js?ver=3.1.1:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
```
What I have tried to get rid out of this issue but fails:
- I have added `jQuery.noConflict(true);`.
- Applied all of these tweaks mentioned inside the https://docs.woocommerce.com/document/jquery-cookie-fails-to-load/ but no luck!

Environment:
**WooCommerce:** 3.1.1
**Storefront**: 2.1.6

PS: I can't upgrade the theme and plugin to the newer version.

**Comment by mikeyarce** [comment]
This is not a problem with storefront but an issue with your server.  You can take a look at some suggestions here: https://wordpress.org/support/topic/cookies-is-not-defined/
