### ISSUE TITLE
Enhancement: Add button for mobile menu to display sub-menus dynamically.

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/storefront#642]
Right now in the mobile menu, sub-menus are displayed by default just indented from the parent item:
<img width="499" alt="screen shot 2017-08-11 at 2 10 11 pm" src="https://user-images.githubusercontent.com/3220162/29232119-d221bb4a-7e9e-11e7-8129-e81801edb151.png">
We should add a button control to display sub-items instead of showing everything by default.

**Comment by kellychoffman** [comment]
How would you navigate to the sub items?

**Comment by mikeyarce** [comment]
@kellychoffman I would do something similar to Twenty Seventeen where you have a button that can show/hide the sub-items:
<img width="636" alt="screen shot 2017-09-26 at 9 04 09 pm" src="https://user-images.githubusercontent.com/3220162/30895318-512cfe3a-a2fe-11e7-9beb-dad3e1b72142.png">

**Comment by jameskoster** [comment]
+1 I like that idea.

**Comment by kellychoffman** [comment]
Me too. I dig it.

**Comment by mikeyarce** [comment]
PR here: https://github.com/woocommerce/storefront/pull/669

**Comment by tiagonoronha** [comment]
This has been merged. :)
