### ISSUE TITLE
How to auto add new sub menu when install the themes

### ISSUE THREAD

**Issue by zigang93** [woocommerce/storefront#643]
In the public function starter_content() , I only see the primary menu have first level of menu only..
but how do i create the second level menu in this function  ??

                                                    'items' => array(
							'shop' => array(
								'type'      => 'post_type',
								'object'    => 'page',
								'object_id' => '{{sf_shop}}',
							),
							'link_home' => array(
							'type' => 'custom',
							'title' => _x( 'Home', 'Theme starter content' ),
							'url' => home_url( '/' ),
							),
							'page_about' => array(
								'type' => 'post_type',
								'object' => 'page',
								'object_id' => '{{about}}',
							),
							'page_blog' => array(
								'type' => 'post_type',
								'object' => 'page',
								'object_id' => '{{blog}}',
							),
							'page_contact' => array(
								'type' => 'post_type',
								'object' => 'page',
								'title' => 'Contact Us',
								'object_id' => '{{contact}}',							
							),
							'link_homes' => array(
							'type' => 'custom',
							'title' => _x( 'Hello', 'Theme starter content' ),
							'url' => home_url( '/' ),
							
							
							)
						),

**Comment by jameskoster** [comment]
I'm not sure, you probably need to use a `parent` attribute or something similar.

Starter Content is a WordPress core feature, I suggest posting this in the [WordPress.org support forums](https://wordpress.org/support/) or somewhere like [StackExchange](https://wordpress.stackexchange.com/). Github is for reporting bugs :)

**Comment by tiagonoronha** [comment]
This is not yet supported: https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-customize-manager.php#L1201
