### ISSUE TITLE
Guided tour: Serve it to everyone

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#644]
Currently the guided tour loads conditionally. I think it should load for everyone, the first time they visit the Customizer after activating Storefront. We should also consider adding the following steps based on feedback we've seen for Store on WP:

* Add shop page to menu(s)
* Make shop page (or homepage template) the homepage

Of course these only apply to existing sites as new sites have these items taken care of via Starter Content.

If we do make the guided tour load for everyone, the logo step should be conditional, IE check if a custom logo exists or not.

**Comment by tiagonoronha** [comment]
@jameskoster started looking into this.

What's the latest on:

>* Add shop page to menu(s)
>* Make shop page (or homepage template) the homepage

??

**Comment by jameskoster** [comment]
I think it's worth adding a step for them. Would be nice if we could check if the shop page has already been added or not though.

**Comment by tiagonoronha** [comment]
@jameskoster ah! Are you talking about adding these two as steps in the guided tour?

"Go here to add the shop page to the menu"
"Go here to change the current default homepage"

**Comment by jameskoster** [comment]
Exactly :)

**Comment by tiagonoronha** [comment]
@jameskoster The Guided Tour now loads conditionally and the logo step is only shown is a custom logo is not set.

As for the two extra steps, they are only for existing sites, correct? At the moment fresh sites have the nav menus set up by the starter content feature.

**Comment by jameskoster** [comment]
> As for the two extra steps, they are only for existing sites, correct?

Correct.

**Comment by jameskoster** [comment]
OK, here's an updated prototype for the guided tour I think we should serve to _existing_ stores.

**Comment by tiagonoronha** [comment]
Added a new step for navigation menus: https://github.com/woocommerce/storefront/commit/75089b56b4edeb1962cf09e4bb09440a594f372f
