### ISSUE TITLE
Product Page Description Width & Priority

### ISSUE THREAD

**Issue by BurlesonBrad** [woocommerce/storefront#647]
@tiagonoronha I'm on Storefront Child theme number 5 now, and I wouldn't be over here opening this and making a case if I didn't think that these two tweaks would benefit **everyone** 👍 

The first one here is this:
`remove_action('woocommerce_single_product_summary','woocommerce_template_single_add_to_cart', 30);
add_action('woocommerce_single_product_summary','woocommerce_template_single_add_to_cart', 15 );`

Basically, we're making a more uniform layout that's consistent with what the user expects from most current shopping experiences on **almost** all other major ecommerce sites like Amazon / WalMart / Kohls / .....

The CTA _(add to cart)_, which store owner's need to happen on the `single-product.php page`, should **stay next to the images**.  As of now, it's consistently **moved** lower or higher around the page based on the `description` content's length.  

It shouldn't be that way.

The store owner should be able to deliver a crisp, clean, and _(most importantly)_ **consistent** layout to their customers which is completely and entirely agnostic of the `description` content length.

The 2nd thing I'd like to propose that Storefront defaults out for all store owners is that the `single-product.php` page's content gets a wider layout.  No, not a full width layout that totally eliminates the `.sidebar`.  

But rather that the `summary` loops back up under the product's images instead of being one smaller column which currently leaves a big blank "gap" under the product images as the customer scrolls.

![dn-full-width-description](https://user-images.githubusercontent.com/6208757/29394293-08ee17de-82cf-11e7-8ffb-edabeefc8417.png)
That's what the new layout would look like _(well, plus on that screenshot, I have the above snippet as well, but still...)_, hopefully that will help visualize what the wider description area can be.

# vs.

![dn-single-current-description](https://user-images.githubusercontent.com/6208757/29394345-4546e4a4-82cf-11e7-92eb-2f1278ff9963.png)

See the large gap that the current layout places under the images?  We can fix that! 👍 

Again, I wouldn't bug y'all if there wasn't evidence to back up the convictions that these changes would, **indeed**, be beneficial _(not just as a tweak)_  rolled into **default** Storefront to benefit **everyone**:
![dn-recordings](https://user-images.githubusercontent.com/6208757/29395199-d81a9582-82d4-11e7-880b-8acf3c11071c.png)

Would anyone have objections to the next update including these modifications?

**Comment by tiagonoronha** [comment]
I think this could be an interesting tweak.

What do you think @jameskoster?

**Comment by jameskoster** [comment]
Moving the add-to-cart button - absolutely. No objections from me. But we should check how that looks with different product types.

I have reservations about wrapping the description. My concern is when the description starts adjacent to the gallery then wraps beneath it. You'll end up with different line lengths in the same body of text which can make it uncomfortable to read imo. I'd like to see a PR.

FWIW, Amazon doesn't wrap...

![amazon](https://cldup.com/U-jpr31oCG-3000x3000.png)

**Comment by BurlesonBrad** [comment]
> _"different line lengths..."_ & _"...product types..."_

Like what? Remember the staging site that you & @claudiosanches tested the import / export on? _(not listing the stage.____.com site here)_?  But if you've still got access, you can feel free to test out the different product types: currently there are simple, variable, mix & match, bundles, & grouped product types; as well as testing the different "line lengths" as well.

> _"if your short description is that long then you're probably not using the feature correctly"_

Actually, since there's always been a slight level of concern with [tabbed content](https://www.google.com/search?q=tabbed+content+google+SEO) _(both for and against)_, I've consistently **not used** any _"tabs"_. In a purposeful effort to **remove any tabbed content**, we normally removed the two tabs leaving only the reviews tab & thereby making the product description the **main** content and never under a tab.  But.... @jameskoster , that's more of an "aside" type-of-point 😜 It's not really about the tabs or either of the `description`'s. It's more about _{...tries to find a better phrasing or descriptive word...}_ **...SYMMETRY!** _(<---nailed it)_ 🤜 💥 🤛  

Not everyone does that, which is totally fine 👍 

My only ...."conviction".... here regarding the _"wrapping"_ is that WC's flagship theme **"should"** & **"can"** be much **BETTER than** _what-it-is-now_  based on a substantial amount of UX testing of different layouts.

Especially when both tweaks are added to the theme, it makes the presentation of the store owner's product page look much more aesthetically balanced:

![dn-sf-layout](https://user-images.githubusercontent.com/6208757/29413078-c53bf004-8320-11e7-83cf-43f33e77a161.png)

At the end of the day,  forks, tweaks and twerks _(wait, not twerks)_ are always great options for anyone using Storefront. After I saw a few consistent UX trends, I thought I'd share the two main ones and contribute back what was found.  Either way: it's all good

**Comment by jameskoster** [comment]
Almost sounds like you're describing the [designed I offered last year](https://github.com/woocommerce/storefront/issues/373#issue-148090572) for a revised single product page :p

**Comment by BurlesonBrad** [comment]
well.... uhm....... **YES!** 😜 I did.  Oh ye wonderful Sensei 👍 

> _"Reviews are hidden - hiding one of the biggest sales drivers by default doesn't feel like a great idea."_

Yup.  I killed that off by putting **all** the product's content in *one* place which thereby removed the need to add additional content in the tabs, which also led to:

> _"... which makes the main content area larger resulting in bigger images and more room for the main product description"_

Hence, the wider content area 👍 

> _"Reviews are visible by default"_

Again, that's a _"custom modification"_ 👍 Do I agree? Well.... of course 😉 But these two additions were mainly for the _"default"_  benefit of everyone.

I did, **indeed** take your suggestions to 💓 .  But then in the implementation of `$what_you_said` I had to juggle both the `store owner` role **along with** the `code` role at-the-same-time.  So, that's when I fired up Hotjar.  Ran some different layouts through different drop shipping SF sites, affiliate site running SF, & UX testing multiple different approaches from the store **owner's** p.o.v. 🔍 as well.

  ......which @jameskoster _(forget about any additional tweaks of removing tabs and stuff like that)_ **your suggestions** are **EXACTLY** why I'm suggesting _(just)_ these **two** edits be merged into the core of Storefront

**Comment by jameskoster** [comment]
Well, I'm definitely cool with moving the add to cart button (assuming it looks fine with different product types / extensions). I also like the idea of revealing reviews.

Still on the fence about the description though. I'll leave that one up to @tiagonoronha :)

**Comment by jameskoster** [comment]
Closing this in favour of https://github.com/woocommerce/storefront/issues/373
