### ISSUE TITLE
Hardcoded JS forces white page content heading

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/storefront#648]
Ticket: 631502-zd-woothemes

When looking at https://github.com/woocommerce/storefront/blob/ee7bd81e1de44d693d212cfd941eeb270650a183/assets/js/homepage.js#L62, it seems that the JS is forcing the text colour to be white via an inline style.

This is problematic when trying to set all `<h1>` via Powerpack as can be seen in the following screenshots:

## Powerpack

![http://cld.wthms.co/qoBFAA](http://cld.wthms.co/qoBFAA+)
Full Image: http://cld.wthms.co/qoBFAA+

## Frontend Specificity

![http://cld.wthms.co/IlbO3v](http://cld.wthms.co/IlbO3v+)
Full Image: http://cld.wthms.co/IlbO3v+

The following interim solution should work: Add this CSS snippet to **Appearance > Customize > Additional CSS** 

```
.page-template-template-homepage .entry-header h1 {
  color: #000 !important;
}
```

**Comment by tiagonoronha** [comment]
@RiaanKnoetze you can filter the list of default selectors in Powerpack with a filter:

```
function sp_designer_custom( $map ) {
	$map['hero-title'] = array(
		'selector' => '.page-template-template-homepage .type-page.has-post-thumbnail h1',
		'name'     => __( 'Hero title', 'storefront-powerpack' ),
	);

	return $map;
}

add_filter( 'sp_designer_selectors_map', 'sp_designer_custom' );
```

**Comment by jameskoster** [comment]
I think we should consider adding a selector to Powerpack for this. 

The `h1` in the hero component is unique in that it might be placed on top of a background which doesn't match the rest of the site (an image). Folks should probably have explicit control of this heading in that case.

**Comment by RiaanKnoetze** [comment]
@jameskoster @tiagonoronha - Is this being added to Powerpack? I'm asking as I don't see a new issue for that in the Powerpack repo.

**Comment by tiagonoronha** [comment]
@RiaanKnoetze please open an issue there / submit PR :)
