### ISSUE TITLE
Deprecation notice on Mobile

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/storefront#649]
Ticket: 641000-zd-woothemes

User writes the following:

---

I'm getting this error on my mobile site, but not on my desktop site. It's also happening on a test site I have setup with a completely clean WP and WC install -- no other plugins. Any idea what's causing it?

```
Notice: woocommerce_get_page_id is deprecated since version 3.0! Use wc_get_page_id instead. in /home/99931.cloudwaysapps.com/vdxesygamq/public_html/wp-includes/functions.php on line 3831
```

---

When looking at the code for Storefront, it seems to be related to getting page ID's for the Cart / My Account page when the mobile footer bar:

https://github.com/woocommerce/storefront/blob/1790927f8cab022bc96847fb0efc4f2f2ff6b2aa/inc/woocommerce/storefront-woocommerce-template-functions.php#L304-L310

**Comment by jameskoster** [comment]
Pretty sure we replaced all instances of `woocommerce_get_page_id()` in Storefront. Is the customer using the latest version @RiaanKnoetze ? Or any extensions?

**Comment by tiagonoronha** [comment]
I can confirm there's no `woocommerce_get_page_id()` in Storefront.

**Comment by RiaanKnoetze** [comment]
This was caused by WooCommerce Smart Checkout by AppPresser. Closing issue.
