### ISSUE TITLE
"Product images" Settings Not Working

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/storefront#650]
When using the "Product images" option within WooCommerce with Storefront, none of the images change size after their settings are changed under `WooCommerce > Settings > Products > Display`:

![http://cld.wthms.co/nokHuu](http://cld.wthms.co/nokHuu+)

I did try the [Regenerate thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) plugin and that didn't help either.

@melindahelt tested this and had the same problem as well.

**Comment by jameskoster** [comment]
Remember this only resizes the source images for the thumbnails. It doesn't affect the size the images are displayed at on the front end.

I just tested this and didn't have any issues.

**Comment by mikeyarce** [comment]
@zwiesman31 I tested this out as well and the images did resize for me without problems.  Are you still seeing this issue and do you have any other steps to reproduce?

**Comment by tiagonoronha** [comment]
Also tested and didn't have any issues.

@zwiesman31 please test it again and let us know if you're still having issues. Closing for now!
