### ISSUE TITLE
Storefront's Widgets w/ Layered Nav's List Elements

### ISSUE THREAD

**Issue by BurlesonBrad** [woocommerce/storefront#652]
`
 .widget_recent_entries ul li, .widget_pages ul li, .widget_categories ul li, .widget_archive ul li, .widget_recent_comments ul li, .widget_nav_menu ul li, .widget_links ul li, .widget_product_categories ul li, .widget_layered_nav ul li, .widget_layered_nav_filters ul li {
    padding-left: 1.618em; 
}
`

**default** = 😱 
![image](https://user-images.githubusercontent.com/6208757/29745740-074b7180-8a89-11e7-89da-7fcc87f97732.png)
**padding removed=** 👍 
![image](https://user-images.githubusercontent.com/6208757/29745742-1662b0c0-8a89-11e7-9f29-d5fbf357e6c3.png)

**Comment by mikeyarce** [comment]
@BurlesonBrad do you get this on the latest `master` branch?  Here's what I'm seeing with just the regular layered nav widget:
<img width="293" alt="screen shot 2017-08-29 at 9 04 40 pm" src="https://user-images.githubusercontent.com/3220162/29854958-c6c515c2-8cfd-11e7-9ca0-cf1ac47c0716.png">

**Comment by tiagonoronha** [comment]
@BurlesonBrad update on this?

**Comment by BurlesonBrad** [comment]
It was https://woocommerce.com/products/ajax-layered-navigation/ running on the latest SF 
But, not seeing it anymore 👍 

_close_
