### ISSUE TITLE
Enhancement: Add context to "Add to Cart" link text

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/storefront#660]
From the WordPress Theme Review Requirements:
```
Links must avoid repetitive non-contextual text strings such as ‘read more…’ and should make sense if taken out of context. Bare urls must not be used as links. Supporting text may use a screen reader class to hide text visually.
```
`Add to Cart` does not really make sense taken out of context - we should add more context to these actions like `Add Pogo Stick to your cart` for example.

This would also apply to `Read More`, `View Products`, and `Select Options` which also would need additional context.

**Comment by jameskoster** [comment]
Yep. I've thought about this in the past. I think we should add this to core though, and wrap the additional copy in a `.screen-reader-text` span, imo. That way all users benefit, not just sf users! What do you think?

**Comment by mikeyarce** [comment]
I agree, core would be best!  Added in https://github.com/woocommerce/woocommerce/issues/16925
