### ISSUE TITLE
Enhancement:  Better Color Contrast

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/storefront#661]
I ran some contrast tests and found some areas that need better contrast:

Examples:
![screen shot 2017-09-22 at 2 59 54 pm](https://user-images.githubusercontent.com/3220162/30765932-ec6acb44-9fa6-11e7-9b87-437ddfccab7e.png)

![screen shot 2017-09-22 at 3 03 48 pm](https://user-images.githubusercontent.com/3220162/30766180-2f4ebce4-9fa8-11e7-9935-ebf4422d84b1.png)

List:
- Secondary Menu
- Current Page Item
- Sidebar
- Pagination (current page)
- Footer Credits
- Product Breadcrumbs
- Search Bar Placeholder
- Placeholder Images (that needs to be address in Core)

**Comment by jameskoster** [comment]
I'm fairly sure all of our color combos pass WCAG AA guidelines, but that doesn't mean they can't be improved. 

Looks like you're using the Chrome extension "Color Contrast Analyser", correct?

**Comment by jameskoster** [comment]
@mikeyarce Can we assign this to you for 2.3.0? Hoping to release in Q4.

**Comment by mikeyarce** [comment]
Yup that's fine. Thanks!
