### ISSUE TITLE
IE/Edge compatibility

### ISSUE THREAD

**Issue by senff** [woocommerce/storefront#663]
The theme demo that is shown at https://demo.woothemes.com/storefront  looks great and functional in IE/Edge.

However, the one that's showcased at https://wp-themes.com/storefront/ (following the "info" link from Calypso) is not working properly in IE/Edge at all, like most CSS is missing.

I'm not sure what the difference is between the two, but for some users, it appears the second (bad) one is what gets applied to their sites.

**Comment by jameskoster** [comment]
The second link is the WordPress.org theme preview. I'm not seeing any missing CSS there. Perhaps it was a temporary issue.

**Comment by senff** [comment]
There's no actual CSS missing (I think), but it looks that way. This is how it looks:

CHROME: http://prntscr.com/gqccjb
IE: http://prntscr.com/gqcd1s
EDGE: http://prntscr.com/gqcleo

It looks like IE does not recognize the various HTML5 tags properly, although they should:
http://prntscr.com/gqcm7q

**Comment by jameskoster** [comment]
That screenshot absolutely suggests that html5 elements aren't rendering correctly. As for why that's happening, I have no idea. Have you checked any other Storefront installs to see if this is only happening on the .org demo site? Are other theme demos similarly affected?

**Comment by senff** [comment]
Whenever I go to any site with the Storefront theme, my IE jumps automatically into IE7 emulation mode, which explains why the HTML5 tags are not being rendered.

I'm not sure why, I don't see anything in the code that stands out.

**Comment by jameskoster** [comment]
That's very strange. But there's nothing in the code that would force that behaviour and I've not seen this reported elsewhere. Any ideas @tiagonoronha ?

**Comment by senff** [comment]
Plot twist: seems it's only on two of my Windows computers, but not the third. All have the same version of IE.

**Comment by jameskoster** [comment]
Does the same thing happen to any other demos on wp-themes.com?

**Comment by tiagonoronha** [comment]
@senff is this still a thing?

You never actually mentioned the versions of IE that are affected by this issue.
