### ISSUE TITLE
Checkout - Issue with fixed position right hand column

### ISSUE THREAD

**Issue by kellyscholey** [woocommerce/storefront#666]
Hi,

I noticed an issue with the fixed right hand column on the checkout. When you scroll down and the right hand column becomes fixed it ends up obstructs the footer. 

![screen shot 2017-10-02 at 16 54 55](https://user-images.githubusercontent.com/7869279/31086709-73a7ee5a-a792-11e7-8030-a7187ab3dea4.png)

Are there any plans to fix this anytime soon? 

Thank you,
Kelly

**Comment by jameskoster** [comment]
We're planning to remove this feature for the next major release :) https://github.com/woocommerce/storefront/issues/637
