### ISSUE TITLE
How to change "New In" Text to "New Arrivals" on Homepage

### ISSUE THREAD

**Issue by Yeadh** [woocommerce/storefront#667]
I want to change "New In" Text to "New Arrivals" on Homepage but can't .
Please Help

**Comment by tiagonoronha** [comment]
Hi @Yeadh,

You can use Filters to change the text here: https://github.com/woocommerce/storefront/blob/master/inc/storefront-template-functions.php#L606-L610

To learn more about Filters please read: https://developer.wordpress.org/reference/functions/add_filter/

GitHub is not for support. If you have further questions, please post on the WordPress.org support forums: https://wordpress.org/support/theme/storefront/

Thank you!
