### ISSUE TITLE
CSS for Smart Coupons

### ISSUE THREAD

**Issue by SirDarcanos** [woocommerce/storefront#67]
Can you add some CSS for smart coupons?
This is how looks the checkout when purchasing a gift certificate: http://cld.wthms.co/U5ZP

Also it would be great to have the coupons styled properly when using this plugin: http://cld.wthms.co/1iBSA

**Comment by yeasinalam** [comment]
> Can you add some CSS for smart coupons?
> This is how looks the checkout when purchasing a gift certificate: http://cld.wthms.co/U5ZP
> 
> Also it would be great to have the coupons styled properly when using this plugin: http://cld.wthms.co/1iBSA

I Have this problem, how I short out it?
