### ISSUE TITLE
display mobile layout on 768px-wide screen

### ISSUE THREAD

**Issue by louisdoe** [woocommerce/storefront#670]
Hi

I developed a child theme from Storefront.

But I need the mobile layout (mobile burger menu, etc) to display on 768px-wide screens.

I tried this

```
// Change Woocommerce css breaktpoint from max width: 768px to 767px  
add_filter('woocommerce_style_smallscreen_breakpoint','woo_custom_breakpoint');
function woo_custom_breakpoint($px) {
  $px = '769px';
  return $px;
}
```

but it doesn’t work.

I tried to change $desktop: 768px; to $desktop: 769px; in _variables.scss in storefront files, but it doesn’t work.

Can you help me achieve that?

Thanks

**Comment by louisdoe** [comment]
Ok just changed the breakpoint in _variables.scss and recompiled everything using grunt.
But a hook would be nice.

**Comment by mikejolley** [comment]
Variable probably could be added, but for now it's possible through the scss. Can reopen if more feedback comes in for the same.

**Comment by ChrisColotti** [comment]
This is in fact simply not working.  If you test in chrome AT exactly 768 wide you get desktop mode.  if you drop to 767 you get mobile.  I am not sure exactly why this is happening and is not honoring the 768 width other than it's using min-width vs max-width, but iPAD is exactly 768 in portrait mode so it's an ugly desktop mode.  How is the easy way to change this or can the original theme be set to properly honor the true 768 exact width?  This seems like SOP to me for a theme.

**Comment by specktator** [comment]
I'm facing the same issue. I strongly believe that storefront, as a parent/base theme, should have/follow a more precise (and developer-friendly) break-point strategy, like [boostrap](https://getbootstrap.com/docs/4.1/layout/overview/#responsive-breakpoints), in order to help developers create responsive themes and being able to tweak for their needs accordingly.
