### ISSUE TITLE
Sensei lessons show breadcrumbs

### ISSUE THREAD

**Issue by aheckler** [woocommerce/storefront#671]
If I have Sensei set up on a Storefront site, it shows me breadcrumbs in lessons:

<img width="499" alt="screen shot 2017-10-18 at 11 41 04 am" src="https://user-images.githubusercontent.com/5512652/31728043-3cc32cec-b3f9-11e7-8f37-aacd5dec90cc.png">

We should prevent this from happening since Sensei lessons are not meant to be access via archive pages.

Related: https://github.com/Automattic/sensei/issues/1650

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18356
