### ISSUE TITLE
Blog Posts seem to be missing some structured data for Google

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/storefront#676]
**Ticket:** 771558-zen

One of our customers reported that Storefront was missing some structured data from blog posts like author, description etc and after testing this would seem to be the case.

<img width="836" alt="puk4k1" src="https://user-images.githubusercontent.com/1190565/32489252-3eeed06c-c3a7-11e7-9d46-e79b2cd4793a.png">

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/issues/620#issuecomment-313629032
