### ISSUE TITLE
square placeholder causes misalignment on catalog images of a different ratio....

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#677]
All my images are a 3:2 ratio, but when displaying Storefront's default 1:1 placeholder (because no image assigned), the product image sizes are vastly misaligned.

See:
![misalignment](https://user-images.githubusercontent.com/30901407/32590096-7bc1d968-c4e6-11e7-90c2-67089269dae6.jpg)

I'd suggest the placeholder should default to the ratio set in the WooCommerce >Settings > Products > Display > Catalog Images.

**Comment by jameskoster** [comment]
@GlennMartin1 the placeholder comes from WooCommerce, not Storefront. 

You can use the `woocommerce_placeholder_img_src` filter to change it to something custom :)
