### ISSUE TITLE
Storefront Mobile Product Viewer

### ISSUE THREAD

**Issue by stonen12** [woocommerce/storefront#681]
On the mobile version of my storefront themed site, instead of being able to zoom and select different product images while staying on the same product page, it reloads the page to the image page when touching the image.  It works correctly on desktop, just not mobile.

**Comment by jameskoster** [comment]
That sounds like it might be a javascript error. Would you be able to share a link?

**Comment by mikejolley** [comment]
Closing due to lack of updates.
