### ISSUE TITLE
Background Image Cover on iOS

### ISSUE THREAD

**Issue by apermo** [woocommerce/storefront#682]
Steps to reproduce:

Define a background image

Set background preset to: fill (css: cover & fixed)

Test a site with "long" content (at least several screenheights length) on an iOS device

----

You will now see a distorted background image, if the content is long enough (archive page of blog with show full content enabled for example), you will barely see the image, as the pixels will be huge.

I will solve it in my childtheme, by adding a div that will be placed in the background, having 100vh,100vw as size, and containing the background image.

**Comment by jameskoster** [comment]
Doesn't this problem apply to all WordPress themes/sites?

**Comment by apermo** [comment]
Yes, it probably applies to all themes, that use

```
body.custom-background {
    background-color: #f9f9f9;
    background-image: url(http://path.to./wp-content/uploads/2017/11/bg-image.jpg);
    background-position: left top;
    background-size: cover;
    background-repeat: no-repeat;
    background-attachment: fixed;
}
```

If that's a WordPress/Customizer default, it can be closed here, and I will reopen it as ticket on the WordPress/Customizer ticket system.

**Comment by apermo** [comment]
https://core.trac.wordpress.org/ticket/42544#ticket

Created ticket on trac.
