### ISSUE TITLE
Cart table overflowing container

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/storefront#683]
Just before the mobile breakpoint, the `table.cart` overlfows into the sidebar:
![screen shot 2017-11-15 at 11 51 44 am](https://user-images.githubusercontent.com/3220162/32857071-8cd8ff3c-c9fb-11e7-8855-0b0c25c747db.png)

Possible solution is just to apply a `table-layout: fixed;` to the `table.cart` but then that makes each row an equal size which is not ideal:

![screen shot 2017-11-15 at 11 53 46 am](https://user-images.githubusercontent.com/3220162/32857104-ad9c71ea-c9fb-11e7-9ca8-ef16079e9bfb.png)

We could also set widths for each row, which would solve that problem.

Alternatively, we could break the sidebar down earlier in the screen width.  Or, we could show the mobile cart earlier by changing the smallscreen-css breakpoint.

Thoughts @jameskoster @tiagonoronha ?

**Comment by jameskoster** [comment]
Hmm, I think we should just decrease the table padding a bit when;

1. The cart page is not using the full width template
2. Viewport is larger than the mobile switch
3. Viewport is small enough to cause this awkward display

**Comment by mcsmithers** [comment]
I can fix this.  I am assuming it's in the 'woocommerce.css' or the `woocoomerce-smallscreen.css`, right?

**Comment by mcsmithers** [comment]
I think I found a fix to this.  If you use Storefront from WooCommerce and use it with out-of-the -box themes such as TwentySixteen or TwentyFifteen, the CSS rules conflict with each other.  I adjusted the storefront to have a little more padding on the right sidebar so things look tidier though when combined with other themes, you may see some overlap.
