### ISSUE TITLE
Missing .org friendly readme

### ISSUE THREAD

**Issue by pattonwebz** [woocommerce/storefront#684]
Hi,

Someone in Theme Review slack channel at .org today noticed the latest version of the Storefront theme available in the .org directory does not include a readme file at all. There used to be a compatible one which the information on the theme information page is parsed from in a previous version (1.5.2 and below).

**A readme is not a requirement** however sometime in the near future an updated readme format will be required and as such I wanted to suggest that one following the new format is added sometime before that happens so that the directory is able to get the info about your theme easily.

The current directory (and the future changes) is able to parse one that's provided in either `.txt` format or `.md` format. I believe that preferably a .txt would be used however it's capable of working with .md too. Here's a link to some notes regarding the format. https://make.wordpress.org/themes/2017/07/06/upcoming-directory-changes/

Note that there is not a planned date for this change however with plugins directory already having the update and some time to work through issues once those issues are worked out it will be deployed for theme directory too.

If you would like I could provide a PR with a suggested format, just let me know if that would be useful.

**Comment by tiagonoronha** [comment]
@pattonwebz PRs are welcomed :)

Thanks for the heads up!

**Comment by pattonwebz** [comment]
Happy to help :) PR will be incoming then in the next few days.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/storefront/pull/723
