### ISSUE TITLE
Loading child theme version when enqueue style

### ISSUE THREAD

**Issue by Eugenii10** [woocommerce/storefront#686]
Hello!
At present Storefront doesn't look for and insert child theme version when enqueue it's stylesheet in the [class-storefront.php](https://github.com/woocommerce/storefront/blob/89e9d3bdbf31900dc853154efbdb943b7e66eb6c/inc/class-storefront.php#L258):
```php
wp_enqueue_style( 'storefront-child-style', get_stylesheet_uri(), '' );
```
So every time when I update my child theme style.css, I need to clean my browser cache (the whole or particularly for the page) to see changes.
Is it intentional? If so, could you tell please the reason of that? Thanks!
To bypass that I had to overload the entire Storefront class in my child theme functions.php with only one line changed to:
```php
wp_enqueue_style( 'storefront-child-style', get_stylesheet_uri(), '', wp_get_theme(get_stylesheet())->get('Version') );
```

**Comment by jameskoster** [comment]
No reason, we should add that :)
