### ISSUE TITLE
Date Picker in Storefront theme doesn't highlight for Bookings

### ISSUE THREAD

**Issue by LaurenaRehbein** [woocommerce/storefront#688]
Using Storefront with Bookings, there is a styling that overrides the visual indication of a chosen date. 

To recreate: 

Set up a site with the Storefront theme, and a Bookings product. Visit the product page, and try to choose a date. Note there is no visual indication of date chosen: 

![http://cld.wthms.co/hBxNZc](http://cld.wthms.co/hBxNZc+) 

When I inspect this page I see: 

```
.wc-bookings-date-picker .ui-datepicker td.bookable a {
    background-color: #96588a !important;
}
```

When I disable this in the Chrome inspector, it is then clear that I am looking for Bookings on the 22nd: 

![http://cld.wthms.co/sq5F4i](http://cld.wthms.co/sq5F4i+)

**Comment by stephhjacq** [comment]
reported again in 834638-zen
