### ISSUE TITLE
Store Notices: Links in notice text get right-aligned with Dismiss button

### ISSUE THREAD

**Issue by allendav** [woocommerce/storefront#691]
i.e. this

<img width="1196" alt="screen shot 2017-12-01 at 11 29 35 am" src="https://user-images.githubusercontent.com/1595739/33499830-783d75e8-d68b-11e7-83e9-ec25f8a2f3b0.png">

renders as

<img width="1218" alt="screen shot 2017-12-01 at 11 29 11 am" src="https://user-images.githubusercontent.com/1595739/33499840-812d379c-d68b-11e7-8846-592ab3c00107.png">

Observed with Storefront 2.2.5

**Comment by allendav** [comment]
ty @tiagonoronha !

**Comment by christnp** [comment]
This still seems to be a bug... was there a work around?

**Comment by haszari** [comment]
Hi there @christnp - this fix hasn't been released yet: https://github.com/woocommerce/storefront/releases

**Comment by christnp** [comment]
Ah, got it! The ticket was a couple of years old so I thought perhaps it
had been addressed and I was doing something wrong. Do you anticipate a fix
in the near future?

**Comment by haszari** [comment]
> Ah, got it! The ticket was a couple of years old so I thought perhaps it
had been addressed and I was doing something wrong. Do you anticipate a fix
in the near future?

Sorry @christnp I misread the date on the fix commit above. I've tested this and I can't reproduce the issue: 

<img width="1189" alt="Screen Shot 2020-01-20 at 11 08 16 AM" src="https://user-images.githubusercontent.com/4167300/72689338-2ff4b480-3b75-11ea-9c3b-84ed48dc1e27.png">

If this issue is still a problem, can you report as a new issue with reproduce steps?  Thank you :)

**Comment by jleo2095** [comment]
> > Ah, got it! The ticket was a couple of years old so I thought perhaps it
> > had been addressed and I was doing something wrong. Do you anticipate a fix
> > in the near future?
> 
> Sorry @christnp I misread the date on the fix commit above. I've tested this and I can't reproduce the issue:
> 
> <img alt="Screen Shot 2020-01-20 at 11 08 16 AM" width="1189" src="https://user-images.githubusercontent.com/4167300/72689338-2ff4b480-3b75-11ea-9c3b-84ed48dc1e27.png">
> 
> If this issue is still a problem, can you report as a new issue with reproduce steps? Thank you :)

Hi @haszari  can I look at the source code for the link you have created? I was trying to do something similar but it also creates a button like same with Dismiss

**Comment by haszari** [comment]
> Hi @haszari can I look at the source code for the link you have created? I was trying to do something similar but it also creates a button like same with Dismiss

Sorry @jleo2095 - that site is long gone now.

I'm guessing I had something like this for my store notice:

```
This is a demo store for testing purposes. <a href="http://testsite.com/blog">Blog is here</a>.
```
