### ISSUE TITLE
Hcard author info missing

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/storefront#692]
See: https://kb.yoast.com/kb/fixing-hcard-author-error/

Current output: 

```
<img alt=''"/>
<div class="label">Written by</div>
<a href="#" title="Posts by Author" rel="author">Author Name</a>
</div>
```

Coming from: https://github.com/woocommerce/storefront/blob/1790927f8cab022bc96847fb0efc4f2f2ff6b2aa/inc/storefront-template-functions.php#L426-L431

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/storefront/pull/724
