### ISSUE TITLE
product image doesnt work

### ISSUE THREAD

**Issue by runningjohan** [woocommerce/storefront#694]
Hi,

on my product page I like to add a product image.. this function is not working any more here.
Image gallery still works but after publishing I dont see any image.

The problem is that I can not make any new product page any more because I can not set a product image!

please have any one a solution?

**Comment by jameskoster** [comment]
Please post support queries on the [WordPress.org support forums](https://wordpress.org/support/theme/storefront). This is likely a plugin conflict.
