### ISSUE TITLE
Disabling or deleting Primary Menu in Storefront Customizer triggers call to wp_page_menu()

### ISSUE THREAD

**Issue by travisaxton** [woocommerce/storefront#695]
**Steps to reproduce the issue**
1. Run fresh install of WordPress 4.9.1 with the Storefront theme enabled.
2. Click on Customize->Menus->Primary Menu
3. Disable or delete the Primary Menu.

**Expected behavior**
When I disable or delete the primary menu, I expect to see a blank space where the primary menu used to be. 

**Actual behavior**
Instead, the menu is replaced by a list of page links. The page links that appear are the 9 default pages from Storefront's theme (About, Blog, Cart, Checkout, etc.).

**Isolating the problem**
This is a problem for users that do not wish to use the Primary Menu on all or part of the website. I think the problem is with **storefront_primary_navigation()**. Within this function, a call to wp_nav_menu() triggers the fallback_cb option because the primary menu is blank and/or deleted. The default for fallback_cb is to call wp_page_menu() which then fills the blank menu with a list of page links.

**Comment by jameskoster** [comment]
This is actually a feature xD

The Theme Review guidelines always required a fallback to display a list of page links if a menu wasn't assigned to the main location. I'm not sure if that's still the case but if so there's not much we can do here.

**Comment by travisaxton** [comment]
Thanks for the information and sorry about that. Makes perfect sense.

**Comment by jameskoster** [comment]
@tiagonoronha we might consider making the args on `wp_nav_menu()` filterable so that folks can remove the callback via child theme/plugin?

**Comment by ghost5egy** [comment]
1 - create main menu 
2 - assign it to Primary Menu
3 - assign it to Handheld Menu
it worked for me
