### ISSUE TITLE
Logo: SVG could not be added

### ISSUE THREAD

**Issue by gaertnert** [woocommerce/storefront#696]
When selecting a logo in format SVG the dialog "Crop image" apears.

There is only the button "Crop Image" which of course only works for pixel graphics.
Could you disable the "Crop Image" dialog for selected vector graphics (SVG) and take the selected graphic as it is?

**Comment by jameskoster** [comment]
This is a WordPress issue rather than a Storefront issue. Probably best to post this on the [WordPress.org support forums](https://wordpress.org/support/forums/).

**Comment by gaertnert** [comment]
Ok. Now I searched for this issue. You can extend your function.php so that the crop can be skipped.
Simply add this code:

add_action( 'after_setup_theme', 'svg_theme_support', 11 );
function svg_theme_support() {

	remove_theme_support( 'custom-logo' );

	add_theme_support( 'custom-logo', array(
		'flex-width'  => true,
		'flex-height' => true,
	) );

}
