### ISSUE TITLE
CSS: -moz-osx-font-smoothing and -webkit-font-smoothing should be removed

### ISSUE THREAD

**Issue by ElectricFeet** [woocommerce/storefront#698]
I just spent a long time trying to figure out why Storefront displays my fonts differently to &mdash;  and worse than &mdash; other themes (on a 5K iMac). I tracked it down to the `-moz-osx-font-smoothing: grayscale;` and `-webkit-font-smoothing: antialiased;` settings for `body` in style.css.

These settings are non-standard with [no future ahead of them](https://caniuse.com/#feat=font-smooth) (and no past or present, either, unless you're using OSX).

While some people (specifically those who have modified their sites to have white text on a dark background) may find them useful, for the vast majority they are not a good idea.

Reasons to take them out:

1) `-moz-osx-font-smoothing` and `-webkit-font-smoothing` are non-standard, are not supported on most operating systems and [MDN web docs recommend](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth): 

> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

2) They introduce discrepancies between what you see in OSX and what you see in other operating systems (as they are only supported on OSX). This makes life harder for the developer (e.g. extra testing on different operating systems) and may cause confusion for clients.

3) It actually makes things worse for most of the Storefront dark-on-light text rendering (the Storefront defaults). More detail on this in the article [Please Stop “Fixing” Font Smoothing](http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/). tldr: It fuzzies your fonts.

4) With the advent of retina screens (especially in these settings' target audience of OSX), a lot of this has become moot anyway, as the pixel-perfect rendering of fonts needs no "improvement". All it ends up doing it making the font thinner, creating less contrast and making it less easy to read. (This is my use-case &mdash; a 5K iMac.) If people _do_ want a thinner font, they can install a thinner font, not try to "thin" a thicker one.

5) Anyone that might see an improvement (the light font on dark background people) can put them in their own additional CSS.

Reading back, I see that a list like this is pretty damning (and aggressive :/ ) I'd be interested if there's a counter-list anywhere, and whether this is really such a slam-dunk as it seems :)

Woocommerce also use these settings, so an issue would need opening there too. Though it's only in the back-end, as far as I can see, so not as important.

**Comment by jameskoster** [comment]
Yeah this is pretty old code. No objections to removing it from me :)
