### ISSUE TITLE
Product page scrolling to the right using Trackpad in Chrome

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/storefront#704]
When viewing the following product: https://demo.woothemes.com/storefront/product/lowepro-slingshot-edge-250-aw/

When this is viewed on Chrome in Ubuntu, using a trackpad with 2 finger scrolling. You can scroll to the right which causes page content to move to the left.

![Screenshot](https://cloudup.com/cTz9yr0ZxPx+)

This only happens with the demo store banner visible. Which is positioned in a fixed position. When this banner is dismissed, you can no longer scroll left.

It seems to be a conflict with the negative margins used in the breadcrumb and navigation headers. So it adds some additional white space to the right of the main content.

Affected ticket: 865845-zen

**Comment by tiagonoronha** [comment]
Possibly related to https://github.com/woocommerce/storefront/pull/612

**Comment by mikejolley** [comment]
Fixed by https://github.com/woocommerce/storefront/commit/3b5c6da496da5a2bf3bc39a8c433362a968f8a21
