### ISSUE TITLE
Mega menu timeout in customizer

### ISSUE THREAD

**Issue by el-presidente** [woocommerce/storefront#714]
I know this is the repo for the theme but I'll let you know anyway that I'm experiencing timeouts when using the mega menu in the customizer. The customizer breaks down and it is not possible to save or publish. I've disabled all plugins and the issue still persists and in my cPanel error log I get a 406 file not found. 

![screen shot 2018-01-05 at 11 11 29](https://user-images.githubusercontent.com/937382/34604841-8df50600-f209-11e7-89d4-8eba80274663.png)
![screen shot 2018-01-05 at 11 10 24](https://user-images.githubusercontent.com/937382/34604842-8e101508-f209-11e7-9433-782dc46b131d.png)
![screen shot 2018-01-05 at 11 10 01](https://user-images.githubusercontent.com/937382/34604843-8e2a3fc8-f209-11e7-9434-fa683e22aad9.png)

**Comment by mikejolley** [comment]
> I know this is the repo for the theme

Then it shouldn't really be logged here. Please use the helpdesk for extension issues. We'll need some help reproducing this and may need access to the site in question. Thanks.
