### ISSUE TITLE
Checkout sticky payment not working when the checkout page change size with JavaScript

### ISSUE THREAD

**Issue by jesucarr** [woocommerce/storefront#719]
I have a plugin that loads the checkout page with some elements hidden and then shows them up. In your checkout.js you assume the height will be always the same as when loaded, so it doesn't work correctly. The fix is simple: move the 2 first lines where you store the heights values inside the stickyPayment function so it gets updated. I'll submit a PR shortly.

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/720
