### ISSUE TITLE
Default Product search box in header not RTL friendly

### ISSUE THREAD

**Issue by formosattic** [woocommerce/storefront#721]
The search widgets added through the customizer are RTL friendly, but not the default Storefront product search in the header.

RTL needs to be applied to the magnifying glass.

<img width="861" alt="screen shot 2018-01-09 at 16 36 40" src="https://user-images.githubusercontent.com/15944096/34711717-5406b056-f55b-11e7-8db0-daf0b5b23fa1.png">

Site stats:

- WooCommerce 3.2.6
- Storefront 2.2.5

889361-zd-woothemes

**Comment by jameskoster** [comment]
@formosattic we've fixed some RTL issues but not deployed them yet. Are you able to test this against the `master` branch?

**Comment by mikejolley** [comment]
Confirmed fixed in 2.2.6/master.
