### ISSUE TITLE
WPML (WooCommerce Multilingual) currency switcher

### ISSUE THREAD

**Issue by amitkvint** [woocommerce/storefront#725]
* Currency switcher doesn't sync with currency symbol in the shopping cart in Storefront

Steps to replicate:
1) Install WPML, WooCommerce Multilingual, WooCommerce, Storefront theme
2) Activate multicurrency, add some new currency 
3) Add the currency switcher to the widget area
3) Go to the homepage and change the currency 
5) You see the new currency in the mini cart during the page loads only, afterward, the previous one appear 

**Note! - Sometimes the currency sticks to the second currency EVEN if WPML and WCML are deactivated**

Seems to be coming from here: I was able to replicate on the fresh installation. There's incompatibility in function storefront_cart_link_fragment() in wp-content/themes/storefront/inc/woocommerce/storefront-woocommerce-template-functions.php:49

    function storefront_cart_link_fragment( $fragments ) {
        global $woocommerce;

        ob_start();
        storefront_cart_link();
        $fragments['a.cart-contents'] = ob_get_clean();

        ob_start();
        storefront_handheld_footer_bar_cart_link();
        $fragments['a.footer-cart-contents'] = ob_get_clean();

        return $fragments;
    }

That's being called by a hook in wp-content/themes/storefront/inc/woocommerce/storefront-woocommerce-template-hooks.php:77

        add_filter( 'woocommerce_add_to_cart_fragments', 'storefront_cart_link_fragment');

We were unable to find a workaround

**Comment by amitkvint** [comment]
last thing we noticed - when you log out in a new tab and I use ob_get_flush() instead of ob_get_clean(), it works fine.

**Comment by tiagonoronha** [comment]
@amitkvint Hi! WooCommerce stores the fragments into sessionStorage on the browser. The fragment will only be updated if a new product is added or removed from the cart. 

You can clear the fragment via JavaScript, like so:

```
$( document.body ).trigger( 'wc_fragment_refresh' );
```

This is probably something your plugin should be doing after a currency change.

**Comment by amitkvint** [comment]
This was fixed by the development team as suggested.
