### ISSUE TITLE
product Lightbox image count

### ISSUE THREAD

**Issue by bigmadness** [woocommerce/storefront#730]
Hi is there any setting or problem with product  lightbox image?

**Comment by bigmadness** [comment]
![screen shot 2018-01-17 at 9 24 26 am](https://user-images.githubusercontent.com/10583985/35024552-3f72688e-fb68-11e7-9308-5ffa4063ad55.png)
![screen shot 2018-01-17 at 9 24 16 am](https://user-images.githubusercontent.com/10583985/35024551-3f31eb92-fb68-11e7-84c0-83cf9fa699ba.png)
![screen shot 2018-01-17 at 9 24 52 am](https://user-images.githubusercontent.com/10583985/35024570-51ce1780-fb68-11e7-9582-2e452839107e.png)

**Comment by tiagonoronha** [comment]
I don't see this issue in your site, have you solved it? http://woocommerce.themeness.com/product/ship-your-idea-3/
