### ISSUE TITLE
Sticky Header CSS results in header disappearing with Chrome

### ISSUE THREAD

**Issue by tommyshellberg** [woocommerce/storefront#732]
If you add the following CSS to make the header sticky:

```
#masthead {
		position: fixed;
		top: 0;
		width: 100%;
}
```
The header disappears when viewing the site from Chrome. After further inspection, for some reason the `left:` position is set to a huge negative amount(in my case -1400):

http://cld.wthms.co/b1OrGI

A temp fix is to define `left:0` but I'm wondering if we can prevent this from happening in the future.

**Comment by tiagonoronha** [comment]
I honestly don't see how this is a bug, seems like an issue resulting from a customisation. I also don't see the `-1400px` left position value you reported.

Do you have a link?
