### ISSUE TITLE
The itemprop attribute was specified, but the element is not a property of any item.

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/storefront#733]
User in live chat reported the above error message, which can be found at the bottom of [Validator W3 Report](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.herbalinea.com%2F)

![](http://cld.wthms.co/VXMSre+)Image Link: http://cld.wthms.co/VXMSre

User tested on Storefront 2.2.6 and I confirmed same issue with 2.2.5

**Comment by tiagonoronha** [comment]
This is a WordPress core issue: https://core.trac.wordpress.org/ticket/37305
