### ISSUE TITLE
Storefront 2.2.6, missing Woocommerce image sizing

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/storefront#736]
Using a clean install of Woocommerce 3.3 RC1 and Storefront, with 2.2.5, I see the image sizing in the Customizer:
<img width="301" alt="grafik" src="https://user-images.githubusercontent.com/25877146/35105234-67287cd4-fc6b-11e7-8f6e-f5ba9f41f795.png">

After updating to 2.2.6, those settings are missing:
<img width="302" alt="grafik" src="https://user-images.githubusercontent.com/25877146/35105370-cd8502cc-fc6b-11e7-9703-62df49729830.png">

**Comment by mikejolley** [comment]
Storefront sets these values for you to something which works for the layout. Themes which define sizes have these options hidden on purpose.
