### ISSUE TITLE
Missing srcset for product images

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/storefront#737]
Logged here https://github.com/woocommerce/woocommerce/issues/18501

srcset is missing for product thumbnails. Since users can control the columns we should probably add some, including retina x2 sizes.

This is how it's done in 2016 https://github.com/WordPress/WordPress/blob/aaf99e691391cfceb004d848450dbbf3344b1bee/wp-content/themes/twentysixteen/functions.php#L382-L414

If you inspect images on the shop page in 2016 you'll see srcset attributes. There are none in storefront.

@tiagonoronha Can we fix this before 3.3 releases?

**Comment by tiagonoronha** [comment]
Turns out this is a WooCommerce core issue. PR submitted: https://github.com/woocommerce/woocommerce/pull/18564
