### ISSUE TITLE
Negative Margin Full-Width Hack Causing Horizontal Scroll in Safari (Mac) After Updating to 2.2.6

### ISSUE THREAD

**Issue by JamesJosephFinn** [woocommerce/storefront#738]
I have a testing environment here in which I've deactivated my customizations:

[test.cloudchemistry.co](https://test.cloudchemistry.co/)

To recreate the issue:

1. First, visit a product page, the blog, or anywhere with breadcrumbs. Negative margin applied to `.woocommerce-breadcrumb`, plus `99em` of left/right padding, is causing a horizontal scroll.
2. Next, on the homepage, negative margin applied to `.sprh-hero` is also causing horizontal scrolling. This CSS class belongs to the *StoreFront Product Hero*, a *StoreFront PowerPack* official extension. If you confirm the bug, please open this ticket on WooCommerce.com for me. Rather than file duplicate tickets, I thought I'd start here first, as my intuition tells me this is related to the theme update.

**Comment by tiagonoronha** [comment]
This commit is the issue: https://github.com/woocommerce/storefront/commit/3b5c6da496da5a2bf3bc39a8c433362a968f8a21

I will revert this change.

**Comment by JamesJosephFinn** [comment]
👍 thanks guys!
