### ISSUE TITLE
Front page styling adds undesired padding when no featured image is used

### ISSUE THREAD

**Issue by Clorith** [woocommerce/storefront#745]
The scenario uses the Hero unit plugin as an example, as it's easier to demonstrate with something expecting media to be displayed.

Remove fields above the hero unit on the front page to make it appear at the top of the page under the heading.
There's now a whitespace area between the hero unit and the header section of your site.

This is caused by the themes styling explicitly adding a padding unless there's a featured image.

```
.page-template-template-homepage:not(.has-post-thumbnail) .site-main {
    padding-top: 4.235801032em;
}
```

Storefront version 2.2.6

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/issues/673
