### ISSUE TITLE
ALL storefront product templates midding ALT attribute for featured image. 

### ISSUE THREAD

**Issue by PortalPacific** [woocommerce/storefront#753]
The alt attribute is missing for featured images in storefront. At first I thought I was losing my mind trying to figure out what was conflicting, than i checked your demo's and they have the same problem.

Featured product images have NO ALT tags... This is kinda.. horrible lol 

How do i fix?

Thanks! <3

**Comment by tiagonoronha** [comment]
Hi! In most of our demo products, an alt tag isn't set. However, if you add the alt text to the image, it does show up: 

![screen shot 2018-02-05 at 12 02 14](https://user-images.githubusercontent.com/1177726/35803666-8c32a2f2-0a6c-11e8-8745-99ed6f075c48.png)

![screen shot 2018-02-05 at 12 03 48](https://user-images.githubusercontent.com/1177726/35803712-af0a5cfc-0a6c-11e8-9cc9-41acf0fcc870.png)
