### ISSUE TITLE
Display issues with WooCommerce Memberships on mobile

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/storefront#754]
I tested this against Twenty Seventeen and the same behavior doesn't happen there so opening the issue here instead of on the Memberships repo.

Anyhow, Memberships content sections display poorly on mobile. e.g. something like this:
![see screen shot](http://cld.wthms.co/jvQac1+)

vs. Twenty Seventeen 
![see screen shot](http://cld.wthms.co/FCLZU0+)

**Comment by tiagonoronha** [comment]
Integration will be merged soon: https://github.com/woocommerce/storefront/pull/658

**Comment by jessepearson** [comment]
@tiagonoronha I just had a chat with this issue today, I can still replicate the above with the latest versions of Memberships and Storefront.

**Comment by ksministries** [comment]
WEv were just asked to try this today and it is still not fixed.

**Comment by tiagonoronha** [comment]
The fix is [here](https://github.com/woocommerce/storefront/pull/890) and will be released in Storefront 2.3.2 next week.

**Comment by ksministries** [comment]
We were just asked to try this today and it did not fix but made the user interface worse on top of not fixing the issue thanks

**Comment by ksministries** [comment]
I was just given this css to try in the customizer and it fixed our problem
                                                   
/* Storefront Memberships Mobile Tweek */

@media only screen and (max-width: 768px) { .woocommerce-account table.my_account_memberships { table-layout: auto; } }

**Comment by tiagonoronha** [comment]
Yes, that looks correct. :)

Glad it fixed your the problem you were having.
