### ISSUE TITLE
JP Infinite Scroll: Missing sorting options

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/storefront#757]
When Infinite Scroll is enabled, the shop archives lose the sorting/filtering options.

Either of these settings: http://cld.wthms.co/2syyDQ = no sorting: http://cld.wthms.co/64uCF2

With the first infinite scroll setting: http://cld.wthms.co/KwuniF

**Comment by WPprodigy** [comment]
NM https://github.com/woocommerce/storefront/blob/master/inc/jetpack/class-storefront-jetpack.php#L101-L116

**Comment by seanconklin** [comment]
I'd like to re-open this one. The sorting options flash briefly with Infinite Scroll enabled whereas we'd like them to remain at least at the top of the loop. Example URL: https://jinnybeyer.com/product-category/fabric/

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1073
