### ISSUE TITLE
Storefront not compatible with versions of PHP higher than 7.2

### ISSUE THREAD

**Issue by zandyring** [woocommerce/storefront#759]
As noted in this topic, PHP v 7.2 or higher will throw an error with Storefront and will result in a white screen:
https://wordpress.org/support/topic/php-error-262/

`Warning: Use of undefined constant REQUEST_URI – assumed ‘REQUEST_URI’ (this will throw an Error in a future version of PHP) in /nfsmnt/hosting1_1/d/5/d5dd81df-6f58-431d-8876-ca97006e1bdb/apartmanposta.sk/sub/shop/wp-content/themes/storefront/functions.php on line 73`

**Comment by tiagonoronha** [comment]
I'm running PHP 7.2 locally without any issues. There's also no `REQUEST_URI` in functions.php.

This must be a customisation issue.
