### ISSUE TITLE
Protect the house's Integrity 

### ISSUE THREAD

**Issue by BurlesonBrad** [woocommerce/storefront#769]
WC + PowerPack + New SF update _(2.2.8)_
Column options are now available in two spots when using PowerPack

One needs to have a **priority** over the other ❗️ 

Upon Update, when there is already a number of columns set in PowerPack, the new update breaks the store making problematic layout issues.

Moving forward, it would be substantially realistic to ask, anticipate, & have a minimal viable expectation that the Ninjas can -**INDEED**- run tests on WooCommerce's Storefront Theme within their own WooCommerce's Storefront Plugins _(like Storefront PowerPack)_ & 👉 **NO LONGER** 👈 need to rely on "community testing" for superficial, basic, top level, simpler compatibility tests within  
# WooCommerce's Own House ❗️  

So for all store owners who **HAVE** stayed within the "WooCommerce House" with Storefront and PowerPack & who have already set their rows, columns, and number of items.....

- The store(s) will now have jacked up ```/shop/``` & ```/product-category/``` pages
- And, they won't know it until they click update
- .....and neither of the two **(yes, TWO)** places to set the **SAME** option actually function correctly
- and, unless the "average store owner" using Storefront+PowerPack, has someone else _or_ self audits each update, then they won't even **spot** the error at all until/unless they visit their own ```/shop``` and ```/product-category/``` pages

[https://prnt.sc/iectbl](https://prnt.sc/iectbl)
![image](https://user-images.githubusercontent.com/6208757/36177798-761e8654-10dc-11e8-8fc0-33ac2b2325a8.png)
[https://prnt.sc/iecuwo](https://prnt.sc/iecuwo)
![image](https://user-images.githubusercontent.com/6208757/36177814-7f6b3392-10dc-11e8-8680-f5994a37d160.png)

It's only until **AFTER** the store owner runs back into their customizer, and makes **BOTH SETTINGS** 100% identical that their store goes back to what it was prior to the update.

Y'all have enough resources and every one of you are **much better than** this repeating cycle over and over again.

**Comment by tiagonoronha** [comment]
There's a Powerpack update coming to address this issue. :)

Thanks!
