### ISSUE TITLE
Sub-menus do not appear on tablets/mobiles/touch devices (UX issue)

### ISSUE THREAD

**Issue by optimusprimed** [woocommerce/storefront#770]
On tablets any sub-menu will not drop down, instead only leaving the top level menu to work. For example, if you create three product categories and place them under a "My Products" top-level menu, the categories will not drop down when the "My Products" menu item is clicked. This is a common UX problem on touch-screen designs. Please can this functionality be added (double tap solution etc).

**Comment by tiagonoronha** [comment]
I've just tested this on a tablet and everything is working as expected.

Please make sure you are using the latest version of the theme. If this is still an issue, please provide more information such as what device and browser you are using.
