### ISSUE TITLE
Add Storefront Footer Bar to core

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#773]
Would you consider also adding Footer Bar to core as well?

Lightweight, low-maintenance feature.

**Comment by jameskoster** [comment]
This feature is already in core ;P

**Comment by GlennMartin1** [comment]
Are we talking about the same thing?
https://woocommerce.com/products/storefront-footer-bar/

Without this plugin installed and active, there is no widget area called "Footer Bar."

**Comment by jameskoster** [comment]
Ah, sorry, I thought you were talking about the menu bar that appears on handheld devices.

**Comment by GlennMartin1** [comment]
Thanks for reopening!

I use this nifty widget area on 100% of my sites.

**Comment by tiagonoronha** [comment]
It's a possibility, but we haven't decided yet :)

**Comment by tiagonoronha** [comment]
We haven't seen any other requests for this feature, please continue using the plugin. Thank you!
