### ISSUE TITLE
Homepage content not showing in IE when featured image is set

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/storefront#775]
### What I expected

To set a Feature image in my homepage template, which adds a background behind the homepage content.

### What happens instead

The feature image and homepage content looks fine in Chrome, FF, and most other browsers:

![Screenshot](http://cld.wthms.co/qjGfAM+)
Screenshot: http://cld.wthms.co/qjGfAM

However, when I open the same page in IE 11, the text doesn't load for me at all:

![Screenshot](http://cld.wthms.co/noioqH+)
Screenshot: http://cld.wthms.co/noioqH

I can see there are some opacity: 0 styles set in IE but not in Chrome. These should probably be removed in JavaScript, but haven't found yet where that should be.

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/issues/775
