### ISSUE TITLE
accseability theme not support 

### ISSUE THREAD

**Issue by esmobg** [woocommerce/storefront#776]
double labeling of bottons in the main theme
dotted with a NVDA screen reader
and a web browser
firefox
IE 
Chrome

**Comment by jameskoster** [comment]
Hey, are you able to provide some more information?

> double labeling of bottons in the main theme

Which buttons? I ask because 99% of all the buttons come from WooCommerce or WordPress core.

> dotted with a NVDA screen reader

What is dotted? The buttons? What is "Dotted" in this context?

Thanks

**Comment by esmobg** [comment]
double bottling labeling in frontstore's main theme

**Comment by tiagonoronha** [comment]
@esmobg would you be able to tell us exactly which buttons are causing these issue for you?

We'd love to help, but we need more information.

**Comment by esmobg** [comment]
the screen reader reads twice the botons of the topic
somewhere in the code itself there are bottons twice described
and read eg home, home
shop, shop

**Comment by tiagonoronha** [comment]
This issue appears to be the same we are fixing on this PR: https://github.com/woocommerce/storefront/pull/1074

Closing.
