### ISSUE TITLE
Resize product thumbnails to fit larger screens

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/storefront#777]
Storefront sets the product page thumbnail width at `416px`, so it can't be changed in WooCommerce settings. At the same time the product gallery column width is `41.1764705882%;` which can be much more than 416px on larger screens. This in result leads to a gap between the thumbnail and the zoom button / product details:

![Screenshot](http://cld.wthms.co/y9nzhs+)
Screenshot: http://cld.wthms.co/y9nzhs

To get this solved we could either set larger thumbnails, or add an option for the store owner to change this size.

**Comment by tiagonoronha** [comment]
@madeincosmos can you share the url to the site?

**Comment by GlennMartin1** [comment]
https://schnittverhext.de/product/unkategorisiert/jersey-bunte-dreiecke-gruen/

**Comment by tiagonoronha** [comment]
That website is using Storefront Powerpack with the "max width" option, which sets the layout to 100%.

I'll open an issue on the Powerpack repository.
