### ISSUE TITLE
Padding shows up when using Parallax hero

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/storefront#780]
There's some CSS that adds padding when there is no featured image:

```
.page-template-template-homepage:not(.has-post-thumbnail) .site-main {
    padding-top: 4.235801032em;
}
```

However when you have a Parallax hero at the top, it is there:

![Screenshot](http://a.mikey.link/iU8DoK+)

We should probably remove the padding for Parallax and Product Heros.

**Comment by tiagonoronha** [comment]
This is an issue to be fixed in the extension. Closing...

**Comment by mikeyarce** [comment]
That works, too!
