### ISSUE TITLE
Jetpack Infinite Scroll tweaks

### ISSUE THREAD

**Issue by tiagonoronha** [woocommerce/storefront#781]
Update `posts_per_page` to respect the number of products per page set in the Customizer. For WooCommerce version under 3.3, we can keep `12` as a default number, or perhaps use the legacy `products_per_page` method somehow.

Figure out why the "load more" button shows one last time after all products have been loaded.

cc @jeffikus

**Comment by jeffikus** [comment]
@danieldudzic please follow this while I'm AFK next week. Thanks.
