### ISSUE TITLE
Parallax Hero doesn't scroll and background image only shows top part. Disappears completely if using full height.

### ISSUE THREAD

**Issue by akakqi** [woocommerce/storefront#783]
Hi, I'm having an issue with Parallax Hero.

1. It doesn't have the scroll effect at all and the image only shows top part. 
<img width="1423" alt="screen shot 2018-03-07 at 7 23 37 pm" src="https://user-images.githubusercontent.com/35842692/37126055-5306a54e-223d-11e8-9526-b4f277e78457.png">

2. And even what bothers me is if I click "Full Height“ under Hero Layout, it would disappear completely.
<img width="1425" alt="screen shot 2018-03-07 at 7 24 36 pm" src="https://user-images.githubusercontent.com/35842692/37126068-604081f8-223d-11e8-9631-2b239f5c9821.png">

Please help. Thanks a lot!

**Comment by tiagonoronha** [comment]
Parallax Hero is a separate extension. Please submit a ticket via the helpdesk instead: https://woocommerce.com/contact-us/

Thank you!
