### ISSUE TITLE
May I submit a wish for single product pages

### ISSUE THREAD

**Issue by ajgw** [woocommerce/storefront#784]
Hi Devs, you did a good job with Storefront. I use it on most of my sites, even if they do not have WooCommerce installed. But in case of WooCommerce there is on single product pages something wrong in case of design and usability, even if I use Storefront Powerpack.

In case we use product images at their dimensions they were upload without any cropping:

Stacking layout set to active by Storefront Powerpack lets product image move to top and display in full width of content area. As I tried this nice feature, div for image got wide but image showed up at smaller size and filled div approx. half the div. I see whole image but the loupe icon isn't placed anymore over image it stays on right of div.

I think it would be much better as WooCommerce Stacked Product Layout By SomewhereWarm did, as it leaves product title, price and some more on right of product image. This is nice in case we have a portrait image. But a portrait image in staked layout would show theoretically in full – we have heavily to scroll before we see any product data.

Many of us are photographers as I am. We like to show our images for sale and the image is the product. So, we like to show them as large as possible without slowing pageload down.

This exampe: I have shot a panorama image which is very wide but not tall. It was uploaded at 1000x200 px. In Storefront product images are displayed 600px width, this image becomes 120 px height! If I use stacked layout I would see much more from image. In this case stacked layout makes sense. But the image should displayed in large, not with default dimensions.

This example: I have a portrait image. This is 600x900 px and there I would to show it in default layout mode. With Storefront Powerpack it should be possible.

Another issue: I use often Product Bundles from SomewhereWarm. If I have few bundled items default layout may OK, but if I have many bundled items the stacked layout in the one I like to use. And there it should be possible to select a) show bundled items as list (default) or b) show bundled items as columns (this is nice for up to hundred bundled items – for example selling postcards, were the image is the product).

Any feedback is welcome. Thank you very much.

Regards, Adrian

**Comment by tiagonoronha** [comment]
@ajgw A new version of Powerpack, 1.4.6, was released yesterday as include a fix for the image behaviour you described. :)

As for issues related to other products, please contact us via our official channels and your request will be forwarded to the developer of the extension:

https://woocommerce.com/my-account/create-a-ticket/

Thanks!

**Comment by ajgw** [comment]
@tiagonoronha Thank you very much for the update and yes, it works. I am happy.
