### ISSUE TITLE
Unable to resize product page image

### ISSUE THREAD

**Issue by fishrice** [woocommerce/storefront#791]
Hi team, I tried everything. I tried edit the filter in "class-storefront.php"  with different values, but I am still unable to resize the product image.  Here's the code below with my values:  Please help, thanks!

`// Declare WooCommerce support.
			add_theme_support( 'woocommerce', apply_filters( 'storefront_woocommerce_args', array(
				'single_image_width'    => 600,
				'thumbnail_image_width' => 400,
				'product_grid'          => array(
					'default_columns' => 3,
					'default_rows'    => 4,
					'min_columns'     => 1,
					'max_columns'     => 6,
					'min_rows'        => 1
				)
			) ) );`

**Comment by tiagonoronha** [comment]
Hi! You can filter the image sizes with the following code: 

```
function my_theme_filter_image_sizes( $args ) {
	$args['single_image_width'] = 501;
	$args['thumbnail_image_width'] = 684;
	return $args;
}

add_filter( 'storefront_woocommerce_args', 'my_theme_filter_image_sizes' );
```

You should place this code in a child theme. Here's how you create one: https://docs.woocommerce.com/document/set-up-and-use-a-child-theme/
