### ISSUE TITLE
Menu items get cut out on mobile when the menu has a large number of items

### ISSUE THREAD

**Issue by fhaps** [woocommerce/storefront#798]
When accessing a site on mobile, if a menu has a large amount of items some of them will be cut out.

This was reported in 1033511-zd-woothemes and I was able to replicate on my site. When testing on my site the mobile menu could only handle 33 items out of a total 45.

On the user's site, the menu got cut off after 41 items – but they did seem to have less spacing between lines. This leads me to believe that the menu has a maximum length limit, and when this is reached items are not displayed.

I used the Chrome Inspector to record what it looks like, but also verified that it behaves in the same manner when on an actual mobile device.

GIF: http://cld.wthms.co/hxRAUI

**Comment by GlennMartin1** [comment]
Here's another site you can see with the same issue: https://www.hometownstructures.com/

Mobile shows 35 of 53 menu items.
