### ISSUE TITLE
Stacked Layout uses default product image

### ISSUE THREAD

**Issue by ajgw** [woocommerce/storefront#799]
I like Stacked Layout in case of using Composite plugin. But default product image is used, not a larger version. This gives us a default image on top left with a loupe for zooming on the right. It would be better if product image may fill whole area above product details. But in this case not the default image should be used – because it will get blurry upscaled –, it should use the original uploaded thumbnail. What do you think?

**Comment by tiagonoronha** [comment]
This repository is for Storefront related issues. Please submit an issue through the official channels, and the developer of this extension will get back to you:

https://woocommerce.com/my-account/create-a-ticket/

Thanks! :)
