### ISSUE TITLE
Store Notices are duplicated on cart and checkout pages, or displayed on incorrect pages

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/storefront#801]
This problem doesn't happen with Twenty Seventeen, so I'm posting it here rather in WooCommerce core repo.

### Steps to reproduce

1. In **WooCommerce > Settings > Shipping > Shipping Options** enable debug mode.
2. Add some non-virtual product to cart and open the cart page.
3. Observe the debug message is shown there twice:

![Screenshot](http://cld.wthms.co/x00MQz+)
Screenshot: http://cld.wthms.co/x00MQz

Proceed to checkout and observe the notice is duplicated there too (but in a bit different way):

![Screenshot](http://cld.wthms.co/rwF7eG+)
Screenshot: http://cld.wthms.co/rwF7eG

**Comment by sixsixninenine** [comment]
I'm seeing this too. I have overridden the `form-checkout.php `and `cart.php` templates, removing the call to the `wc_print_notices` function on line 23 for now.

**Comment by tiagonoronha** [comment]
Thanks for reporting! :) 

This is a WooCommerce issue: https://github.com/woocommerce/woocommerce/issues/19717
