### ISSUE TITLE
Body class of Author Archive page has margin-bottom set from .author class in style.css

### ISSUE THREAD

**Issue by opicron** [woocommerce/storefront#808]
I noticed an odd margin-bottom occuring on the Author Archive. 

It seems to originate from .author class which is added to body class on this page. 

.author class is declared on Storefront style.css version 2.2.8 line 33.

Added body.author override to fix for the time being.

**Comment by tiagonoronha** [comment]
A fix for this is already in master and will be available in Storefront 2.3. :)

https://github.com/woocommerce/storefront/issues/789
