### ISSUE TITLE
Images with ratio other than 1:1 are incorrectly cropped

### ISSUE THREAD

**Issue by alaczek** [woocommerce/storefront#809]
## Steps to replicate

@joelwills attempted to reproduce this in a test site and wasn't able to do so (see discussion ref below). Re-uploading the image seemed to help, although this issue seems to manifest in Firefox, not Chrome.

<img width="349" alt="necklace_crop1" src="https://user-images.githubusercontent.com/2912202/38463739-b68936f6-3b09-11e8-9b51-3dbfbee9cf6a.png">

## Result

From the user:

>_To recap_, the display of product images greater than a 1:1 ratio, with Storefront theme, utillizing woocomerce, is subject to improper framing. So the images can appear "cut off" or cropped. But when the framing problem automatically catches up with itself, corrects itself, the image becomes per expected, "normal". This appears to be a Firefox related problem as the wordpress technician using Chrome didn't have the problem.

>A related problem_ is that Firefox is showing some images as side-ways. So rotated 45 degrees. For example, go to our website homepage, display dewolf necklaces, scroll down to the coral masquerade necklace, and it appears side-ways (in Firefox, but not in Chrome). That product image appears side-ways in the media library also (using Firefox), but fine in Chrome.

## Expected

Uploaded images should be displayed consistently and, where cropped, cropped similarly for Firefox and Chrome.

<img width="310" alt="necklace_crop" src="https://user-images.githubusercontent.com/2912202/38463741-bfbdf126-3b09-11e8-909f-ddd193cbf502.png">

* User report: 2283124-hc (see also p1522340092000459-slack-C2C8F5PNJ)
* Follow-up ticket: 1051005-zen
* User's site: dewolfdesignden.com generally, see Pretty in Peach page.

----
Issue originally reported in https://github.com/Automattic/themes/issues/86

**Comment by separatelyunited** [comment]
The user has come back in 1051005-zen to ask for an update.

**Comment by tiagonoronha** [comment]
I've wasn't also able to replicate this issue. 

@mikejolley can you please test this as well? Thanks

**Comment by mikejolley** [comment]
@tiagonoronha Not sure how to - I don't have the issue. WC doesn't control cropping mode or rotation. Nothing afaik rotates images...

The featured image displayed above fwiw is controlled by WP not WooCommerce. Our cropping code doesn't affect WP image sizes.

> So the images can appear "cut off" or cropped. But when the framing problem automatically catches up with itself, corrects itself, the image becomes per expected, "normal". 

Images could be cut off before thumbs are regenerated on the frontend if the image sizes were modified. Thats expected and part of image regen process.

**Comment by Robertght** [comment]
Placed on-hold again. Any news?

**Comment by tiagonoronha** [comment]
Replied on the ticket.

**Comment by tiagonoronha** [comment]
I'm closing this issue. Please reopen it if you still feel there's still an issue here.
