### ISSUE TITLE
De-emphasise the "remove" icon in the cart

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#812]
https://cloudup.com/ixql1OO7dKB

Based on analysis in p6q8Tx-Ii-p2 let's tweak the design here a bit. I think we can use a more neutral color and switch out the icon for the less bold version of the `x` - https://fontawesome.com/icons/times-circle?style=regular

**Comment by uok** [comment]
Good suggestion! 
But the "regular" icon font (as Font Awesome calls it) needs to be integrated in Woo icons.css
In the meantime I will be using `a.remove::before { color: #ccc }` to blend it more.

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1107
