### ISSUE TITLE
Mobile: Cart text alignment

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#813]
<img src="https://cldup.com/SpFrbpdp_b-3000x3000.png" width="320">

The large gaps between labels / content on the cart makes the content here difficult to read / scan. See p6q8Tx-Ii-p2 for further info. I think the simplest solution would be to left-justify the content on the right of the table.

<img src="https://cldup.com/gT4e0S3vL1-3000x3000.png" width="320">

**Comment by tiagonoronha** [comment]
The markup on the cart page doesn't make that design possible without creating other issues. Let's revisit this another time.
