### ISSUE TITLE
Breadcrumb - optional?

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/storefront#816]
For larger stores with deep categorisation/navigation the breadcrumb feature in WooCommerce is undoubtedly useful beyond SEO. But for smaller stores it's usefulness is questionable and it takes up valuable screen real-estate particularly on mobile.

Should we add an option to disable the breadcrumb?

**Comment by GlennMartin1** [comment]
PowerPack's Designer already has this. 

If this is added to Storefront, you'll just have to resolve conflict with Designer.

**Comment by tiagonoronha** [comment]
I agree that this would be an interesting option to add. Let's add this after 2.3.

**Comment by acal** [comment]
Nice to have but already doable this way:
```
add_action( 'init', 'storefront_remove_storefront_breadcrumbs' ); 
function storefront_remove_storefront_breadcrumbs() {   
    remove_action( 'storefront_before_content', 'woocommerce_breadcrumb', 10 );
}
```
