### ISSUE TITLE
[2.3.0 beta 1] Sticky Add-To-Cart doesn't activate correctly...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#833]
WordPress 4.9.5
Storefront 2.3.0 beta 1

_Sticky Add-To-Cart_ doesn't activate until first deactivated and saved, then reactivated and saved.

First, to illustrate that it's turned on out-of-the-box, but not active:
- On a new install of **Storefront 2.3.0 beta 1**, activate _Sticky Add-To-Cart_. Note that _Sticky Add-to-Cart_ is not active.
- Go to **Customizer** > **Product Page**. Note that _Sticky Add-To-Cart_ is checked (it also works in the Customizer, but not on the real site).

Second, to turn on _Sticky Add-to-Cart_:
- Uncheck _Sticky Add-to-Cart_.
- Save **Customizer**.
- Re-check _Sticky Add-to-Cart_.
- Save **Customizer**. Now _Sticky Add-to-Cart_ is live.

**Comment by rynaldos** [comment]
I could be missing something here, but it looks like the product thumbnails aren't being displayed either

<img width="1117" alt="screen shot 2018-04-26 at 9 30 08 am" src="https://user-images.githubusercontent.com/6198774/39291863-9efacde0-4934-11e8-8d7f-e469204bb27c.png">

**Comment by GlennMartin1** [comment]
@rynaldos I cannot replicate this.

_Sticky Add-to-Cart_ seems to work for me on:

- Storefront
- Storefront with Homestore
- Storefront with Boutique
- Storefront with Toystore

_Sticky Add-to-Cart_ seems to **NOT** work for me on:

- Storefront with Deli

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/commit/5b1e9a41eb59fac0289a632644dfd809432442b9
