### ISSUE TITLE
Add support for privacy policy URL template tags (WordPress 4.9.6)

### ISSUE THREAD

**Issue by tiagonoronha** [woocommerce/storefront#835]
https://core.trac.wordpress.org/ticket/43715
https://core.trac.wordpress.org/ticket/43850

Suggested output:

![43715 3](https://user-images.githubusercontent.com/1177726/39242885-91ea4d1c-4883-11e8-861d-57c5eaa184d8.jpg)

cc @jameskoster

**Comment by jameskoster** [comment]
LGTM!
