### ISSUE TITLE
Storefront installation failing due to missing style.css

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#838]
Tested on Master.

The CSS/SCSS refactoring introduced a failing installation. Installation fails with this message:
_The package could not be installed. The theme is missing the style.css stylesheet._

See:
https://snag.gy/19vca0.jpg

**Comment by tiagonoronha** [comment]
@GlennMartin1 this repository only includes source files, if you are downloading from master, you need to run the build tools: https://github.com/woocommerce/storefront/blob/master/CONTRIBUTING.md#set-up-your-development-environment

You can download the storefront.zip file for each version of Storefront here: https://github.com/woocommerce/storefront/releases
