### ISSUE TITLE
Customize image sizes in the customizer – missing Main image width.

### ISSUE THREAD

**Issue by bigmadness** [woocommerce/storefront#839]
Customize image sizes in the customizer – missing Main image width.

**Comment by tiagonoronha** [comment]
@bigmadness what do you mean by "Main image"? Which image are you referring to?

**Comment by tiagonoronha** [comment]
@bigmadness since we've received any feedback from you, I'm closing this issue. 

Feel free to open it back if there's still an issue here. :)
