### ISSUE TITLE
[2.3.0 RC1] missing Customizer option...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#847]
In Storefront 2.2.8, with the Product Pagination plugin (ever since v 1.1), there was an option for displaying pagination only within the same product category.

See https://snag.gy/cSwP1h.jpg

That seems to be missing in Storefront 2.3.0 beta and RC1.

**Comment by tiagonoronha** [comment]
This option was intentionally left out. There's a filter that can be used to turn on this feature:

`add_filter( 'storefront_single_product_pagination_same_category', '__return_true' ); `
