### ISSUE TITLE
[2.3.0 RC1] Product Pagination not working properly....

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#848]
Setup a new store with the WC sample products.

Go to the Shop, and open any product page. For example, pick Logo Collection.

Using the pagination LEFT, gives only these three:
- Long Sleeve Tee
- Hoodie with Zipper
- V-Neck T-Shirt

Using the pagination RIGHT, gives only these three:
- Belt
- Long Sleeve Tee
- T-Shirt with Logo

These same choices appear no matter which product you start with.

Clearly, the Product Pagination is not working properly.

**Comment by tiagonoronha** [comment]
@GlennMartin1 if you imported the WC sample products, the date and time for each product is basically the same.

This causes issues in WordPress and it's the reason why pagination doesn't work as expected.

If you start changing the dates and time, you'll see that pagination will work properly.
