### ISSUE TITLE
Remove breadcrumbs for Storefront 2.3RC1 theme

### ISSUE THREAD

**Issue by rikofert** [woocommerce/storefront#850]
Using the following code:
`
add_action( 'init', 'wc_remove_storefront_breadcrumbs');

function wc_remove_storefront_breadcrumbs() {
  remove_action( 'storefront_content_top', 'woocommerce_breadcrumb', 10 );
}
`
Does now remove breadcrumbs only in home page.

**Comment by tiagonoronha** [comment]
@rikofert the breadcrumb was moved to the `storefront_before_content` hook.

```
add_action( 'init', 'wc_remove_storefront_breadcrumbs' );

function wc_remove_storefront_breadcrumbs() {
    remove_action( 'storefront_before_content', 'woocommerce_breadcrumb', 10 );
}
```

This should do the trick :)
