### ISSUE TITLE
Down facing arrow for submenus in mega menus not displaying correctly

### ISSUE THREAD

**Issue by inakicalvo** [woocommerce/storefront#853]
Square being shown instead of down facing arrow ([example](https://talenland.nl/)).

Location of the media query: /storefront/assets/css/base/icons.css?ver=2.3.0

**line 4124**: content: "\f107";

**Comment by tiagonoronha** [comment]
@inakicalvo thanks for the report! How did you update to Storefront 2.3? Did you update automatically from WordPress.org?

**Comment by inakicalvo** [comment]
I updated from the dashboard of the site (local install of WP).

**Comment by inakicalvo** [comment]
There are also some issues with the icon fonts used in the breadcrumbs.

**Comment by tiagonoronha** [comment]
@inakicalvo Icons are not loading in your site in Chrome and Firefox. They seem to load correctly on Safari.

I'm currently debugging this issue on my end. Please revert to Storefront 2.2.8 in the meantime. You can download it here: https://github.com/woocommerce/storefront/releases/download/version%2F2.2.8/storefront.zip

**Comment by inakicalvo** [comment]
Thanks a lot @tiagonoronha. The roll-back fixed the problem. I'll check on the new version of the theme once this is fixed.

**Comment by tiagonoronha** [comment]
@inakicalvo do you have a child theme of Storefront active in your site? You seem to be loading two instances of Storefront's `style.css` file.

<img width="1234" alt="screen shot 2018-05-08 at 14 25 14" src="https://user-images.githubusercontent.com/1177726/39759873-bddd488c-52cb-11e8-8982-47e8630f3c22.png">

Please share the contents of your child theme `functions.php` in a [Gist file ](https://gist.github.com)and post the link here. :)

**Comment by inakicalvo** [comment]
@tiagonoronha I do have a custom child theme active on the site. Here's the content of fucntions.php:
<script src="https://gist.github.com/inakicalvo/93b08771d8ee701b1b7a8c6913dae873.js"></script>

**Comment by tiagonoronha** [comment]
Please replace:

```
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
}
```

with

```
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    global $storefront_version;
    wp_enqueue_style( 'storefront-style', get_template_directory_uri() . '/style.css', $storefront_version );
}
```

**Comment by inakicalvo** [comment]
@tiagonoronha I did follow your instructions and cleared my cache, but it didn't work.

But after changing this the css for Storefront is only loading once.

I'm rolling back to 2.2.8.

**Comment by mdmoore** [comment]
@tiagonoronha We're seeing some other cases of this as well.  Working in Safari but not Firefox or Chrome.

**Comment by tiagonoronha** [comment]
@inakicalvo would it be possible for you to update to 2.3.0 one more time, and manually replace the contents of your `/assets/css/base/icons.css` with this version? Gist: https://gist.githubusercontent.com/tiagonoronha/1e5724149879ea30aba2079e28d4f3cb/raw/204f169f3ba42751f8b47c4f219d7205250b3202/icons.css

Don't forget to clear your browser's cache after updating the file.

Thank you so much for your help!

**Comment by opicron** [comment]
Can confirm that many font-awesome icons are not functioning. All psuedo :after class content.

For me the dropdown buttons for menu and description icon in single product are not showing. Trying @tiagonoronha solution now.

**Comment by tiagonoronha** [comment]
@opicron Thank you for testing! We're still trying to replicate this issue on our end. 

Please revert to Storefront 2.2.8 in the meantime. You can download it here: https://github.com/woocommerce/storefront/releases/download/version%2F2.2.8/storefront.zip

**Comment by opicron** [comment]
@tiagonoronha Mail send!

**Comment by tiagonoronha** [comment]
Here's an updates `icons.css` file: https://gist.githubusercontent.com/tiagonoronha/51262bf9402c0511fdd43d20ecf82c7b/raw/a160bc24887e08671c66d566e7b60a9d5fe8b9a5/icons.css

For reasons I don't quite understand yet, the CSS is being interpreted slightly differently across different sites, but the CSS above should fix the issue.

**Comment by inakicalvo** [comment]
@tiagonoronha I've changed Storefront Designer for Storefront Powerpack, updated Storefront to 2.3 and pasted the contents of your gist into icons.css. And it works now! You can check it out [here](https://talenland.nl/).

Thanks a lot for your help!

**Comment by opicron** [comment]
Just an heads up, the fix currently sets all icons as a heavy weight (900). In the previous storefront they were lighter. Is there a way to make the dropdown arrows a lighter weight again?

**Comment by seoidau** [comment]
With 2.3.1 in Chrome (both desktop browser with mobile emulation and on an Android phone), the Font Awesome icons for search and cart in the `storefront-handheld-footer-bar` can not be rendered (white vertical rectangle) because of the (second) declaration in the `icons.css` file line 3079 `font-weight: 400;`.

Changing to bold/501 (or higher) and they display.

**Comment by mdmoore** [comment]
I'm seeing the same as @seoidau with the cart and search icons on mobile.
