### ISSUE TITLE
Product pagination needs padding when there's no featured image

### ISSUE THREAD

**Issue by tiagonoronha** [woocommerce/storefront#855]
<img width="568" alt="screen shot 2018-05-08 at 19 37 49" src="https://user-images.githubusercontent.com/1177726/39775982-656333de-52f7-11e8-8699-3bd62f2e95ca.png">

**Comment by GlennMartin1** [comment]
SUGGESTION: Rather than adding padding, the Product Pagination should use the image placeholder.

That would offer consistency with the image shown on the product page.

**Comment by tiagonoronha** [comment]
This one is actually invalid. The site where I was testing had failed to import images from the dummy content, so the placeholder images were not showing up.

All good! :)
