### ISSUE TITLE
storefront-product-pagination is missing a background-color

### ISSUE THREAD

**Issue by sandrodz** [woocommerce/storefront#864]
<img width="1280" alt="screen shot 2018-05-10 at 10 37 56 am" src="https://user-images.githubusercontent.com/8479569/39855760-4553e67c-543e-11e8-919a-aaae077578b6.png">

**Comment by tiagonoronha** [comment]
Hi @sandrodz! I'm aware of this issue, this PR fixes it: https://github.com/woocommerce/storefront/pull/863

This will be fixed in 2.3.1.

Thank you :)
