### ISSUE TITLE
Sticky Add-to-Cart and Product Pagination not activated automatically

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#869]
After upgrading to 2.3.1, the Customizer shows **Sticky Add-to-Cart** and **Product Pagination** turned on.

But they are not activated until turned off in Customizer, saved, then turned on, and resaved.

https://github.com/woocommerce/storefront/pull/841 was supposed to address this, but the bug persists.

**Comment by tiagonoronha** [comment]
I've tested this coming from a new install and from 2.2 to 2.3.1, and I couldn't replicate this issue.

I believe this is not an issue anymore, but I'll keep an eye open for other reports.
