### ISSUE TITLE
Update the "Customize the WooCommerce breadcrumb" Docs page.

### ISSUE THREAD

**Issue by WM4362** [woocommerce/storefront#870]
Quick FYI - the [Customize the WooCommerce breadcrub](https://docs.woocommerce.com/document/customise-the-woocommerce-breadcrumb/) Docs page, could do with an update. Specifically I have found:

1. Per issue #609 the [Change the breadcrumb separator](https://docs.woocommerce.com/document/customise-the-woocommerce-breadcrumb/#section-1) and the [Change all the things](https://docs.woocommerce.com/document/customise-the-woocommerce-breadcrumb/#section-2) snippets both need to have a priority set.
2. You might also want to mention how the delimiter can now simply be set using the Storefront Customiser via the WordPress Dashboard.
3. Due to the Breadcrumb wrapper changes in Storefront 2.3.0, the [Change all the things](https://docs.woocommerce.com/document/customise-the-woocommerce-breadcrumb/#section-2) snippet also needs to include the div classes _storefront-breadcrumb_ and _col-full _ in the _wrap-before_ and _wrap-after_ array elements, otherwise you cannot set a background-color for the Breadcrumb and it will float left to the edge of the screen (this is how I fixed mine, anyways...). I think the _nav itemprop="breadcrumb"_ can also be removed from _wrap-before_:
`'wrap_before' => '<div class="storefront-breadcrumb"><div class="col-full"><nav class="woocommerce-breadcrumb">',
            'wrap_after'  => '</nav></div></div>',`
4. Finally, per issue #850 the [Remove the breadcrumbs](https://docs.woocommerce.com/document/customise-the-woocommerce-breadcrumb/#section-4) snippet for the Storefront theme needs the hook updated.

Hopefully that'll saves some future angst for others and newbies trying to get on the Woo-Train! :-)

**Comment by tiagonoronha** [comment]
Thanks! Docs have been updated. :)
