### ISSUE TITLE
Storefront Breadcrumb with coloured background Margin conflict.

### ISSUE THREAD

**Issue by WM4362** [woocommerce/storefront#871]
The Breadcrumb wrapper changes in Storefront 2.3.0 appear to have introduced a small issue for Breadcrumbs with a background-color that differs from the content.

From what I can tell, Storefront 2.3.0 has the new div class="storefront-breadcrumb", as well as the div class="col-full" which both wrap the nav class="woocommerce-breadcrumb". Pre-SF2.3.0 I set the BG-color on this nav class for a colored Breadcrumb (edge-to-edge of screen). Now however it only goes as far wide as the col-full div (YELLOW).

So logically I applied the BG-color to the storefront-breadcrumb div (RED) which looks fine at desktop resolutions, however line 632 of woocommerce.css sets a bottom margin of 1.618em to the woocommerce-breadcrumb nav at mobile resolutions which then leaves colored (RED) "white-space" at the bottom of the Breadcrumb. Again, the simple fix was to remove that bottom margin from the woocommerce-breadcrumb nav, and apply it to the storefront-breadcrumb div within my child style.css.

However I raised the issue as I figured you might want to address this some way in either/or code base (Woo/SF), as opposed to users hacking together child-theme workarounds.

The below screenshot should help explain it (tested on vanilla WP4.9.5, Storefront 2.3.1, WooCommerce 3.3.5 install with the imported sample_products.csv), if any clarification is needed just let me know.

![breadcrumb](https://user-images.githubusercontent.com/21233532/39908723-b9352be2-5532-11e8-9c50-29cff230e32c.jpg)

**Comment by tiagonoronha** [comment]
Confirmed. I intended to move the styling to the new `.storefront-breadcrumb` selector, but it seems that change got lost along the way.

Temporary CSS fix:

```
.storefront-breadcrumb {
    margin: 0 0 1.618em;
    padding: 1em 0;
}

.woocommerce-breadcrumb {
	padding: 0;
	margin: 0;
}

@media screen and (min-width: 768px) {
	.storefront-breadcrumb {
		padding: 1.41575em 0;
		margin: 0 0 4.235801032em;
	}
	
	.woocommerce-breadcrumb {
		padding: 0;
		margin: 0;
	}
}
```
