### ISSUE TITLE
storefront-primary-nagivation alignment at mobile res.

### ISSUE THREAD

**Issue by WM4362** [woocommerce/storefront#872]
I was surprised I couldn't find an existing issue for this (is its me?), but having tested on vanilla WP4.9.5, Storefront 2.3.1, and WooCommerce 3.3.5 with the imported sample_products.csv, I'm fairly certain its a core issue.

It appears that the SF2.3.0 change to _div.storefront-primary-navigation_ nolonger being wrapped by the _div.col-full_ of the _header#masthead.site-header_ causes the mobile primary nav menu to now display beneath div.col-full, as opposed to inline with the Site Name/Logo on mobile resolutions.

I tried playing with display, position, etc... but couldn't get it to line-up like pre-SF2.3.0...

![storefront-primary-navigation](https://user-images.githubusercontent.com/21233532/39910180-4bdd8272-5539-11e8-90b4-47d14dd10490.jpg)

**Comment by tiagonoronha** [comment]
Hi @WM4362, 

Thanks for reporting this issue.

It seems this issue was introduced [here](https://github.com/woocommerce/storefront/pull/862).

Please use the following CSS as a temporary fix:

```
.col-full::after,
.col-full::before {
    content: none;
}

.woocommerce-active .site-header .col-full {
    position: static;
}

@media (min-width:768px) {
    .col-full::after,
    .col-full::before {
        content: '';
    }
}
```
