### ISSUE TITLE
storefront-sticky-add-to-cart__content

### ISSUE THREAD

**Issue by antondrob** [woocommerce/storefront#873]
New feature storefront-sticky-add-to-cart__content
The phrase 'You're viewing' can not be locolized there

**Comment by tiagonoronha** [comment]
Hi @antondrob,

The string is localisable and included the the `storefront.pot` file: https://github.com/woocommerce/storefront/blob/master/languages/storefront.pot#L750-L752

Make sure that you update that file and/or rescan on the plugin that you're using to translate the strings.
