### ISSUE TITLE
storefront-template-functions.php line 186 <h1 class ="logo">

### ISSUE THREAD

**Issue by webmarketingxperts** [woocommerce/storefront#874]
I saw another thread discussing this in reference to a blog page.  This is an SEO issue. You only get one H1 on the home page of your site and this one is being used on a logo. There must be another way to handle this.

**Comment by tiagonoronha** [comment]
There was indeed a change made to this in version 2.2.8 and I may have made a mistake, I'll review this again.

**Comment by tiagonoronha** [comment]
@webmarketingxperts see https://github.com/woocommerce/storefront/pull/889 for a description of the issue.

@GlennMartin1 Tuesday, 23 May at the latest.

**Comment by bondimedical3** [comment]
I would appreciate a fix for this. Currently I cannot use my store logo and have had to put text there instead and remove my page title so as to only have 1 h1 tag on the homepage.
