### ISSUE TITLE
"Popular products" list widget uses full size product images resized with CSS

### ISSUE THREAD

**Issue by Wegerich** [woocommerce/storefront#883]
I just updated for the first time in a few months and GTmetrix reveals that my homepage size has increased by 1mb (300%) because the "popular products" widget is taking the full size product images and just rescaling them to be tiny using CSS, meaning they use full bandwidth.

https://gtmetrix.com/reports/www.reagent-tests.uk/Oaq3pvra

Is this something that has been done deliberately that's fair enough, I'm sure there is a good reason but otherwise, please could it be returned to using smaller versions of the images?

thanks

**Comment by tiagonoronha** [comment]
WordPress includes a list of all the available image sizes for an image and it is up to the browser to decide which image to use.

However, it seems that manually setting a maximum size to the image selector itself prevents this browser feature from working correctly.

I need to do a bit more research on this subject.

Thanks for reporting!

**Comment by tiagonoronha** [comment]
Hi @Wegerich,

If you'd like to change the size of the images in the Products widget, you'll need to:

1) Register a new image size: https://developer.wordpress.org/reference/functions/add_image_size/
2) Replace the `content-widget-product.php` template file and in:

`<?php echo $product->get_image(); ?>`

Add your custom image size:

`<?php echo $product->get_image( 'custom-image-size-name' ); ?>`

How to replace templates: https://docs.woocommerce.com/document/woocommerce-theme-developer-handbook/

I'm closing this thread as it is not really an issue.

For further support, please open a topic in the support forum: https://wordpress.org/support/theme/storefront

Thank you.

**Comment by Wegerich** [comment]
That's very disappointing, it was working until the update and seems like it would be a beneficial change for any other store using this widget - there is no need for visitors  to load a 100kb image if it's 32x32 pixels.
