### ISSUE TITLE
Switching tab doesn't add has to url anymore

### ISSUE THREAD

**Issue by sandrodz** [woocommerce/storefront#885]
When switching tabs on product page, has was added to url. It was a good accessibility feature.

At the moment no hash is added when switching between tabs.

![screen shot 2018-05-18 at 3 44 16 pm](https://user-images.githubusercontent.com/8479569/40233035-58307b6e-5ab2-11e8-8f78-ef67c76736d3.png)

**Comment by tiagonoronha** [comment]
Hi @sandrodz! 

I couldn't find any reference to this ever being a feature in Storefront/WooCommerce.

I agree it is a nice enhancement, and I'll try to address it in WooCommerce in the near future.

Since this is not a Storefront issue, I'm closing this issue.

Thank you!

**Comment by sandrodz** [comment]
hm, I'm pretty sure I was using this feature to direct customers to specific sections in my shop.
Do you mean it is part of WooCommerce core plugin and not Storefront?

**Comment by tiagonoronha** [comment]
If you right click and copy the url of a tab to new browser window, it will send you to the correct tab.

This is all handled by WooCommerce core.

If we do add the hash to the url, it needs to go in WooCommerce core.

**Comment by sandrodz** [comment]
Then in previous versions of WooCommerce this functionality was present. I will diff versions and see if I can find what has changed.
