### ISSUE TITLE
Should FontAwesome be Font Awesome 5 Free?

### ISSUE THREAD

**Issue by sarukuku** [woocommerce/storefront#891]
On [this](https://github.com/woocommerce/storefront/blob/dfe79b94c2d6a648a99db00532a290314e9608f7/assets/css/sass/utils/_mixins.scss#L53) row the `font-family` name is still `FontAwesome`. Should it be updated to `Font Awesome 5 Free`?

**Comment by tiagonoronha** [comment]
@sarukuku thanks for reporting! The `message` mixin is not really being used anywhere, so it is safe to remove.

**Comment by sarukuku** [comment]
Alright. I'll make a PR that removes the `message` mixin.

**Comment by tiagonoronha** [comment]
I've already gone ahead and done that: https://github.com/woocommerce/storefront/pull/895

Thanks :)

**Comment by sarukuku** [comment]
Ah you were quicker! Well you can just close down the PR then. I already made it. :)
