### ISSUE TITLE
Logo on hidpi screens

### ISSUE THREAD

**Issue by sandrodz** [woocommerce/storefront#898]
Logo should use `srcset`, it looks terrible on hidipi screens atm.

**Comment by tiagonoronha** [comment]
@sandrodz this is scheduled for 2.2.3 :)

**Comment by sandrodz** [comment]
@tiagonoronha that's great news! I searched around issues and couldn't find anything, sorry if this is planned and discussed somewhere already :)

**Comment by sandrodz** [comment]
I search everywhere in issues, didn't see it mentioned. Also isn't current version 2.3.2 ?

**Comment by tiagonoronha** [comment]
Yes, my mistake.

2.3.2 was deployed today, this will go in the next version.

**Comment by sandrodz** [comment]
Awesome news! thanks ^_^

**Comment by tiagonoronha** [comment]
@sandrodz I just tested this and WordPress is definitively outputting a `srcset` for the logo.

<img width="1307" alt="screen shot 2018-06-20 at 12 25 36" src="https://user-images.githubusercontent.com/1177726/41655553-201c300a-7485-11e8-9a71-6f5c57a708d1.png">

I've also opened a new PR to allow for skipping cropping of the logo - https://github.com/woocommerce/storefront/pull/917

**Comment by sandrodz** [comment]
okay, on 1 site, removing logo and re-adding it made `srscset` appear.
on another it still doesn't show.

both are clean installs. Without any plugins.

![screen shot 2018-06-27 at 2 32 25 pm](https://user-images.githubusercontent.com/8479569/41968934-ece763b6-7a16-11e8-8542-00fc4ad96c66.png)
