### ISSUE TITLE
Jetpack causing a header taller than normal, for a second

### ISSUE THREAD

**Issue by Sophivorus** [woocommerce/storefront#899]
When I load my site (https://mercadoetico.com.ar/) the header looks several times taller than normal, for a second. I'm using the latest WordPress, WooCommerce, Storefront and Jetpack. The issue happens both in the latest Chrome and Firefox, so it doesn't seem a browser issue. When I disable Jetpack the issue disappears, but it doesn't happen with other themes (I tried with Fagri and Hestia) so it seems to be a Jetpack + Storefront issue. Unfortunately I have no clue as to what the cause may be, but perhaps you guys can figure it out. Cheers!

**Comment by tiagonoronha** [comment]
Hi @Sophivorus! This issue seems to be caused by the LazyLoad module in Jetpack.

To minimize the page jump, you can try adding an height to the logo with custom CSS:

```
.site-header .custom-logo-link img {
    max-width: 49px;
}

@media (min-width: 768px) {
  .site-header .custom-logo-link img {
    max-width: 54px;
  }
}
```

Thank you!
