### ISSUE TITLE
Menu navigation issue on mobile

### ISSUE THREAD

**Issue by SonataAmanes** [woocommerce/storefront#904]
Hello, 

After V2.3.0, there was an issue regarding the menu on mobile, when there is also a sub menu. The problem is that the menu is retracted, but the arrows that would allow a visitor to navigate at the sub menu are not visible.

This was supposed to be fixed at 2.3.1, but even now with 2.3.2 I still face the same issue.

![menu_mobile](https://user-images.githubusercontent.com/16976318/40775747-7cf28806-64d1-11e8-9136-eb4091abf387.JPG)

Is there an update for this or a known fix?

Thanks in advance,

Kostas

**Comment by tiagonoronha** [comment]
Hi @SonataAmanes 

I wasn't able to replicate this issue locally. I see that your site has a significant amount of custom CSS, please make sure that it is not conflicting with Storefront.

Please submit a support ticket, include a link to your test site running Storefront 2.3.2, and we'll help you debug this issue. - https://woocommerce.com/contact-us/

Thank you!
