### ISSUE TITLE
New Update - Homepage Rearranged

### ISSUE THREAD

**Issue by ben-sears** [woocommerce/storefront#909]
Hi, after updating the storefront theme in WordPress, it has now moved my search bar under my main logo in the menu and then then added a massive white border around the main page body. 

How do I fix this?

Thanks 

![home-page](https://user-images.githubusercontent.com/39042031/40970548-10a0e444-690f-11e8-807b-a0878aa01c74.png)

**Comment by ben-sears** [comment]
It only seems to happen once you go over 1100px wide in the screen.  Below that it is fine. 

Any ideas?

**Comment by tiagonoronha** [comment]
Hi @ben-sears! Any chance you can send the URL so that we can debug this issue?

If you're a WooCommerce.com customer, please open a support request here: https://woocommerce.com/contact-us/

Thanks

**Comment by ben-sears** [comment]
Hi,



I have fixed it now.



Thanks,

Ben Sears

*Amplifi* Your Business with Digital Solutions

022 045 3040  |  www.amplifi.nz



*From:* Tiago Noronha <notifications@github.com>
*Sent:* Monday, 11 June 2018 11:00 PM
*To:* woocommerce/storefront <storefront@noreply.github.com>
*Cc:* ben-sears <ben@amplifi.nz>; Mention <mention@noreply.github.com>
*Subject:* Re: [woocommerce/storefront] New Update - Homepage Rearranged
(#909)



Hi @ben-sears <https://github.com/ben-sears>! Any chance you can send the
URL so that we can debug this issue?

If you're a WooCommerce.com customer, please open a support request here:
https://woocommerce.com/contact-us/

Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/woocommerce/storefront/issues/909#issuecomment-396204674>,
or mute the thread
