### ISSUE TITLE
Font Awesome Instagram Icon

### ISSUE THREAD

**Issue by jamiechong** [woocommerce/storefront#913]
Before version 2.3.0 I was able to use the Font Awesome instagram Icon in my child theme. 

```
.instagram:before {
  content: '\f16d';
}
```

But with your upgrade to font awesome 5 it seems like these icons are now missing. Is this intentional?

**Comment by ben72** [comment]
With Font Awesome 5 the brands icons are optional. The Storefront theme does not load that part, only the solid and regular fonts. You could argue that it should load all as it does not matter much in size, 49,17Kb from what I can see. And a lot of people will likely have the same issue as we had now.
I added it with this code:
```
add_action('wp_head','hook_header');
function hook_header() {
	echo '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/brands.css" integrity="sha384-VGCZwiSnlHXYDojsRqeMn3IVvdzTx5JEuHgqZ3bYLCLUBV8rvihHApoA1Aso2TZA" crossorigin="anonymous">
				<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/fontawesome.css" integrity="sha384-GVa9GOgVQgOk+TNYXu7S/InPTfSDTtBalSgkgqQ7sCik56N9ztlkoTr2f/T44oKV" crossorigin="anonymous">';
}
```
See here for more details:
https://fontawesome.com/get-started

**Comment by tiagonoronha** [comment]
Hi @jamiechong! Since social icons are not used anywhere in Storefront by default, it doesn't make sense to include the extra font.

@ben72's suggested code will add the brands font to your Storefront site.

Thank you!

**Comment by kincau2** [comment]
Thank you @ben72 for the code! After i add the function into the my child theme PHP, it seems like the stylesheet CDN was correctly hooked into the metadata, but the icon is still not load....

any ideas would help me a lot, thank you...

my dummy site: 
http://35.229.224.208

**Comment by dzhonkz** [comment]
Hi, 

I have the same problem with whatsapp icon. 
I have added the code via Theme Customisations plugin:
`add_action('wp_head','hook_header');
function hook_header() {
	echo '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/brands.css" integrity="sha384-QT2Z8ljl3UupqMtQNmPyhSPO/d5qbrzWmFxJqmY7tqoTuT2YrQLEqzvVOP2cT5XW" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/fontawesome.css" integrity="sha384-u5J7JghGz0qUrmEsWzBQkfvc8nK3fUT7DCaQzNQ+q4oEXhGSx+P2OqjWsfIRB8QT" crossorigin="anonymous">';
}`

but the icon still doesnt show in the handheld footer bar. The link itself works, but icon doesnt show up.

What im doing wrong?
