### ISSUE TITLE
Extension CSS for Brands plugin affects all H3 tags

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/storefront#914]
#### Affected ticket(s)

1212692-zd

#### What I expected

When Brands is active, that my theme `h3` tags will continue to look the same throughout the theme

#### What happened instead

When Brands is installed, the following CSS is loaded on all pages:

```
h3 {
    width: 73.9130434783%;
    float: right;
    margin-right: 0;
    clear: right;
    text-transform: uppercase; }
    
h3:first-of-type {
      margin-top: 0; }
```

This affects all `h3` tags across the entire site regardless of the theme that's active. I believe it should be prefixed as follows:

```
div#brands_a_z h3 {
    width: 73.9130434783%;
    float: right;
    margin-right: 0;
    clear: right;
    text-transform: uppercase;
  }

  div#brands_a_z h3:first-of-type {
      margin-top: 0; 
  }
```

Looks like this is caused by having `}` in the wrong place at https://github.com/woocommerce/storefront/blob/master/assets/css/woocommerce/extensions/brands.scss#L150

As an example, compare the following `h3` tag:

**With Brands Active**

![http://cld.wthms.co/eW8O3K](http://cld.wthms.co/eW8O3K+)
Full Image: http://cld.wthms.co/eW8O3K+

**With Brands Deactivated**

![http://cld.wthms.co/Ev0qYj](http://cld.wthms.co/Ev0qYj+)
Full Image: http://cld.wthms.co/Ev0qYj+

#### Steps to reproduce the issue

1. Install and activate Storefront
2. Install and activate Brands
3. Inspect any `h3` tag on your side and see that CSS intended for Brands is getting applied.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by ben72** [comment]
+1 on this! I made a workaround on my site as any text within h3 looks really off.

**Comment by tiagonoronha** [comment]
Already fixed here: https://github.com/woocommerce/storefront/pull/908
