### ISSUE TITLE
Product Pagination should show relevant products 

### ISSUE THREAD

**Issue by xbb123** [woocommerce/storefront#922]
Hello,

 Product Pagination currently shows previous and next products, which can be, and in our case, totally unrelated products. This confuses the customers as they may think that those products have similar applications. 
  I would recommend showing products based on the product name.
  Thank you!

**Comment by ben72** [comment]
I also get unrelated products showing up. Another possibility would be to match category/tag.

And when on the first/last product it could be useful if it was circular so there is always one product on each side.

**Comment by GlennMartin1** [comment]
@ben72 

Agreed!
(1) it should be pagination within a category
(2) it should be circular

Until this is fixed (especially the first point), I have Product Pagination turned off - it's just confusing and not useful as is.

Perhaps there should be a setting for this behavior in the Customizer.

**Comment by tiagonoronha** [comment]
Let's do this for 2.4.0. :)

1) Within a category by default
2) Circular

**Comment by SimplyBoho** [comment]
I have mine set to within the category, but it still has a bug. If the product is in more than one category it is switching categories in the pagination.

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1043
