### ISSUE TITLE
Switching to Max Width (Storefront Powerpack) leads to uneven product images

### ISSUE THREAD

**Issue by edwinhamers** [woocommerce/storefront#928]
Storefront: 2.3.2
Powerpack for Storefront

Reproduce steps:
Upload product images in various shapes (portrait, landscape, square)
Set non-square featured product image
Customiser > Powerpack > LayOut > Page Layout > Max Width

On any product archive page the featured product images will look uneven when non-square images are used. When the "Default" page layout is selected all images are cropped nice and square. See screenshots:

**Default Width**
![image](https://user-images.githubusercontent.com/3518216/42313777-d2af4116-8043-11e8-8ae1-e5443a4704ab.png)

**Max Width**
![image](https://user-images.githubusercontent.com/3518216/42313816-ea3a4826-8043-11e8-87fd-d13c52afd68e.png)

**Comment by tiagonoronha** [comment]
@edwinhamers for paid products, please contact us through the official channels: https://woocommerce.com/contact-us/

The "max width" option uses the original image and it's not resized or cropped.

Thanks!
