### ISSUE TITLE
Font Awesome regular fonts missing

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/storefront#929]
The regular and brand fonts appear missing from Font Awesome. This is noticeable on checkout where the payment selections are now a solid circle icon instead of the previous ring icon. The solid circle for unselected payment method is IMO confusing as it doesn't imply that you can click / select. 

Suggested update:
In /assets/fonts/ add the files for
fa-regular-400.eot
fa-regular-400.svg
fa-regular-400.ttf
fa-regular-400.woff
fa-regular-400.woff2

Then reference the regular fonts in /assets/css/base/icons.css : 

@font-face{font-family:'Font Awesome 5 Free';font-style:normal;font-weight:400;src:url("../../../assets/fonts/fa-regular-400.eot");src:url("../../../assets/fonts/fa-regular-400.eot?#iefix") format("embedded-opentype"),url("../../../assets/fonts/fa-regular-400.woff2") format("woff2"),url("../../../assets/fonts/fa-regular-400.woff") format("woff"),url("../../../assets/fonts/fa-regular-400.ttf") format("truetype"),url("../../../assets/fonts/fa-regular-400.svg#fontawesome") format("svg")}
.far{font-weight:400}

@font-face{font-family:'Font Awesome 5 Free';font-style:normal;font-weight:900;src:url("../../../assets/fonts/fa-solid-900.eot");src:url("../../../assets/fonts/fa-solid-900.eot?#iefix") format("embedded-opentype"),url("../../../assets/fonts/fa-solid-900.woff2") format("woff2"),url("../../../assets/fonts/fa-solid-900.woff") format("woff"),url("../../../assets/fonts/fa-solid-900.ttf") format("truetype"),url("../../../assets/fonts/fa-solid-900.svg#fontawesome") format("svg")}
.fa,.far,.fas{font-family:"Font Awesome 5 Free"}
.fa,.fas{font-weight:900}

NB: I've seen that the current build has changes to how the Font Awesome CSS is written but I can't see the regular font files in the /fonts/ folder. If my post crosses with current changes, please advise. 

The above changes will then allow the display of a ring icon f111 on checkout with font-weight: 400;

**Comment by tiagonoronha** [comment]
Hi @EdithAllison! We recently update from FontAwesome 4 to 5. 

FontAwesome has 740 free icons on the "solid" weight, but only 152 icons in the regular weight. We decided to switch to the weight with more icons.

You can find the list of icons here: https://fontawesome.com/icons?d=gallery&s=solid&m=free

As for the Brands font, we are not using it for anything in Storefront, so we're not including it with the theme.

Thanks

**Comment by EdithAllison** [comment]
Sorry, I intended to delete mention of "brands" as I realised it's not in use, apologies for the confusion. 

For regular fonts, is there a reason why it can't be added in addition to solid? Especially rings (non solid circles) are IMO useful for tickboxes eg at checkout. 

Thank you for taking the time to review the request. If non solid icons are not of relevance in your view, no need to reply, I will work around via hook in a child theme.

**Comment by tiagonoronha** [comment]
Unfortunately the regular font doesn't include all the icons we currently need.

If you prefer to use the regular font, you can enqueue it in a child theme and replace the other icons with CSS.

You can even enqueue the font using FontAwesome's CDN like I did here for the Brands font: https://github.com/woocommerce/storefront-product-sharing/pull/8/files

**Comment by EdithAllison** [comment]
Thank you! I didn't mean that you should replace solid with regular; but to use both. I've now added regular to my site and the solid icons work as before, no conflict I'm aware of. 

The hook I'm using is the one suggested here for brands: https://github.com/woocommerce/storefront/issues/913. 

```
// Let's add Font Awesome 5 Regular 
add_action('wp_head','add_awesome_regular');
function add_awesome_regular() {
	echo '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/regular.css" integrity="sha384-avJt9MoJH2rB4PKRsJRHZv7yiFZn8LrnXuzvmZoD3fh1aL6aM6s0BBcnCvBe6XSD" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/fontawesome.css" integrity="sha384-ozJwkrqb90Oa3ZNb+yKFW2lToAWYdTiF1vt8JiH5ptTGHTGcN7qdoR1F95e0kYyG" crossorigin="anonymous">';
}
```

My suggestion is to use both regular & solid; but if there's a conflict I'm not aware of, please ignore & close. Thank you for your time!
