### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by SirDarcanos** [woocommerce/storefront#93]
On Storefront with only WooCommerce enabled, i can't go to the page 2.
I think the problem is with the `&` which is escaped in the URL.

With this URL http://local.storefront/?post_type=product#038;paged=2 it does not work
while with this http://local.storefront/?post_type=product&paged=2 it works fine

It's weird though, it should work also with the escaped `&`

**Comment by Everdien** [comment]
Hi,
I´m having the same problem. When will this be fixed (when is the new release of woo commerce)?
kind regards, Everdien

**Comment by SiR-DanieL** [comment]
This is already fixed in WC 2.3. You can download the beta and test if you want, here: http://develop.woothemes.com/woocommerce/2015/01/2-3-handsome-hippo-beta-2/
