### ISSUE TITLE
Can't set Categories/Products Per Row for home page

### ISSUE THREAD

**Issue by millionleaves** [woocommerce/storefront#943]
It's possible to set the Products Per Row for the shop pages in the Customizer. This applies to categories and products.

However, this does not apply to the Home page. Changing the number of category columns on the home page requires a custom function.

**Preferred solution**: allow the number of columns to be set separately for the home page, below the existing options for the Shop in the Customizer.

**Acceptable solution**: use the existing Shop settings for the Home page as well.

Reference: https://wordpress.org/support/topic/show-more-than-3-categories-on-homepage-control-storefront-product-categories/

**Comment by gitotwee** [comment]
sorely needed. Plus, as a buyer, it should be included in the PowerPack options....
So you have my vote on this one.
In the meantime it would be nice if a support engineer could comment with the exact code to use in functions.php. I have seen many examples, but they all change the global settings, and we just need to have it work on the homepage...

**Comment by edwinhamers** [comment]
YES! Someone saw the light. Please add this to the options in the customizer or at least in the PowerPAck

**Comment by edwinhamers** [comment]
@gitotwee : This option is included in the PowerPack (premium plugin from Woo)

**Comment by millionleaves** [comment]
This is the code I added to functions.php in my Storefront child theme:

```
add_filter('storefront_product_categories_shortcode_args','custom_storefront_category_per_page' );
 
// Category Products
function custom_storefront_category_per_page( $args ) {
 $args['number'] = 4;
 $args['columns'] = 4;
 return $args;
}
```

**Comment by edwinhamers** [comment]
Correct me if i'm wrong, but will that code not globally change the [products] shortcode, not just for the homepage ?

**Comment by tiagonoronha** [comment]
@edwinhamers it will only change the categories shortcode in the homepage.

**Comment by edwinhamers** [comment]
@tiagonoronha : Can you explain how this how works just on the home page ?

**Comment by magiciancade** [comment]
okay there's the code for customizing the php file.
to get it there you should find the functions.php
i did found the file and also got the code but the problem here is where should i paste it?Above the existing codes?or under the existing codes? please be specific cuz i added the code in the functions.php and nothing happens still has a limit of 3 categories shown in my homepage

**Comment by KsinFergo** [comment]
Brilliant! I was looking for it and it's working perfectly. 
Just added in the row nr 65 in funcions.php after last } and that's it, thx!

**Comment by XiShNiK** [comment]
I have added the code to my functions.php and I can see it is displaying correctly when I am within the theme customization screen from within the Wordpress manager but when I go to the live site, the homepage is still only displaying 3 categories. Does anyone know how to fix this?

Thanks.

**Comment by tiagonoronha** [comment]
We'll soon start working on a new homepage using core blocks and also [WooCommerce Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/) so it will be possible to interact with the block to adjust columns and rows.

I'm closing this issue!
