### ISSUE TITLE
Upgrade Font Awesome to most recent version

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#945]
Font Awesome 5.2 has been released, featuring many more free icons. 

https://fontawesome.com/changelog/latest

Good idea to upgrade, I'd suggest.

**Comment by jessepearson** [comment]
@tiagonoronha Got another request for this in 1503446-zen

**Comment by By-oussef** [comment]
+1

**Comment by seanreloaded** [comment]
@tiagonoronha Got another request for this in 1814890-zen. Thnx!

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/1097
