### ISSUE TITLE
Gutenberg compatibility?

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#947]
Is Storefront already Gutenberg compatible? if not, what's the ETA on that?

Here's one issue that the Gutenberg team says is due to Storefront not supporting Gutenberg. See https://github.com/WordPress/gutenberg/issues/8826

**Comment by tiagonoronha** [comment]
Hi! We will start working on Gutenberg compatibility very soon.

https://github.com/woocommerce/storefront/issues/653
