### ISSUE TITLE
Font Awesome icons do not load on certain buttons

### ISSUE THREAD

**Issue by waterfireprov** [woocommerce/storefront#949]
icons in the `.view-more` buttons do not load. 

https://store.waterfire.org

i see a similar bug was fixed in 2.3.2 #878 

we're running 2.3.3

**Comment by tiagonoronha** [comment]
Hi @waterfireprov. That `.view-more` is coming from a deprecated Storefront extension called "Storefront WooCommerce Customizer".

That extension hasn't been in development for a couple of years and has been replaced by Storefront Powerpack.

You can still fix the issue with some CSS though:

```
.view-more .button:after {
    font-family: 'Font Awesome 5 Free';
    font-weight: 900;
    content: '\f30b';
}
```

Thanks!

**Comment by waterfireprov** [comment]
Thanks!
