### ISSUE TITLE
inconsistent padding with Powerpack hiding breadcrumb...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#950]
### Environment:
WordPress 4.9.8
Storefront 2.3.3
Storefront Powerpack 1.4.11
WooCommerce 3.4.4

### Settings:
1. Have at least two pages - the homepage and any other page/post.
2. Open the page/post (not homepage) you created.
3. Go to **Customizer** > **Powerpack** > **Designer** > **Add a Style** > click on the breadcrumb.
4. Click to **Hide** the breadcrumb.
5. Save and close the Customizer.

### Description of issue:
On the front-end, compare the homepage (which never shows a breadcrumb), versus the other page/post (which now has the breadcrumb disabled). You will notice a great difference in the size of padding between the header and the page/post title.

### Homepage (shows correctly):
![padding homepage](https://user-images.githubusercontent.com/30901407/44407506-489a0e80-a52c-11e8-8ad1-0924443a93dd.jpg)

### Regular page (shows with huge padding):
![padding regular page](https://user-images.githubusercontent.com/30901407/44407498-3fa93d00-a52c-11e8-9611-0c15828a1916.jpg)

### Other notes:
- Works correctly on **Boutique**.
- Works correctly on **Homestore**.
- Does NOT work correctly on **Storefront**.
- Does NOT work correctly on **Deli**.
- Does NOT work correctly on **Toyshop**.

**Comment by tiagonoronha** [comment]
Hi @GlennMartin1, this will be fix soon in Powerpack. 

For Powerpack related issues, please contact us via the WooCommerce.com support portal: https://woocommerce.com/contact-us/
