### ISSUE TITLE
Storefront WC options should display only if WC is activated

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront#953]
In Storefront 2.3.0, **Sticky Add-To-Cart** and **Product Pagination** was added for WooCommerce products.

**BUG:** These options display in the Customizer even if WooCommerce is not installed/activated.

**Expected:** these options should only appear in the Customizer if WooCommerce is active.

**Comment by tiagonoronha** [comment]
This is coming in Storefront 2.4. If you download from master, you'll see this already implemented.

https://github.com/woocommerce/storefront/pull/954#issuecomment-418751575

Changes were done here: https://github.com/woocommerce/storefront/pull/912

Closing :)
