### ISSUE TITLE
some Font Awesome icons do not load on custom button on handheld footer bar 

### ISSUE THREAD

**Issue by kincau2** [woocommerce/storefront#956]
on 2.3.3

some icon from Font Awesome is not loaded when adding new button in handheld.

icon i am using is /f232

`.storefront-handheld-footer-bar ul li.whatsapp > a:before {
	content: "\f232"; }`

seems like it is similar to #878 
![screen cap](https://user-images.githubusercontent.com/41952180/44954403-0087ce00-aed4-11e8-89dd-e7410de57d41.png)

**Comment by ben72** [comment]
I think this is the same issue as this one, https://github.com/woocommerce/storefront/issues/913

**Comment by tiagonoronha** [comment]
Hi @kincau2!

As referenced by @ben72 above, please read: https://github.com/woocommerce/storefront/issues/913

Thank you!
