### ISSUE TITLE
My Account > Bookings: Not able to see all info on Mobile

### ISSUE THREAD

**Issue by rwaynick** [woocommerce/storefront#957]
#### Steps to reproduce
1. Create a Bookable Product using WooCommerce Bookings and checkout.
2. Navigate to the My Account > Bookings page (/my-account/bookings/) to see Upcoming and Past Bookings.
3. Notice that on Desktop all of the info is shown properly,

![screen_shot_2018-09-06_at_1_22_27_pm](https://user-images.githubusercontent.com/10882502/45174262-6035f000-b1d8-11e8-8e31-61d11ca47168.jpg)

But on Mobile not all of the info is shown in Portrait view and it's not possible to scroll,

<img width="192" alt="screen shot 2018-09-06 at 1 22 44 pm" src="https://user-images.githubusercontent.com/10882502/45174323-92dfe880-b1d8-11e8-9e65-96e75f60473a.png">

#### What I expected

The booking info to be responsive and fit in the current view without having to scroll.

#### Context / Source
#user-report 
6248622-hc
1398127-zen

**Comment by tiagonoronha** [comment]
The table styling needs to be adapted for mobile use. Added to the 2.4 milestone.

Thanks!

**Comment by tiagonoronha** [comment]
This is an issue in Bookings, not Storefront. 

https://github.com/woocommerce/woocommerce-bookings/issues/1757
