### ISSUE TITLE
Product pagination sorting

### ISSUE THREAD

**Issue by sandrodz** [woocommerce/storefront#960]
All other sections like related products list, or category listing honor/are sorted by Menu order as default. Product pagination is not.

**Comment by tiagonoronha** [comment]
Product Pagination makes use of `get_previous_post` and `get_next_post` functions.

While we acknowledge that are improvements to be made to Product Pagination (see https://github.com/woocommerce/storefront/issues/922) we are not looking to create a custom function at this point.

You make a good point though, I'll keep this issue open as an enhancement, and we will revisit it in the future.

**Comment by tiagonoronha** [comment]
Same as https://github.com/woocommerce/storefront/issues/983
