### ISSUE TITLE
Dropdown menu does not open correctly on a tablet

### ISSUE THREAD

**Issue by serabi** [woocommerce/storefront#962]
If a drop down menu with the top-level menu item as a link is tapped in tablet view, the drop down menu does not open. Instead, the top link opens. 

Ticket here: 1406543-zen

**Comment by jobthomas** [comment]
I was able to kind of reproduce - it's not the entirely same scenario: the dropdown does open when using XCode Simulator with an iPad Pro on the Storefront demo when clicking "shop", however it loads the shop page at the same time.

As a hack approach here, I've suggested using a `#` for destinations of the top one, but ideally, there would be a difference between desktop and tablet approaches if possible.

https://wordpress.org/support/topic/woocommerce-storefront-dropdown-menu-touch-screen-2/#post-10674871

**Comment by tiagonoronha** [comment]
I can reproduce the issue as well. It's a bit tricky because not all platforms/browsers handle touch the same way.

I added this to the 2.3.4 milestone, but I might move it to 2.4 if it requires a lot of work.

**Comment by jobthomas** [comment]
Another one 1421209-hc
