### ISSUE TITLE
Composite Products and their accessories are not clearly displayed on the cart page in mobile viewpoint

### ISSUE THREAD

**Issue by keepsmilyn** [woocommerce/storefront#963]
This is something that has been highlighted with the Woo Composite Products plugin, however they advised that it needs addressing with the storefront theme developers as its controlled by configuration in the theme itself. 

In short, there is no clear definition between composite products, their accessories and simple products in the cart on the cart page in mobile viewpoint. All products look like simple products without any grouping characteristics. It is slightly clearer in the mini-cart widget and checkout page, perhaps a similar layout / structure could be used on the cart page to make this clearer.

**Comment by franticpsyx** [comment]
Solved in https://github.com/woocommerce/storefront/pull/970

The approach we've followed there requires CP 3.14 and relies on:

1. Hiding all line items that correspond to Components
2. Displaying Component selections as item meta, similar to how Variable product attributes are displayed in the cart.

This content is only visible on handheld screen sizes.

As you might expect, this means that on handheld sizes it's no longer possible to see Component subtotals or adjust quantities, but that's a good compromise in most cases. It's also consistent with how Composite Products 3.14+ displays Composites in the cart widget.

**Comment by franticpsyx** [comment]
@keepsmilyn I know you've done some customizations on top of Storefront and CP 3.13 -- if you want to take an early look at how #970 and CP 3.14 will affect your work, drop us a line via support and we'll send you a pre-release version of CP. To take #970 for a spin you can of course checkout the `franticpsyx:cp-3.14-pb-5.8-2.3` branch. Just note you will need to build it (`npm install` and then `grunt`) to generate the required files and make the theme usable.

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/pull/970
