### ISSUE TITLE
Should break point be set differently desktop?

### ISSUE THREAD

**Issue by geeklore** [woocommerce/storefront#967]
We have a customer that is saying that the break point is incorrectly set at `768` for Desktop. They believe it should be `769` to be mobile at exactly `768`.

Customer (1426421-zen) states:

> I tested with chrome on desktop at EXACTLY 768 the desktop mode kicks in....this is really not good the theme is not honoring the 768 you have to be at 767 to actually kick in responsive. This should be fixed by you guys and I think it has to do with the Min vs Max setting on screen.

This is in reference to `storefront/assets/css/sass/utils/_variables.scss` Lines 22 and 23.

I do not think this is a bug, but it might be. That's why I have opened as a question.

**Comment by ben72** [comment]
Looks related to this, https://github.com/woocommerce/storefront/issues/670#issuecomment-422851036

**Comment by tiagonoronha** [comment]
@geeklore `768px` is the most common break point used in the web for Tablets/Desktop. 

For the most part, we try to look at other frameworks and how they handle these type of things. Here's Bootstrap's responsive breakpoints: http://getbootstrap.com/docs/4.1/layout/overview/#responsive-breakpoints

If the customer is not happy with the defaults, and would like to try something different, it's possible to edit the values in `_variables.scss` and then recompile the CSS using the Grunt task (details can be found in the README). 

Another possibility would be to extend and customize the current CSS.

**Comment by ChrisColotti** [comment]
The issue is that at 768 exactly on a tablet based on your default setting there is NO responsive on tablets unless the tablet is at 767px.  The default breakpoint should be at 769.  See any storefront based site on iPAD in portait mode and it's NOT responsive and looks awful!
