### ISSUE TITLE
Issue with Safari Desktop / Iphone (and all Iphone browsers as based on Safari)

### ISSUE THREAD

**Issue by gbruzzo** [woocommerce/storefront#973]
Dear All

Encountered this issue on Safari (12.0) on Mac (Mojave), as well as on every iOs browser we tested on Iphone (they are all Safari mobile based - all most recent versions )

using Safari Desktop (12.0) or latest Safari / Firefox / Opera / Chrome on iOS 12

Go to https://themes.woocommerce.com/storefront/shop/ 

add two simple products to cart 
cart fragments update (bottom right)

Now scroll to the bottom, jump to a another page on shop 

add a few more products 
cart fragments update. 

now click on the back button. 

the cart fragments regress to before the first products were added. 
Safari is either not refreshing fragments (cart hash is "")

now click the forward button. 
Cart fragments still are not updating. 

FYI: the problem does not manifest itself when trying to replicate the above on Chrome / Firefox for Desktop or Chrome for Android 

Is this to be expected?

**Comment by tiagonoronha** [comment]
Issue moved to [woocommerce/woocommerce #21544](https://github.com/woocommerce/woocommerce/issues/21544) via [**ZenHub**](https://www.zenhub.com/)
