### ISSUE TITLE
Brands homepage columns and results

### ISSUE THREAD

**Issue by mediageni** [woocommerce/storefront#974]
I have the Woocommerce brands plugin, but I cannot find an option to change total brands listing and columns

**Comment by tiagonoronha** [comment]
There's currently no interface to change the number of brands shown and number columns.

It is possible to change using a filter:

`
function storefront_github_974( $args ) {
	$args['number'] = 6;
	$args['columns'] = 4;
}

add_filter( 'storefront_woocommerce_brands_args', 'storefront_gh_974' );
`

You can paste the snippet in the functions.php file of your child theme.

**Comment by mediageni** [comment]
If I paste this code I get this error

Uncaught DivisionByZeroError: Modulo by zero in
wp-content/plugins/woocommerce-brands/templates/widgets/brand-thumbnails.php:16
Stack trace:
#0 wp-content/plugins/woocommerce/includes/wc-core-functions.php(210): include()
#1 wp-content/plugins/woocommerce-brands/includes/class-wc-brands.php(590):
wc_get_template('widgets/brand-t...', Array, 'woocommerce-bra...',
'/home/appsde1q/...')
#2 wp-content/themes/storefront/inc/storefront-functions.php(51):
WC_Brands->output_product_brand_thumbnails(Array, NULL,
'product_brand_t...')
#3 wp-content/themes/storefront/inc/woocommerce/storefront-woocommerce-template-functions.php(492):
storefront_do_shortcode('product_brand_t...', Array)
#4 wp-includes/class-wp-hook.php(286):
storefront_woocommerce_brands_homepage_section('')

**Comment by tiagonoronha** [comment]
My bad. Here's the updated code:

```
function storefront_github_974( $args ) {
	$args['number'] = 6;
	$args['columns'] = 4;

	return $args;
}

add_filter( 'storefront_woocommerce_brands_args', 'storefront_gh_974' );
```

**Comment by mediageni** [comment]
I don't know whats wrong but I get the same issue
