### ISSUE TITLE
Clicked menu item with custom link URL "#" remains open in non-touchscreens

### ISSUE THREAD

**Issue by dsmithweb** [woocommerce/storefront#977]
Hello! 

This is a minor UI bug. With WordPress 4.9.8 and no plugins, the default behavior (as seen in Twenty Seventeen) is that if you use `#` as the custom link URL for a top-level menu item, clicking that item opens that menu of sub-items, and the menu remains open until you click elsewhere on the page.

With Storefront active, clicking elsewhere on the page is this scenario does not close the "stuck open" menu -- except on touchscreens. 

Is this something to do with storefront/assets/js/navigation.js ?

**Comment by tiagonoronha** [comment]
Related: https://github.com/woocommerce/storefront/issues/981

Closing this issue.
