### ISSUE TITLE
RUR currency abbreviation looks strange.

### ISSUE THREAD

**Issue by fogiusus** [woocommerce/storefront#978]
Please change the look of Russian Ruble currency font to non bold nead the cart on the main page. Also the Russian Ruble sign consists of one first letter, not of 3 letter as it is now. Please keep just the first letter. Thanks in advance.

**Comment by tiagonoronha** [comment]
Currency comes from WooCommerce, not Storefront. It can be changed with a filter: https://docs.woocommerce.com/document/change-a-currency-symbol/
