### ISSUE TITLE
No icons of cart, search etc. on mobile Android

### ISSUE THREAD

**Issue by fogiusus** [woocommerce/storefront#979]
No icons of cart, login and search are visible on mobile Android phone.

**Comment by tiagonoronha** [comment]
@fogiusus I own an Android phone and all the icons and showing up for me. 

Could you please share more information about the issue you are having? Also, if possible, share the URL to the site in question.

Thanks!

**Comment by tiagonoronha** [comment]
Your website is loading 4 different versions of FontAwesome, the font we use for icons.

It seems to be a conflict with some of the third party Storefront extensions that you've installed on your site.

We are currently using version 5 of FontAwesome while the extensions you are using are on version 4.

Please contact the plugin developer for support.

Thank you!
