### ISSUE TITLE
Sensei integration

### ISSUE THREAD

**Issue by ajgw** [woocommerce/storefront#980]
Hi, I see few layout issues with Sensei and Storefront. For example course or lesson feature images are diplayed by Sensei left of content but Sensei puts a margin between image thumbnail and text but Storefront overwrites css and removes space so text begins right next at image.

I see at Sensei that they are on their way making Sensei ready for none Sensei supported themes but this will not help me in case of using Storefront in neither way. How about supporting Sensei at all with Storefront?

**Comment by tiagonoronha** [comment]
@ajgw a full Sensei integration is not currently in our plans for Storefront.

We're currently focused on WooCommerce and its ecosystem of extensions.

Thank you!
