### ISSUE TITLE
Parent menu items dysfunctional after update to 2.3.4

### ISSUE THREAD

**Issue by derweltbuerger** [woocommerce/storefront#981]
Hi there,
I recently updated from Storefront 2.3.3 to 2.3.4. After some time I realized that parent menu items became dysfunctional when they had sub-menu items below them. Clicking on the affected menu items simply did nothing. Other menu items were not affected. I could still right-click and open in new tab on those affected items though.

Reverting back to 2.3.3 immediately solved the issue, as did turning off JS in browser. So, I assume there must be some JS script interfering.

I hope the issue is clear. If not let me know and I can elaborate.

Best, David

**Comment by tiagonoronha** [comment]
Hi @derweltbuerger! Can you tell us more about your setup? Are you on Windows or Mac? If on Windows, does your computer have a touch screen?

Thank you!

**Comment by derweltbuerger** [comment]
Hi @tiagonoronha! I'm on Windows. Yes, my computer does have a touchscreen. I was using a mouse to click though. Tried both Firefox and Chrome and in both browsers the parent menu links did not work.

All software on my computer is up-to-date as are WP & WC versions and all plugins.

**Comment by tiagonoronha** [comment]
Thank you. I've been able to replicate this issue and I'm currently working on a fix.
