### ISSUE TITLE
Setting Checkout phone number to 'required' doesn't seem to work

### ISSUE THREAD

**Issue by jamiemarsland** [woocommerce/storefront#984]
We've had a few reports from customers that setting phone number to required isn't working. 

We've managed to replicate as well (although it seems a little random)

**Comment by jamiemarsland** [comment]
hi, paypal and stripe (just the default ones) - i tested by removing stripe (it wasn't set up), but the issue remains

It's running on one of our demo sites here https://wp-skins.com/

**Comment by dougaitken** [comment]
> i tested by removing stripe (it wasn't set up), but the issue remains

@jamiemarsland the PayPal Express checkout is the one which you have active. This is payment gateway which @lkraav mentioned. 

http://cld.wthms.co/CZ52T6

Can you try the reverse - keep Stripe active (in test mode) and then deactivate PayPal Express Checkout, please? 

Alternatively, can you have a look at this part of the docs and see what is checked on your PayPal Express Checkout settings, please?

https://docs.woocommerce.com/document/paypal-express-checkout/#section-6

**Comment by jamiemarsland** [comment]
Hi, 

Just tested with stripe active (in test mode) and with paypal xpress de-activated and we see the same issue.

**Comment by lkraav** [comment]
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/426 is the problematic issue.

**Comment by dougaitken** [comment]
I can't replicate this one at all using Storefront and WooCommerce.

Can you replicate this with _just_ Storefront active, Jamie? I see you're using a child theme which could be causing some of the problems.
Deactivate all payment gateways and use cash on delivery or another offline method to rule out payment gateway troubles.

For reference, here is a test order I've just placed: 
![sf_nophone_test](https://user-images.githubusercontent.com/52214/47881758-fd02bb80-de1e-11e8-86cd-35030816433c.png)

no phone number
SF `2.3.5`
WC `3.5.0`
Stripe `4.1.12`

I'm going to close this issue for now as I cannot replicate this as it is pointing towards a conflict with either another plugin or your child theme.
