### ISSUE TITLE
[WP 5.0] Inconsistent widget block line heights

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/storefront#992]
<img width="378" alt="screen shot 2018-11-05 at 10 54 03 am" src="https://user-images.githubusercontent.com/7317227/48009241-4554fe80-e0e9-11e8-9b57-b7d639b25f3f.png">

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/commit/c7e12b1c07c687f7b53344c14c6b09cba7fc7245
