### ISSUE TITLE
[WP 5.0] Full-width 6-column layout goes all the way to the edge of the screen

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/storefront#995]
<img width="1676" alt="screen shot 2018-11-05 at 11 44 35 am" src="https://user-images.githubusercontent.com/7317227/48012558-476e8b80-e0f0-11e8-8253-7de50d2193a5.png">

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront/commit/ca8ee37b836644ceaef65e0564340ab101eb7262
