### ISSUE TITLE
Product Search/magnifying glass and expectations

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/storefront#999]
This issue is specific to Proshop, but opening here as I feel it's probably the more appropriate place.

The user in ticket: 1569964-zen expects that clicking the magnifying glass on the search box would submit the query, e.g. 
![see screen shot](https://cld.wthms.co/9xssqK+)

The CSS for the submit button moves it well away from the search box.

**Comment by tiagonoronha** [comment]
Issue moved to [woocommerce/proshop #45](https://github.com/woocommerce/proshop/issues/45) via [**ZenHub**](https://www.zenhub.com/)
